import FWCore.ParameterSet.Config as cms

import RecoBTag.SecondaryVertex.combinedSecondaryVertexES_cfi

combinedSecondaryVertexNegative = RecoBTag.SecondaryVertex.combinedSecondaryVertexES_cfi.combinedSecondaryVertex.clone()
combinedSecondaryVertexNegative.vertexFlip = True
combinedSecondaryVertexNegative.trackFlip = True
combinedSecondaryVertexNegative.trackSelection.sip3dSigMax = 0
combinedSecondaryVertexNegative.trackPseudoSelection.sip3dSigMax = 0
combinedSecondaryVertexNegative.trackPseudoSelection.sip2dSigMin = -99999.9
combinedSecondaryVertexNegative.trackPseudoSelection.sip2dSigMax = -2.0

combinedSecondaryVertexV2Negative = RecoBTag.SecondaryVertex.combinedSecondaryVertexES_cfi.combinedSecondaryVertexV2.clone()
combinedSecondaryVertexV2Negative.vertexFlip = True
combinedSecondaryVertexV2Negative.trackFlip = True
combinedSecondaryVertexV2Negative.trackSelection.sip3dSigMax = 0
combinedSecondaryVertexV2Negative.trackPseudoSelection.sip3dSigMax = 0
combinedSecondaryVertexV2Negative.trackPseudoSelection.sip2dSigMin = -99999.9
combinedSecondaryVertexV2Negative.trackPseudoSelection.sip2dSigMax = -2.0
