import FWCore.ParameterSet.Config as cms

from RecoBTag.SecondaryVertex.pfInclusiveSecondaryVertexFinderCtagLTagInfos_cfi import *

pfInclusiveSecondaryVertexFinderCtagLNegativeTagInfos = pfInclusiveSecondaryVertexFinderCtagLTagInfos.clone()
pfInclusiveSecondaryVertexFinderCtagLNegativeTagInfos.extSVDeltaRToJet = cms.double(-0.3)
pfInclusiveSecondaryVertexFinderCtagLNegativeTagInfos.vertexCuts.distVal2dMin = -2.5
pfInclusiveSecondaryVertexFinderCtagLNegativeTagInfos.vertexCuts.distVal2dMax = -0.01
pfInclusiveSecondaryVertexFinderCtagLNegativeTagInfos.vertexCuts.distSig2dMin = -99999.9
pfInclusiveSecondaryVertexFinderCtagLNegativeTagInfos.vertexCuts.distSig2dMax = -2.0
pfInclusiveSecondaryVertexFinderCtagLNegativeTagInfos.vertexCuts.maxDeltaRToJetAxis = -0.5
