#include "DataFormats/Common/interface/DeviceProduct.h"
#include "DataFormats/Common/interface/Wrapper.h"
#include "DataFormats/TICL/interface/CaloClusterSoA.h"
#include "DataFormats/TICL/interface/alpaka/CaloClusterDeviceCollection.h"
#include "DataFormats/TICL/interface/ClusterMask.h"
#include "DataFormats/TICL/interface/alpaka/ClusterMaskDevice.h"
#include "DataFormats/TICL/interface/AssociationMap.h"
#include "DataFormats/TICL/interface/alpaka/HitsAndFractionsDevice.h"
