/bin/sh dropBoxOffline.sh CASTORRECO_Geometry.db metaCASTORRECO-prod.txt
/bin/sh dropBoxOffline.sh CSCRECODIGI_Geometry.db metaCSCRECODIGI-prod.txt
/bin/sh dropBoxOffline.sh CSCRECO_Geometry.db metaCSCRECO-prod.txt
/bin/sh dropBoxOffline.sh CTRECO_Geometry.db metaCTRECO-prod.txt
/bin/sh dropBoxOffline.sh DTRECO_Geometry.db metaDTRECO-prod.txt
/bin/sh dropBoxOffline.sh EBRECO_Geometry.db metaEBRECO-prod.txt
/bin/sh dropBoxOffline.sh EERECO_Geometry.db metaEERECO-prod.txt
/bin/sh dropBoxOffline.sh EPRECO_Geometry.db metaEPRECO-prod.txt
/bin/sh dropBoxOffline.sh GeometryFileExtended.db metaGeometryExtended-prod.txt 
/bin/sh dropBoxOffline.sh GeometryFileExtendedGFlash.db metaGeometryExtendedGFlash-prod.txt 
/bin/sh dropBoxOffline.sh GeometryFileIdeal.db metaGeometryIdeal-prod.txt 
/bin/sh dropBoxOffline.sh GeometryFileExtendedLiMin.db metaGeometryExtendedLiMin-prod.txt 
/bin/sh dropBoxOffline.sh GeometryFileExtendedLiMax.db metaGeometryExtendedLiMax-prod.txt
/bin/sh dropBoxOffline.sh GeometryFileExtendedX0Min.db metaGeometryExtendedX0Min-prod.txt
/bin/sh dropBoxOffline.sh GeometryFileExtendedX0Max.db metaGeometryExtendedX0Max-prod.txt
/bin/sh dropBoxOffline.sh HCALRECO_Geometry.db metaHCALRECO-prod.txt
/bin/sh dropBoxOffline.sh RPCRECO_Geometry.db metaRPCRECO-prod.txt
/bin/sh dropBoxOffline.sh TKRECO_Geometry.db metaTKRECO-prod.txt
/bin/sh dropBoxOffline.sh TKExtra_Geometry.db metaTKExtra-prod.txt
/bin/sh dropBoxOffline.sh ZDCRECO_Geometry.db metaZDCRECO-prod.txt
