/bin/sh dropBoxOffline_test.sh CASTORRECO_Geometry.db metaCASTORRECO.txt
/bin/sh dropBoxOffline_test.sh CSCRECODIGI_Geometry.db metaCSCRECODIGI.txt
/bin/sh dropBoxOffline_test.sh CSCRECO_Geometry.db metaCSCRECO.txt
/bin/sh dropBoxOffline_test.sh CTRECO_Geometry.db metaCTRECO.txt
/bin/sh dropBoxOffline_test.sh DTRECO_Geometry.db metaDTRECO.txt
/bin/sh dropBoxOffline_test.sh EBRECO_Geometry.db metaEBRECO.txt
/bin/sh dropBoxOffline_test.sh EERECO_Geometry.db metaEERECO.txt
/bin/sh dropBoxOffline_test.sh EPRECO_Geometry.db metaEPRECO.txt
/bin/sh dropBoxOffline_test.sh GeometryFileExtended.db metaGeometryExtended.txt 
/bin/sh dropBoxOffline_test.sh GeometryFileExtendedGFlash.db metaGeometryExtendedGFlash.txt 
/bin/sh dropBoxOffline_test.sh GeometryFileIdeal.db metaGeometryIdeal.txt 
/bin/sh dropBoxOffline_test.sh GeometryFileExtendedLiMin.db metaGeometryExtendedLiMin.txt 
/bin/sh dropBoxOffline_test.sh GeometryFileExtendedLiMax.db metaGeometryExtendedLiMax.txt
/bin/sh dropBoxOffline_test.sh GeometryFileExtendedX0Min.db metaGeometryExtendedX0Min.txt
/bin/sh dropBoxOffline_test.sh GeometryFileExtendedX0Max.db metaGeometryExtendedX0Max.txt
/bin/sh dropBoxOffline_test.sh HCALRECO_Geometry.db metaHCALRECO.txt
/bin/sh dropBoxOffline_test.sh RPCRECO_Geometry.db metaRPCRECO.txt
/bin/sh dropBoxOffline_test.sh TKRECO_Geometry.db metaTKRECO.txt
/bin/sh dropBoxOffline_test.sh TKExtra_Geometry.db metaTKExtra.txt
/bin/sh dropBoxOffline_test.sh ZDCRECO_Geometry.db metaZDCRECO.txt
