-- Create payload object tables generated from EcalPedestals-mapping-custom.xml
CREATE TABLE CMS_ECAL."ECALPEDESTALS" ( "IOV_VALUE_ID" NUMBER(10), CONSTRAINT "ECALPEDESTALS_PK" PRIMARY KEY ( "IOV_VALUE_ID" ) );
CREATE TABLE CMS_ECAL."ECALPEDESTALS_ITEM" ( "POS" NUMBER(10) NOT NULL, "IOV_VALUE_ID" NUMBER(10) NOT NULL, "MEAN_X1" BINARY_FLOAT NOT NULL, "MEAN_X12" BINARY_FLOAT NOT NULL, "MEAN_X6" BINARY_FLOAT NOT NULL, "RMS_X1" BINARY_FLOAT NOT NULL, "RMS_X12" BINARY_FLOAT NOT NULL, "RMS_X6" BINARY_FLOAT NOT NULL, "DET_ID" NUMBER(10) NOT NULL, CONSTRAINT "ECALPEDESTALS_ITEM_PK" PRIMARY KEY ( "IOV_VALUE_ID","POS" ), CONSTRAINT "ECALPEDESTALS_ITEM_ID_FK" FOREIGN KEY ( "IOV_VALUE_ID" ) REFERENCES CMS_ECAL."ECALPEDESTALS" ( "IOV_VALUE_ID" ) );

-- Add TIME column for IOV
ALTER TABLE CMS_ECAL."ECALPEDESTALS" ADD "TIME" NUMBER(10);

-- Create payload object tables generated from ./EcalWeight-mapping-custom.xml
CREATE TABLE CMS_ECAL."ECALWEIGHT" ( "IOV_VALUE_ID" NUMBER(10), "WEIGHT" BINARY_DOUBLE NOT NULL, CONSTRAINT "ECALWEIGHT_PK" PRIMARY KEY ( "IOV_VALUE_ID" ) );

-- Add TIME column for IOV
ALTER TABLE CMS_ECAL."ECALWEIGHT" ADD "TIME" NUMBER(10);

-- Create payload object tables generated from ./EcalWeightRecAlgoWeights-mapping-custom.xml
CREATE TABLE CMS_ECAL."ECALWEIGHTRECALGOWEIGHTS" ( "IOV_VALUE_ID" NUMBER(10), CONSTRAINT "ECALWEIGHTRECALGOWEIGHTS_PK" PRIMARY KEY ( "IOV_VALUE_ID" ) );
CREATE TABLE CMS_ECAL."WGTAFTERSWITCH" ( "POS" NUMBER(10) NOT NULL, "ID_ID" NUMBER(10) NOT NULL, CONSTRAINT "WGTAFTERSWITCH_PK" PRIMARY KEY ( "ID_ID","POS" ), CONSTRAINT "WGTAFTERSWITCH_ID_FK" FOREIGN KEY ( "ID_ID" ) REFERENCES CMS_ECAL."ECALWEIGHTRECALGOWEIGHTS" ( "IOV_VALUE_ID" ) );
CREATE TABLE CMS_ECAL."WGTAFTERSWITCH_VEC" ( "POS" NUMBER(10) NOT NULL, "ID_POS" NUMBER(10) NOT NULL, "ID_ID_ID" NUMBER(10) NOT NULL, "WEIGHT" BINARY_DOUBLE NOT NULL, CONSTRAINT "WGTAFTERSWITCH_VEC_PK" PRIMARY KEY ( "ID_ID_ID","ID_POS","POS" ), CONSTRAINT "WGTAFTERSWITCH_VEC_ID_FK" FOREIGN KEY ( "ID_ID_ID","ID_POS" ) REFERENCES CMS_ECAL."WGTAFTERSWITCH" ( "ID_ID","POS" ) );
CREATE TABLE CMS_ECAL."WGTBEFORESWITCH" ( "POS" NUMBER(10) NOT NULL, "ID_ID" NUMBER(10) NOT NULL, CONSTRAINT "WGTBEFORESWITCH_PK" PRIMARY KEY ( "ID_ID","POS" ), CONSTRAINT "WGTBEFORESWITCH_ID_FK" FOREIGN KEY ( "ID_ID" ) REFERENCES CMS_ECAL."ECALWEIGHTRECALGOWEIGHTS" ( "IOV_VALUE_ID" ) );
CREATE TABLE CMS_ECAL."WGTBEFORESWITCH_VEC" ( "POS" NUMBER(10) NOT NULL, "ID_POS" NUMBER(10) NOT NULL, "ID_ID_ID" NUMBER(10) NOT NULL, "WEIGHT" BINARY_DOUBLE NOT NULL, CONSTRAINT "WGTBEFORESWITCH_VEC_PK" PRIMARY KEY ( "ID_ID_ID","ID_POS","POS" ), CONSTRAINT "WGTBEFORESWITCH_VEC_ID_FK" FOREIGN KEY ( "ID_ID_ID","ID_POS" ) REFERENCES CMS_ECAL."WGTBEFORESWITCH" ( "ID_ID","POS" ) );
CREATE TABLE CMS_ECAL."WGTCHI2AFTERSWITCH" ( "POS" NUMBER(10) NOT NULL, "ID_ID" NUMBER(10) NOT NULL, CONSTRAINT "WGTCHI2AFTERSWITCH_PK" PRIMARY KEY ( "ID_ID","POS" ), CONSTRAINT "WGTCHI2AFTERSWITCH_ID_FK" FOREIGN KEY ( "ID_ID" ) REFERENCES CMS_ECAL."ECALWEIGHTRECALGOWEIGHTS" ( "IOV_VALUE_ID" ) );
CREATE TABLE CMS_ECAL."WGTCHI2AFTERSWITCH_VEC" ( "POS" NUMBER(10) NOT NULL, "ID_POS" NUMBER(10) NOT NULL, "ID_ID_ID" NUMBER(10) NOT NULL, "WEIGHT" BINARY_DOUBLE NOT NULL, CONSTRAINT "WGTCHI2AFTERSWITCH_VEC_PK" PRIMARY KEY ( "ID_ID_ID","ID_POS","POS" ), CONSTRAINT "WGTCHI2AFTERSWITCH_VEC_ID_FK" FOREIGN KEY ( "ID_ID_ID","ID_POS" ) REFERENCES CMS_ECAL."WGTCHI2AFTERSWITCH" ( "ID_ID","POS" ) );
CREATE TABLE CMS_ECAL."WGTCHI2BEFORESWITCH" ( "POS" NUMBER(10) NOT NULL, "ID_ID" NUMBER(10) NOT NULL, CONSTRAINT "WGTCHI2BEFORESWITCH_PK" PRIMARY KEY ( "ID_ID","POS" ), CONSTRAINT "WGTCHI2BEFORESWITCH_ID_FK" FOREIGN KEY ( "ID_ID" ) REFERENCES CMS_ECAL."ECALWEIGHTRECALGOWEIGHTS" ( "IOV_VALUE_ID" ) );
CREATE TABLE CMS_ECAL."WGTCHI2BEFORESWITCH_VEC" ( "POS" NUMBER(10) NOT NULL, "ID_POS" NUMBER(10) NOT NULL, "ID_ID_ID" NUMBER(10) NOT NULL, "WEIGHT" BINARY_DOUBLE NOT NULL, CONSTRAINT "WGTCHI2BEFORESWITCH_VEC_PK" PRIMARY KEY ( "ID_ID_ID","ID_POS","POS" ), CONSTRAINT "WGTCHI2BEFORESWITCH_VEC_ID_FK" FOREIGN KEY ( "ID_ID_ID","ID_POS" ) REFERENCES CMS_ECAL."WGTCHI2BEFORESWITCH" ( "ID_ID","POS" ) );

-- Add TIME column for IOV
ALTER TABLE CMS_ECAL."ECALWEIGHTRECALGOWEIGHTS" ADD "TIME" NUMBER(10);
