CREATE TABLE COND_TABLE_META (
DEF_ID NUMBER(10) NOT NULL,
TABLE_NAME VARCHAR2(30),
TABLE_TYPE NUMBER(10),
NUMBER_OF_FIELDS NUMBER(10),
FILLED_BY VARCHAR2(30),
CONTENT_EXPLANATION VARCHAR2(100), 
LOGIC_ID_EXPLANATION VARCHAR2(100),
LOGIC_ID_NAME VARCHAR2(50),
MAP_TO_BE_DONE_BY_i NUMBER(10),
MAP_TO_BE_DONE_BY_j NUMBER(10) 
);

CREATE SEQUENCE COND_TABLE_SQ INCREMENT BY 1 START WITH 1;

ALTER TABLE COND_TABLE_META ADD CONSTRAINT COND_TABLE_META_PK PRIMARY KEY (DEF_ID);

CREATE TABLE COND_FIELD_META (
DEF_ID NUMBER(10) NOT NULL,
TAB_ID NUMBER(10) NOT NULL,
FIELD_NAME VARCHAR2(30),
IS_PLOTTABLE CHAR(1),
FIELD_TYPE VARCHAR2(15),
CONTENT_EXPLANATION VARCHAR2(100), 
LABEL VARCHAR2(80)); 

CREATE SEQUENCE COND_FIELD_SQ INCREMENT BY 1 START WITH 1;

ALTER TABLE COND_FIELD_META ADD CONSTRAINT COND_FIELD_META_PK PRIMARY KEY (DEF_ID);

ALTER TABLE COND_FIELD_META ADD CONSTRAINT COND_FIELD_to_COND_TABLE_fk FOREIGN KEY (TAB_ID) REFERENCES COND_TABLE_META (DEF_ID);
