/**
  *  New Model DDL generated by Schemester
  *  12/02/2008 10:05:14
  */


/*  LMF_RUN_TAG  */
drop table LMF_LASER_CONFIG_DAT;
drop table LMF_RUN_DAT;
drop table LMF_TEST_PULSE_CONFIG_DAT;
drop table LMF_LASER_PULSE_DAT;
drop table LMF_LASER_BLUe_PRIM_DAT;
drop table LMF_CALIB_PRIM_DAT;
drop table RUN_LASERRUN_CONFIG_DAT;
drop table LMF_LASER_BLUE_PN_PRIM_DAT;
drop table lmf_run_iov;
drop TABLE LMF_RUN_TAG;
