DROP TABLE POOL_OR_MAPPING_VERSIONS;
DROP TABLE POOL_OR_MAPPING_ELEMENTS;
DROP TABLE POOL_OR_MAPPING_COLUMNS;
DROP TABLE POOL_RSS_DB;
DROP TABLE POOL_RSS_CONTAINERS;
DROP TABLE POOL_CONT___SHAPES;
DROP TABLE POOL_CONT___LINKS;
DROP TABLE POOL_CONT___PARAMS;
