/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef CMSBKGLINESHAPE
#define CMSBKGLINESHAPE

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class CMSBkgLineShape : public RooAbsPdf {
public:
  CMSBkgLineShape() {} ; 
  CMSBkgLineShape(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _alpha,
	      RooAbsReal& _beta,
	      RooAbsReal& _peak,
	      RooAbsReal& _gamma);
  CMSBkgLineShape(const CMSBkgLineShape& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new CMSBkgLineShape(*this,newname); }
  inline virtual ~CMSBkgLineShape() { }


protected:

  RooRealProxy x ;
  RooRealProxy alpha ;
  RooRealProxy beta ;
  RooRealProxy peak ;
  RooRealProxy gamma ;
  
  Double_t evaluate() const ;

private:

  ClassDef(CMSBkgLineShape,1) // Your description goes here...
};
 
#endif
