#!/bin/sh
for d in TkStrct PixBar PixFwdPlus PixFwdMinus TIB TIDF TIDB InnerServices TOB TEC Tracker BeamPipe; do
    cmsRun runP_Tracker_cfg.py geom=Extended2017Plan1 label=${d}  >& /dev/null
done

for d in TkStrct PixBar PixFwdPlus PixFwdMinus TIB TIDF TIDB InnerServices TOB TEC Tracker TrackerSum Pixel Strip BeamPipe; do
    python MaterialBudget.py -s -d ${d}
done

root -b -q 'MaterialBudget_TDR.C()'

