#ifndef HeterogeneousCore_CUDAUtilities_requireCUDADevices_h
#define HeterogeneousCore_CUDAUtilities_requireCUDADevices_h

void requireCUDADevices();

#endif  // HeterogeneousCore_CUDAUtilities_requireCUDADevices_h
