#!/bin/tcsh 

# Save current dir on lxbatch machine
setenv LXBATCH_DIR `pwd`
setenv CMSSW_DIR   TEMPLATECMSDIR
setenv OUTPUT_DIR  TEMPLATEOUTDIR
setenv jobidx      JOBINDEX 

# Set scram runtime environment
cd $CMSSW_DIR
cmsenv
cd $LXBATCH_DIR

# Create the cmsswrc file for the current job
cp ${OUTPUT_DIR}/../MuScleFit_cfg.py .
cp ${OUTPUT_DIR}/TreeSplitter_${jobidx}_cfg.py .
rfcp /castor/cern.ch/user/t/trocino/MuScleFit/tree_Summer10JPsiPromptSTARTUP.root .
rfcp /castor/cern.ch/user/t/trocino/MuScleFit/Probs_merge.root .

date
echo "cmsRun TreeSplitter_${jobidx}_cfg.py"
cmsRun TreeSplitter_${jobidx}_cfg.py > log1.log
echo "cmsRun MuScleFit_cfg.py"
cmsRun MuScleFit_cfg.py > log2.log

date
echo "Content of working directory is: "
\ls -lrt

echo "scp FitParameters.txt ${OUTPUT_DIR}/FitParameters_${jobidx}.txt"
scp FitParameters.txt ${OUTPUT_DIR}/FitParameters_${jobidx}.txt
echo "rm ${OUTPUT_DIR}/TreeSplitter_${jobidx}_cfg.py"
rm ${OUTPUT_DIR}/TreeSplitter_${jobidx}_cfg.py

exit 0
