// Double_t fit_func(Double_t *x, Double_t *par){
//   Float_t xx =x[0];
//   if(xx<par[0])f = par[1]*x+par[2];
//   else f=par[3]*x+par[0]*(par[1]-par[3])+par[2];
//   return f;
// }
{
  int NBINS=32;
    TFile *resfile=new TFile("resolution_new.root");
 // TFile *resfile=new TFile("resolution_good.root");
  float tibrms[NBINS],tobrms[NBINS],tidrms[NBINS],tecrms[NBINS];
  float tibsigma[NBINS],tobsigma[NBINS],tidsigma[NBINS],tecsigma[NBINS];
  float tibrmserror[NBINS],tobrmserror[NBINS],tidrmserror[NBINS],tecrmserror[NBINS];
  float tibsigmaerror[NBINS],tobsigmaerror[NBINS],tidsigmaerror[NBINS],tecsigmaerror[NBINS];
  TH1F *tibres[NBINS],*tobres[NBINS],*tidres[NBINS],*tecres[NBINS];
  TH1F *allres[NBINS];
  float allrms[NBINS],allrmserror[NBINS];
  float allsigma[NBINS],allsigmaerror[NBINS];
  for(int i=0;i<NBINS;i++){
    cout<<Form("CPEtest/TIBres_%f-%f",i*8./NBINS,i*8./NBINS+8./NBINS)<<endl;
   tibres[i]=(TH1F*)resfile->Get(Form("CPEtest/TIBres_%f-%f",i*8./NBINS,i*8./NBINS+8./NBINS));
   tobres[i]=(TH1F*)resfile->Get(Form("CPEtest/TOBres_%f-%f",i*8./NBINS,i*8./NBINS+8./NBINS));
   tidres[i]=(TH1F*)resfile->Get(Form("CPEtest/TIDres_%f-%f",i*8./NBINS,i*8./NBINS+8./NBINS));
   tecres[i]=(TH1F*)resfile->Get(Form("CPEtest/TECres_%f-%f",i*8./NBINS,i*8./NBINS+8./NBINS));
    allres[i]=(TH1F*)tibres[i]->Clone(Form("Allres_%f-%f",i*8./NBINS,i*8./NBINS+8./NBINS));
    allres[i]->Add(tobres[i]);
    allres[i]->Add(tidres[i]);
    allres[i]->Add(tecres[i]);
//     tibres[i]->Fit("gaus");
//     tobres[i]->Fit("gaus");
//     tidres[i]->Fit("gaus");
//     tecres[i]->Fit("gaus");
//     allres[i]->Fit("gaus");
//     tibrms[i]=tibres[i]->GetFunction("gaus")->GetParameter(2);
//     tibrmserror[i]=tibres[i]->GetFunction("gaus")->GetParError(2);
//     tobrms[i]=tobres[i]->GetFunction("gaus")->GetParameter(2);
//     tobrmserror[i]=tobres[i]->GetFunction("gaus")->GetParError(2);
//     tidrms[i]=tidres[i]->GetFunction("gaus")->GetParameter(2);
//     tidrmserror[i]=tidres[i]->GetFunction("gaus")->GetParError(2);
//     tecrms[i]=tecres[i]->GetFunction("gaus")->GetParameter(2);
//     tecrmserror[i]=tecres[i]->GetFunction("gaus")->GetParError(2);
//     allrms[i]=allres[i]->GetFunction("gaus")->GetParameter(2);
//     allrmserror[i]=allres[i]->GetFunction("gaus")->GetParError(2);
    TF1 *param_old=new TF1("error_param_old","[0]*x*exp(-x*[1])+[2]",0.,4);
    TF1 *newparam_old=new TF1("error_newparam_old","1/sqrt(12)",0.,4);
    param_old->SetParameter(0,-3.39e-01);
    param_old->SetParameter(1,9.0e-01);
    param_old->SetParameter(2,2.79e-01);
    newparam_old->SetLineColor(kRed);
    float range=newparam_old->Eval(float(i)/4+0.125)*sqrt(30);
    tibres[i]->GetXaxis()->SetRangeUser(-range,range);
    tidres[i]->GetXaxis()->SetRangeUser(-range,range);
    tobres[i]->GetXaxis()->SetRangeUser(-range,range);
    tecres[i]->GetXaxis()->SetRangeUser(-range,range);
    allres[i]->GetXaxis()->SetRangeUser(-range,range);
    tibrms[i]=tibres[i]->GetRMS();
    tibrmserror[i]=tibres[i]->GetRMSError();
    tobrms[i]=tobres[i]->GetRMS();
    tobrmserror[i]=tobres[i]->GetRMSError();
    tidrms[i]=tidres[i]->GetRMS();
    tidrmserror[i]=tidres[i]->GetRMSError();
    tecrms[i]=tecres[i]->GetRMS();
    tecrmserror[i]=tecres[i]->GetRMSError();
    allrms[i]=allres[i]->GetRMS();
    allrmserror[i]=allres[i]->GetRMSError();
  }
  float proj[NBINS],proje[NBINS];
  for (int i=0;i<NBINS;i++){proj[i]=float(i)/4+0.125; proje[i]=0.;};
  TGraphErrors *TIB=new TGraphErrors(NBINS/2,proj,tibrms,proje,tibrmserror);
  TGraphErrors *TOB=new TGraphErrors(NBINS/2,proj,tobrms,proje,tobrmserror);
  TGraphErrors *TID=new TGraphErrors(NBINS/2,proj,tidrms,proje,tidrmserror);
  TGraphErrors *TEC=new TGraphErrors(NBINS/2,proj,tecrms,proje,tecrmserror);
  TGraphErrors *ALL=new TGraphErrors(NBINS/2,proj,allrms,proje,allrmserror);

  TF1 *errparamtib=new TF1("error_paramtib","((x-[0])*(x-[0])*([1]-[2])/([0]*[0])+[2])",0.01,4);
  errparamtib->SetParameter(0,38.07*0.032);
  errparamtib->SetParameter(1,0.3184);
  errparamtib->SetParameter(2,0.09828);
  TF1 *errparamtob=new TF1("error_paramtob","((x-[0])*(x-[0])*([1]-[2])/([0]*[0])+[2])",0.01,4);
  errparamtob->SetParameter(0,38.07*0.05);
  errparamtob->SetParameter(1,0.3184);
  errparamtob->SetParameter(2,0.09828);

  //  TF1 *newparam=new TF1("error_param","(((x-[0])*(x-[0])*([1]-[2])/([0]*[0]))*(([3]-x)/[3])+[2])*(((x-[0])*(x-[0])*([1]-[2])/([0]*[0]))*(([3]-x)/[3])+[2])",0,8); 
  TF1 *newparam=new TF1("error_param","[0]*x*exp(-x*[1])+[2]",0.,4);
  //TF1 *newparam=new TF1("error_param","[0]*exp(-0.5*((x-[3])/[1])**2)+[2]*x",0.0001,8);
  // TF1 *newparam=new TF1("error_param",fit_func,0.0001,8,4);
  newparam->SetParameter(0,-0.339);
  newparam->SetParameter(1,0.9);
  newparam->SetParameter(2,0.279);
  // newparam->SetParameter(3,0.25);
  gROOT->SetStyle("Plain");
  //  gStyle->SetOptTitle(1);

 TCanvas * plot=new TCanvas("resolution","resolution");
 plot->Divide(2,2,0.001,0.001);
  plot->cd(1);
  TIB->SetMaximum(0.4);
  TIB->SetMinimum(0.);
  TIB->GetHistogram()->GetXaxis()->SetTitle("W_{track}");
  TIB->GetHistogram()->GetYaxis()->SetTitle("Resolution");
  TIB->GetHistogram()->SetTitle("TIB");
  TIB->GetHistogram()->GetXaxis()->SetRangeUser(0,4);
  TIB->Draw("ap");
  //  TIB->Fit(newparam);
  TLine *l=new TLine(0,1./sqrt(12),4,1./sqrt(12));
  l->SetLineColor(3);
  l->SetLineWidth(2);
//   l->Draw("same");
//   errparamtib->SetLineColor(4);
//   errparamtib->Draw("same");
//   newparam->Draw("same");

  plot->cd(2);
  TOB->SetMaximum(0.4);
  TOB->SetMinimum(0.);
  TOB->GetHistogram()->GetXaxis()->SetTitle("W_{track}");
  TOB->GetHistogram()->GetYaxis()->SetTitle("Resolution");
  TOB->GetHistogram()->GetXaxis()->SetRangeUser(0,4);
  TOB->GetHistogram()->SetTitle("TOB");
  TOB->Draw("ap");
  //  TOB->Fit(newparam);
  TLine *l=new TLine(0,1./sqrt(12),4,1./sqrt(12));
  l->SetLineColor(3);
  l->SetLineWidth(2);
//   l->Draw("same");
//   errparamtob->SetLineColor(4);
//   errparamtob->Draw("same");
//   newparam->Draw("same");

  plot->cd(3);
  TID->SetMaximum(0.4);
  TID->SetMinimum(0.);
  TID->GetHistogram()->GetXaxis()->SetTitle("W_{track}");
  TID->GetHistogram()->GetYaxis()->SetTitle("Resolution");
  TID->GetHistogram()->GetXaxis()->SetRangeUser(0,4);
  TID->GetHistogram()->SetTitle("TID");
  TID->Draw("ap");
  //  TID->Fit(newparam);
  TLine *l=new TLine(0,1./sqrt(12),4,1./sqrt(12));
  l->SetLineColor(3);
//   l->Draw("same");
//   errparamtib->SetLineColor(4);
//   errparamtib->Draw("same");
//   newparam->Draw("same");

  plot->cd(4);
  TEC->SetMaximum(0.4);
  TEC->SetMinimum(0.);
  TEC->GetHistogram()->GetXaxis()->SetTitle("W_{track}");
  TEC->GetHistogram()->GetYaxis()->SetTitle("Resolution");
  TEC->GetHistogram()->GetXaxis()->SetRangeUser(0,4);
  TEC->GetHistogram()->SetTitle("TEC");
  TEC->Draw("ap");
  //  TEC->Fit(newparam);
  TLine *l=new TLine(0,1./sqrt(12),4,1./sqrt(12));
  l->SetLineColor(3);
  l->SetLineWidth(2);
//   l->Draw("same");
//   newparam->Draw("same");
//    gStyle->SetOptTitle(0);
    gStyle->SetOptFit(1111);

 TCanvas * plot2=new TCanvas("resolution2","resolution2");
 ALL->SetMaximum(0.4);
 ALL->SetMinimum(0.);
 ALL->GetHistogram()->SetTitle("Hit resolution");
 ALL->GetHistogram()->SetMarkerStyle(20);
 ALL->GetHistogram()->GetXaxis()->SetTitle("Track projection (n. strip)");
 ALL->GetHistogram()->GetYaxis()->SetTitle("Resolution (units of pitch)");
 ALL->GetHistogram()->GetXaxis()->SetRangeUser(0,4);
 ALL->Draw("ap");
 ALL->Fit(newparam);
 TLine *l=new TLine(0,1./sqrt(12),4,1./sqrt(12));
 l->SetLineColor(3);
 // l->Draw("same");
  param_old->SetLineColor(kRed); 
  param_old->Draw("same");
}
