autoDQM = { 'common' : ['DQMOfflineCommon',
                        'DQMHarvestCommon+DQMCertCommon'],
            'commonSiStripZeroBias' : ['DQMOfflineCommonSiStripZeroBias',
                                       'DQMHarvestCommonSiStripZeroBias+DQMCertCommon'],
            'trackingOnlyDQM' : ["DQMOfflineTracking",
                             "DQMHarvestTracking"],
            'muon': ['DQMOfflineMuon',
                     'DQMHarvestMuon+DQMCertMuon'],
            'hcal':     ['DQMOfflineHcal',
                         'DQMHarvestHcal+DQMCertHcal'],
            'jetmet':  ['DQMOfflineJetMET',
                        'DQMHarvestJetMET+DQMCertJetMET'],
            'ecal':       ['DQMOfflineEcal',
                           'DQMHarvestEcal+DQMCertEcal'],
            'egamma':       ['DQMOfflineEGamma',
                           'DQMHarvestEGamma'],
            'btag':       ['DQMOfflineBTag',
                           'DQMHarvestBTag'],
            'HLTMon':     ['HLTMonitoring',
                           'HLTMonitoringClient'],
            'express':       ['@commonSiStripZeroBias+@muon+@hcal+@jetmet+@ecal',
                              '@commonSiStripZeroBias+@muon+@hcal+@jetmet+@ecal'],
            'allForPrompt':  ['@common+@muon+@hcal+@jetmet+@ecal',
                              '@common+@muon+@hcal+@jetmet+@ecal'],

            'miniAODDQM': ['DQMOfflineMiniAOD','DQMOfflineMiniAODEndPath',
                        'DQMHarvestMiniAOD'],
            'standardDQM': ['DQMOffline','DQMOfflineEndPath',
                            'dqmHarvesting'],
            'standardDQMFakeHLT': ['DQMOfflineFakeHLT',
                                   'dqmHarvestingFakeHLT']
            }

