#! /bin/bash
#
# generate HLT tables from master table in ConfDB
#

MASTER="/dev/CMSSW_14_1_0/HLT"                      # no version, take the latest one
TARGET="/online/collisions/2024/HIon/v1.0/HLT"      # where to store the online-compliant menu
PREFIX=""
TABLES="online_hion"

source subtables.sh
createSubtables "v3/run3" "$MASTER" "$TARGET" "$PREFIX" "$TABLES"
