#! /bin/bash
#
# generate HLT tables from master table in ConfDB
#

MASTER="/dev/CMSSW_4_2_0/HLT"                   # no version, take the latest one
TARGET="/online/cosmics/2011/3e33/v1.1/HLT"     # where to store the online-compliant menu
TABLES="cosmics"

source subtables.sh
createSubtables "hltdev" "$MASTER" "$TARGET" "$TABLES"
