#! /bin/bash
#
# generate HLT tables from master table in ConfDB
#

MASTER="/dev/CMSSW_13_3_0/HLT"                 # no version, take the latest one
TARGET="/online/special/2024/v1.0/HLT" # where to store the online-compliant menu
TABLES="online_special"

source subtables.sh
createSubtables "v3/run3" "$MASTER" "$TARGET" "$TABLES"
