#! /bin/bash
#
# generate HLT tables from master table in ConfDB
#

MASTER="/dev/CMSSW_4_2_0/HLT"                   # no version, take the latest one
TARGET="/online/collisions/2011/1e33/v2.3/HLT"  # where to store the online-compliant menu
TABLES="online"

source subtables.sh
createSubtables "hltdev" "$MASTER" "$TARGET" "$TABLES"
