#! /bin/bash
#
# generate HLT tables from master table in ConfDB
#

MASTER="/dev/CMSSW_4_2_0/HLT"                       # no version, take the latest one
TARGET="/online/collisions/2011/1.4e33/v1.0/HLT"    # where to store the online-compliant menu
TABLES="online"

source subtables.sh
createSubtables "hltdev" "$MASTER" "$TARGET" "$TABLES"
