#! /bin/bash
#
# generate HLT tables from master table in ConfDB
#

MASTER="/dev/CMSSW_14_0_0/HLT"                 # no version, take the latest one
TARGET="/online/collisions/2024/2e34/v1.2/HLT" # where to store the online-compliant menu
PREFIX=""
TABLES="online_grun"

source subtables.sh
createSubtables "v3/run3" "$MASTER" "$TARGET" "$PREFIX" "$TABLES"
