#! /bin/bash
#
# generate HLT tables from master table in ConfDB
#

MASTER="/dev/CMSSW_8_0_0/HLT"                        # no version, take the latest one
TARGET="/online/collisions/2016/ProtonIon/v1.0/HLT"  # where to store the online-compliant menu
TABLES="online_pion"

source subtables.sh
createSubtables "v2/offline" "$MASTER" "$TARGET" "$TABLES"
