#! /bin/bash
#
# generate HLT tables from master table in ConfDB
#

MASTER="/dev/CMSSW_7_4_0/HLT"           # no version, take the latest one
TARGET="/dev/CMSSW_7_4_0/TABLE"         # directory where to store the sub-tables
TABLES="GRun HIon PIon"                 # which sub-tables to create

source subtables.sh
createSubtables "hltdev" "$MASTER" "$TARGET" "$TABLES"
