#! /bin/bash
#
# generate HLT tables from master table in ConfDB
#

MASTER="/dev/CMSSW_10_1_0/HLT"                 # no version, take the latest one
TARGET="/online/collisions/2018/2e34/v2.2/HLT" # where to store the online-compliant menu
TABLES="online_grun"

source subtables.sh
createSubtables "v2/offline" "$MASTER" "$TARGET" "$TABLES"
