#! /bin/bash
#
# generate HLT tables from master table in ConfDB
#

echo
echo "Create online version of the combined Special subtable"
echo
MASTER="/dev/CMSSW_14_1_0/HLT"             # no version, take the latest one
TARGET="/online/special/2024/v1.6/TABLE"   # where to store the online-compliant menu
PREFIX="online_"
TABLES="Special"

source subtables.sh
createSubtables "v3/run3" "$MASTER" "$TARGET" "$PREFIX" "$TABLES"

echo
echo "Create online versions of special subtables from combined Special table"
echo

MASTER="/online/special/2024/v1.6/Special" # no version, take the latest one
TARGET="/online/special/2024/v1.6/TABLE"   # where to store the online-compliant menu
PREFIX="online_"
TABLES="Circulating Cosmics ECAL FirstCollisions LumiScan PPS Splashes TrackerVR"

source subtables.sh
createSubtables "v3/run3" "$MASTER" "$TARGET" "$PREFIX" "$TABLES"
