#! /bin/bash
#
# generate HLT tables from master table in ConfDB
#

MASTER="/dev/CMSSW_7_4_0/50nsHLT"                   # no version, take the latest one
TARGET="/online/collisions/2015/50ns_5e33/v2.1/HLT" # where to store the online-compliant menu
TABLES="online_50nsgrun"

source subtables.sh
createSubtables "hltdev" "$MASTER" "$TARGET" "$TABLES"
