from DQMOffline.L1Trigger.LegacyL1TriggerDqmOffline_cff import *
#replacements for stage2
import DQMOffline.L1Trigger.Stage2L1TriggerDqmOffline_cff as stage2_cffs_
stage2L1Trigger.toReplaceWith(l1TriggerOnline, stage2_cffs_.l1TriggerOnline)
stage2L1Trigger.toReplaceWith(l1TriggerEmulatorOnline, stage2_cffs_.l1TriggerEmulatorOnline)
stage2L1Trigger.toReplaceWith(l1TriggerDqmOffline, stage2_cffs_.l1TriggerDqmOffline)
stage2L1Trigger.toReplaceWith(l1TriggerDqmOfflineClient, stage2_cffs_.l1TriggerDqmOfflineClient)
