import FWCore.ParameterSet.Config as cms

from RecoTracker.CkfPattern.CkfTrajectoryBuilderESProducer_cff import *
import copy
from RecoTracker.CkfPattern.CkfTrajectoryBuilderESProducer_cfi import *
#TrajectoryBuilder
TrajectoryBuilderForPixelMatchElectronsL1IsoLargeWindow = copy.deepcopy(CkfTrajectoryBuilder)
# Navigation School record
from RecoTracker.TkNavigation.NavigationSchoolESProducer_cff import *
import copy
from RecoEgamma.EgammaHLTProducers.pixelMatchElectronsForHLT_cfi import *
#pixelMatchedElectrons
pixelMatchElectronsL1IsoLargeWindowForHLT = copy.deepcopy(pixelMatchElectronsForHLT)
TrajectoryBuilderForPixelMatchElectronsL1IsoLargeWindow.ComponentName = 'TrajectoryBuilderForPixelMatchElectronsL1IsoLargeWindow'
TrajectoryBuilderForPixelMatchElectronsL1IsoLargeWindow.estimator = 'egammaHLTChi2'
pixelMatchElectronsL1IsoLargeWindowForHLT.TrackProducer = 'ctfL1IsoLargeWindowWithMaterialTracks'
pixelMatchElectronsL1IsoLargeWindowForHLT.TrajectoryBuilder = 'TrajectoryBuilderForPixelMatchElectronsL1IsoLargeWindow'

