//-------------------------------------------------
//
/** \class L1MuGMTLFSortRankPtQLUT
 *
 *   LFSortRankPtQ look-up table
 *          
 *   this class was automatically generated by 
 *     L1MuGMTLUT::MakeSubClass()  
*/ 
//   $Date: 2007/04/02 15:45:39 $
//   $Revision: 1.3 $
//
//   Author :
//   H. Sakulin            HEPHY Vienna
//
//   Migrated to CMSSW:
//   I. Mikulec
//
//--------------------------------------------------
#ifndef L1TriggerGlobalMuonTrigger_L1MuGMTLFSortRankPtQLUT_h
#define L1TriggerGlobalMuonTrigger_L1MuGMTLFSortRankPtQLUT_h

//---------------
// C++ Headers --
//---------------


//----------------------
// Base Class Headers --
//----------------------
#include "L1Trigger/GlobalMuonTrigger/src/L1MuGMTLUT.h"

//------------------------------------
// Collaborating Class Declarations --
//------------------------------------

//              ---------------------
//              -- Class Interface --
//              ---------------------


class L1MuGMTLFSortRankPtQLUT : public L1MuGMTLUT {
  
 public:
  enum {DT, BRPC, CSC, FRPC};

  /// constuctor using function-lookup
  L1MuGMTLFSortRankPtQLUT() : L1MuGMTLUT("LFSortRankPtQ", 
				       "DT BRPC CSC FRPC",
				       "q(3) pt(5)",
				       "rank_ptq(7)", 7, false) {
    InitParameters();
  } ;

  /// destructor
  virtual ~L1MuGMTLFSortRankPtQLUT() {};

  /// specific lookup function for rank_ptq
  unsigned SpecificLookup_rank_ptq (int idx, unsigned q, unsigned pt) const {
    std::vector<unsigned> addr(2);
    addr[0] = q;
    addr[1] = pt;
    return Lookup(idx, addr) [0];
  };

  /// specific lookup function for entire output field
  unsigned SpecificLookup (int idx, unsigned q, unsigned pt) const {
    std::vector<unsigned> addr(2);
    addr[0] = q;
    addr[1] = pt;
    return LookupPacked(idx, addr);
  };



  /// access to lookup function with packed input and output

  virtual unsigned LookupFunctionPacked (int idx, unsigned address) const {
    std::vector<unsigned> addr = u2vec(address, m_Inputs);
    return TheLookupFunction(idx ,addr[0] ,addr[1]);

  };

 private:
  /// Initialize scales, configuration parameters, alignment constants, ...
  void InitParameters();

  /// The lookup function - here the functionality of the LUT is implemented
  unsigned TheLookupFunction (int idx, unsigned q, unsigned pt) const;

  /// Private data members (LUT parameters);
};
#endif



















