#!/bin/sh

for v in `pwd | sed 's|.*/IGUANA_||; s|/.*||'`; do
#   set --
#   UTILSDIR=`pwd`
#   DEPDIR=$HOME/scratch/deps/iguana/$1/$2
#   DIST=/afs/cern.ch/cms/Releases/IGUANA/IGUANA_$1

  set -- $v ${1+"$@"} ${1-linux}

  UTILSDIR=`pwd`/src/Ig_Infrastructure/IgNominy/src
  DEPDIR=`pwd`/doc/deps/$2
  DIST=`pwd`
  APP="IGUANA `echo $1 | sed 's/_/./g'`"

  export UTILSDIR DEPDIR DIST APP

  [ -z $CMS_PATH ] && CMS_PATH=/afs/cern.ch/cms
  export CMS_PATH

  # PATH=$UTILSDIR:$PATH:/afs/cern.ch/cms/Releases/sw/Linux__2.2/graphviz-1.7a/bin
  # LD_LIBRARY_PATH=${LD_LIBRARY_PATH+"$LD_LIBRARY_PATH:"}/usr/local/gcc-alt-2.95.2/lib
  # export PATH LD_LIBRARY_PATH
  PATH=$UTILSDIR:$PATH
  export PATH

  $UTILSDIR/mkconfs $2
  $UTILSDIR/mklogicalmap $2
  $UTILSDIR/mkdeps $2
  $UTILSDIR/mkgraphs $2
  $UTILSDIR/mkxdeps $2
  $UTILSDIR/mkmetrics $2
  $UTILSDIR/mkgifs $2
  $UTILSDIR/mkdirindex $2
done
