#!/bin/sh

binsel="Direct binary"
srcsel="Direct source"
comsel="Direct combined"

apps="Examples Applications"
globs=

deps2metrics $DEPDIR/dependencies.txt "$comsel" no $apps $globs > $DEPDIR/metrics
