#!/bin/sh

pkgsel="no Ig_Applications Examples QPlotter QpAdapters Qwt AIDA qxt LessTif"
confp="--group=$UTILSDIR/group-purpose.conf --rename=$UTILSDIR/rename-origin.conf"
confo="--group=$UTILSDIR/group-origin.conf --rename=$UTILSDIR/rename-origin.conf"
globs=

grep 'source dependency' $DEPDIR/log | \
  sed 's/^ *//; s/: source dependency on//; s/ via.*//;' | \
  egrep -v '<.*>' | \
  sort | uniq -c > $DEPDIR/xdeps.inc

grep 'source dependency' $DEPDIR/log | \
  sed 's/^ *//; s/: source dependency on//;' | \
  egrep -v '<.*>' | \
  sort | uniq -c > $DEPDIR/xdeps.incdetail

grep '^binary .* found in ' $DEPDIR/log | \
  sed 's/^binary /s%/; s/ found in /($| )%/; s/$/$1%go;/; s/+/\\+/g' > /tmp/$$.perl

grep '^.*: .*: resolved from ' $DEPDIR/log | \
  sed 's/: .*: resolved from / /;' | \
  perl -ne '/^(\S+)\s+(\S+(,\s+\S+)*)$/; map { print "$1 $_\n" } split(/,\s+/,$2)' \
  > /tmp/$$.lib-raw

sort < /tmp/$$.lib-raw | uniq -c > $DEPDIR/xdeps.lib-raw
perl -p /tmp/$$.perl < /tmp/$$.lib-raw | egrep -v '<.*>' | sort | uniq -c > $DEPDIR/xdeps.lib

xmerge $confp $DEPDIR/xdeps.inc $DEPDIR/xdeps.lib $pkgsel $globs > $DEPDIR/xdeps.all
xmerge $confp --side-by-side $DEPDIR/xdeps.inc $DEPDIR/xdeps.lib $pkgsel $globs> $DEPDIR/xdeps-purpose.ps
xmerge $confo --side-by-side $DEPDIR/xdeps.inc $DEPDIR/xdeps.lib $pkgsel $globs> $DEPDIR/xdeps-origin.ps

(echo 'h3.page-break { page-break-before: always; }'
 echo '@html2ps {'
 echo '  margin { left: 1cm; right 1cm; top: 1cm; bottom: 1cm }'
 echo '  font { arial { names: "Helvetica Helvetica-Oblique Helvetica-Bold Helvetica-BoldOblique" } }'
 echo '}'
 echo 'ol { font-family: arial, helvetica, sans-serif; font-size: 7pt; }'
 echo 'table { font-family: arial, helvetica, sans-serif; font-size: 7pt; }'
 echo 'td { font-family: arial, helvetica, sans-serif; font-size: 7pt; text-align: center; }'
 echo 'th { font-family: arial, helvetica, sans-serif; font-size: 7pt; font-weight: normal; }'
 ) > $DEPDIR/xdeps.css
(echo "<HTML><TITLE>$APP Dependency Statistics</TITLE>"
 echo '<LINK REL="stylesheet" href="xdeps.css" type="text/css">'
 echo '<BODY>'
 xmerge $confp --html $DEPDIR/xdeps.inc $DEPDIR/xdeps.lib $pkgsel $globs
 echo '</BODY></HTML>') > $DEPDIR/xdeps.html

# html2ps -U -L -f $DEPDIR/xdeps.css $DEPDIR/xdeps.html > $DEPDIR/xdeps.html.ps
rm -f /tmp/$$.perl /tmp/$$.lib-raw
