#!/bin/tcsh

## $1 is the final iteration number
## $2 is output directory
## $3 is a list of data files
## $4 is the IOV file
## $5 is the common config. file name
## $6 is the align config file name
## $7 is the track selection config
## $8 is the surface deformations flag
## $9 is the proxy redirection flag
## $10 Dry run option (0 by default) (note: more than 9 parameters need curly brackets)

# setup environment: have call script from Package/Subpackage dir
cd ../..
# cmsenv
eval `scramv1 runtime -csh`
cd Alignment/HIPAlignmentAlgorithm

mkdir -p $2
set odir = `cd $2; pwd` # get full output path
set errfile = "$odir/ERROR"

# configure all of the scripts
configureHippy.pl $odir $3 $4 $5 $6 $7 $8 $9

if ( -f $errfile ) then
   echo "$errfile exists! Please fix the errors and re-run."
else
  cp scripts/runControl.csh $odir/main/

  # submit parallel jobs
  if (  ${10} == 0 ) then
    submitJobs_py $1 $2 $4
    # create DB objects
    cp $odir/main/IOAlignedPositions*.root $odir/main/IOIteration*.root $odir/
  else
    echo "Dry run setup complete"
  endif
endif