#!/bin/tcsh -f

##########################################
# root
cd root
  root -q -b -l analyzer.C
cd ..
endif

##########################################
# gnu
cd gnu
foreach prod (PbPb)
foreach type (Pixel Global)

  set dir = {$prod}{$type}
  echo $dir

  ln -fs ../out/$dir out
  ln -fs ../eps/$dir eps
  foreach file (*.gnu)
    echo " "$file
    gnuplot $file #>& /dev/null
  end
  rm out eps
  
  echo " epstopdf"
  cd ../eps/$dir
  foreach file (*.eps)
    epstopdf $file
  end
  cd ../../gnu

end
end
cd ..

##########################################
# tex
cd tex
  cat header.tex                          >  performance.tex

  perl -pe 's|xxx|ppPixel|g'    plots.tex >> performance.tex
  perl -pe 's|xxx|ppGlobal|g'   plots.tex >> performance.tex

  perl -pe 's|xxx|PbPbPixel|g'  plots.tex >> performance.tex
  perl -pe 's|xxx|PbPbGlobal|g' plots.tex >> performance.tex

  cat footer.tex                          >> performance.tex

  pdflatex performance.tex
  pdflatex performance.tex
  mv performance.pdf ../pdf
cd ..
