#!/bin/tcsh
oval run publish.ValFastVsFullTTbarStartup_gedGsfE
oval run publish.ValFastVsFullZEEStartup_gedGsfE
oval run publish.ValFastVsFastTTbarStartup_gedGsfE
oval run publish.ValFastVsFastZEEStartup_gedGsfE
