import FWCore.ParameterSet.Config as cms

from CommonTools.RecoAlgos.trackingParticleRefSelector_cfi import trackingParticleRefSelector as _trackingParticleRefSelector
cutsTPEffic = _trackingParticleRefSelector.clone()
