CREATE TABLE Question(id INTEGER PRIMARY KEY NOT NULL, title TEXT NOT NULL, place INTEGER NOT NULL, is_separator INTEGER NOT NULL DEFAULT 0);
CREATE TABLE Option( id INTEGER PRIMARY KEY NOT NULL, question_id INTEGER NOT NULL, place INTEGER NOT NULL, title TEXT NOT NULL, is_text INTEGER NOT NULL, is_radio INTEGER NOT NULL, is_checkbox INTEGER NOT NULL, is_commentable INTEGER, is_comment INTEGER NOT NULL DEFAULT 0);
CREATE TABLE Response(id INTEGER PRIMARY KEY NOT NULL, questionnaire_id INTEGER NOT NULL, selected INTEGER NOT NULL, text TEXT NOT NULL, option_id INTEGER NOT NULL, tier INTEGER NOT NULL DEFAULT 0);
CREATE TABLE Questionnaire( id INTEGER PRIMARY KEY NOT NULL, publication_number TEXT, tiers INTEGER, email TEXT NOT NULL DEFAULT ' ', password TEXT NOT NULL DEFAULT ' ');
