import FWCore.ParameterSet.Config as cms

from Validation.HGCalValidation.caloparticlevalidationDefault_cfi import caloparticlevalidationDefault as _caloparticlevalidationDefault
caloparticlevalidation = _caloparticlevalidationDefault.clone()
