def btaglayout(i, p, *rows): i["Btag/Layouts/" + p] = DQMItem(layout=rows)

btaglayout(dqmitems, "00 - Jet Property",
 [{ 'path': "Btag/TCHP_GLOBAL/jetMultiplicity_TCHP_GLOBALALL",
    'description': "Jet Multiplicity ",
    'draw': { 'withref': "no" }},
  { 'path': "Btag/TCHP_GLOBAL/jetPt_TCHP_GLOBALALL",
    'description': "Jet Pt ",
    'draw': { 'withref': "no" }}],
 [{ 'path': "Btag/TCHP_GLOBAL/jetEta_TCHP_GLOBALALL",
    'description': "Jet Eta ",
    'draw': { 'withref': "no" }},
  { 'path': "Btag/TCHP_GLOBAL/jetPhi_TCHP_GLOBALALL",
    'description': "Jet Phi ",
    'draw': { 'withref': "no" }}])
btaglayout(dqmitems, "01 - Tracks in Jet",
 [{ 'path': "Btag/IPTag_GLOBAL/selectedTrackMultVsJetPt_IPTag_GLOBALALL",
    'description': "Track Multiplicity vs Jet Pt for Selected Tracks Associated to Jets",
    'draw': { 'withref': "no" }},
  { 'path': "Btag/IPTag_GLOBAL/trackMultVsJetPt_IPTag_GLOBALALL",
    'description': "Track Multiplicity vs Jet Pt for Tracks Associated to Jets",
    'draw': { 'withref': "no" }}],
 [{ 'path': "Btag/IPTag_GLOBAL/selectedTrackQual_IPTag_GLOBALALL",
    'description': "Track Quality of Selected Tracks Associated to Jets",
    'draw': { 'withref': "no" }},
  { 'path': "Btag/IPTag_GLOBAL/trackQual_IPTag_GLOBALALL",
    'description': "Track Quality of Tracks Associated to Jets",
    'draw': { 'withref': "no" }}])
btaglayout(dqmitems, "02 - Vertex Property",
 [{ 'path': "Btag/CSVTag_GLOBAL/vertexCategoryALL",
    'description': "Category of Secondary Vertex (Reco, Pseudo, No) ",
    'draw': { 'withref': "no" }},
  { 'path': "Btag/CSVTag_GLOBAL/vertexMassALL",
    'description': "Mass of Track sum at Secondary Vertex  ",
   'draw': { 'withref': "no" }}],    
 [{ 'path': "Btag/CSVTag_GLOBAL/vertexEnergyRatioALL",
    'description': "Ratio of Energy at secondary vertex over Total Energy ",
    'draw': { 'withref': "no" }},
  { 'path': "Btag/CSVTag_GLOBAL/vertexNTracksALL",
    'description': "Number of Tracks at Secondary Vertex ",
   'draw': { 'withref': "no" }},
  { 'path': "Btag/CSVTag_GLOBAL/vertexJetDeltaRALL",
    'description': "Pseudoangular Distance between Jet Axis and Secondary Vertex Direction",
   'draw': { 'withref': "no" }}])    
btaglayout(dqmitems, "03 - Flight Distance Summary",
 [{ 'path': "Btag/CSVTag_GLOBAL/flightDistance2dValALL",
    'description': "Transverse Distance between Primary and Secondary Vertex ",
    'draw': { 'withref': "no" }},
  { 'path': "Btag/CSVTag_GLOBAL/flightDistance3dValALL",
    'description': "Distance between Primary and Secondary Vertex  ",
   'draw': { 'withref': "no" }}],    
 [{ 'path': "Btag/CSVTag_GLOBAL/flightDistance2dSigALL",
    'description': "Transverse Distance Significance between Primary and Secondary vertex all jets",
    'draw': { 'withref': "no" }},
  { 'path': "Btag/CSVTag_GLOBAL/flightDistance3dSigALL",
    'description': "distance significance between primary and secondary vertex all jets ",
   'draw': { 'withref': "no" }}])    
btaglayout(dqmitems, "04 - Discriminator Summary",
 [{ 'path': "Btag/CSV_GLOBAL/discr_CSV_GLOBALALL",
    'description': "Discriminator for CombinedSecondaryVertex ",
    'draw': { 'withref': "no" }},
  { 'path': "Btag/GhTrk_GLOBAL/discr_GhTrk_GLOBALALL",
    'description': "Discriminator for GhostTrack ",
    'draw': { 'withref': "no" }},    
  { 'path': "Btag/JBP_GLOBAL/discr_JBP_GLOBALALL",
    'description': "Discriminator for jetBProbabilityBJetTags ",
    'draw': { 'withref': "no" }},
  { 'path': "Btag/JP_GLOBAL/discr_JP_GLOBALALL",
    'description': "Discriminator for JetProbability ",
    'draw': { 'withref': "no" }},
  { 'path': "Btag/SSVHE_GLOBAL/discr_SSVHE_GLOBALALL",
    'description': "Discriminator for SimpleSecondaryVertexHighEff ",
    'draw': { 'withref': "no" }}],           
 [{ 'path': "Btag/TCHE_GLOBAL/discr_TCHE_GLOBALALL",
    'description': "Discriminator for TrackCountingHighEff ",
    'draw': { 'withref': "no" }},
  { 'path': "Btag/TCHP_GLOBAL/discr_TCHP_GLOBALALL",
    'description': "Discriminator for TrackCountingHighPur ",
    'draw': { 'withref': "no" }},
  { 'path': "Btag/SMT_GLOBAL/discr_SMT_GLOBALALL",
    'description': "Discriminator for SoftMuonB ",
    'draw': { 'withref': "no" }},           
  { 'path': "Btag/SMTIP3d_GLOBAL/discr_SMTIP3d_GLOBALALL",
    'description': "Discriminator for SoftMuonByIP3D ",
    'draw': { 'withref': "no" }},           
  { 'path': "Btag/SMTPt_GLOBAL/discr_SMTPt_GLOBALALL",
    'description': "Discriminator for SoftMuonByPt ",
    'draw': { 'withref': "no" }}])
btaglayout(dqmitems, "05 - 2D-Impact Parameter",
 [{ 'path': "Btag/IPTag_GLOBAL/ip_2D_IPTag_GLOBALALL",
    'description': "2D Impact Parameter Value",
    'draw': { 'withref': "no" }},
  { 'path': "Btag/IPTag_GLOBAL/ipe_2D_IPTag_GLOBALALL",
    'description': "2D Impact Parameter Error",
    'draw': { 'withref': "no" }},
  { 'path': "Btag/IPTag_GLOBAL/prob_2D_IPTag_GLOBALALL",
    'description': "2D Impact Parameter Probability",
    'draw': { 'withref': "no" }}],
 [{ 'path': "Btag/IPTag_GLOBAL/tkNHits_2D_IPTag_GLOBALALL",
    'description': "# of Hits in Tracks used in 2D Impact Parameter",
    'draw': { 'withref': "no" }},
  { 'path': "Btag/IPTag_GLOBAL/tkNChiSqr_2D_IPTag_GLOBALALL",
    'description': "Chi2Sq of Tracks used in 2D Impact Parameter",
    'draw': { 'withref': "no" }},
  { 'path': "Btag/IPTag_GLOBAL/decLen_2D_IPTag_GLOBALALL",
    'description': "2D Decay Length",
    'draw': { 'withref': "no" }},
  { 'path': "Btag/IPTag_GLOBAL/jetDist_2D_IPTag_GLOBALALL",
    'description': "2D Jet Distance",
    'draw': { 'withref': "no" }}])
btaglayout(dqmitems, "06 - 3D-Impact Parameter",
 [{ 'path': "Btag/IPTag_GLOBAL/ip_3D_IPTag_GLOBALALL",
    'description': "3D Impact Parameter Value",
    'draw': { 'withref': "no" }},
  { 'path': "Btag/IPTag_GLOBAL/ipe_3D_IPTag_GLOBALALL",
    'description': "3D Impact Parameter Error",
    'draw': { 'withref': "no" }},
  { 'path': "Btag/IPTag_GLOBAL/prob_3D_IPTag_GLOBALALL",
    'description': "3D Impact Parameter Probability",
    'draw': { 'withref': "no" }},
  { 'path': "Btag/IPTag_GLOBAL/ips_3D_IPTag_GLOBALALL",
    'description': "3D Impact Parameter Significance",
    'draw': { 'withref': "no" }},
  { 'path': "Btag/IPTag_GLOBAL/ips1_3D_IPTag_GLOBALALL",
    'description': "3D Impact Parameter Significance 1-Track",
    'draw': { 'withref': "no" }}],
 [{ 'path': "Btag/IPTag_GLOBAL/tkPt_3D_IPTag_GLOBALALL",
    'description': "Pt 3D of Tracks used in 3D Impact Parameter",
    'draw': { 'withref': "no" }},
  { 'path': "Btag/IPTag_GLOBAL/tkNChiSqr_3D_IPTag_GLOBALALL",
    'description': "Chi2Sq of Tracks used in 3D Impact Parameter",
    'draw': { 'withref': "no" }},
  { 'path': "Btag/IPTag_GLOBAL/tkNHits_3D_IPTag_GLOBALALL",
    'description': "# of Hits in Tracks used in 3D Impact Parameter",
    'draw': { 'withref': "no" }},
  { 'path': "Btag/IPTag_GLOBAL/decLen_3D_IPTag_GLOBALALL",
    'description': "3D Decay Length",
    'draw': { 'withref': "no" }},
  { 'path': "Btag/IPTag_GLOBAL/jetDist_3D_IPTag_GLOBALALL",
    'description': "3D Jet Distance",
    'draw': { 'withref': "no" }}])
           
