server.service('Online',           'https://cmsweb.cern.ch/dqm/online')
server.service('Online playback',  'https://cmsweb.cern.ch/dqm/online-playback')
server.service('Offline',          'https://cmsweb.cern.ch/dqm/offline')
server.service('RelVal',           'https://cmsweb.cern.ch/dqm/relval')
server.service('CAF',              'https://cmsweb.cern.ch/dqm/caf')
server.service('Development',      'https://cmsweb.cern.ch/dqm/dev')
