#!/bin/zsh

# Set parameters. Use the latest installed server by default.
DQMV=${1:-latest}
ARCH=slc4_ia32_gcc345
HOST=$(hostname)
NOW=$(date +%Y%m%d%H%M%S)

case $HOST in
  srv-* ) DQM_DIR=/home/dqm DQM_SW=/home/dqm/rpms DQM_DATA=/dqmdata/dqm ;;
  vocms* ) DQM_DIR=/data/dqm DQM_SW=/data/sw ;;
esac

if [ X"$DQMV" = Xlatest ]; then
  DQMV=$(ls -tr $DQM_SW/$ARCH/cms/dqmgui | tail -1)
fi

# Source server environment. Move to $DQM_DIR so cwd is safe.
cd $DQM_DIR
. $DQM_SW/cmsset_default.sh
. $DQM_SW/$ARCH/cms/dqmgui/$DQMV/etc/profile.d/env.sh

# Verify invocation came from documented (copy-and-paste) instructions.
CHECK=$(echo -n "$2" | tr -c '[A-Za-z]' '_' | tr '[:upper:]' '[:lower:]')
if { ps -oargs= $PPID | grep -q -e /restart; } || \
   [ X"$CHECK" = Xi_did_read_documentation ]; then :; else
  echo "$0: cannot complete request, please check documentation."
  exit 1
fi

# Start file handling agents.
echo "$0: cannot complete request, please check documentation."
exit 2
for D in offline caf dev; do
  DQM_DATA=/data/dqm/$D
  mkdir -p $DQM_DATA/agents
  cd $DQM_DATA
  (for f in $(find $DQM_DATA/old/data -name '*.root.origin' | sort); do
     if [ $(find $DQM_DATA/repository/data -name $(basename ${f%.origin}) | wc -l) = 0 ]; then
       v=$(basename $f | sed 's/.*_V\([0-9][0-9][0-9][0-9]\)_.*/\1/')
       b=$DQM_DATA/uploads2/$v/$(basename $f | sed s/_V${v}_/_V0001_/)
       if [ ! -f $b -a ! -f $b.bad ]; then
         mkdir -p $(dirname $b)
         ln $f $b
         ln ${f%.origin} ${b%.origin}
       fi
     fi
   done) >>& $DQM_DATA/agents/upload-$NOW.log </dev/null &
done
