#!/bin/tcsh
cd xCMSSW_BASEx/src
cmsenv
setenv STAGE_SVCCLASS cmscaf
set run=xRUN_NAMEx
set job=xJOB_NAMEx
set tmpdir=/tmp/$USER/$run/$job
mkdir -p $tmpdir
cd xCURRENT_DIRx/$run/$job
cmsRun SiStripDQMOfflineGlobalRunCAFxSUFFIXx >! DQM_SiStrip_${run}.log
xCOPYx $tmpdir/DQM_SiStrip_${run}.root xOUTPUT_DIRx/DQM_SiStrip_${job}.root
xCOPYx DQM_SiStrip_${run}.log xOUTPUT_DIRx/DQM_SiStrip_${job}.log
rm -rf $tmpdir
