#!/bin/sh
eval `scramv1 runtime -sh`

echo "initializeForGREN "
./initializeForGREN
echo "./start \> online_dqm.log 2\>&1"
#./start > online_dqm.log 2>&1 &
./start &
sleep 30
echo "Started the application and Configuring"
./configure
sleep 60
echo "Configured"
./enable
echo "Enabled"


