/********************************************************************
* MyMakePlotsDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error MyMakePlotsDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableMyMakePlotsDict();
extern void G__cpp_setup_inheritanceMyMakePlotsDict();
extern void G__cpp_setup_typetableMyMakePlotsDict();
extern void G__cpp_setup_memvarMyMakePlotsDict();
extern void G__cpp_setup_globalMyMakePlotsDict();
extern void G__cpp_setup_memfuncMyMakePlotsDict();
extern void G__cpp_setup_funcMyMakePlotsDict();
extern void G__set_cpp_environmentMyMakePlotsDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MyMakePlots.h"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__MyMakePlotsDictLN_TString;
extern G__linked_taginfo G__MyMakePlotsDictLN_MyMakePlots;

/* STUB derived class for protected member access */
