void test()
{
/*
  TFile* f = new TFile("treefile_b0old.root");
  TTree* tree = f->Get("ana/hi");
  TH1D* heta = new TH1D("eta","",120,-12,12);
  TH1D* hpt = new TH1D("pt","",200,0.,20);
  TH1D* hb = new TH1D("b","",300,0.,30);
  heta->SetMarkerColor(2);
  hpt->SetMarkerColor(2);
  hb->SetMarkerColor(2);
  tree->Draw("b>>b","","GOFF");
  tree->Draw("eta>>eta","abs(eta)<10.&&chg!=0","GOFF");
  heta->Scale(1.0/heta->GetBinWidth(1)/hb->GetEntries());
  heta->SetTitle(";#eta;dN/d#eta");
  tree->Draw("pt>>pt","chg!=0","GOFF");
  hpt->Scale(1.0/hpt->Integral());
  hpt->SetTitle(";p_{T};dN/dp_{T}");

  TFile* f1 = new TFile("treefile_b0pt5old.root");
  TTree* tree1 = f1->Get("ana/hi");
  TH1D* heta1 = new TH1D("eta1","",120,-12,12);
  TH1D* hpt1 = new TH1D("pt1","",200,0.,20);
  TH1D* hb1 = new TH1D("b1","",300,0.,30);
  heta1->SetMarkerColor(3);
  hpt1->SetMarkerColor(3);
  hb1->SetMarkerColor(3);
  tree1->Draw("b>>b1","","GOFF");
  tree1->Draw("eta>>eta1","abs(eta)<10.&&chg!=0","GOFF");
  heta1->Scale(1.0/heta1->GetBinWidth(1)/hb1->GetEntries());
  heta1->SetTitle(";#eta;dN/d#eta");
  tree1->Draw("pt>>pt1","chg!=0","GOFF");
  hpt1->Scale(1.0/hpt1->Integral());
  hpt1->SetTitle(";p_{T};dN/dp_{T}");

  TFile* f2 = new TFile("treefile_b0new.root");
  TTree* tree2 = f2->Get("ana/hi");
  TH1D* heta2 = new TH1D("eta2","",120,-12,12);
  TH1D* hpt2 = new TH1D("pt2","",200,0.,20);
  TH1D* hb2 = new TH1D("b2","",300,0.,30);
  heta2->SetMarkerColor(4);
  hpt2->SetMarkerColor(4);
  hb2->SetMarkerColor(4);
  tree2->Draw("b>>b2","","GOFF");
  tree2->Draw("eta>>eta2","abs(eta)<10.&&chg!=0","GOFF");
  heta2->Scale(1.0/heta2->GetBinWidth(1)/hb2->GetEntries());
  heta2->SetTitle(";#eta;dN/d#eta");
  tree2->Draw("pt>>pt2","chg!=0","GOFF");
  hpt2->Scale(1.0/hpt2->Integral());
  hpt2->SetTitle(";p_{T};dN/dp_{T}");

  TFile* f3 = new TFile("treefile_b0ampt_old.root");
  TTree* tree3 = f3->Get("ana/hi");
  TH1D* heta3 = new TH1D("eta3","",120,-12,12);
  TH1D* hpt3 = new TH1D("pt3","",200,0.,20);
  TH1D* hb3 = new TH1D("b3","",300,0.,30);
  heta3->SetMarkerColor(2);
  hpt3->SetMarkerColor(2);
  hb3->SetMarkerColor(2);
  tree3->Draw("b>>b3","","GOFF");
  tree3->Draw("eta>>eta3","abs(eta)<10.&&chg!=0","GOFF");
  heta3->Scale(1.0/heta3->GetBinWidth(1)/hb3->GetEntries());
  heta3->SetTitle(";#eta;dN/d#eta");
  tree3->Draw("pt>>pt3","chg!=0","GOFF");
  hpt3->Scale(1.0/hpt3->Integral());
  hpt3->SetTitle(";p_{T};dN/dp_{T}");
*/
  TFile* f4 = new TFile("treefile_ampt.root");
  TTree* tree4 = f4->Get("ana/hi");
  TH1D* heta4 = new TH1D("eta4","",80,-12,12);
  TH1D* hpt4 = new TH1D("pt4","",200,0.,20);
  TH1D* hb4 = new TH1D("b4","",300,0.,30);
  TH1D* hpdg4 = new TH1D("pdg4","",2000,-1000,1000);
//  heta4->SetMarkerColor(6);
//  hpt4->SetMarkerColor(6);
//  hb4->SetMarkerColor(6);
  tree4->Draw("b>>b4","","GOFF");
//  tree4->Draw("eta>>eta4","abs(eta)<10.&& (abs(pdg)==11 || abs(pdg)==13 || abs(pdg)==211 || abs(pdg)==321 || abs(pdg)==3222 || abs(pdg)==3112 || abs(pdg)==3312 || abs(pdg)==3332 || abs(pdg)==15 || abs(pdg)==411 || abs(pdg)==431 || abs(pdg)==24 || abs(pdg)==4122)","GOFF");
  tree4->Draw("eta>>eta4","abs(eta)<10.&&chg!=0","GOFF");
  tree4->Draw("pdg>>pdg4","abs(eta)<5.","GOFF");
  heta4->Scale(1.0/heta4->GetBinWidth(1)/hb4->GetEntries());
  heta4->SetTitle(";#eta;dN/d#eta");
  tree4->Draw("pt>>pt4","chg!=0","GOFF");
  hpt4->Scale(1.0/hpt4->Integral());
  hpt4->SetTitle(";p_{T};dN/dp_{T}");

  TCanvas* c1 = new TCanvas("c1","",500,500);
  hpdg4->Draw("hist");

  TCanvas* cd = new TCanvas("cd","",500,500);
//  cd->Divide(2,1);
//  cd->cd(1);
  heta4->SetTitle("AMPT, Pb+Pb, b=0");
//  heta1->SetAxisRange(0,4500,"Y");
//  heta1->Draw("PE");
//  heta->Draw("PESAME");
//  heta2->Draw("PESAME");
  heta4->Draw("PE");
//  heta3->Draw("PESAME");

return;
  TLegend* legend = new TLegend(0.3,0.75,0.9,0.9);
  legend->SetFillColor(0);
  legend->AddEntry(heta,"HYDJET, 2.8TeV, Old settings","P");
  legend->AddEntry(heta1,"HYDJET, 2.8TeV, Old settings, p_{T}^{hard}>5.0","P");
  legend->AddEntry(heta2,"HYDJET, 4TeV, Old settings","P");
  legend->AddEntry(heta3,"HYDJET, 2.8TeV, New settings","P");
  legend->AddEntry(heta4,"AMPT, 2.8TeV","P");
  legend->Draw("SAME");
  cd->cd(2);
  cd->GetPad(2)->SetLogy();
  hpt3->SetTitle("b=0");
  hpt3->SetAxisRange(0.00001,0.3,"Y");
  hpt3->SetAxisRange(0,4.0,"X");
  hpt3->Draw("PE");
  hpt->Draw("PESAME");
  hpt1->Draw("PESAME");
  hpt2->Draw("PESAME");
  hpt4->Draw("PESAME");
  TLegend* legend1 = new TLegend(0.6,0.7,0.9,0.9);
  legend1->SetFillColor(0);
  legend1->AddEntry(hpt,Form("<p_{T}>=%.3f",hpt->GetMean()),"P");
  legend1->AddEntry(hpt1,Form("<p_{T}>=%.3f",hpt1->GetMean()),"P");
  legend1->AddEntry(hpt2,Form("<p_{T}>=%.3f",hpt2->GetMean()),"P");
  legend1->AddEntry(hpt3,Form("<p_{T}>=%.3f",hpt3->GetMean()),"P");
  legend1->AddEntry(hpt4,Form("<p_{T}>=%.3f",hpt4->GetMean()),"P");
  legend1->Draw("SAME");
}
