/*
 * =====================================================================================
 *
 *       Filename:  HistoType.h
 *
 *    Description:  Histo Type Constants
 *
 *        Version:  1.0
 *        Created:  10/03/2008 11:54:31 AM
 *       Revision:  none
 *       Compiler:  gcc
 *
 *         Author:  Valdas Rapsevicius (VR), Valdas.Rapsevicius@cern.ch
 *        Company:  CERN, CH
 *
 * =====================================================================================
 */

#ifndef HistoType_H
#define HistoType_H 

namespace cscdqm {

  typedef enum HistoType {

    EMU_READOUT_ERROR,
    EMU_DDU_FORMAT_ERROR,
    EMU_DMB_REPORTING,
    EMU_CSC_REPORTING,
    EMU_CSC_WO_ALCT,
    EMU_DMB_WO_ALCT,
    EMU_CSC_WO_CLCT,
    EMU_DMB_WO_CLCT,
    EMU_CSC_WO_CFEB,
    EMU_DMB_WO_CFEB,
    EMU_CSC_DMB_INPUT_FIFO_FULL,
    EMU_DMB_INPUT_FIFO_FULL,
    EMU_CSC_DMB_INPUT_TIMEOUT,
    EMU_DMB_INPUT_TIMEOUT,
    EMU_DMB_FORMAT_WARNINGS,
    EMU_CSC_FORMAT_WARNINGS,
    EMU_DMB_FORMAT_ERRORS,
    EMU_DMB_UNPACKED_WITH_ERRORS,
    EMU_CSC_FORMAT_ERRORS,
    EMU_CSC_UNPACKED_WITH_ERRORS,
    EMU_ALL_DDUS_IN_READOUT,
    EMU_ALL_DDUS_EVENT_SIZE,
    EMU_ALL_DDU_AVERAGE_EVENT_SIZE,
    EMU_ALL_DDUS_L1A_INCREMENT,
    EMU_ALL_DDUS_INPUTS_WITH_DATA,
    EMU_ALL_DDUS_LIVE_INPUTS,
    EMU_ALL_DDUS_INPUTS_ERRORS,
    EMU_ALL_DDUS_INPUTS_WARNINGS,
    EMU_ALL_DDUS_AVERAGE_LIVE_INPUTS,
    EMU_ALL_DDUS_AVERAGE_INPUTS_WITH_DATA,
    EMU_ALL_DDUS_TRAILER_ERRORS,
    EMU_CSC_UNPACKED,
    EMU_DMB_UNPACKED,

    DDU_BUFFER_SIZE,
    DDU_WORD_COUNT,
    DDU_BXN,
    DDU_L1A_INCREMENT,
    DDU_DMB_DAV_HEADER_OCCUPANCY_RATE,
    DDU_DMB_DAV_HEADER_OCCUPANCY,
    DDU_DMB_CONNECTED_INPUTS_RATE,
    DDU_DMB_CONNECTED_INPUTS,
    DDU_CSC_ERRORS_RATE,
    DDU_CSC_ERRORS,
    DDU_CSC_WARNINGS_RATE,
    DDU_CSC_WARNINGS,
    DDU_DMB_ACTIVE_HEADER_COUNT,
    DDU_DMB_DAV_HEADER_COUNT_VS_DMB_ACTIVE_HEADER_COUNT,
    DDU_TRAILER_ERRORSTAT_RATE,
    DDU_TRAILER_ERRORSTAT_FREQUENCY,
    DDU_TRAILER_ERRORSTAT_TABLE,
    DDU_DMB_UNPACKED_VS_DAV,

    CSC_ACTUAL_DMB_CFEB_DAV_RATE,
    CSC_ACTUAL_DMB_CFEB_DAV_FREQUENCY,
    CSC_DMB_CFEB_DAV_UNPACKING_INEFFICIENCY,
    CSC_DMB_CFEB_DAV,
    CSC_ACTUAL_DMB_CFEB_DAV_MULTIPLICITY_RATE,
    CSC_ACTUAL_DMB_CFEB_DAV_MULTIPLICITY_FREQUENCY,
    CSC_DMB_CFEB_DAV_MULTIPLICITY_UNPACKING_INEFFICIENCY,
    CSC_DMB_CFEB_DAV_MULTIPLICITY,
    CSC_DMB_CFEB_ACTIVE_VS_DAV,
    CSC_ACTUAL_DMB_FEB_DAV_RATE,
    CSC_ACTUAL_DMB_FEB_DAV_FREQUENCY,
    CSC_DMB_FEB_DAV_UNPACKING_INEFFICIENCY,
    CSC_DMB_FEB_DAV_RATE,
    CSC_ACTUAL_DMB_FEB_COMBINATIONS_DAV_RATE,
    CSC_ACTUAL_DMB_FEB_COMBINATIONS_DAV_FREQUENCY,
    CSC_DMB_FEB_COMBINATIONS_DAV_UNPACKING_INEFFICIENCY,
    CSC_DMB_FEB_COMBINATIONS_DAV_RATE,
    CSC_BINCHECK_DATAFLOW_PROBLEMS_TABLE,
    CSC_BINCHECK_ERRORSTAT_TABLE,
    CSC_UNPACKED,
    CSC_DMB_L1A_DISTRIB,
    CSC_DMB_DDU_L1A_DIFF,
    CSC_DMB_L1A_VS_DDU_L1A,
    CSC_DMB_BXN_DISTRIB,
    CSC_DMB_DDU_BXN_DIFF,
    CSC_DMB_BXN_VS_DDU_BXN,
    CSC_DMB_CFEB_MOVLP,
    CSC_DMB_CFEB_SYNC,
    CSC_DMB_CFEB_ACTIVE,
    CSC_DMB_L1_PIPE,
    CSC_DMB_FIFO_STATS,
    CSC_DMB_FEB_TIMEOUTS,
    CSC_DMB_FEB_DAV_EFFICIENCY,
    CSC_DMB_FEB_COMBINATIONS_DAV_EFFICIENCY,
    CSC_DMB_FEB_UNPACKED_VS_DAV,
    CSC_ALCT_L1A,
    CSC_ALCT_DMB_L1A_DIFF,
    CSC_DMB_L1A_VS_ALCT_L1A,
    CSC_ALCT_DMB_BXN_DIFF,
    CSC_ALCT_BXN,
    CSC_ALCT_BXN_VS_DMB_BXN,
    CSC_ALCT_NUMBER_RATE,
    CSC_ALCT_NUMBER_EFFICIENCY,
    CSC_ALCT_WORD_COUNT,
    CSC_CSC_RATE,
    CSC_CSC_EFFICIENCY

  };

}

#endif
