MAPPING_FILE=${MAPPING_PATH}/DTReadOutMapping-mapping-custom_1.0.xml
OBJECT_LIBRARY=CondFormatsDTObjects
OBJECT_NAME=DTReadOutMapping
OBJECT_TABLE=DTREADOUTMAPPING
TAG=${OBJECT_NAME}_from_online
INFINITE=1
