# General DB setup
echo "[INFO]   Sourcing general-db-setup.sh"
OFFLINE_DB=orcon
ONLINE_DB=omds
GENERAL_DB_USER=CMS_COND_GENERAL
GENERAL_DB_PASSWORD=__CHANGE_ME__
export POOL_CATALOG=relationalcatalog_oracle://${OFFLINE_DB}/${GENERAL_DB_USER}
echo "[INFO]   OFFLINE_DB: $OFFLINE_DB"
echo "[INFO]   ONLINE_DB: $ONLINE_DB"
echo "[INFO]   GENERAL_DB_USER: $GENERAL_DB_USER"
echo "[INFO]   POOL_CATALOG: $POOL_CATALOG"
