#!/bin/sh

PATH=$CMSSW_BASE

if [ ! -d "$PATH/src/Documentation/DataFormats/python" ]; then
PATH=$CMSSW_RELEASE_BASE
fi

echo $PATH

#python $PATH/src/Documentation/DataFormats/scripts/dataformats.py $PATH $1
