var TREE_TPL = {
'target'  : 'frameset',
'icon_e'  : 'http://www.phys.ufl.edu/~barashko/dqm/icons/empty.gif',
'icon_l'  : 'http://www.phys.ufl.edu/~barashko/dqm/icons/line.gif',
'icon_32' : 'http://www.phys.ufl.edu/~barashko/dqm/icons/base.gif',
'icon_36' : 'http://www.phys.ufl.edu/~barashko/dqm/icons/base.gif',
'icon_48' : 'http://www.phys.ufl.edu/~barashko/dqm/icons/base.gif',
'icon_52' : 'http://www.phys.ufl.edu/~barashko/dqm/icons/base.gif',
'icon_56' : 'http://www.phys.ufl.edu/~barashko/dqm/icons/base.gif',
'icon_60' : 'http://www.phys.ufl.edu/~barashko/dqm/icons/base.gif',
'icon_16' : 'http://www.phys.ufl.edu/~barashko/dqm/icons/folder.gif',
'icon_20' : 'http://www.phys.ufl.edu/~barashko/dqm/icons/folderopen.gif',
'icon_24' : 'http://www.phys.ufl.edu/~barashko/dqm/icons/folderopen.gif',
'icon_28' : 'http://www.phys.ufl.edu/~barashko/dqm/icons/folderopen.gif',
'icon_0'  : 'http://www.phys.ufl.edu/~barashko/dqm/icons/page.gif',
'icon_4'  : 'http://www.phys.ufl.edu/~barashko/dqm/icons/page.gif',
'icon_2'  : 'http://www.phys.ufl.edu/~barashko/dqm/icons/joinbottom.gif',
'icon_3'  : 'http://www.phys.ufl.edu/~barashko/dqm/icons/join.gif',
'icon_18' : 'http://www.phys.ufl.edu/~barashko/dqm/icons/plusbottom.gif',
'icon_19' : 'http://www.phys.ufl.edu/~barashko/dqm/icons/plus.gif',
'icon_26' : 'http://www.phys.ufl.edu/~barashko/dqm/icons/minusbottom.gif',
'icon_27' : 'http://www.phys.ufl.edu/~barashko/dqm/icons/minus.gif'
};
