# These are the AlCaReco matrixes used during Run 2
# Since these are not really used anywhere in CMSSW,
# we move them here for documentation purposes

# AlCaReco matrix used in CMSSW releases in 2018
AlCaRecoMatrix2018 = {
                      "AlCaLumiPixels"        : "AlCaPCCZeroBias+AlCaPCCRandom",
                      "AlcaLumiPixelsExpress" : "AlCaPCCRandom",
                      "Charmonium"            : "TkAlJpsiMuMu",
                      "Commissioning"         : "HcalCalIsoTrk+HcalCalIsolatedBunchSelector+TkAlMinBias+SiStripCalMinBias",
                      "Cosmics"               : "SiPixelCalCosmics+SiStripCalCosmics+TkAlCosmics0T+MuAlGlobalCosmics",
                      "DoubleElectron"        : "EcalCalZElectron+EcalUncalZElectron",
                      "DoubleEG"              : "EcalCalZElectron+EcalUncalZElectron+HcalCalIterativePhiSym+HcalCalIsoTrkProducerFilter",
                      "DoubleMu"              : "MuAlCalIsolatedMu+MuAlOverlaps+TkAlZMuMu",
                      "DoubleMuon"            : "TkAlZMuMu+TkAlDiMuonAndVertex+MuAlCalIsolatedMu+MuAlOverlaps+MuAlZMuMu+HcalCalLowPUHBHEMuonFilter",
                      "DoubleMuParked"        : "MuAlCalIsolatedMu+MuAlOverlaps+TkAlZMuMu",
                      "EGamma"                : "EcalESAlign+EcalUncalWElectron+EcalUncalZElectron+HcalCalIsoTrkProducerFilter+HcalCalIterativePhiSym",
                      "Express"               : "SiStripCalZeroBias+TkAlMinBias+SiStripPCLHistos+SiStripCalMinBias+SiStripCalMinBiasAAG+Hotline+LumiPixelsMinBias+SiPixelCalZeroBias",
                      "ExpressAlignment"      : "TkAlMinBias",
                      "ExpressCosmics"        : "SiStripPCLHistos+SiStripCalZeroBias+TkAlCosmics0T+SiPixelCalZeroBias",
                      "HcalNZS"               : "HcalCalMinBias",
                      "HLTPhysics"            : "TkAlMinBias+HcalCalIterativePhiSym+HcalCalIsoTrkProducerFilter+HcalCalHO+HcalCalHBHEMuonProducerFilter",
                      "JetHT"                 : "HcalCalIsoTrkProducerFilter+HcalCalIsolatedBunchFilter+TkAlMinBias",
                      "MinimumBias"           : "SiStripCalZeroBias+SiStripCalMinBias+TkAlMinBias",
                      "MET"                   : "HcalCalNoise",
                      "MuOnia"                : "TkAlUpsilonMuMu",
                      "MuOniaParked"          : "TkAlJpsiMuMu+TkAlUpsilonMuMu",
                      "NoBPTX"                : "TkAlCosmicsInCollisions",
                      "SingleElectron"        : "EcalUncalWElectron+EcalUncalZElectron+HcalCalIterativePhiSym+EcalESAlign",
                      "SingleMu"              : "MuAlCalIsolatedMu+MuAlOverlaps+TkAlMuonIsolated+MuAlZMuMu+HcalCalHO",
                      "SingleMuon"            : "SiPixelCalSingleMuonLoose+SiPixelCalSingleMuonTight+TkAlMuonIsolated+MuAlCalIsolatedMu+MuAlOverlaps+MuAlZMuMu+HcalCalHO+HcalCalIterativePhiSym+HcalCalHBHEMuonProducerFilter",
                      "SinglePhoton"          : "HcalCalGammaJet",
                      "StreamExpress"         : "SiStripCalZeroBias+TkAlMinBias+SiStripPCLHistos+SiStripCalMinBias+SiStripCalMinBiasAAG+Hotline+LumiPixelsMinBias+SiPixelCalZeroBias+SiPixelCalSingleMuon+PPSCalTrackBasedSel",
                      "StreamExpressHI"       : "SiStripCalZeroBias+TkAlMinBiasHI+SiStripPCLHistos+SiStripCalMinBias+SiStripCalMinBiasAAG+SiPixelCalZeroBias",
                      "ZeroBias"              : "SiStripCalZeroBias+TkAlMinBias+LumiPixelsMinBias+SiStripCalMinBias+AlCaPCCZeroBiasFromRECO",
                     }

# AlCaReco matrix used in CMSSW releases in 2017
AlCaRecoMatrix2017 = {
                      "AlCaLumiPixels"        : "AlCaPCCZeroBias+AlCaPCCRandom",
                      "AlcaLumiPixelsExpress" : "AlCaPCCRandom",
                      "Charmonium"            : "TkAlJpsiMuMu",
                      "Commissioning"         : "HcalCalIsoTrk+HcalCalIsolatedBunchSelector+TkAlMinBias+SiStripCalMinBias",
                      "Cosmics"               : "SiPixelCalCosmics+SiStripCalCosmics+TkAlCosmics0T+MuAlGlobalCosmics",
                      "DoubleElectron"        : "EcalCalZElectron+EcalUncalZElectron",
                      "DoubleEG"              : "EcalCalZElectron+EcalUncalZElectron+HcalCalIterativePhiSym+HcalCalIsoTrkProducerFilter",
                      "DoubleMu"              : "MuAlCalIsolatedMu+MuAlOverlaps+TkAlZMuMu",
                      "DoubleMuon"            : "TkAlZMuMu+TkAlDiMuonAndVertex+MuAlCalIsolatedMu+MuAlOverlaps+MuAlZMuMu+HcalCalLowPUHBHEMuonFilter",
                      "DoubleMuParked"        : "MuAlCalIsolatedMu+MuAlOverlaps+TkAlZMuMu",
                      "EGamma"                : "EcalESAlign+EcalUncalWElectron+EcalUncalZElectron+HcalCalIsoTrkProducerFilter+HcalCalIterativePhiSym",
                      "Express"               : "SiStripCalZeroBias+TkAlMinBias+SiStripPCLHistos+SiStripCalMinBias+SiStripCalMinBiasAAG+Hotline+LumiPixelsMinBias+SiPixelCalZeroBias",
                      "ExpressAlignment"      : "TkAlMinBias",
                      "ExpressCosmics"        : "SiStripPCLHistos+SiStripCalZeroBias+TkAlCosmics0T+SiPixelCalZeroBias",
                      "HcalNZS"               : "HcalCalMinBias",
                      "HLTPhysics"            : "TkAlMinBias+HcalCalIterativePhiSym+HcalCalIsoTrkProducerFilter+HcalCalHO+HcalCalHBHEMuonProducerFilter",
                      "JetHT"                 : "HcalCalIsoTrkProducerFilter+HcalCalIsolatedBunchFilter+TkAlMinBias",
                      "MET"                   : "HcalCalNoise",
                      "MinimumBias"           : "SiStripCalZeroBias+SiStripCalMinBias+TkAlMinBias",
                      "MuOnia"                : "TkAlUpsilonMuMu",
                      "MuOniaParked"          : "TkAlJpsiMuMu+TkAlUpsilonMuMu",
                      "NoBPTX"                : "TkAlCosmicsInCollisions",
                      "SingleElectron"        : "EcalUncalWElectron+EcalUncalZElectron+HcalCalIterativePhiSym+EcalESAlign",
                      "SingleMu"              : "MuAlCalIsolatedMu+MuAlOverlaps+TkAlMuonIsolated+MuAlZMuMu+HcalCalHO",
                      "SingleMuon"            : "SiPixelCalSingleMuonLoose+SiPixelCalSingleMuonTight+TkAlMuonIsolated+MuAlCalIsolatedMu+MuAlOverlaps+MuAlZMuMu+HcalCalHO+HcalCalIterativePhiSym+HcalCalHBHEMuonProducerFilter",
                      "SinglePhoton"          : "HcalCalGammaJet",
                      "StreamExpress"         : "SiStripCalZeroBias+TkAlMinBias+SiStripPCLHistos+SiStripCalMinBias+SiStripCalMinBiasAAG+Hotline+LumiPixelsMinBias+SiPixelCalZeroBias+SiPixelCalSingleMuon+PPSCalTrackBasedSel",
                      "StreamExpressHI"       : "SiStripCalZeroBias+TkAlMinBiasHI+SiStripPCLHistos+SiStripCalMinBias+SiStripCalMinBiasAAG+SiPixelCalZeroBias",
                      "ZeroBias"              : "SiStripCalZeroBias+TkAlMinBias+LumiPixelsMinBias+SiStripCalMinBias+AlCaPCCZeroBiasFromRECO",
                     }

# This matrix has been used for the legacy reprocessing of the 2016 2016B-H dataset.
# With the exception of ZeroBias, it was also used for the 23Sept16 reprocessing of 2016B-G
AlCaRecoMatrix2016 = {
                      "AlCaLumiPixels"        : "AlCaPCCZeroBias+AlCaPCCRandom",
                      "AlcaLumiPixelsExpress" : "AlCaPCCRandom",
                      "Charmonium"            : "TkAlJpsiMuMu",
                      "Commissioning"         : "HcalCalIsoTrk+HcalCalIsolatedBunchSelector+TkAlMinBias+SiStripCalMinBias",
                      "Cosmics"               : "SiPixelCalCosmics+SiStripCalCosmics+TkAlCosmics0T+MuAlGlobalCosmics",
                      "DoubleEG"              : "EcalCalZElectron+EcalUncalZElectron+HcalCalIterativePhiSym+HcalCalIsoTrkProducerFilter",
                      "DoubleElectron"        : "EcalCalZElectron+EcalUncalZElectron",
                      "DoubleMu"              : "MuAlCalIsolatedMu+MuAlOverlaps+TkAlZMuMu",
                      "DoubleMuon"            : "TkAlZMuMu+TkAlDiMuonAndVertex+MuAlCalIsolatedMu+MuAlOverlaps+MuAlZMuMu+HcalCalLowPUHBHEMuonFilter",
                      "DoubleMuParked"        : "MuAlCalIsolatedMu+MuAlOverlaps+TkAlZMuMu",
                      "EGamma"                : "EcalESAlign+EcalUncalWElectron+EcalUncalZElectron+HcalCalIsoTrkProducerFilter+HcalCalIterativePhiSym",
                      "Express"               : "SiStripCalZeroBias+TkAlMinBias+SiStripPCLHistos+SiStripCalMinBias+SiStripCalMinBiasAAG+Hotline+LumiPixelsMinBias+SiPixelCalZeroBias",
                      "ExpressAlignment"      : "TkAlMinBias",
                      "ExpressCosmics"        : "SiStripPCLHistos+SiStripCalZeroBias+TkAlCosmics0T+SiPixelCalZeroBias",
                      "HcalNZS"               : "HcalCalMinBias",
                      "HLTPhysics"            : "TkAlMinBias+HcalCalIterativePhiSym+HcalCalIsoTrkProducerFilter+HcalCalHO+HcalCalHBHEMuonProducerFilter",
                      "JetHT"                 : "HcalCalIsoTrkProducerFilter+HcalCalIsolatedBunchFilter+TkAlMinBias",
                      "MET"                   : "HcalCalNoise",
                      "MinimumBias"           : "SiStripCalZeroBias+SiStripCalMinBias+TkAlMinBias",
                      "MuOnia"                : "TkAlUpsilonMuMu",
                      "MuOniaParked"          : "TkAlJpsiMuMu+TkAlUpsilonMuMu",
                      "NoBPTX"                : "TkAlCosmicsInCollisions",
                      "SingleElectron"        : "EcalUncalWElectron+EcalUncalZElectron+HcalCalIterativePhiSym+EcalESAlign",
                      "SingleMu"              : "MuAlCalIsolatedMu+MuAlOverlaps+TkAlMuonIsolated+MuAlZMuMu+HcalCalHO",
                      "SingleMuon"            : "SiPixelCalSingleMuonLoose+SiPixelCalSingleMuonTight+TkAlMuonIsolated+MuAlCalIsolatedMu+MuAlOverlaps+MuAlZMuMu+HcalCalHO+HcalCalIterativePhiSym+HcalCalHBHEMuonProducerFilter",
                      "SinglePhoton"          : "HcalCalGammaJet",
                      "StreamExpress"         : "SiStripCalZeroBias+TkAlMinBias+SiStripPCLHistos+SiStripCalMinBias+SiStripCalMinBiasAAG+Hotline+LumiPixelsMinBias+SiPixelCalZeroBias+SiPixelCalSingleMuon+PPSCalTrackBasedSel",
                      "StreamExpressHI"       : "SiStripCalZeroBias+TkAlMinBiasHI+SiStripPCLHistos+SiStripCalMinBias+SiStripCalMinBiasAAG+SiPixelCalZeroBias",
                      "ZeroBias"              : "SiStripCalZeroBias+TkAlMinBias+LumiPixelsMinBias+SiStripCalMinBias+AlCaPCCZeroBiasFromRECO",
                     }

# AlCaReco matrix used in 2015 at 50 ns
AlCaRecoMatrix2015 = {
                      "DoubleElectron" : "EcalCalZElectron+EcalUncalZElectron",
                      "DoubleMu"       : "MuAlCalIsolatedMu+MuAlOverlaps+TkAlZMuMu",
                      "SingleMu"       : "MuAlCalIsolatedMu+MuAlOverlaps+TkAlMuonIsolated+MuAlZMuMu+HcalCalHO",
                     }
