# The following comments couldn't be translated into the new config version:

# Triggering on singles and running the core",
# Charge Quality and Rank of fake track, produced from singles",
# Output muon pT to spy on",
# Core settings (i.e. BXA on, ... )",
# Reset ETA counter to set EtaMin, EtaMax, and EtaWin",
# EtaMin[0] = 22",
# EtaMin[1] = 22",
# EtaMin[2] = 14",
# EtaMin[3] = 14",
# EtaMin[4] = 14",
# EtaMin[5] = 10",
# EtaMin[6] = 10",
# EtaMin[7] = 10",
# EtaMax[0] = 127",
# EtaMax[1] = 127",
# EtaMax[2] = 127",
# EtaMax[3] = 127",
# EtaMax[4] = 127",
# EtaMax[5] = 24",
# EtaMax[6] = 24",
# EtaMax[7] = 24",
# EtaWin[0] = 4",
# EtaWin[1] = 4",
# EtaWin[2] = 4",
# EtaWin[3] = 4",
# EtaWin[4] = 4",
# EtaWin[5] = 4",
# mindphip     = 2",
# mindeta_accp = 4",
# maxdeta_accp = 16",
# maxdphi_accp = 128"
import FWCore.ParameterSet.Config as cms

l1CSCTFConfig = cms.ESProducer("CSCTFConfigProducer",
    globalPhi3LUT_path = cms.untracked.string(''),
    globalPhi1LUT_path = cms.untracked.string(''),
    globalPhi4LUT_path = cms.untracked.string(''),
    globalEta4LUT_path = cms.untracked.string(''),
    globalPhi2LUT_path = cms.untracked.string(''),
    dt2LUT_path = cms.untracked.string(''),
    localPhiLUT_path = cms.untracked.string(''),
    globalEta1LUT_path = cms.untracked.string(''),
    globalPhi5LUT_path = cms.untracked.string(''),
    registers = cms.vstring('CSR_REQ SP MA 0x801F # Triggering on singles and running the core', 'DAT_FTR SP MA 0xFF   # Charge Quality and Rank of fake track, produced from singles', 'CSR_SFC SP MA 0x1000 # Output muon pT to spy on', 'CSR_SCC SP MA 0x1    # Core settings (i.e. BXA on, ... )', 'CNT_ETA SP MA 0x0    # Reset ETA counter to set EtaMin, EtaMax, and EtaWin', 'DAT_ETA SP MA 0x16   # EtaMin[0] = 22', 'DAT_ETA SP MA 0x16   # EtaMin[1] = 22', 'DAT_ETA SP MA 0xE    # EtaMin[2] = 14', 'DAT_ETA SP MA 0xE    # EtaMin[3] = 14', 'DAT_ETA SP MA 0xE    # EtaMin[4] = 14', 'DAT_ETA SP MA 0xA    # EtaMin[5] = 10', 'DAT_ETA SP MA 0xA    # EtaMin[6] = 10', 'DAT_ETA SP MA 0xA    # EtaMin[7] = 10', 'DAT_ETA SP MA 0x7F   # EtaMax[0] = 127', 'DAT_ETA SP MA 0x7F   # EtaMax[1] = 127', 'DAT_ETA SP MA 0x7F   # EtaMax[2] = 127', 'DAT_ETA SP MA 0x7F   # EtaMax[3] = 127', 'DAT_ETA SP MA 0x7F   # EtaMax[4] = 127', 'DAT_ETA SP MA 0x18   # EtaMax[5] = 24', 'DAT_ETA SP MA 0x18   # EtaMax[6] = 24', 'DAT_ETA SP MA 0x18   # EtaMax[7] = 24', 'DAT_ETA SP MA 0x4    # EtaWin[0] = 4', 'DAT_ETA SP MA 0x4    # EtaWin[1] = 4', 'DAT_ETA SP MA 0x4    # EtaWin[2] = 4', 'DAT_ETA SP MA 0x4    # EtaWin[3] = 4', 'DAT_ETA SP MA 0x4    # EtaWin[4] = 4', 'DAT_ETA SP MA 0x4    # EtaWin[5] = 4', 'DAT_ETA SP MA 0x2    # mindphip     = 2', 'DAT_ETA SP MA 0x4    # mindeta_accp = 4', 'DAT_ETA SP MA 0x10   # maxdeta_accp = 16', 'DAT_ETA SP MA 0x80   # maxdphi_accp = 128'),
    globalEta5LUT_path = cms.untracked.string(''),
    ptLUT_path = cms.untracked.string(''),
    globalEta2LUT_path = cms.untracked.string(''),
    globalEta3LUT_path = cms.untracked.string(''),
    dt1LUT_path = cms.untracked.string('')
)


