import FWCore.ParameterSet.Config as cms

HGCalTBAnalyzer = cms.EDAnalyzer("HGCalTBAnalyzer",
                                 DetectorEE   = cms.string('HGCalEESensitive'),
                                 UseEE        = cms.bool(True),
                                 ZFrontEE     = cms.double(0),
                                 DetectorFH   = cms.string('HGCalHESiliconSensitive'),
                                 UseFH        = cms.bool(False),
                                 ZFrontFH     = cms.double(0),
                                 DetectorBH   = cms.string('AHCal'),
                                 UseBH        = cms.bool(False),
                                 ZFrontBH     = cms.double(0),
                                 DoSimHits    = cms.bool(True),
                                 DoDigis      = cms.bool(True),
                                 DoRecHits    = cms.bool(True),
                                 SampleIndex  = cms.int32(0),
                                 DoTree       = cms.untracked.bool(True),
                                 DoTreeCell   = cms.untracked.bool(True),
                                 GeneratorSrc = cms.InputTag('generatorSmeared'),
                                 CaloHitSrcEE = cms.string('HGCHitsEE'),
                                 DigiSrcEE    = cms.InputTag('mix','HGCDigisEE'),
                                 RecHitSrcEE  = cms.InputTag('HGCalRecHit','HGCEERecHits'),
                                 CaloHitSrcFH = cms.string('HGCHitsHEfront'),
                                 DigiSrcFH    = cms.InputTag('mix','HGCDigisHEfront'),
                                 RecHitSrcFH  = cms.InputTag('HGCalRecHit','HGCHEFRecHits'),
                                 CaloHitSrcBH = cms.string('HcalHits'),
                                 DigiSrcBH    = cms.InputTag('mix','HGCDigisHEback'),
                                 RecHitSrcBH  = cms.InputTag('HGCalRecHit','HGCHEBRecHits'),
)
