ALTER TABLE "SISTRIPPEDESTALS" ADD "TIME" NUMBER(10);
ALTER TABLE "DETREGISTRYINDEX_PED" ADD "TIME" NUMBER(10);
ALTER TABLE "SISTRIPNOISES" ADD "TIME" NUMBER(10);
ALTER TABLE "DETREGISTRYINDEX_NOISE" ADD "TIME" NUMBER(10);
ALTER TABLE "SISTRIPFEDCABLING" ADD "TIME" NUMBER(10);







