CREATE TABLE CMS_XIEZHEN_DEV."METADATA" ( "NAME" VARCHAR2(4000), "TOKEN" VARCHAR2(4000) NOT NULL, CONSTRAINT "METADATA_PK" PRIMARY KEY ( "NAME" ) );	
GRANT SELECT ON CMS_XIEZHEN_DEV."METADATA" TO PUBLIC
