-- D:\CMS-PROJECTS\Detector_Geometry_DB\CMS_DTCTR_GEOMETRY_OWNER.sql
--
-- Generated for Oracle 9i on Mon May 16  16:13:16 2005 by Server Generator 9.0.2.92.10


SPOOL CMS_DTCTR_GEOMETRY_OWNER.lst

@@CMS_DTCTR_GEOMETRY_OWNER.tab
@@CMS_DTCTR_GEOMETRY_OWNER.vw
@@CMS_DTCTR_GEOMETRY_OWNER.ind
@@CMS_DTCTR_GEOMETRY_OWNER.con
@@CMS_DTCTR_GEOMETRY_OWNER.sqs
@@CMS_DTCTR_GEOMETRY_OWNER.syn
@@CMS_DTCTR_GEOMETRY_OWNER.trg
@@CMS_DTCTR_GEOMETRY_OWNER.grt

SPOOL OFF
