import FWCore.ParameterSet.Config as cms

from DQMOffline.Ecal.ecal_dqm_source_offline_cff import *
from DQMOffline.Ecal.ecal_dqm_client_offline_cff import *

eb_dqm_sourceclient_offline1 = cms.Sequence(ecalBarrelMonitorModule*ecalBarrelMonitorClient)
eb_dqm_sourceclient_offline2 = cms.Sequence(ecalBarrelOccupancyTask*ecalBarrelIntegrityTask*ecalBarrelStatusFlagsTask*ecalBarrelSelectiveReadoutTask*ecalBarrelRawDataTask*ecalBarrelPedestalOnlineTask*ecalBarrelTriggerTowerTask*ecalBarrelTimingTask*ecalBarrelCosmicTask*ecalBarrelClusterTask)

ee_dqm_sourceclient_offline1 = cms.Sequence(ecalEndcapMonitorModule*ecalEndcapMonitorClient)
ee_dqm_sourceclient_offline2 = cms.Sequence(ecalEndcapOccupancyTask*ecalEndcapIntegrityTask*ecalEndcapStatusFlagsTask*ecalEndcapSelectiveReadoutTask*ecalEndcapRawDataTask*ecalEndcapPedestalOnlineTask*ecalEndcapTriggerTowerTask*ecalEndcapTimingTask*ecalEndcapCosmicTask*ecalEndcapClusterTask)

ecal_dqm_sourceclient_offline1 = cms.Sequence(eb_dqm_sourceclient_offline1*ee_dqm_sourceclient_offline1)

ecal_dqm_sourceclient_offline2 = cms.Sequence(eb_dqm_sourceclient_offline2*ee_dqm_sourceclient_offline2)

