#!/usr/bin/env sh

export MYQUEUE=$1
shift

export CURRENT_DIR=`pwd`
export JOB_SCRIPT=bsub.${MY_ENV_NAME}.sh
export JOB_DIR=electronBsub.${MY_ENV_NAME}.$$
export JOB_CASTOR=${MY_OUTPUT_CASTOR_DIR}
mkdir -p ${JOB_DIR}
nsmkdir -p ${JOB_CASTOR}

cat << EOF  > ${JOB_DIR}/${JOB_SCRIPT}
scram project CMSSW ${MY_CMSSW_RELEASE}
cd ${MY_CMSSW_RELEASE}/src
eval \`scram runtime -sh\`
cp -r ${CURRENT_DIR}/../../../RecoEgamma .
scram b
cd RecoEgamma/Configuration/test
$* && rfcp *.root ${JOB_CASTOR}
EOF

cd ${JOB_DIR}
chmod a+x ${JOB_SCRIPT}
bsub -q ${MYQUEUE} ${JOB_SCRIPT}

