import FWCore.ParameterSet.Config as cms

trackingMaterialAnalyser = cms.EDAnalyzer("TrackingMaterialAnalyser",
    MaterialAccounting      = cms.InputTag("trackingMaterialProducer"),
    SplitMode               = cms.string("NearestLayer"),
    SkipBeforeFirstDetector = cms.bool(False),
    SkipAfterLastDetector   = cms.bool(False),
    SaveSummaryPlot         = cms.bool(True),
    SaveDetailedPlots       = cms.bool(False),
    SaveParameters          = cms.bool(True),
    SaveXML                 = cms.bool(True),
# to derive the following list:
# cat ../data/trackingMaterialGroups_ForPhaseII.xml | grep TrackingMaterialGroup | sed -e 's/\s*//' | cut -d ' ' -f 3 | tr '=' ' ' | cut -d ' ' -f 2 | tr -d '"' | sed -e 's/\(.*\)/"\1",/'
    Groups = cms.vstring(
"TrackerRecMaterialPixelBarrelLayer0",
"TrackerRecMaterialPixelBarrelLayer1",
"TrackerRecMaterialPixelBarrelLayer2",
"TrackerRecMaterialPixelBarrelLayer3",
"TrackerRecMaterialPixelEndcapDisk1Fw",
"TrackerRecMaterialPixelEndcapDisk2Fw",
"TrackerRecMaterialPixelEndcapDisk3Fw",
"TrackerRecMaterialPixelEndcapDisk4Fw",
"TrackerRecMaterialPixelEndcapDisk5Fw",
"TrackerRecMaterialPixelEndcapDisk6Fw",
"TrackerRecMaterialPixelEndcapDisk7Fw",
"TrackerRecMaterialPixelEndcapDisk8Fw",
"TrackerRecMaterialPixelEndcapDisk9Fw",
"TrackerRecMaterialPixelEndcapDisk10Fw",
"TrackerRecMaterialPixelEndcapDisk1Bw",
"TrackerRecMaterialPixelEndcapDisk2Bw",
"TrackerRecMaterialPixelEndcapDisk3Bw",
"TrackerRecMaterialPixelEndcapDisk4Bw",
"TrackerRecMaterialPixelEndcapDisk5Bw",
"TrackerRecMaterialPixelEndcapDisk6Bw",
"TrackerRecMaterialPixelEndcapDisk7Bw",
"TrackerRecMaterialPixelEndcapDisk8Bw",
"TrackerRecMaterialPixelEndcapDisk9Bw",
"TrackerRecMaterialPixelEndcapDisk10Bw",
"TrackerRecMaterialTOBPixelBarrelLayer1",
"TrackerRecMaterialTOBPixelBarrelLayer2",
"TrackerRecMaterialTOBPixelBarrelLayer3",
"TrackerRecMaterialTOBPixelBarrelLayer4",
"TrackerRecMaterialTOBPixelBarrelLayer5",
"TrackerRecMaterialTOBPixelBarrelLayer6",
"TrackerRecMaterialTIDDisk67Fw",
"TrackerRecMaterialTIDDisk89Fw",
"TrackerRecMaterialTIDDisk10Fw",
"TrackerRecMaterialTIDDisk67Bw",
"TrackerRecMaterialTIDDisk89Bw",
"TrackerRecMaterialTIDDisk10Bw",
    )
)
