import FWCore.ParameterSet.Config as cms

selectionName = 'DtCalibSynchCosmics'
#from DQM.HLTEvF.HLTMonBitSummary_cfi import hltMonBitSummary
from CalibMuon.DTCalibration.ALCARECODtCalib_cff import ALCARECODtCalibHLTFilter
from CalibMuon.DTCalibration.ALCARECODtCalibCosmics_cff import ALCARECODtCalibCosmicsHLTFilter as ALCARECODtCalibCosmicsHLTFilterRef
