import FWCore.ParameterSet.Config as cms

from RecoTracker.TransientTrackingRecHit.TransientTrackingRecHitBuilder_cfi import *
from RecoTracker.TransientTrackingRecHit.TransientTrackingRecHitBuilderWithoutRefit_cfi import *
from RecoTracker.TkSeedingLayers.TTRHBuilderWithoutAngle4MixedPairs_cfi import *
from RecoTracker.TkSeedingLayers.TTRHBuilderWithoutAngle4MixedTriplets_cfi import *
from RecoTracker.TkSeedingLayers.TTRHBuilderWithoutAngle4PixelPairs_cfi import *
from RecoTracker.TkSeedingLayers.TTRHBuilderWithoutAngle4PixelTriplets_cfi import *
#TransientTRH builder with template
from RecoLocalTracker.SiPixelRecHits.PixelCPETemplateReco_cfi import *
from RecoLocalTracker.SiPixelRecHits.PixelCPEClusterRepair_cfi import *
from RecoTracker.TransientTrackingRecHit.TTRHBuilderWithTemplate_cfi import *

