#!/usr/bin/env perl

################################################################################
#
# edmConfDBDiff
# -------------
#
#             01/17/2008 Philipp Schieferdecker <philipp.schieferdecker@cern.ch>
################################################################################

my $usage =
    "USAGE:\nedmConfDBDiff\n" .
    "\t--configs <cfg1,cfg2>        (compare configuration cfg1 and cfg2)\n" .
    "\t--search  p:<name>[,newname] (compare specified path)\n" .
    "\t--search  s:<name>[,newname] (compare specified sequence)\n" .
    "\t--search  m:<name>[,newname] (compare specified module)\n" .
    "\n";

die $usage if @ARGV<2;

my $log_file = "/dev/null";
my $configs  = "";
my $search   = "";

while (@ARGV) {
  my $arg = shift @ARGV;
  
  if ($arg eq "--configs") {
      $configs = shift @ARGV;
  }
  elsif ($arg eq "--search") {
      $search = shift @ARGV;
  }
  else {
      die "ERROR: invalid option $arg\n";
  }
}

die "--configs <cfg1,cfg2> *must* be specified!" if ($configs eq "");

my $url =
    "http://cms-project-confdb-hltdev.web.cern.ch/" .
    "cms-project-confdb-hltdev/diff.jsp?configs=$configs";
if (!$search eq "") { $url = $url . "&search=$search"; }

system("wget \"$url\" -O- -o $log_file");

exit 0;
