from ..layouts.layout_manager import register_layout


register_layout(source='Btag/TCHP_GLOBAL/jetMultiplicity_TCHP_GLOBALALL', destination='Btag/Layouts/jetMultiplicity_TCHP_GLOBALALL', name='00 - Jet Property', overlay='')
register_layout(source='Btag/TCHP_GLOBAL/jetPt_TCHP_GLOBALALL', destination='Btag/Layouts/jetPt_TCHP_GLOBALALL', name='00 - Jet Property', overlay='')
register_layout(source='Btag/TCHP_GLOBAL/jetEta_TCHP_GLOBALALL', destination='Btag/Layouts/jetEta_TCHP_GLOBALALL', name='00 - Jet Property', overlay='')
register_layout(source='Btag/TCHP_GLOBAL/jetPhi_TCHP_GLOBALALL', destination='Btag/Layouts/jetPhi_TCHP_GLOBALALL', name='00 - Jet Property', overlay='')
register_layout(source='Btag/IPTag_GLOBAL/selectedTrackMultVsJetPt_IPTag_GLOBALALL', destination='Btag/Layouts/selectedTrackMultVsJetPt_IPTag_GLOBALALL', name='01 - Tracks in Jet', overlay='')
register_layout(source='Btag/IPTag_GLOBAL/trackMultVsJetPt_IPTag_GLOBALALL', destination='Btag/Layouts/trackMultVsJetPt_IPTag_GLOBALALL', name='01 - Tracks in Jet', overlay='')
register_layout(source='Btag/IPTag_GLOBAL/selectedTrackQual_IPTag_GLOBALALL', destination='Btag/Layouts/selectedTrackQual_IPTag_GLOBALALL', name='01 - Tracks in Jet', overlay='')
register_layout(source='Btag/IPTag_GLOBAL/trackQual_IPTag_GLOBALALL', destination='Btag/Layouts/trackQual_IPTag_GLOBALALL', name='01 - Tracks in Jet', overlay='')
register_layout(source='Btag/CSVTag_GLOBAL/vertexCategoryALL', destination='Btag/Layouts/vertexCategoryALL', name='02 - Vertex Property', overlay='')
register_layout(source='Btag/CSVTag_GLOBAL/vertexMassALL', destination='Btag/Layouts/vertexMassALL', name='02 - Vertex Property', overlay='')
register_layout(source='Btag/CSVTag_GLOBAL/vertexEnergyRatioALL', destination='Btag/Layouts/vertexEnergyRatioALL', name='02 - Vertex Property', overlay='')
register_layout(source='Btag/CSVTag_GLOBAL/vertexNTracksALL', destination='Btag/Layouts/vertexNTracksALL', name='02 - Vertex Property', overlay='')
register_layout(source='Btag/CSVTag_GLOBAL/vertexJetDeltaRALL', destination='Btag/Layouts/vertexJetDeltaRALL', name='02 - Vertex Property', overlay='')
register_layout(source='Btag/CSVTag_GLOBAL/flightDistance2dValALL', destination='Btag/Layouts/flightDistance2dValALL', name='03 - Flight Distance Summary', overlay='')
register_layout(source='Btag/CSVTag_GLOBAL/flightDistance3dValALL', destination='Btag/Layouts/flightDistance3dValALL', name='03 - Flight Distance Summary', overlay='')
register_layout(source='Btag/CSVTag_GLOBAL/flightDistance2dSigALL', destination='Btag/Layouts/flightDistance2dSigALL', name='03 - Flight Distance Summary', overlay='')
register_layout(source='Btag/CSVTag_GLOBAL/flightDistance3dSigALL', destination='Btag/Layouts/flightDistance3dSigALL', name='03 - Flight Distance Summary', overlay='')
register_layout(source='Btag/CSV_GLOBAL/discr_CSV_GLOBALALL', destination='Btag/Layouts/discr_CSV_GLOBALALL', name='04 - Discriminator Summary', overlay='')
register_layout(source='Btag/GhTrk_GLOBAL/discr_GhTrk_GLOBALALL', destination='Btag/Layouts/discr_GhTrk_GLOBALALL', name='04 - Discriminator Summary', overlay='')
register_layout(source='Btag/JBP_GLOBAL/discr_JBP_GLOBALALL', destination='Btag/Layouts/discr_JBP_GLOBALALL', name='04 - Discriminator Summary', overlay='')
register_layout(source='Btag/JP_GLOBAL/discr_JP_GLOBALALL', destination='Btag/Layouts/discr_JP_GLOBALALL', name='04 - Discriminator Summary', overlay='')
register_layout(source='Btag/SSVHE_GLOBAL/discr_SSVHE_GLOBALALL', destination='Btag/Layouts/discr_SSVHE_GLOBALALL', name='04 - Discriminator Summary', overlay='')
register_layout(source='Btag/TCHE_GLOBAL/discr_TCHE_GLOBALALL', destination='Btag/Layouts/discr_TCHE_GLOBALALL', name='04 - Discriminator Summary', overlay='')
register_layout(source='Btag/TCHP_GLOBAL/discr_TCHP_GLOBALALL', destination='Btag/Layouts/discr_TCHP_GLOBALALL', name='04 - Discriminator Summary', overlay='')
register_layout(source='Btag/SMT_GLOBAL/discr_SMT_GLOBALALL', destination='Btag/Layouts/discr_SMT_GLOBALALL', name='04 - Discriminator Summary', overlay='')
register_layout(source='Btag/SMTIP3d_GLOBAL/discr_SMTIP3d_GLOBALALL', destination='Btag/Layouts/discr_SMTIP3d_GLOBALALL', name='04 - Discriminator Summary', overlay='')
register_layout(source='Btag/SMTPt_GLOBAL/discr_SMTPt_GLOBALALL', destination='Btag/Layouts/discr_SMTPt_GLOBALALL', name='04 - Discriminator Summary', overlay='')
register_layout(source='Btag/IPTag_GLOBAL/ip_2D_IPTag_GLOBALALL', destination='Btag/Layouts/ip_2D_IPTag_GLOBALALL', name='05 - 2D-Impact Parameter', overlay='')
register_layout(source='Btag/IPTag_GLOBAL/ipe_2D_IPTag_GLOBALALL', destination='Btag/Layouts/ipe_2D_IPTag_GLOBALALL', name='05 - 2D-Impact Parameter', overlay='')
register_layout(source='Btag/IPTag_GLOBAL/prob_2D_IPTag_GLOBALALL', destination='Btag/Layouts/prob_2D_IPTag_GLOBALALL', name='05 - 2D-Impact Parameter', overlay='')
register_layout(source='Btag/IPTag_GLOBAL/tkNHits_2D_IPTag_GLOBALALL', destination='Btag/Layouts/tkNHits_2D_IPTag_GLOBALALL', name='05 - 2D-Impact Parameter', overlay='')
register_layout(source='Btag/IPTag_GLOBAL/tkNChiSqr_2D_IPTag_GLOBALALL', destination='Btag/Layouts/tkNChiSqr_2D_IPTag_GLOBALALL', name='05 - 2D-Impact Parameter', overlay='')
register_layout(source='Btag/IPTag_GLOBAL/decLen_2D_IPTag_GLOBALALL', destination='Btag/Layouts/decLen_2D_IPTag_GLOBALALL', name='05 - 2D-Impact Parameter', overlay='')
register_layout(source='Btag/IPTag_GLOBAL/jetDist_2D_IPTag_GLOBALALL', destination='Btag/Layouts/jetDist_2D_IPTag_GLOBALALL', name='05 - 2D-Impact Parameter', overlay='')
register_layout(source='Btag/IPTag_GLOBAL/ip_3D_IPTag_GLOBALALL', destination='Btag/Layouts/ip_3D_IPTag_GLOBALALL', name='06 - 3D-Impact Parameter', overlay='')
register_layout(source='Btag/IPTag_GLOBAL/ipe_3D_IPTag_GLOBALALL', destination='Btag/Layouts/ipe_3D_IPTag_GLOBALALL', name='06 - 3D-Impact Parameter', overlay='')
register_layout(source='Btag/IPTag_GLOBAL/prob_3D_IPTag_GLOBALALL', destination='Btag/Layouts/prob_3D_IPTag_GLOBALALL', name='06 - 3D-Impact Parameter', overlay='')
register_layout(source='Btag/IPTag_GLOBAL/ips_3D_IPTag_GLOBALALL', destination='Btag/Layouts/ips_3D_IPTag_GLOBALALL', name='06 - 3D-Impact Parameter', overlay='')
register_layout(source='Btag/IPTag_GLOBAL/ips1_3D_IPTag_GLOBALALL', destination='Btag/Layouts/ips1_3D_IPTag_GLOBALALL', name='06 - 3D-Impact Parameter', overlay='')
register_layout(source='Btag/IPTag_GLOBAL/tkPt_3D_IPTag_GLOBALALL', destination='Btag/Layouts/tkPt_3D_IPTag_GLOBALALL', name='06 - 3D-Impact Parameter', overlay='')
register_layout(source='Btag/IPTag_GLOBAL/tkNChiSqr_3D_IPTag_GLOBALALL', destination='Btag/Layouts/tkNChiSqr_3D_IPTag_GLOBALALL', name='06 - 3D-Impact Parameter', overlay='')
register_layout(source='Btag/IPTag_GLOBAL/tkNHits_3D_IPTag_GLOBALALL', destination='Btag/Layouts/tkNHits_3D_IPTag_GLOBALALL', name='06 - 3D-Impact Parameter', overlay='')
register_layout(source='Btag/IPTag_GLOBAL/decLen_3D_IPTag_GLOBALALL', destination='Btag/Layouts/decLen_3D_IPTag_GLOBALALL', name='06 - 3D-Impact Parameter', overlay='')
register_layout(source='Btag/IPTag_GLOBAL/jetDist_3D_IPTag_GLOBALALL', destination='Btag/Layouts/jetDist_3D_IPTag_GLOBALALL', name='06 - 3D-Impact Parameter', overlay='')
