from ..layouts.layout_manager import register_layout


register_layout(source='CSC/Summary/Physics_EMU', destination='CSC/Layouts/Physics_EMU', name='00 Top Physics Efficiency', overlay='')
register_layout(source='CSC/Summary/Physics_ME1', destination='CSC/Layouts/Physics_ME1', name='01 Station Physics Efficiency', overlay='')
register_layout(source='CSC/Summary/Physics_ME2', destination='CSC/Layouts/Physics_ME2', name='01 Station Physics Efficiency', overlay='')
register_layout(source='CSC/Summary/Physics_ME3', destination='CSC/Layouts/Physics_ME3', name='01 Station Physics Efficiency', overlay='')
register_layout(source='CSC/Summary/Physics_ME4', destination='CSC/Layouts/Physics_ME4', name='01 Station Physics Efficiency', overlay='')
register_layout(source='CSC/Summary/All_DDUs_in_Readout', destination='CSC/Layouts/02 EMU Summary/All_DDUs_in_ReadoutAll_DDUs_in_Readout', name='EMU Test01 - DDUs in Readout', overlay='')
register_layout(source='CSC/Summary/All_DDUs_L1A_Increment', destination='CSC/Layouts/02 EMU Summary/All_DDUs_L1A_IncrementAll_DDUs_L1A_Increment', name='EMU Test01 - DDUs in Readout', overlay='')
register_layout(source='CSC/Summary/All_DDUs_Trailer_Errors', destination='CSC/Layouts/02 EMU Summary/All_DDUs_Trailer_ErrorsAll_DDUs_Trailer_Errors', name='EMU Test03 - DDU Reported Errors', overlay='')
register_layout(source='CSC/Summary/All_DDUs_Format_Errors', destination='CSC/Layouts/02 EMU Summary/All_DDUs_Format_ErrorsAll_DDUs_Format_Errors', name='EMU Test04 - DDU Format Errors', overlay='')
register_layout(source='CSC/Summary/All_DDUs_Live_Inputs', destination='CSC/Layouts/02 EMU Summary/All_DDUs_Live_InputsAll_DDUs_Live_Inputs', name='EMU Test05 - DDU Inputs Status', overlay='')
register_layout(source='CSC/Summary/All_DDUs_Inputs_with_Data', destination='CSC/Layouts/02 EMU Summary/All_DDUs_Inputs_with_DataAll_DDUs_Inputs_with_Data', name='EMU Test05 - DDU Inputs Status', overlay='')
register_layout(source='CSC/Summary/All_DDUs_Inputs_Errors', destination='CSC/Layouts/02 EMU Summary/All_DDUs_Inputs_ErrorsAll_DDUs_Inputs_Errors', name='EMU Test06 - DDU Inputs in ERROR-WARNING State', overlay='')
register_layout(source='CSC/Summary/All_DDUs_Inputs_Warnings', destination='CSC/Layouts/02 EMU Summary/All_DDUs_Inputs_WarningsAll_DDUs_Inputs_Warnings', name='EMU Test06 - DDU Inputs in ERROR-WARNING State', overlay='')
register_layout(source='CSC/Summary/CSC_Reporting', destination='CSC/Layouts/02 EMU Summary/CSC_ReportingCSC_Reporting', name='EMU Test08 - CSCs Reporting Data and Unpacked', overlay='')
register_layout(source='CSC/Summary/CSC_Unpacked_Fract', destination='CSC/Layouts/02 EMU Summary/CSC_Unpacked_FractCSC_Unpacked_Fract', name='EMU Test08 - CSCs Reporting Data and Unpacked', overlay='')
register_layout(source='CSC/Summary/CSC_Format_Errors_Fract', destination='CSC/Layouts/02 EMU Summary/CSC_Format_Errors_FractCSC_Format_Errors_Fract', name='EMU Test10 - CSCs with Errors and Warnings (Fractions)', overlay='')
register_layout(source='CSC/Summary/CSC_L1A_out_of_sync_Fract', destination='CSC/Layouts/02 EMU Summary/CSC_L1A_out_of_sync_FractCSC_L1A_out_of_sync_Fract', name='EMU Test10 - CSCs with Errors and Warnings (Fractions)', overlay='')
register_layout(source='CSC/Summary/CSC_DMB_input_fifo_full_Fract', destination='CSC/Layouts/02 EMU Summary/CSC_DMB_input_fifo_full_FractCSC_DMB_input_fifo_full_Fract', name='EMU Test10 - CSCs with Errors and Warnings (Fractions)', overlay='')
register_layout(source='CSC/Summary/CSC_DMB_input_timeout_Fract', destination='CSC/Layouts/02 EMU Summary/CSC_DMB_input_timeout_FractCSC_DMB_input_timeout_Fract', name='EMU Test10 - CSCs with Errors and Warnings (Fractions)', overlay='')
register_layout(source='CSC/Summary/CSC_wo_ALCT_Fract', destination='CSC/Layouts/02 EMU Summary/CSC_wo_ALCT_FractCSC_wo_ALCT_Fract', name='EMU Test11 - CSCs without Data Blocks', overlay='')
register_layout(source='CSC/Summary/CSC_wo_CLCT_Fract', destination='CSC/Layouts/02 EMU Summary/CSC_wo_CLCT_FractCSC_wo_CLCT_Fract', name='EMU Test11 - CSCs without Data Blocks', overlay='')
register_layout(source='CSC/Summary/CSC_wo_CFEB_Fract', destination='CSC/Layouts/02 EMU Summary/CSC_wo_CFEB_FractCSC_wo_CFEB_Fract', name='EMU Test11 - CSCs without Data Blocks', overlay='')
register_layout(source='CSC/Summary/CSC_Format_Warnings_Fract', destination='CSC/Layouts/02 EMU Summary/CSC_Format_Warnings_FractCSC_Format_Warnings_Fract', name='EMU Test11 - CSCs without Data Blocks', overlay='')
register_layout(source='CSC/Summary/CSC_STATS_format_err', destination='CSC/Layouts/03 Shifter/CSC_STATS_format_errCSC_STATS_format_err', name='Chamber Errors and Warnings (Statistically Significant)', overlay='')
register_layout(source='CSC/Summary/CSC_STATS_l1sync_err', destination='CSC/Layouts/03 Shifter/CSC_STATS_l1sync_errCSC_STATS_l1sync_err', name='Chamber Errors and Warnings (Statistically Significant)', overlay='')
register_layout(source='CSC/Summary/CSC_STATS_fifofull_err', destination='CSC/Layouts/03 Shifter/CSC_STATS_fifofull_errCSC_STATS_fifofull_err', name='Chamber Errors and Warnings (Statistically Significant)', overlay='')
register_layout(source='CSC/Summary/CSC_STATS_inputto_err', destination='CSC/Layouts/03 Shifter/CSC_STATS_inputto_errCSC_STATS_inputto_err', name='Chamber Errors and Warnings (Statistically Significant)', overlay='')
register_layout(source='CSC/Summary/CSC_STATS_occupancy', destination='CSC/Layouts/03 Shifter/CSC_STATS_occupancyCSC_STATS_occupancy', name='Chamber Occupancy Exceptions (Statistically Significant)', overlay='')
register_layout(source='CSC/Summary/CSC_STATS_wo_alct', destination='CSC/Layouts/03 Shifter/CSC_STATS_wo_alctCSC_STATS_wo_alct', name='Chambers without Data (Statistically Significant)', overlay='')
register_layout(source='CSC/Summary/CSC_STATS_wo_clct', destination='CSC/Layouts/03 Shifter/CSC_STATS_wo_clctCSC_STATS_wo_clct', name='Chambers without Data (Statistically Significant)', overlay='')
register_layout(source='CSC/Summary/CSC_STATS_wo_cfeb', destination='CSC/Layouts/03 Shifter/CSC_STATS_wo_cfebCSC_STATS_wo_cfeb', name='Chambers without Data (Statistically Significant)', overlay='')
register_layout(source='CSC/Summary/CSC_STATS_cfeb_bwords', destination='CSC/Layouts/03 Shifter/CSC_STATS_cfeb_bwordsCSC_STATS_cfeb_bwords', name='Chambers without Data (Statistically Significant)', overlay='')
register_layout(source='CSC/Summary/CSC_ALCT0_BXN_mean', destination='CSC/Layouts/04 Timing/CSC_ALCT0_BXN_meanCSC_ALCT0_BXN_mean', name='00 ALCT Timing', overlay='')
register_layout(source='CSC/Summary/Plus_endcap_ALCT0_dTime', destination='CSC/Layouts/04 Timing/Plus_endcap_ALCT0_dTimePlus_endcap_ALCT0_dTime', name='00 ALCT Timing', overlay='')
register_layout(source='CSC/Summary/CSC_ALCT0_BXN_rms', destination='CSC/Layouts/04 Timing/CSC_ALCT0_BXN_rmsCSC_ALCT0_BXN_rms', name='00 ALCT Timing', overlay='')
register_layout(source='CSC/Summary/Minus_endcap_ALCT0_dTime', destination='CSC/Layouts/04 Timing/Minus_endcap_ALCT0_dTimeMinus_endcap_ALCT0_dTime', name='00 ALCT Timing', overlay='')
register_layout(source='CSC/Summary/CSC_CLCT0_BXN_mean', destination='CSC/Layouts/04 Timing/CSC_CLCT0_BXN_meanCSC_CLCT0_BXN_mean', name='01 CLCT Timing', overlay='')
register_layout(source='CSC/Summary/Plus_endcap_CLCT0_dTime', destination='CSC/Layouts/04 Timing/Plus_endcap_CLCT0_dTimePlus_endcap_CLCT0_dTime', name='01 CLCT Timing', overlay='')
register_layout(source='CSC/Summary/CSC_CLCT0_BXN_rms', destination='CSC/Layouts/04 Timing/CSC_CLCT0_BXN_rmsCSC_CLCT0_BXN_rms', name='01 CLCT Timing', overlay='')
register_layout(source='CSC/Summary/Minus_endcap_CLCT0_dTime', destination='CSC/Layouts/04 Timing/Minus_endcap_CLCT0_dTimeMinus_endcap_CLCT0_dTime', name='01 CLCT Timing', overlay='')
register_layout(source='CSC/Summary/CSC_AFEB_RawHits_Time_mean', destination='CSC/Layouts/04 Timing/CSC_AFEB_RawHits_Time_meanCSC_AFEB_RawHits_Time_mean', name='02 AFEB RawHits Timing', overlay='')
register_layout(source='CSC/Summary/Plus_endcap_AFEB_RawHits_Time', destination='CSC/Layouts/04 Timing/Plus_endcap_AFEB_RawHits_TimePlus_endcap_AFEB_RawHits_Time', name='02 AFEB RawHits Timing', overlay='')
register_layout(source='CSC/Summary/CSC_AFEB_RawHits_Time_rms', destination='CSC/Layouts/04 Timing/CSC_AFEB_RawHits_Time_rmsCSC_AFEB_RawHits_Time_rms', name='02 AFEB RawHits Timing', overlay='')
register_layout(source='CSC/Summary/Minus_endcap_AFEB_RawHits_Time', destination='CSC/Layouts/04 Timing/Minus_endcap_AFEB_RawHits_TimeMinus_endcap_AFEB_RawHits_Time', name='02 AFEB RawHits Timing', overlay='')
register_layout(source='CSC/Summary/CSC_CFEB_Comparators_Time_mean', destination='CSC/Layouts/04 Timing/CSC_CFEB_Comparators_Time_meanCSC_CFEB_Comparators_Time_mean', name='03 CFEB Comparator Hits Timing', overlay='')
register_layout(source='CSC/Summary/Plus_endcap_CFEB_Comparators_Time', destination='CSC/Layouts/04 Timing/Plus_endcap_CFEB_Comparators_TimePlus_endcap_CFEB_Comparators_Time', name='03 CFEB Comparator Hits Timing', overlay='')
register_layout(source='CSC/Summary/CSC_CFEB_Comparators_Time_rms', destination='CSC/Layouts/04 Timing/CSC_CFEB_Comparators_Time_rmsCSC_CFEB_Comparators_Time_rms', name='03 CFEB Comparator Hits Timing', overlay='')
register_layout(source='CSC/Summary/Minus_endcap_CFEB_Comparators_Time', destination='CSC/Layouts/04 Timing/Minus_endcap_CFEB_Comparators_TimeMinus_endcap_CFEB_Comparators_Time', name='03 CFEB Comparator Hits Timing', overlay='')
register_layout(source='CSC/Summary/CSC_CFEB_SCA_CellPeak_Time_mean', destination='CSC/Layouts/04 Timing/CSC_CFEB_SCA_CellPeak_Time_meanCSC_CFEB_SCA_CellPeak_Time_mean', name='04 CFEB SCA Cell Peak Timing', overlay='')
register_layout(source='CSC/Summary/Plus_endcap_CFEB_SCA_CellPeak_Time', destination='CSC/Layouts/04 Timing/Plus_endcap_CFEB_SCA_CellPeak_TimePlus_endcap_CFEB_SCA_CellPeak_Time', name='04 CFEB SCA Cell Peak Timing', overlay='')
register_layout(source='CSC/Summary/CSC_CFEB_SCA_CellPeak_Time_rms', destination='CSC/Layouts/04 Timing/CSC_CFEB_SCA_CellPeak_Time_rmsCSC_CFEB_SCA_CellPeak_Time_rms', name='04 CFEB SCA Cell Peak Timing', overlay='')
register_layout(source='CSC/Summary/Minus_endcap_CFEB_SCA_CellPeak_Time', destination='CSC/Layouts/04 Timing/Minus_endcap_CFEB_SCA_CellPeak_TimeMinus_endcap_CFEB_SCA_CellPeak_Time', name='04 CFEB SCA Cell Peak Timing', overlay='')
register_layout(source='CSC/Summary/CSC_ALCT_CLCT_Match_mean', destination='CSC/Layouts/04 Timing/CSC_ALCT_CLCT_Match_meanCSC_ALCT_CLCT_Match_mean', name='05 ALCT-CLCT Match Timing', overlay='')
register_layout(source='CSC/Summary/Plus_endcap_CFEB_SCA_CellPeak_Time', destination='CSC/Layouts/04 Timing/Plus_endcap_CFEB_SCA_CellPeak_TimePlus_endcap_CFEB_SCA_CellPeak_Time', name='05 ALCT-CLCT Match Timing', overlay='')
register_layout(source='CSC/Summary/CSC_ALCT_CLCT_Match_rms', destination='CSC/Layouts/04 Timing/CSC_ALCT_CLCT_Match_rmsCSC_ALCT_CLCT_Match_rms', name='05 ALCT-CLCT Match Timing', overlay='')
register_layout(source='CSC/Summary/Minus_endcap_ALCT_CLCT_Match_Time', destination='CSC/Layouts/04 Timing/Minus_endcap_ALCT_CLCT_Match_TimeMinus_endcap_ALCT_CLCT_Match_Time', name='05 ALCT-CLCT Match Timing', overlay='')
register_layout(source='CSC/Summary/Event_Display_Anode', destination='CSC/Layouts/05 EventDisplay/Event_Display_AnodeEvent_Display_Anode', name='01 Event Display in Z-R projection', overlay='')
register_layout(source='CSC/Summary/Event_Display_Cathode', destination='CSC/Layouts/05 EventDisplay/Event_Display_CathodeEvent_Display_Cathode', name='02 Event Display in Z-Phi projection)', overlay='')
register_layout(source='CSC/Summary/Event_Display_XY', destination='CSC/Layouts/05 EventDisplay/Event_Display_XYEvent_Display_XY', name='03 Event Display in X-Y projection', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/recHits/hRHGlobalm1', destination='CSC/Layouts/hRHGlobalm1', name='06 Physics Efficiency - RecHits Minus', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/recHits/hRHGlobalm2', destination='CSC/Layouts/hRHGlobalm2', name='06 Physics Efficiency - RecHits Minus', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/recHits/hRHGlobalm3', destination='CSC/Layouts/hRHGlobalm3', name='06 Physics Efficiency - RecHits Minus', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/recHits/hRHGlobalm4', destination='CSC/Layouts/hRHGlobalm4', name='06 Physics Efficiency - RecHits Minus', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/recHits/hRHGlobalp1', destination='CSC/Layouts/hRHGlobalp1', name='07 Physics Efficiency - RecHits Plus', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/recHits/hRHGlobalp2', destination='CSC/Layouts/hRHGlobalp2', name='07 Physics Efficiency - RecHits Plus', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/recHits/hRHGlobalp3', destination='CSC/Layouts/hRHGlobalp3', name='07 Physics Efficiency - RecHits Plus', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/recHits/hRHGlobalp4', destination='CSC/Layouts/hRHGlobalp4', name='07 Physics Efficiency - RecHits Plus', overlay='')
register_layout(source='CSC/Summary/FEDTotalEventSize', destination='CSC/Layouts/08 FED Data Integrity/FEDTotalEventSizeFEDTotalEventSize', name='00 FED Stats', overlay='')
register_layout(source='CSC/Summary/FEDTotalCSCs', destination='CSC/Layouts/08 FED Data Integrity/FEDTotalCSCsFEDTotalCSCs', name='01 FED CSCs Stats', overlay='')
register_layout(source='CSC/Summary/FEDTotalALCTs', destination='CSC/Layouts/08 FED Data Integrity/FEDTotalALCTsFEDTotalALCTs', name='01 FED CSCs Stats', overlay='')
register_layout(source='CSC/Summary/FEDTotalCFEBs', destination='CSC/Layouts/08 FED Data Integrity/FEDTotalCFEBsFEDTotalCFEBs', name='01 FED CSCs Stats', overlay='')
register_layout(source='CSC/Summary/FEDTotalTMBs', destination='CSC/Layouts/08 FED Data Integrity/FEDTotalTMBsFEDTotalTMBs', name='01 FED CSCs Stats', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeAnode_m13', destination='CSC/Layouts/09 Segments Timing/hSTimeAnode_m13hSTimeAnode_m13', name='01 Anodes Segments Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeAnode_m42', destination='CSC/Layouts/09 Segments Timing/hSTimeAnode_m42hSTimeAnode_m42', name='01 Anodes Segments Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeAnode_m32', destination='CSC/Layouts/09 Segments Timing/hSTimeAnode_m32hSTimeAnode_m32', name='01 Anodes Segments Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeAnode_m22', destination='CSC/Layouts/09 Segments Timing/hSTimeAnode_m22hSTimeAnode_m22', name='01 Anodes Segments Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeAnode_m12', destination='CSC/Layouts/09 Segments Timing/hSTimeAnode_m12hSTimeAnode_m12', name='01 Anodes Segments Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeAnode_m41', destination='CSC/Layouts/09 Segments Timing/hSTimeAnode_m41hSTimeAnode_m41', name='01 Anodes Segments Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeAnode_m31', destination='CSC/Layouts/09 Segments Timing/hSTimeAnode_m31hSTimeAnode_m31', name='01 Anodes Segments Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeAnode_m21', destination='CSC/Layouts/09 Segments Timing/hSTimeAnode_m21hSTimeAnode_m21', name='01 Anodes Segments Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeAnode_m11b', destination='CSC/Layouts/09 Segments Timing/hSTimeAnode_m11bhSTimeAnode_m11b', name='01 Anodes Segments Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeAnode_m11a', destination='CSC/Layouts/09 Segments Timing/hSTimeAnode_m11ahSTimeAnode_m11a', name='01 Anodes Segments Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeAnode_p13', destination='CSC/Layouts/09 Segments Timing/hSTimeAnode_p13hSTimeAnode_p13', name='02 Anodes Segments Timing ME+', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeAnode_p12', destination='CSC/Layouts/09 Segments Timing/hSTimeAnode_p12hSTimeAnode_p12', name='02 Anodes Segments Timing ME+', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeAnode_p22', destination='CSC/Layouts/09 Segments Timing/hSTimeAnode_p22hSTimeAnode_p22', name='02 Anodes Segments Timing ME+', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeAnode_p32', destination='CSC/Layouts/09 Segments Timing/hSTimeAnode_p32hSTimeAnode_p32', name='02 Anodes Segments Timing ME+', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeAnode_p42', destination='CSC/Layouts/09 Segments Timing/hSTimeAnode_p42hSTimeAnode_p42', name='02 Anodes Segments Timing ME+', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeAnode_p11b', destination='CSC/Layouts/09 Segments Timing/hSTimeAnode_p11bhSTimeAnode_p11b', name='02 Anodes Segments Timing ME+', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeAnode_p21', destination='CSC/Layouts/09 Segments Timing/hSTimeAnode_p21hSTimeAnode_p21', name='02 Anodes Segments Timing ME+', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeAnode_p31', destination='CSC/Layouts/09 Segments Timing/hSTimeAnode_p31hSTimeAnode_p31', name='02 Anodes Segments Timing ME+', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeAnode_p41', destination='CSC/Layouts/09 Segments Timing/hSTimeAnode_p41hSTimeAnode_p41', name='02 Anodes Segments Timing ME+', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeAnode_p11a', destination='CSC/Layouts/09 Segments Timing/hSTimeAnode_p11ahSTimeAnode_p11a', name='02 Anodes Segments Timing ME+', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCathode_m13', destination='CSC/Layouts/09 Segments Timing/hSTimeCathode_m13hSTimeCathode_m13', name='03 Cathodes Segments Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCathode_m42', destination='CSC/Layouts/09 Segments Timing/hSTimeCathode_m42hSTimeCathode_m42', name='03 Cathodes Segments Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCathode_m32', destination='CSC/Layouts/09 Segments Timing/hSTimeCathode_m32hSTimeCathode_m32', name='03 Cathodes Segments Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCathode_m22', destination='CSC/Layouts/09 Segments Timing/hSTimeCathode_m22hSTimeCathode_m22', name='03 Cathodes Segments Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCathode_m12', destination='CSC/Layouts/09 Segments Timing/hSTimeCathode_m12hSTimeCathode_m12', name='03 Cathodes Segments Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCathode_m41', destination='CSC/Layouts/09 Segments Timing/hSTimeCathode_m41hSTimeCathode_m41', name='03 Cathodes Segments Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCathode_m31', destination='CSC/Layouts/09 Segments Timing/hSTimeCathode_m31hSTimeCathode_m31', name='03 Cathodes Segments Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCathode_m21', destination='CSC/Layouts/09 Segments Timing/hSTimeCathode_m21hSTimeCathode_m21', name='03 Cathodes Segments Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCathode_m11b', destination='CSC/Layouts/09 Segments Timing/hSTimeCathode_m11bhSTimeCathode_m11b', name='03 Cathodes Segments Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCathode_m11a', destination='CSC/Layouts/09 Segments Timing/hSTimeCathode_m11ahSTimeCathode_m11a', name='03 Cathodes Segments Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCathode_p13', destination='CSC/Layouts/09 Segments Timing/hSTimeCathode_p13hSTimeCathode_p13', name='04 Cathodes Segments Timing ME+', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCathode_p12', destination='CSC/Layouts/09 Segments Timing/hSTimeCathode_p12hSTimeCathode_p12', name='04 Cathodes Segments Timing ME+', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCathode_p22', destination='CSC/Layouts/09 Segments Timing/hSTimeCathode_p22hSTimeCathode_p22', name='04 Cathodes Segments Timing ME+', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCathode_p32', destination='CSC/Layouts/09 Segments Timing/hSTimeCathode_p32hSTimeCathode_p32', name='04 Cathodes Segments Timing ME+', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCathode_p42', destination='CSC/Layouts/09 Segments Timing/hSTimeCathode_p42hSTimeCathode_p42', name='04 Cathodes Segments Timing ME+', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCathode_p11b', destination='CSC/Layouts/09 Segments Timing/hSTimeCathode_p11bhSTimeCathode_p11b', name='04 Cathodes Segments Timing ME+', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCathode_p21', destination='CSC/Layouts/09 Segments Timing/hSTimeCathode_p21hSTimeCathode_p21', name='04 Cathodes Segments Timing ME+', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCathode_p31', destination='CSC/Layouts/09 Segments Timing/hSTimeCathode_p31hSTimeCathode_p31', name='04 Cathodes Segments Timing ME+', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCathode_p41', destination='CSC/Layouts/09 Segments Timing/hSTimeCathode_p41hSTimeCathode_p41', name='04 Cathodes Segments Timing ME+', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCathode_p11a', destination='CSC/Layouts/09 Segments Timing/hSTimeCathode_p11ahSTimeCathode_p11a', name='04 Cathodes Segments Timing ME+', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCombined_m13', destination='CSC/Layouts/09 Segments Timing/hSTimeCombined_m13hSTimeCombined_m13', name='05 Combined (anode+cathode) Segments Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCombined_m42', destination='CSC/Layouts/09 Segments Timing/hSTimeCombined_m42hSTimeCombined_m42', name='05 Combined (anode+cathode) Segments Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCombined_m32', destination='CSC/Layouts/09 Segments Timing/hSTimeCombined_m32hSTimeCombined_m32', name='05 Combined (anode+cathode) Segments Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCombined_m22', destination='CSC/Layouts/09 Segments Timing/hSTimeCombined_m22hSTimeCombined_m22', name='05 Combined (anode+cathode) Segments Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCombined_m12', destination='CSC/Layouts/09 Segments Timing/hSTimeCombined_m12hSTimeCombined_m12', name='05 Combined (anode+cathode) Segments Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCombined_m41', destination='CSC/Layouts/09 Segments Timing/hSTimeCombined_m41hSTimeCombined_m41', name='05 Combined (anode+cathode) Segments Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCombined_m31', destination='CSC/Layouts/09 Segments Timing/hSTimeCombined_m31hSTimeCombined_m31', name='05 Combined (anode+cathode) Segments Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCombined_m21', destination='CSC/Layouts/09 Segments Timing/hSTimeCombined_m21hSTimeCombined_m21', name='05 Combined (anode+cathode) Segments Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCombined_m11b', destination='CSC/Layouts/09 Segments Timing/hSTimeCombined_m11bhSTimeCombined_m11b', name='05 Combined (anode+cathode) Segments Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCombined_m11a', destination='CSC/Layouts/09 Segments Timing/hSTimeCombined_m11ahSTimeCombined_m11a', name='05 Combined (anode+cathode) Segments Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCombined_p13', destination='CSC/Layouts/09 Segments Timing/hSTimeCombined_p13hSTimeCombined_p13', name='06 Combined (anode+cathode) Segments Timing ME+', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCombined_p12', destination='CSC/Layouts/09 Segments Timing/hSTimeCombined_p12hSTimeCombined_p12', name='06 Combined (anode+cathode) Segments Timing ME+', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCombined_p22', destination='CSC/Layouts/09 Segments Timing/hSTimeCombined_p22hSTimeCombined_p22', name='06 Combined (anode+cathode) Segments Timing ME+', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCombined_p32', destination='CSC/Layouts/09 Segments Timing/hSTimeCombined_p32hSTimeCombined_p32', name='06 Combined (anode+cathode) Segments Timing ME+', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCombined_p42', destination='CSC/Layouts/09 Segments Timing/hSTimeCombined_p42hSTimeCombined_p42', name='06 Combined (anode+cathode) Segments Timing ME+', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCombined_p11b', destination='CSC/Layouts/09 Segments Timing/hSTimeCombined_p11bhSTimeCombined_p11b', name='06 Combined (anode+cathode) Segments Timing ME+', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCombined_p21', destination='CSC/Layouts/09 Segments Timing/hSTimeCombined_p21hSTimeCombined_p21', name='06 Combined (anode+cathode) Segments Timing ME+', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCombined_p31', destination='CSC/Layouts/09 Segments Timing/hSTimeCombined_p31hSTimeCombined_p31', name='06 Combined (anode+cathode) Segments Timing ME+', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCombined_p41', destination='CSC/Layouts/09 Segments Timing/hSTimeCombined_p41hSTimeCombined_p41', name='06 Combined (anode+cathode) Segments Timing ME+', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeCombined_p11a', destination='CSC/Layouts/09 Segments Timing/hSTimeCombined_p11ahSTimeCombined_p11a', name='06 Combined (anode+cathode) Segments Timing ME+', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeDiff_m13', destination='CSC/Layouts/09 Segments Timing/hSTimeDiff_m13hSTimeDiff_m13', name='07 Anode minus Cathode Segment Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeDiff_m42', destination='CSC/Layouts/09 Segments Timing/hSTimeDiff_m42hSTimeDiff_m42', name='07 Anode minus Cathode Segment Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeDiff_m32', destination='CSC/Layouts/09 Segments Timing/hSTimeDiff_m32hSTimeDiff_m32', name='07 Anode minus Cathode Segment Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeDiff_m22', destination='CSC/Layouts/09 Segments Timing/hSTimeDiff_m22hSTimeDiff_m22', name='07 Anode minus Cathode Segment Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeDiff_m12', destination='CSC/Layouts/09 Segments Timing/hSTimeDiff_m12hSTimeDiff_m12', name='07 Anode minus Cathode Segment Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeDiff_m41', destination='CSC/Layouts/09 Segments Timing/hSTimeDiff_m41hSTimeDiff_m41', name='07 Anode minus Cathode Segment Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeDiff_m31', destination='CSC/Layouts/09 Segments Timing/hSTimeDiff_m31hSTimeDiff_m31', name='07 Anode minus Cathode Segment Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeDiff_m21', destination='CSC/Layouts/09 Segments Timing/hSTimeDiff_m21hSTimeDiff_m21', name='07 Anode minus Cathode Segment Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeDiff_m11b', destination='CSC/Layouts/09 Segments Timing/hSTimeDiff_m11bhSTimeDiff_m11b', name='07 Anode minus Cathode Segment Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeDiff_m11a', destination='CSC/Layouts/09 Segments Timing/hSTimeDiff_m11ahSTimeDiff_m11a', name='07 Anode minus Cathode Segment Timing ME-', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeDiff_p13', destination='CSC/Layouts/09 Segments Timing/hSTimeDiff_p13hSTimeDiff_p13', name='08 Anode minus Cathode Segment Timing ME+', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeDiff_p12', destination='CSC/Layouts/09 Segments Timing/hSTimeDiff_p12hSTimeDiff_p12', name='08 Anode minus Cathode Segment Timing ME+', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeDiff_p22', destination='CSC/Layouts/09 Segments Timing/hSTimeDiff_p22hSTimeDiff_p22', name='08 Anode minus Cathode Segment Timing ME+', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeDiff_p32', destination='CSC/Layouts/09 Segments Timing/hSTimeDiff_p32hSTimeDiff_p32', name='08 Anode minus Cathode Segment Timing ME+', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeDiff_p42', destination='CSC/Layouts/09 Segments Timing/hSTimeDiff_p42hSTimeDiff_p42', name='08 Anode minus Cathode Segment Timing ME+', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeDiff_p11b', destination='CSC/Layouts/09 Segments Timing/hSTimeDiff_p11bhSTimeDiff_p11b', name='08 Anode minus Cathode Segment Timing ME+', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeDiff_p21', destination='CSC/Layouts/09 Segments Timing/hSTimeDiff_p21hSTimeDiff_p21', name='08 Anode minus Cathode Segment Timing ME+', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeDiff_p31', destination='CSC/Layouts/09 Segments Timing/hSTimeDiff_p31hSTimeDiff_p31', name='08 Anode minus Cathode Segment Timing ME+', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeDiff_p41', destination='CSC/Layouts/09 Segments Timing/hSTimeDiff_p41hSTimeDiff_p41', name='08 Anode minus Cathode Segment Timing ME+', overlay='')
register_layout(source='CSC/CSCOfflineMonitor/Segments/hSTimeDiff_p11a', destination='CSC/Layouts/09 Segments Timing/hSTimeDiff_p11ahSTimeDiff_p11a', name='08 Anode minus Cathode Segment Timing ME+', overlay='')
