from ..layouts.layout_manager import register_layout

register_layout(source='HLT/TriggerRates/HLT/HLT_PFJet200_v2 accept', destination='HLT/Layouts/HLT_PFJet200_v2 acceptHLT_PFJet200_v2 accept', name='highestRate Summary', description='# accepts per LS (divide by 23.3 to get rate in Hz)', overlay='')
register_layout(source='HLT/TriggerRates/HLT/HLT_Ele27_eta2p1_WPLoose_Gsf_v1 accept', destination='HLT/Layouts/HLT_Ele27_eta2p1_WPLoose_Gsf_v1 acceptHLT_Ele27_eta2p1_WPLoose_Gsf_v1 accept', name='highestRate Summary', description='# accepts per LS (divide by 23.3 to get rate in Hz)', overlay='')
register_layout(source='HLT/TriggerRates/HLT/HLT_Photon30_R9Id90_HE10_IsoM_v2 accept', destination='HLT/Layouts/HLT_Photon30_R9Id90_HE10_IsoM_v2 acceptHLT_Photon30_R9Id90_HE10_IsoM_v2 accept', name='highestRate Summary', description='# accepts per LS (divide by 23.3 to get rate in Hz)', overlay='')
register_layout(source='HLT/TriggerRates/HLT/HLT_IsoMu24_eta2p1_v2 accept', destination='HLT/Layouts/HLT_IsoMu24_eta2p1_v2 acceptHLT_IsoMu24_eta2p1_v2 accept', name='highestRate Summary', description='# accepts per LS (divide by 23.3 to get rate in Hz)', overlay='')
register_layout(source='HLT/Layouts/secondaryObjectMonitor/TrackEta_ImpactPoint_GenTk', destination='Collisions/HLTFeedBack/TrackEta_ImpactPoint_GenTk', description='', overlay='')
register_layout(source='HLT/Layouts/secondaryObjectMonitor/bJet_phi', destination='Collisions/HLTFeedBack/bJet_phi', description='', overlay='')
register_layout(source='HLT/Layouts/secondaryObjectMonitor/Photon_eta', destination='Collisions/HLTFeedBack/Photon_eta', description='', overlay='')
register_layout(source='HLT/Layouts/secondaryObjectMonitor/Photon_phi', destination='Collisions/HLTFeedBack/Photon_phi', description='', overlay='')
register_layout(source='HLT/Layouts/secondaryObjectMonitor/Muon_eta', destination='Collisions/HLTFeedBack/Muon_eta', description='', overlay='')
register_layout(source='HLT/Layouts/secondaryObjectMonitor/Muon_phi', destination='Collisions/HLTFeedBack/Muon_phi', description='', overlay='')
register_layout(source='HLT/Layouts/secondaryObjectMonitor/L2Muon_eta', destination='Collisions/HLTFeedBack/L2Muon_eta', description='', overlay='')
register_layout(source='HLT/Layouts/secondaryObjectMonitor/L2Muon_phi', destination='Collisions/HLTFeedBack/L2Muon_phi', description='', overlay='')
register_layout(source='HLT/Layouts/secondaryObjectMonitor/L2NoBPTXMuon_eta', destination='Collisions/HLTFeedBack/L2NoBPTXMuon_eta', description='', overlay='')
register_layout(source='HLT/Layouts/secondaryObjectMonitor/L2NoBPTXMuon_phi', destination='Collisions/HLTFeedBack/L2NoBPTXMuon_phi', description='', overlay='')
register_layout(source='HLT/Layouts/secondaryObjectMonitor/Electron_eta', destination='Collisions/HLTFeedBack/Electron_eta', description='', overlay='')
register_layout(source='HLT/Layouts/secondaryObjectMonitor/Electron_phi', destination='Collisions/HLTFeedBack/Electron_phi', description='', overlay='')
register_layout(source='HLT/Layouts/secondaryObjectMonitor/CaloMET_phi', destination='Collisions/HLTFeedBack/CaloMET_phi', description='', overlay='')
register_layout(source='HLT/Layouts/secondaryObjectMonitor/PFMET_phi', destination='Collisions/HLTFeedBack/PFMET_phi', description='', overlay='')
register_layout(source='HLT/Layouts/secondaryObjectMonitor/bJet_phi', destination='Collisions/HLTFeedBack/bJet_phi', description='', overlay='')
register_layout(source='HLT/Layouts/secondaryObjectMonitor/bJet_eta', destination='Collisions/HLTFeedBack/bJet_eta', description='', overlay='')
register_layout(source='HLT/Layouts/secondaryObjectMonitor/TrackEta_ImpactPoint_GenTk__iter2Merged', destination='Collisions/HLTFeedBack/TrackEta_ImpactPoint_GenTk__iter2Merged', description='', overlay='')
register_layout(source='HLT/Layouts/secondaryObjectMonitor/TrackEta_ImpactPoint_GenTk__pixelTracks', destination='Collisions/HLTFeedBack/TrackEta_ImpactPoint_GenTk__pixelTracks', description='', overlay='')
register_layout(source='HLT/Layouts/secondaryObjectMonitor/MergedTrackPhi_ImpactPoint_GenTk__iter2Merged', destination='Collisions/HLTFeedBack/MergedTrackPhi_ImpactPoint_GenTk__iter2Merged', description='', overlay='')
register_layout(source='HLT/Layouts/secondaryObjectMonitor/TrackPhi_ImpactPoint_GenTk__pixelTracks', destination='Collisions/HLTFeedBack/TrackPhi_ImpactPoint_GenTk__pixelTracks', description='', overlay='')
register_layout(source='HLT/Layouts/secondaryObjectMonitor/NumberOfTracks_GenTk__iter2Merged', destination='Collisions/HLTFeedBack/NumberOfTracks_GenTk__iter2Merged', description='', overlay='')
register_layout(source='HLT/Layouts/secondaryObjectMonitor/NumberOfTracks_GenTk__pixelTracks', destination='Collisions/HLTFeedBack/NumberOfTracks_GenTk__pixelTracks', description='', overlay='')
register_layout(source='HLT/Layouts/secondaryObjectMonitor/Summary_ClusterCharge_OffTrack__TIB', destination='Collisions/HLTFeedBack/Summary_ClusterCharge_OffTrack__TIB', description='', overlay='')
register_layout(source='HLT/Layouts/secondaryObjectMonitor/Summary_ClusterStoNCorr_OnTrack__TIB', destination='Collisions/HLTFeedBack/Summary_ClusterStoNCorr_OnTrack__TIB', description='', overlay='')
register_layout(source='HLT/Layouts/secondaryObjectMonitor/Summary_ClusterStoNCorr_OnTrack__TOB', destination='Collisions/HLTFeedBack/Summary_ClusterStoNCorr_OnTrack__TOB', description='', overlay='')
register_layout(source='HLT/Layouts/secondaryObjectMonitor/Summary_ClusterStoNCorr_OnTrack__TID__MINUS', destination='Collisions/HLTFeedBack/Summary_ClusterStoNCorr_OnTrack__TID__MINUS', description='', overlay='')
register_layout(source='HLT/Layouts/secondaryObjectMonitor/Summary_ClusterStoNCorr_OnTrack__TID__PLUS', destination='Collisions/HLTFeedBack/Summary_ClusterStoNCorr_OnTrack__TID__PLUS', description='', overlay='')
register_layout(source='HLT/Layouts/secondaryObjectMonitor/Summary_ClusterStoNCorr_OnTrack__TEC__MINUS', destination='Collisions/HLTFeedBack/Summary_ClusterStoNCorr_OnTrack__TEC__MINUS', description='', overlay='')
register_layout(source='HLT/Layouts/secondaryObjectMonitor/Summary_ClusterStoNCorr_OnTrack__TEC__PLUS', destination='Collisions/HLTFeedBack/Summary_ClusterStoNCorr_OnTrack__TEC__PLUS', description='', overlay='')
register_layout(source='HLT/FourVectorHLT/HLT1Electron_etaphi', destination='HLT/Layouts/00-FourVector-Summary/HLT1Electron_etaphi', description='', overlay='')
register_layout(source='L1T/L1TScalersSCAL/Level1TriggerRates/Physics Trigger Rate', destination='L1T/Layouts/TPG-Summary-L1T/Physics Trigger Rate', name='01 - L1 Predeadtime Rate - Physics', description='Physics Predeadtime', overlay='')
register_layout(source='L1T/L1TScalersSCAL/Level1TriggerRates/TechnicalRates/Rate_TechBit_005', destination='L1T/Layouts/TPG-Summary-L1T/Rate_TechBit_005', name='02 - L1 Predeadtime Rate - Technical', description='Technical Predeadtime', overlay='')
register_layout(source='L1T/L1TGMT/bx_DT_vs_CSC', destination='L1T/Layouts/TPG-Summary-L1T/bx_DT_vs_CSC', name='03.01 - Muon Timing DT vs CSC', description='Muon Timing', overlay='')
register_layout(source='L1T/L1TGMT/bx_DT_vs_RPC', destination='L1T/Layouts/TPG-Summary-L1T/bx_DT_vs_RPC', name='03.02 - Muon Timing DT vs RPC', description='Muon Timing', overlay='')
register_layout(source='L1T/L1TGMT/bx_CSC_vs_RPC', destination='L1T/Layouts/TPG-Summary-L1T/bx_CSC_vs_RPC', name='03.03 - Muon Timing DT vs RPC', description='Muon Timing', overlay='')
register_layout(source='HLT/HLTScalers_EvF/hltRateNorm', destination='HLT/Layouts/TPG-Summary-HLT/hltRateNorm', name='01 - HLT Postdeadtime Rate', description='HLT Rate Postdeadtime', overlay='')
register_layout(source='HLT/HLTScalers_EvF/RateHistory/norm_rate_p093', destination='HLT/Layouts/TPG-Summary-HLT/norm_rate_p093', name='02 - HLT MinBiasBSC Rate', description='HLT MinBias BSC Rate per lumi sec', overlay='')
register_layout(source='HLT/HLTScalers_EvF/RateHistory/norm_rate_p092', destination='HLT/Layouts/TPG-Summary-HLT/norm_rate_p092', name='03 - HLT ZeroBias Rate', description='HLT Zero Bias Rate per lumi sec', overlay='')
register_layout(source='HLT/HLTMonMuon/L3Triggers/Level3/HLTMuonL3_etaphi', destination='HLT/Layouts/TPG-Summary-HLT/HLTMuonL3_etaphi', name='04 - Muon POG HLT', description='Muons Passing HLT_Mu3 Occupancy phi vs eta', overlay='')
register_layout(source='HLT/HLTMonMuon/L3Triggers/Level3/HLTMuonL3_pt', destination='HLT/Layouts/TPG-Summary-HLT/HLTMuonL3_pt', name='05 - Muon POG HLT', description='Muons Passing HLT_Mu3 Occpancy vs Pt', overlay='')
register_layout(source='HLT/HLTMonMuon/L1PassThrough/Level1/HLTMuonL1_etaphi', destination='HLT/Layouts/TPG-Summary-HLT/HLTMuonL1_etaphi', name='06 - Muon POG L1 Passthru', description='Muons Passing HLT_L1Mu Occpancy phi vs eta', overlay='')
register_layout(source='HLT/HLTMonMuon/L1PassThrough/Level1/HLTMuonL1_pt', destination='HLT/Layouts/TPG-Summary-HLT/HLTMuonL1_pt', name='07 - Muon POG L1 Passthru', description='Muons Passing HLT_L1Mu Occpancy vs Pt', overlay='')
register_layout(source='HLT/JetMET/All/HLT_Jet15U/HLT_Jet15U_EtaPhi', destination='HLT/Layouts/TPG-Summary-HLT/HLT_Jet15U_EtaPhi', name='08 - JET POG HLT', description='HLT_Jet15U occupancy eta vs phi', overlay='')
register_layout(source='HLT/JetMET/All/HLT_Jet15U/HLT_Jet15U_Et', destination='HLT/Layouts/TPG-Summary-HLT/HLT_Jet15U_Et', name='09 - JET POG HLT', description='HLT_Jet15U occupancy Et', overlay='')
register_layout(source='HLT/JetMET/All/HLT_L1Jet6U/HLT_L1Jet6U_EtaPhi', destination='HLT/Layouts/TPG-Summary-HLT/HLT_L1Jet6U_EtaPhi', name='10 - JET POG HLT L1 Passthru', description='HLT_L1Jet6U occupancy, eta vs phi', overlay='')
register_layout(source='HLT/JetMET/All/HLT_L1Jet6U/HLT_L1Jet6U_Et', destination='HLT/Layouts/TPG-Summary-HLT/HLT_L1Jet6U_Et', name='11 - JET POG HLT L1 Passthru', description='HLT_L1Jet6U occupancy, Et ', overlay='')
register_layout(source='HLT/FourVector/paths/HLT_Ele10_LW_L1R/HLT_Ele10_LW_L1R_wrt__l1Etal1PhiL1On', destination='HLT/Layouts/TPG-Summary-HLT/HLT_Ele10_LW_L1R_wrt__l1Etal1PhiL1On', name='12 - EG POG HLT ', description='HLT_Ele10_LW_L1R occupancy, eta vs phi', overlay='')
register_layout(source='HLT/FourVector/paths/HLT_Ele10_LW_L1R/HLT_Ele10_LW_L1R_wrt__l1EtL1', destination='HLT/Layouts/TPG-Summary-HLT/HLT_Ele10_LW_L1R_wrt__l1EtL1', name='13 - EG POG HLT', description='', overlay='')
register_layout(source='HLT/FourVector/paths/HLT_SingleLooseIsoTau20/HLT_SingleLooseIsoTau20_wrt__l1EtL1', destination='HLT/Layouts/TPG-Summary-HLT/HLT_SingleLooseIsoTau20_wrt__l1EtL1', name='14 - Tau POG HLT', description='SingleLooseIsoTau20 et', overlay='')
register_layout(source='HLT/FourVector/paths/HLT_SingleLooseIsoTau20/HLT_SingleLooseIsoTau20_wrt__l1Etal1PhiL1OnUM', destination='HLT/Layouts/TPG-Summary-HLT/HLT_SingleLooseIsoTau20_wrt__l1Etal1PhiL1OnUM', name='15 - Tau POG HLT', description='SingleLooseIsoTau20 eta vs phi', overlay='')
