from ..layouts.layout_manager import register_layout

register_layout(source='JetMET/Jet/Cleanedak4CaloJets/PtFirst', destination='00 Shift/JetMET/PtFirst', name='01 Calo Jet Plots (for collisions)', overlay='')
register_layout(source='JetMET/Jet/Cleanedak4CaloJets/Constituents', destination='00 Shift/JetMET/Constituents', name='01 Calo Jet Plots (for collisions)', overlay='')
register_layout(source='JetMET/Jet/Cleanedak4CaloJets/Phi', destination='00 Shift/JetMET/Phi', name='01 Calo Jet Plots (for collisions)', overlay='')
register_layout(source='JetMET/Jet/Cleanedak4CaloJets/EtaFirst', destination='00 Shift/JetMET/EtaFirst', name='01 Calo Jet Plots (for collisions)', overlay='')
register_layout(source='JetMET/Jet/Cleanedak4PFJets/PtFirst', destination='00 Shift/JetMET/PtFirst', name='02 PF Jet Plots (for collisions)', overlay='')
register_layout(source='JetMET/Jet/Cleanedak4PFJets/Eta', destination='00 Shift/JetMET/Eta', name='02 PF Jet Plots (for collisions)', overlay='')
register_layout(source='JetMET/Jet/Cleanedak4PFJets/Constituents', destination='00 Shift/JetMET/Constituents', name='02 PF Jet Plots (for collisions)', overlay='')
register_layout(source='JetMET/Jet/Cleanedak4PFJets/NJets', destination='00 Shift/JetMET/NJets', name='02 PF Jet Plots (for collisions)', overlay='')
register_layout(source='JetMET/Jet/Cleanedak4PFJets/Phi_Barrel', destination='00 Shift/JetMET/Phi_Barrel', name='03 PF Jet Plots (for collisions)', overlay='')
register_layout(source='JetMET/Jet/Cleanedak4PFJets/Phi_EndCap', destination='00 Shift/JetMET/Phi_EndCap', name='03 PF Jet Plots (for collisions)', overlay='')
register_layout(source='JetMET/Jet/Cleanedak4PFJets/Phi_Forward', destination='00 Shift/JetMET/Phi_Forward', name='03 PF Jet Plots (for collisions)', overlay='')
register_layout(source='JetMET/MET/pfMet/Cleaned/MET', destination='00 Shift/JetMET/MET', name='05 PF MET Plots (for collisions)', overlay='')
register_layout(source='JetMET/MET/pfMet/Cleaned/METPhi', destination='00 Shift/JetMET/METPhi', name='05 PF MET Plots (for collisions)', overlay='')
register_layout(source='JetMET/MET/pfMet/Cleaned/MEx', destination='00 Shift/JetMET/MEx', name='05 PF MET Plots (for collisions)', overlay='')
register_layout(source='JetMET/MET/pfMet/Cleaned/MEy', destination='00 Shift/JetMET/MEy', name='05 PF MET Plots (for collisions)', overlay='')
register_layout(source='JetMET/MET/pfMet/Cleaned/SumET', destination='00 Shift/JetMET/SumET', name='06 PF MET Plots (for collisions)', overlay='')
register_layout(source='JetMET/MET/pfMet/Cleaned/MET_logx', destination='00 Shift/JetMET/MET_logx', name='06 PF MET Plots (for collisions)', overlay='')
register_layout(source='JetMET/MET/pfMet/Cleaned/PfPhotonEtFraction', destination='00 Shift/JetMET/PfPhotonEtFraction', name='07 PF MET Plots (for collisions)', overlay='')
register_layout(source='JetMET/MET/pfMet/Cleaned/PfNeutralHadronEtFraction', destination='00 Shift/JetMET/PfNeutralHadronEtFraction', name='07 PF MET Plots (for collisions)', overlay='')
register_layout(source='JetMET/MET/pfMet/Cleaned/h0Barrel_multiplicity_', destination='00 Shift/JetMET/h0Barrel_multiplicity_', name='07 PF MET Plots (for collisions)', overlay='')
register_layout(source='JetMET/MET/pfMet/Cleaned/h0Endcap_multiplicity_', destination='00 Shift/JetMET/h0Endcap_multiplicity_', name='07 PF MET Plots (for collisions)', overlay='')
register_layout(source='JetMET/MET/pfMet/Cleaned/PfHFEMEtFraction', destination='00 Shift/JetMET/PfHFEMEtFraction', name='08 PF MET Plots (for collisions)', overlay='')
register_layout(source='JetMET/MET/pfMet/Cleaned/PfHFHadronEtFraction', destination='00 Shift/JetMET/PfHFHadronEtFraction', name='08 PF MET Plots (for collisions)', overlay='')
register_layout(source='JetMET/MET/pfMet/Cleaned/PfChargedHadronEtFraction', destination='00 Shift/JetMET/PfChargedHadronEtFraction', name='08 PF MET Plots (for collisions)', overlay='')
register_layout(source='JetMET/MET/pfMet/Cleaned/h_occupancy_', destination='00 Shift/JetMET/h_occupancy_', name='09 PF candidates map', overlay='')
