from ..layouts.layout_manager import register_layout

register_layout(source='SiStrip/MechanicalView/detFractionReportMap', destination='00 Shift/SiStrip/detFractionReportMap', name='00 - SiStrip ReportSummary', overlay='')
register_layout(source='SiStrip/MechanicalView/sToNReportMap', destination='00 Shift/SiStrip/sToNReportMap', name='00 - SiStrip ReportSummary', overlay='')
register_layout(source='SiStrip/EventInfo/reportSummaryMap', destination='00 Shift/SiStrip/reportSummaryMap', name='00 - SiStrip ReportSummary', overlay='')
register_layout(source='SiStrip/ReadoutView/FEDErrorsVsId', destination='00 Shift/SiStrip/FEDErrorsVsId', name='01 - FED Errors vs FED ID and APV ID', overlay='')
register_layout(source='SiStrip/ReadoutView/FedIdVsApvId', destination='00 Shift/SiStrip/FedIdVsApvId', name='01 - FED Errors vs FED ID and APV ID', overlay='')
register_layout(source='SiStrip/ReadoutView/FED/nFEDErrors', destination='00 Shift/SiStrip/nFEDErrors', name='01a - FED-Detected Errors Summary', overlay='')
register_layout(source='SiStrip/ReadoutView/Fiber/nBadActiveChannelStatusBits', destination='00 Shift/SiStrip/nBadActiveChannelStatusBits', name='01a - FED-Detected Errors Summary', overlay='')
register_layout(source='SiStrip/ReadoutView/Fiber/VsId/BadActiveChannelStatusBits', destination='00 Shift/SiStrip/BadActiveChannelStatusBits', name='01b - FED-Detected Errors', overlay='')
register_layout(source='SiStrip/ReadoutView/Fiber/VsId/BadChannelStatusBits', destination='00 Shift/SiStrip/BadChannelStatusBits', name='01b - FED-Detected Errors', overlay='')
register_layout(source='SiStrip/ReadoutView/FED/VsId/AnyFEDErrors', destination='00 Shift/SiStrip/AnyFEDErrors', name='01b - FED-Detected Errors', overlay='')
register_layout(source='SiStrip/ReadoutView/Fiber/nUnlocked', destination='00 Shift/SiStrip/nUnlocked', name='01b - FED-Detected Errors', overlay='')
register_layout(source='SiStrip/ReadoutView/Fiber/nOutOfSync', destination='00 Shift/SiStrip/nOutOfSync', name='01b - FED-Detected Errors', overlay='')
register_layout(source='SiStrip/ReadoutView/APV/nAPVAddressError', destination='00 Shift/SiStrip/nAPVAddressError', name='01b - FED-Detected Errors', overlay='')
register_layout(source='SiStrip/MechanicalView/TIB/TotalNumberOfClusterProfile__TIB', destination='00 Shift/SiStrip/TotalNumberOfClusterProfile__TIB', name='02 - # of Cluster Trend', overlay='')
register_layout(source='SiStrip/MechanicalView/TOB/TotalNumberOfClusterProfile__TOB', destination='00 Shift/SiStrip/TotalNumberOfClusterProfile__TOB', name='02 - # of Cluster Trend', overlay='')
register_layout(source='SiStrip/MechanicalView/TID/MINUS/TotalNumberOfClusterProfile__TID__MINUS', destination='00 Shift/SiStrip/TotalNumberOfClusterProfile__TID__MINUS', name='02 - # of Cluster Trend', overlay='')
register_layout(source='SiStrip/MechanicalView/TID/PLUS/TotalNumberOfClusterProfile__TID__PLUS', destination='00 Shift/SiStrip/TotalNumberOfClusterProfile__TID__PLUS', name='02 - # of Cluster Trend', overlay='')
register_layout(source='SiStrip/MechanicalView/TEC/MINUS/TotalNumberOfClusterProfile__TEC__MINUS', destination='00 Shift/SiStrip/TotalNumberOfClusterProfile__TEC__MINUS', name='02 - # of Cluster Trend', overlay='')
register_layout(source='SiStrip/MechanicalView/TEC/PLUS/TotalNumberOfClusterProfile__TEC__PLUS', destination='00 Shift/SiStrip/TotalNumberOfClusterProfile__TEC__PLUS', name='02 - # of Cluster Trend', overlay='')
register_layout(source='SiStrip/MechanicalView/TIB/Summary_ClusterStoNCorr_OnTrack__TIB', destination='00 Shift/SiStrip/Summary_ClusterStoNCorr_OnTrack__TIB', name='03a OnTrackCluster (StoN)', overlay='')
register_layout(source='SiStrip/MechanicalView/TOB/Summary_ClusterStoNCorr_OnTrack__TOB', destination='00 Shift/SiStrip/Summary_ClusterStoNCorr_OnTrack__TOB', name='03a OnTrackCluster (StoN)', overlay='')
register_layout(source='SiStrip/MechanicalView/TID/MINUS/Summary_ClusterStoNCorr_OnTrack__TID__MINUS', destination='00 Shift/SiStrip/Summary_ClusterStoNCorr_OnTrack__TID__MINUS', name='03a OnTrackCluster (StoN)', overlay='')
register_layout(source='SiStrip/MechanicalView/TID/PLUS/Summary_ClusterStoNCorr_OnTrack__TID__PLUS', destination='00 Shift/SiStrip/Summary_ClusterStoNCorr_OnTrack__TID__PLUS', name='03a OnTrackCluster (StoN)', overlay='')
register_layout(source='SiStrip/MechanicalView/TEC/MINUS/Summary_ClusterStoNCorr_OnTrack__TEC__MINUS', destination='00 Shift/SiStrip/Summary_ClusterStoNCorr_OnTrack__TEC__MINUS', name='03a OnTrackCluster (StoN)', overlay='')
register_layout(source='SiStrip/MechanicalView/TEC/PLUS/Summary_ClusterStoNCorr_OnTrack__TEC__PLUS', destination='00 Shift/SiStrip/Summary_ClusterStoNCorr_OnTrack__TEC__PLUS', name='03a OnTrackCluster (StoN)', overlay='')
register_layout(source='SiStrip/MechanicalView/TIB/Summary_ClusterChargePerCMfromOrigin_OnTrack__TIB', destination='00 Shift/SiStrip/Summary_ClusterChargePerCMfromOrigin_OnTrack__TIB', name='03b - Cluster Charge per CM (On-Track)', overlay='')
register_layout(source='SiStrip/MechanicalView/TOB/Summary_ClusterChargePerCMfromOrigin_OnTrack__TOB', destination='00 Shift/SiStrip/Summary_ClusterChargePerCMfromOrigin_OnTrack__TOB', name='03b - Cluster Charge per CM (On-Track)', overlay='')
register_layout(source='SiStrip/MechanicalView/TID/MINUS/Summary_ClusterChargePerCMfromOrigin_OnTrack__TID__MINUS', destination='00 Shift/SiStrip/Summary_ClusterChargePerCMfromOrigin_OnTrack__TID__MINUS', name='03b - Cluster Charge per CM (On-Track)', overlay='')
register_layout(source='SiStrip/MechanicalView/TID/PLUS/Summary_ClusterChargePerCMfromOrigin_OnTrack__TID__PLUS', destination='00 Shift/SiStrip/Summary_ClusterChargePerCMfromOrigin_OnTrack__TID__PLUS', name='03b - Cluster Charge per CM (On-Track)', overlay='')
register_layout(source='SiStrip/MechanicalView/TEC/MINUS/Summary_ClusterChargePerCMfromOrigin_OnTrack__TEC__MINUS', destination='00 Shift/SiStrip/Summary_ClusterChargePerCMfromOrigin_OnTrack__TEC__MINUS', name='03b - Cluster Charge per CM (On-Track)', overlay='')
register_layout(source='SiStrip/MechanicalView/TEC/PLUS/Summary_ClusterChargePerCMfromOrigin_OnTrack__TEC__PLUS', destination='00 Shift/SiStrip/Summary_ClusterChargePerCMfromOrigin_OnTrack__TEC__PLUS', name='03b - Cluster Charge per CM (On-Track)', overlay='')
register_layout(source='SiStrip/MechanicalView/TIB/layer_1/HitResiduals_TIB__Layer__1', destination='00 Shift/SiStrip/HitResiduals_TIB__Layer__1', name='04a - TIB Residuals', overlay='')
register_layout(source='SiStrip/MechanicalView/TIB/layer_2/HitResiduals_TIB__Layer__2', destination='00 Shift/SiStrip/HitResiduals_TIB__Layer__2', name='04a - TIB Residuals', overlay='')
register_layout(source='SiStrip/MechanicalView/TIB/layer_3/HitResiduals_TIB__Layer__3', destination='00 Shift/SiStrip/HitResiduals_TIB__Layer__3', name='04a - TIB Residuals', overlay='')
register_layout(source='SiStrip/MechanicalView/TIB/layer_4/HitResiduals_TIB__Layer__4', destination='00 Shift/SiStrip/HitResiduals_TIB__Layer__4', name='04a - TIB Residuals', overlay='')
register_layout(source='SiStrip/MechanicalView/TOB/layer_1/HitResiduals_TOB__Layer__1', destination='00 Shift/SiStrip/HitResiduals_TOB__Layer__1', name='04b - TOB Residuals', overlay='')
register_layout(source='SiStrip/MechanicalView/TOB/layer_2/HitResiduals_TOB__Layer__2', destination='00 Shift/SiStrip/HitResiduals_TOB__Layer__2', name='04b - TOB Residuals', overlay='')
register_layout(source='SiStrip/MechanicalView/TOB/layer_3/HitResiduals_TOB__Layer__3', destination='00 Shift/SiStrip/HitResiduals_TOB__Layer__3', name='04b - TOB Residuals', overlay='')
register_layout(source='SiStrip/MechanicalView/TOB/layer_4/HitResiduals_TOB__Layer__4', destination='00 Shift/SiStrip/HitResiduals_TOB__Layer__4', name='04b - TOB Residuals', overlay='')
register_layout(source='SiStrip/MechanicalView/TOB/layer_5/HitResiduals_TOB__Layer__5', destination='00 Shift/SiStrip/HitResiduals_TOB__Layer__5', name='04b - TOB Residuals', overlay='')
register_layout(source='SiStrip/MechanicalView/TOB/layer_6/HitResiduals_TOB__Layer__6', destination='00 Shift/SiStrip/HitResiduals_TOB__Layer__6', name='04b - TOB Residuals', overlay='')
register_layout(source='SiStrip/MechanicalView/TID/PLUS/wheel_1/HitResiduals_TID__wheel__1', destination='00 Shift/SiStrip/HitResiduals_TID__wheel__1', name='04c - TID+ Residuals', overlay='')
register_layout(source='SiStrip/MechanicalView/TID/PLUS/wheel_2/HitResiduals_TID__wheel__2', destination='00 Shift/SiStrip/HitResiduals_TID__wheel__2', name='04c - TID+ Residuals', overlay='')
register_layout(source='SiStrip/MechanicalView/TID/PLUS/wheel_3/HitResiduals_TID__wheel__3', destination='00 Shift/SiStrip/HitResiduals_TID__wheel__3', name='04c - TID+ Residuals', overlay='')
register_layout(source='SiStrip/MechanicalView/TID/MINUS/wheel_1/HitResiduals_TID__wheel__1', destination='00 Shift/SiStrip/HitResiduals_TID__wheel__1', name='04d - TID- Residuals', overlay='')
register_layout(source='SiStrip/MechanicalView/TID/MINUS/wheel_2/HitResiduals_TID__wheel__2', destination='00 Shift/SiStrip/HitResiduals_TID__wheel__2', name='04d - TID- Residuals', overlay='')
register_layout(source='SiStrip/MechanicalView/TID/MINUS/wheel_3/HitResiduals_TID__wheel__3', destination='00 Shift/SiStrip/HitResiduals_TID__wheel__3', name='04d - TID- Residuals', overlay='')
register_layout(source='SiStrip/MechanicalView/TEC/PLUS/wheel_1/HitResiduals_TEC__wheel__1', destination='00 Shift/SiStrip/HitResiduals_TEC__wheel__1', name='04e - TEC+ Residual', overlay='')
register_layout(source='SiStrip/MechanicalView/TEC/PLUS/wheel_2/HitResiduals_TEC__wheel__2', destination='00 Shift/SiStrip/HitResiduals_TEC__wheel__2', name='04e - TEC+ Residual', overlay='')
register_layout(source='SiStrip/MechanicalView/TEC/PLUS/wheel_3/HitResiduals_TEC__wheel__3', destination='00 Shift/SiStrip/HitResiduals_TEC__wheel__3', name='04e - TEC+ Residual', overlay='')
register_layout(source='SiStrip/MechanicalView/TEC/PLUS/wheel_4/HitResiduals_TEC__wheel__4', destination='00 Shift/SiStrip/HitResiduals_TEC__wheel__4', name='04e - TEC+ Residual', overlay='')
register_layout(source='SiStrip/MechanicalView/TEC/PLUS/wheel_5/HitResiduals_TEC__wheel__5', destination='00 Shift/SiStrip/HitResiduals_TEC__wheel__5', name='04e - TEC+ Residual', overlay='')
register_layout(source='SiStrip/MechanicalView/TEC/PLUS/wheel_6/HitResiduals_TEC__wheel__6', destination='00 Shift/SiStrip/HitResiduals_TEC__wheel__6', name='04e - TEC+ Residual', overlay='')
register_layout(source='SiStrip/MechanicalView/TEC/PLUS/wheel_7/HitResiduals_TEC__wheel__7', destination='00 Shift/SiStrip/HitResiduals_TEC__wheel__7', name='04e - TEC+ Residual', overlay='')
register_layout(source='SiStrip/MechanicalView/TEC/PLUS/wheel_8/HitResiduals_TEC__wheel__8', destination='00 Shift/SiStrip/HitResiduals_TEC__wheel__8', name='04e - TEC+ Residual', overlay='')
register_layout(source='SiStrip/MechanicalView/TEC/PLUS/wheel_9/HitResiduals_TEC__wheel__9', destination='00 Shift/SiStrip/HitResiduals_TEC__wheel__9', name='04e - TEC+ Residual', overlay='')
register_layout(source='SiStrip/MechanicalView/TEC/MINUS/wheel_1/HitResiduals_TEC__wheel__1', destination='00 Shift/SiStrip/HitResiduals_TEC__wheel__1', name='04f - TEC- Residual', overlay='')
register_layout(source='SiStrip/MechanicalView/TEC/MINUS/wheel_2/HitResiduals_TEC__wheel__2', destination='00 Shift/SiStrip/HitResiduals_TEC__wheel__2', name='04f - TEC- Residual', overlay='')
register_layout(source='SiStrip/MechanicalView/TEC/MINUS/wheel_3/HitResiduals_TEC__wheel__3', destination='00 Shift/SiStrip/HitResiduals_TEC__wheel__3', name='04f - TEC- Residual', overlay='')
register_layout(source='SiStrip/MechanicalView/TEC/MINUS/wheel_4/HitResiduals_TEC__wheel__4', destination='00 Shift/SiStrip/HitResiduals_TEC__wheel__4', name='04f - TEC- Residual', overlay='')
register_layout(source='SiStrip/MechanicalView/TEC/MINUS/wheel_5/HitResiduals_TEC__wheel__5', destination='00 Shift/SiStrip/HitResiduals_TEC__wheel__5', name='04f - TEC- Residual', overlay='')
register_layout(source='SiStrip/MechanicalView/TEC/MINUS/wheel_6/HitResiduals_TEC__wheel__6', destination='00 Shift/SiStrip/HitResiduals_TEC__wheel__6', name='04f - TEC- Residual', overlay='')
register_layout(source='SiStrip/MechanicalView/TEC/MINUS/wheel_7/HitResiduals_TEC__wheel__7', destination='00 Shift/SiStrip/HitResiduals_TEC__wheel__7', name='04f - TEC- Residual', overlay='')
register_layout(source='SiStrip/MechanicalView/TEC/MINUS/wheel_8/HitResiduals_TEC__wheel__8', destination='00 Shift/SiStrip/HitResiduals_TEC__wheel__8', name='04f - TEC- Residual', overlay='')
register_layout(source='SiStrip/MechanicalView/TEC/MINUS/wheel_9/HitResiduals_TEC__wheel__9', destination='00 Shift/SiStrip/HitResiduals_TEC__wheel__9', name='04f - TEC- Residual', overlay='')
register_layout(source='SiStrip/MechanicalView/StripClusVsPixClus', destination='00 Shift/SiStrip/StripClusVsPixClus', name='05 Strip Clusters Vs Pixel Clusters', overlay='')
register_layout(source='SiStrip/MechanicalView/DeltaBx_vs_ApvCycle', destination='00 Shift/SiStrip/DeltaBx_vs_ApvCycle', name='06 DeltaBx_vs_ApvCycle', overlay='')
