from ..layouts.layout_manager import register_layout

register_layout(source='HLT/FourVector_Val/client/HLT_Mu9/custom-eff/HLT_Mu9_wrt__mcEt_Eff_OnToMc', destination='00 Shift/HLT/RelVal/FourVector/Muon/HLT_Mu9_wrt__mcEt_Eff_OnToMc', name='Eff HLT to MC', overlay='')
register_layout(source='HLT/FourVector_Val/client/HLT_Mu9/custom-eff/HLT_Mu9_wrt__mcEtamcPhi_Eff_OnToMc', destination='00 Shift/HLT/RelVal/FourVector/Muon/HLT_Mu9_wrt__mcEtamcPhi_Eff_OnToMc', name='Eff HLT to MC eta-phi', overlay='')
register_layout(source='HLT/FourVector_Val/client/HLT_Mu9/custom-eff/HLT_Mu9_wrt__l1Et_Eff_OnToL1', destination='00 Shift/HLT/RelVal/FourVector/Muon/HLT_Mu9_wrt__l1Et_Eff_OnToL1', name='Eff HLT to L1', overlay='')
register_layout(source='HLT/FourVector_Val/client/HLT_Mu9/custom-eff/HLT_Mu9_wrt__offEt_Eff_OnToOff', destination='00 Shift/HLT/RelVal/FourVector/Muon/HLT_Mu9_wrt__offEt_Eff_OnToOff', name='Eff HLT to RECO', overlay='')
register_layout(source='HLT/FourVector_Val/client/HLT_Mu9/custom-eff/HLT_Mu9_wrt__mcEt_Eff_L1ToMc', destination='00 Shift/HLT/RelVal/FourVector/Muon/HLT_Mu9_wrt__mcEt_Eff_L1ToMc', name='Eff L1 to MC', overlay='')
register_layout(source='HLT/FourVector_Val/client/HLT_Mu9/custom-eff/HLT_Mu9_wrt__offEt_Eff_L1ToOff', destination='00 Shift/HLT/RelVal/FourVector/Muon/HLT_Mu9_wrt__offEt_Eff_L1ToOff', name='Eff L1 to RECO', overlay='')
register_layout(source='HLT/FourVector_Val/client/HLT_Ele10_LW_L1R/custom-eff/HLT_Ele10_LW_L1R_wrt__mcEt_Eff_OnToMc', destination='00 Shift/HLT/RelVal/FourVector/Electron/HLT_Ele10_LW_L1R_wrt__mcEt_Eff_OnToMc', name='Eff HLT to MC', overlay='')
register_layout(source='HLT/FourVector_Val/client/HLT_Ele10_LW_L1R/custom-eff/HLT_Ele10_LW_L1R_wrt__mcEtamcPhi_Eff_OnToMc', destination='00 Shift/HLT/RelVal/FourVector/Electron/HLT_Ele10_LW_L1R_wrt__mcEtamcPhi_Eff_OnToMc', name='Eff HLT to MC eta-phi', overlay='')
register_layout(source='HLT/FourVector_Val/client/HLT_Ele10_LW_L1R/custom-eff/HLT_Ele10_LW_L1R_wrt__l1Et_Eff_OnToL1', destination='00 Shift/HLT/RelVal/FourVector/Electron/HLT_Ele10_LW_L1R_wrt__l1Et_Eff_OnToL1', name='Eff HLT to L1', overlay='')
register_layout(source='HLT/FourVector_Val/client/HLT_Ele10_LW_L1R/custom-eff/HLT_Ele10_LW_L1R_wrt__offEt_Eff_OnToOff', destination='00 Shift/HLT/RelVal/FourVector/Electron/HLT_Ele10_LW_L1R_wrt__offEt_Eff_OnToOff', name='Eff HLT to RECO', overlay='')
register_layout(source='HLT/FourVector_Val/client/HLT_Ele10_LW_L1R/custom-eff/HLT_Ele10_LW_L1R_wrt__mcEt_Eff_L1ToMc', destination='00 Shift/HLT/RelVal/FourVector/Electron/HLT_Ele10_LW_L1R_wrt__mcEt_Eff_L1ToMc', name='Eff L1 to MC', overlay='')
register_layout(source='HLT/FourVector_Val/client/HLT_Ele10_LW_L1R/custom-eff/HLT_Ele10_LW_L1R_wrt__offEt_Eff_L1ToOff', destination='00 Shift/HLT/RelVal/FourVector/Electron/HLT_Ele10_LW_L1R_wrt__offEt_Eff_L1ToOff', name='Eff L1 to RECO', overlay='')
register_layout(source='HLT/FourVector_Val/client/HLT_Jet30U/custom-eff/HLT_Jet30U_wrt__mcEt_Eff_OnToMc', destination='00 Shift/HLT/RelVal/FourVector/Jet/HLT_Jet30U_wrt__mcEt_Eff_OnToMc', name='Eff HLT to MC', overlay='')
register_layout(source='HLT/FourVector_Val/client/HLT_Jet30U/custom-eff/HLT_Jet30U_wrt__mcEtamcPhi_Eff_OnToMc', destination='00 Shift/HLT/RelVal/FourVector/Jet/HLT_Jet30U_wrt__mcEtamcPhi_Eff_OnToMc', name='Eff HLT to MC eta-phi', overlay='')
register_layout(source='HLT/FourVector_Val/client/HLT_Jet30U/custom-eff/HLT_Jet30U_wrt__l1Et_Eff_OnToL1', destination='00 Shift/HLT/RelVal/FourVector/Jet/HLT_Jet30U_wrt__l1Et_Eff_OnToL1', name='Eff HLT to L1', overlay='')
register_layout(source='HLT/FourVector_Val/client/HLT_Jet30U/custom-eff/HLT_Jet30U_wrt__offEt_Eff_OnToOff', destination='00 Shift/HLT/RelVal/FourVector/Jet/HLT_Jet30U_wrt__offEt_Eff_OnToOff', name='Eff HLT to RECO', overlay='')
register_layout(source='HLT/FourVector_Val/client/HLT_Jet30U/custom-eff/HLT_Jet30U_wrt__mcEt_Eff_L1ToMc', destination='00 Shift/HLT/RelVal/FourVector/Jet/HLT_Jet30U_wrt__mcEt_Eff_L1ToMc', name='Eff L1 to MC', overlay='')
register_layout(source='HLT/FourVector_Val/client/HLT_Jet30U/custom-eff/HLT_Jet30U_wrt__offEt_Eff_L1ToOff', destination='00 Shift/HLT/RelVal/FourVector/Jet/HLT_Jet30U_wrt__offEt_Eff_L1ToOff', name='Eff L1 to RECO', overlay='')
register_layout(source='HLT/FourVector_Val/client/HLT_Photon15_L1R/custom-eff/HLT_Photon15_L1R_wrt__mcEt_Eff_OnToMc', destination='00 Shift/HLT/RelVal/FourVector/Photon/HLT_Photon15_L1R_wrt__mcEt_Eff_OnToMc', name='Eff HLT to MC', overlay='')
register_layout(source='HLT/FourVector_Val/client/HLT_Photon15_L1R/custom-eff/HLT_Photon15_L1R_wrt__mcEtamcPhi_Eff_OnToMc', destination='00 Shift/HLT/RelVal/FourVector/Photon/HLT_Photon15_L1R_wrt__mcEtamcPhi_Eff_OnToMc', name='Eff HLT to MC eta-phi', overlay='')
register_layout(source='HLT/FourVector_Val/client/HLT_Photon15_L1R/custom-eff/HLT_Photon15_L1R_wrt__l1Et_Eff_OnToL1', destination='00 Shift/HLT/RelVal/FourVector/Photon/HLT_Photon15_L1R_wrt__l1Et_Eff_OnToL1', name='Eff HLT to L1', overlay='')
register_layout(source='HLT/FourVector_Val/client/HLT_Photon15_L1R/custom-eff/HLT_Photon15_L1R_wrt__offEt_Eff_OnToOff', destination='00 Shift/HLT/RelVal/FourVector/Photon/HLT_Photon15_L1R_wrt__offEt_Eff_OnToOff', name='Eff HLT to RECO', overlay='')
register_layout(source='HLT/FourVector_Val/client/HLT_Photon15_L1R/custom-eff/HLT_Photon15_L1R_wrt__mcEt_Eff_L1ToMc', destination='00 Shift/HLT/RelVal/FourVector/Photon/HLT_Photon15_L1R_wrt__mcEt_Eff_L1ToMc', name='Eff L1 to MC', overlay='')
register_layout(source='HLT/FourVector_Val/client/HLT_Photon15_L1R/custom-eff/HLT_Photon15_L1R_wrt__offEt_Eff_L1ToOff', destination='00 Shift/HLT/RelVal/FourVector/Photon/HLT_Photon15_L1R_wrt__offEt_Eff_L1ToOff', name='Eff L1 to RECO', overlay='')
register_layout(source='HLT/HLTEgammaValidation/HLT_DoubleEle5_SW_L1RDQMZee/efficiency_by_step_MC_matched', destination='00 Shift/HLT/Egamma/Zee Preselection/efficiency_by_step_MC_matched', name='doubleEle5SWL1R', overlay='')
register_layout(source='HLT/HLTEgammaValidation/HLT_Ele10_LW_L1RDQMZee/efficiency_by_step_MC_matched', destination='00 Shift/HLT/Egamma/Zee Preselection/efficiency_by_step_MC_matched', name='Ele10LWL1R', overlay='')
register_layout(source='HLT/HLTEgammaValidation/HLT_Ele10_LW_EleId_L1RDQMZee/efficiency_by_step_MC_matched', destination='00 Shift/HLT/Egamma/Zee Preselection/efficiency_by_step_MC_matched', name='Ele10LWEleIdL1R', overlay='')
register_layout(source='HLT/HLTEgammaValidation/HLT_Ele10_LW_L1RDQMWenu/efficiency_by_step_MC_matched', destination='00 Shift/HLT/Egamma/Wenu Preselection/efficiency_by_step_MC_matched', name='Ele10LWL1R', overlay='')
register_layout(source='HLT/HLTEgammaValidation/HLT_Ele10_LW_EleId_L1RDQMWenu/efficiency_by_step_MC_matched', destination='00 Shift/HLT/Egamma/Wenu Preselection/efficiency_by_step_MC_matched', name='Ele10LWEleIdL1R', overlay='')
register_layout(source='HLT/Muon/Distributions/HLT_IsoMu3/genEffEta_L1', destination='00 Shift/HLT/Muon/genEffEta_L1', name='Efficiency of L1', overlay='')
register_layout(source='HLT/Muon/Distributions/HLT_IsoMu3/genEffEta_L2', destination='00 Shift/HLT/Muon/genEffEta_L2', name='Efficiency of L2', overlay='')
register_layout(source='HLT/Muon/Distributions/HLT_IsoMu3/genEffEta_L2Iso', destination='00 Shift/HLT/Muon/genEffEta_L2Iso', name='Efficiency of L2 After Isolation Step', overlay='')
register_layout(source='HLT/Muon/Distributions/HLT_IsoMu3/genEffEta_L3', destination='00 Shift/HLT/Muon/genEffEta_L3', name='Efficiency of L3', overlay='')
register_layout(source='HLT/Muon/Distributions/HLT_IsoMu3/genEffEta_L3Iso', destination='00 Shift/HLT/Muon/genEffEta_L3Iso', name='Efficiency of L3 After Isolation Step', overlay='')
register_layout(source='HLT/TauRelVal/MC_8E29/DoubleTau/EfficiencyRefInput', destination='00 Shift/HLT/Tau/EfficiencyRefInput', name='Double Tau Path Performance', overlay='')
register_layout(source='HLT/TauRelVal/MC_8E29/DoubleTau/EfficiencyRefPrevious', destination='00 Shift/HLT/Tau/EfficiencyRefPrevious', name='Double Tau Path Performance', overlay='')
register_layout(source='HLT/TauRelVal/MC_8E29/SingleTau/EfficiencyRefInput', destination='00 Shift/HLT/Tau/EfficiencyRefInput', name='Single Tau Path Performance', overlay='')
register_layout(source='HLT/TauRelVal/MC_8E29/SingleTau/EfficiencyRefPrevious', destination='00 Shift/HLT/Tau/EfficiencyRefPrevious', name='Single Tau Path Performance', overlay='')
register_layout(source='HLT/TauRelVal/MC_8E29/L1/L1TauEtEff', destination='00 Shift/HLT/Tau/L1TauEtEff', name='L1 Performance', overlay='')
register_layout(source='HLT/TauRelVal/MC_8E29/L1/L1TauEtaEff', destination='00 Shift/HLT/Tau/L1TauEtaEff', name='L1 Performance', overlay='')
register_layout(source='HLT/TauRelVal/MC_8E29/L2/L2TauEtEff', destination='00 Shift/HLT/Tau/L2TauEtEff', name='L2 Performance', overlay='')
register_layout(source='HLT/TauRelVal/MC_8E29/L2/L2TauEtaEff', destination='00 Shift/HLT/Tau/L2TauEtaEff', name='L2 Performance', overlay='')
register_layout(source='HLT/TauRelVal/MC_8E29/L1/L1TauEtResol', destination='00 Shift/HLT/Tau/L1TauEtResol', name='L1 Resolution', overlay='')
register_layout(source='HLT/TauRelVal/MC_8E29/L2/L2TauEtResol', destination='00 Shift/HLT/Tau/L2TauEtResol', name='L2 Resolution', overlay='')
register_layout(source='HLT/HLTJETMET/SingleMET35/Reco Missing ET Turn-On Data', destination='00 Shift/HLT/JetMET/Reco Missing ET Turn-On Data', name='HLTMET35 eff vs recMet Data', overlay='')
register_layout(source='HLT/HLTJETMET/SingleMET45/Reco Missing ET Turn-On Data', destination='00 Shift/HLT/JetMET/Reco Missing ET Turn-On Data', name='HLTMET45 eff vs recMet Data', overlay='')
register_layout(source='HLT/HLTJETMET/SingleMET60/Reco Missing ET Turn-On Data', destination='00 Shift/HLT/JetMET/Reco Missing ET Turn-On Data', name='HLTMET60 eff vs recMet Data', overlay='')
register_layout(source='HLT/HLTJETMET/SingleMET100/Reco Missing ET Turn-On Data', destination='00 Shift/HLT/JetMET/Reco Missing ET Turn-On Data', name='HLTMET100 eff vs recMet Data', overlay='')
register_layout(source='HLT/HLTJETMET/SingleJet15U/Reco Jet Pt Turn-On Data', destination='00 Shift/HLT/JetMET/Reco Jet Pt Turn-On Data', name='HLTJet15U eff vs recJet Pt Data', overlay='')
register_layout(source='HLT/HLTJETMET/SingleJet30U/Reco Jet Pt Turn-On Data', destination='00 Shift/HLT/JetMET/Reco Jet Pt Turn-On Data', name='HLTJet30U eff vs recJet Pt Data', overlay='')
register_layout(source='HLT/HLTJETMET/SingleJet50U/Reco Jet Pt Turn-On Data', destination='00 Shift/HLT/JetMET/Reco Jet Pt Turn-On Data', name='HLTJet50U eff vs recJet Pt Data', overlay='')
register_layout(source='HLT/HLTJETMET/SingleJet70U/Reco Jet Pt Turn-On Data', destination='00 Shift/HLT/JetMET/Reco Jet Pt Turn-On Data', name='HLTJet70U eff vs recJet Pt Data', overlay='')
register_layout(source='HLT/HLTJETMET/SingleJet100U/Reco Jet Pt Turn-On Data', destination='00 Shift/HLT/JetMET/Reco Jet Pt Turn-On Data', name='HLTJet100U eff vs recJet Pt Data', overlay='')
register_layout(source='HLT/HLTJETMET/SingleJet15U/Reco Jet Eta Turn-On Data', destination='00 Shift/HLT/JetMET/Reco Jet Eta Turn-On Data', name='HLTJet15U eff vs recJet Eta Data', overlay='')
register_layout(source='HLT/HLTJETMET/SingleJet30U/Reco Jet Eta Turn-On Data', destination='00 Shift/HLT/JetMET/Reco Jet Eta Turn-On Data', name='HLTJet30U eff vs recJet Eta Data', overlay='')
register_layout(source='HLT/HLTJETMET/SingleJet50U/Reco Jet Eta Turn-On Data', destination='00 Shift/HLT/JetMET/Reco Jet Eta Turn-On Data', name='HLTJet50U eff vs recJet Eta Data', overlay='')
register_layout(source='HLT/HLTJETMET/SingleJet70U/Reco Jet Eta Turn-On Data', destination='00 Shift/HLT/JetMET/Reco Jet Eta Turn-On Data', name='HLTJet70U eff vs recJet Eta Data', overlay='')
register_layout(source='HLT/HLTJETMET/SingleJet100U/Reco Jet Eta Turn-On Data', destination='00 Shift/HLT/JetMET/Reco Jet Eta Turn-On Data', name='HLTJet100U eff vs recJet Eta Data', overlay='')
register_layout(source='HLT/HLTJETMET/SingleJet15U/Reco Jet Phi Turn-On Data', destination='00 Shift/HLT/JetMET/Reco Jet Phi Turn-On Data', name='HLTJet15U eff vs recJet Phi Data', overlay='')
register_layout(source='HLT/HLTJETMET/SingleJet30U/Reco Jet Phi Turn-On Data', destination='00 Shift/HLT/JetMET/Reco Jet Phi Turn-On Data', name='HLTJet30U eff vs recJet Phi Data', overlay='')
register_layout(source='HLT/HLTJETMET/SingleJet50U/Reco Jet Phi Turn-On Data', destination='00 Shift/HLT/JetMET/Reco Jet Phi Turn-On Data', name='HLTJet50U eff vs recJet Phi Data', overlay='')
register_layout(source='HLT/HLTJETMET/SingleJet70U/Reco Jet Phi Turn-On Data', destination='00 Shift/HLT/JetMET/Reco Jet Phi Turn-On Data', name='HLTJet70U eff vs recJet Phi Data', overlay='')
register_layout(source='HLT/HLTJETMET/SingleJet100U/Reco Jet Phi Turn-On Data', destination='00 Shift/HLT/JetMET/Reco Jet Phi Turn-On Data', name='HLTJet100U eff vs recJet Phi Data', overlay='')
register_layout(source='HLT/HLTJETMET/HT300MHT100/Reco HT Turn-On Data', destination='00 Shift/HLT/JetMET/Reco HT Turn-On Data', name='HLTHT300MHT100 eff vs recHT Data', overlay='')
register_layout(source='HLT/AlCaEcalPi0/Pi0InvmassEB', destination='00 Shift/HLT/AlCa/Pi0InvmassEB', name='Pi0 inv mass', overlay='')
register_layout(source='HLT/EcalPhiSym/eventEnergyEB', destination='00 Shift/HLT/AlCa/eventEnergyEB', name='event energy eb', overlay='')
register_layout(source='HLT/HeavyFlavor/QuarkoniumEfficiencies/genQuakonium_genPt', destination='00 Shift/HLT/HeavyFlavor/genQuakonium_genPt', name='Quakonium efficiency', overlay='')
register_layout(source='HLT/Top/Semileptonic_muon/EffVsEta_HLT_Mu9', destination='00 Shift/HLT/Top/EffVsEta_HLT_Mu9', name='HLT_Mu9 eff vs Eta', overlay='')
register_layout(source='HLT/Top/Semileptonic_muon/EffVsPt_HLT_Mu9', destination='00 Shift/HLT/Top/EffVsPt_HLT_Mu9', name='HLT_Mu9 eff vs Pt', overlay='')
register_layout(source='HLT/Top/Semileptonic_electron/EffVsEta_HLT_Ele15_SW_LooseTrackIso_L1R', destination='00 Shift/HLT/Top/EffVsEta_HLT_Ele15_SW_LooseTrackIso_L1R', name='HLT_Ele15SWLooseTrkIso eff vs Eta', overlay='')
register_layout(source='HLT/Top/Semileptonic_electron/EffVsPt_HLT_Ele15_SW_LooseTrackIso_L1R', destination='00 Shift/HLT/Top/EffVsPt_HLT_Ele15_SW_LooseTrackIso_L1R', name='HLT_Ele15SWLooseTrkIso eff vs Pt', overlay='')
register_layout(source='HLT/SusyExo/TriggerBits/L1_EG', destination='00 Shift/HLT/SusyExo/00 NoSelection/00 L1/L1_EGL1_EG', name='00 L1_EG', overlay='')
register_layout(source='HLT/SusyExo/TriggerBits/L1_Mu', destination='00 Shift/HLT/SusyExo/00 NoSelection/00 L1/L1_MuL1_Mu', name='01 L1_Mu', overlay='')
register_layout(source='HLT/SusyExo/TriggerBits/L1_Jet', destination='00 Shift/HLT/SusyExo/00 NoSelection/00 L1/L1_JetL1_Jet', name='02 L1_Jet', overlay='')
register_layout(source='HLT/SusyExo/TriggerBits/L1_ETM_ETT_HTT', destination='00 Shift/HLT/SusyExo/00 NoSelection/00 L1/L1_ETM_ETT_HTTL1_ETM_ETT_HTT', name='03 L1_ETM_ETT_HTT', overlay='')
register_layout(source='HLT/SusyExo/TriggerBits/L1_TauJet', destination='00 Shift/HLT/SusyExo/00 NoSelection/00 L1/L1_TauJetL1_TauJet', name='04 L1_TauJet', overlay='')
register_layout(source='HLT/SusyExo/TriggerBits/L1_XTrigger', destination='00 Shift/HLT/SusyExo/00 NoSelection/00 L1/L1_XTriggerL1_XTrigger', name='05 L1_XTrigger', overlay='')
register_layout(source='HLT/SusyExo/TriggerBits/L1_Overflow', destination='00 Shift/HLT/SusyExo/00 NoSelection/00 L1/L1_OverflowL1_Overflow', name='06 L1_Others', overlay='')
register_layout(source='HLT/SusyExo/TriggerBits/Hlt_Ele', destination='00 Shift/HLT/SusyExo/00 NoSelection/01 HLT/Hlt_EleHlt_Ele', name='00 Hlt_Ele', overlay='')
register_layout(source='HLT/SusyExo/TriggerBits/Hlt_Photon', destination='00 Shift/HLT/SusyExo/00 NoSelection/01 HLT/Hlt_PhotonHlt_Photon', name='01 Hlt_Photon', overlay='')
register_layout(source='HLT/SusyExo/TriggerBits/Hlt_Mu', destination='00 Shift/HLT/SusyExo/00 NoSelection/01 HLT/Hlt_MuHlt_Mu', name='02 Hlt_Mu', overlay='')
register_layout(source='HLT/SusyExo/TriggerBits/Hlt_Jet', destination='00 Shift/HLT/SusyExo/00 NoSelection/01 HLT/Hlt_JetHlt_Jet', name='03 Hlt_Jet', overlay='')
register_layout(source='HLT/SusyExo/TriggerBits/Hlt_MET_HT', destination='00 Shift/HLT/SusyExo/00 NoSelection/01 HLT/Hlt_MET_HTHlt_MET_HT', name='04 Hlt_MET_HT', overlay='')
register_layout(source='HLT/SusyExo/TriggerBits/Hlt_Tau_BTag', destination='00 Shift/HLT/SusyExo/00 NoSelection/01 HLT/Hlt_Tau_BTagHlt_Tau_BTag', name='05 Hlt_Tau_BTag', overlay='')
register_layout(source='HLT/SusyExo/TriggerBits/Hlt_XTrigger', destination='00 Shift/HLT/SusyExo/00 NoSelection/01 HLT/Hlt_XTriggerHlt_XTrigger', name='06 Hlt_XTrigger', overlay='')
register_layout(source='HLT/SusyExo/TriggerBits/Hlt_Overflow', destination='00 Shift/HLT/SusyExo/00 NoSelection/01 HLT/Hlt_OverflowHlt_Overflow', name='07 Hlt_Others', overlay='')
register_layout(source='HLT/Higgs/HWW/EffVsEta_HLT_Mu9_EM', destination='00 Shift/HLT/Higgs/EffVsEta_HLT_Mu9_EM', name='HLTMu9 eff vs eta ', overlay='')
register_layout(source='HLT/Higgs/HWW/EffVsPt_HLT_Mu9_EM', destination='00 Shift/HLT/Higgs/EffVsPt_HLT_Mu9_EM', name='HLTMu9 eff vs pt ', overlay='')
register_layout(source='HLT/Higgs/HWW/EffVsPt_HLT_Ele10_LW_L1R_EM', destination='00 Shift/HLT/Higgs/EffVsPt_HLT_Ele10_LW_L1R_EM', name='HLTEle10LWL1R eff vs pt ', overlay='')
register_layout(source='HLT/Higgs/HWW/EffVsEta_HLT_Ele10_LW_L1R_EM', destination='00 Shift/HLT/Higgs/EffVsEta_HLT_Ele10_LW_L1R_EM', name='HLTEle10LWL1R eff vs eta', overlay='')
register_layout(source='HLT/Higgs/Hgg/EffVsEta_HLT_DoublePhoton10_L1R', destination='00 Shift/HLT/Higgs/EffVsEta_HLT_DoublePhoton10_L1R', name='HLTDoublePhoton10L1R eff vs eta', overlay='')
register_layout(source='HLT/Higgs/Hgg/EffVsPt_HLT_DoublePhoton10_L1R', destination='00 Shift/HLT/Higgs/EffVsPt_HLT_DoublePhoton10_L1R', name='HLTDoublePhoton10L1R eff vs pt', overlay='')
