from ..layouts.layout_manager import register_layout

register_layout(source='L1T/L1TStage2CaloLayer1/ecalOccRecdEtWgt', destination='00 Shift/L1T/ecalOccRecdEtWgt', name='00 - CaloLayer1 ECAL occupancy', overlay='')
register_layout(source='L1T/L1TStage2CaloLayer1/hcalOccRecdEtWgt', destination='00 Shift/L1T/hcalOccRecdEtWgt', name='01 - CaloLayer1 HCAL occupancy', overlay='')
register_layout(source='L1T/L1TStage2CaloLayer2/shifter/CenJetsEtEtaPhi_shift', destination='00 Shift/L1T/CenJetsEtEtaPhi_shift', name='02 - CaloLayer2 central jet E_T eta phi', overlay='')
register_layout(source='L1T/L1TStage2CaloLayer2/shifter/ForJetsEtEtaPhi_shift', destination='00 Shift/L1T/ForJetsEtEtaPhi_shift', name='03 - CaloLayer2 forward jet E_T eta phi', overlay='')
register_layout(source='L1T/L1TStage2CaloLayer2/shifter/IsoEGsEtEtaPhi_shift', destination='00 Shift/L1T/IsoEGsEtEtaPhi_shift', name='04 - CaloLayer2 iso EG E_T eta phi', overlay='')
register_layout(source='L1T/L1TStage2CaloLayer2/shifter/NonIsoEGsEtEtaPhi_shift', destination='00 Shift/L1T/NonIsoEGsEtEtaPhi_shift', name='05 - CaloLayer2 noniso EG E_T eta phi', overlay='')
register_layout(source='L1T/L1TStage2CaloLayer2/shifter/IsoTausEtEtaPhi_shift', destination='00 Shift/L1T/IsoTausEtEtaPhi_shift', name='06 - CaloLayer2 iso tau E_T eta phi', overlay='')
register_layout(source='L1T/L1TStage2CaloLayer2/shifter/TausEtEtaPhi_shift', destination='00 Shift/L1T/TausEtEtaPhi_shift', name='07 - CaloLayer2 noniso tau E_T eta phi', overlay='')
register_layout(source='L1T/L1TStage2uGMT/ugmtMuonPt', destination='00 Shift/L1T/ugmtMuonPt', name='08 - uGMT muon p_T', overlay='')
register_layout(source='L1T/L1TStage2uGMT/ugmtMuonEta', destination='00 Shift/L1T/ugmtMuonEta', name='09 - uGMT muon eta', overlay='')
register_layout(source='L1T/L1TStage2uGMT/ugmtMuonPhi', destination='00 Shift/L1T/ugmtMuonPhi', name='10 - uGMT muon phi', overlay='')
register_layout(source='L1T/L1TStage2uGMT/ugmtMuonPhivsEta', destination='00 Shift/L1T/ugmtMuonPhivsEta', name='11 - uGMT muon eta phi', overlay='')
register_layout(source='L1T/L1TStage2uGMT/ugmtMuonPhiAtVtxvsEtaAtVtx', destination='00 Shift/L1T/ugmtMuonPhiAtVtxvsEtaAtVtx', name='12 - uGMT muon eta phi at vertex', overlay='')
register_layout(source='L1T/L1TStage2uGMT/ugmtBXvsLink', destination='00 Shift/L1T/ugmtBXvsLink', name='13 - uGMT input link vs. input muon BX', overlay='')
register_layout(source='L1T/L1TStage2uGMT/ugmtMuonChargevsLink', destination='00 Shift/L1T/ugmtMuonChargevsLink', name='14 - uGMT input link vs. muon charge', overlay='')
register_layout(source='L1T/L1TStage2EMTF/cscLCTOccupancy', destination='00 Shift/L1T/cscLCTOccupancy', name='15 - EMTF Chamber Occupancy', overlay='')
register_layout(source='L1T/L1TStage2EMTF/emtfTrackBX', destination='00 Shift/L1T/emtfTrackBX', name='16 - EMTF Track Bunch Crossing', overlay='')
register_layout(source='L1T/L1TStage2uGT/algoBits_after_prescale_bx_global', destination='00 Shift/L1T/algoBits_after_prescale_bx_global', name='17 - uGT Algorithm Trigger Bits (after prescale) vs. Global BX Number', overlay='')
register_layout(source='L1T/L1TStage2uGT/algoBits_after_prescale_bx_inEvt', destination='00 Shift/L1T/algoBits_after_prescale_bx_inEvt', name='18 - uGT Algorithm Trigger Bits (after prescale) vs. BX Number in Event', overlay='')
register_layout(source='L1T/L1TStage2uGT/Ratio_Unprescaled_First_Bunch_In_Train', destination='00 Shift/L1T/Ratio_Unprescaled_First_Bunch_In_Train', name='19 - uGT # of unprescaled algo accepts relative to # of all algo accepts in +-2 BX vs. BX number in event for first bunch in train', overlay='')
register_layout(source='L1T/L1TStage2uGT/Ratio_Unprescaled_Last_Bunch_In_Train', destination='00 Shift/L1T/Ratio_Unprescaled_Last_Bunch_In_Train', name='20 - uGT # of unprescaled algo accepts relative to # of all algo accepts in +-2 BX vs. BX number in event for last bunch in train', overlay='')
register_layout(source='L1T/L1TStage2uGT/Ratio_Prescaled_First_Bunch_In_Train', destination='00 Shift/L1T/Ratio_Prescaled_First_Bunch_In_Train', name='21 - uGT # of prescaled algo accepts relative to # of all algo accepts in +-2 BX vs. BX number in event for first bunch in train', overlay='')
register_layout(source='L1T/L1TStage2uGT/Ratio_Prescaled_Last_Bunch_In_Train', destination='00 Shift/L1T/Ratio_Prescaled_Last_Bunch_In_Train', name='22 - uGT # of prescaled algo accepts relative to # of all algo accepts in +-2 BX vs. BX number in event for last bunch in train', overlay='')
