from ..layouts.layout_manager import register_layout

register_layout(source='EcalPreshower/ESIntegrityClient/ES Integrity Summary 1 Z 1 P 1', destination='00 Shift/EcalPreshower/ES Integrity Summary 1 Z 1 P 1', name='01-IntegritySummary', overlay='')
register_layout(source='EcalPreshower/ESIntegrityClient/ES Integrity Summary 1 Z -1 P 1', destination='00 Shift/EcalPreshower/ES Integrity Summary 1 Z -1 P 1', name='01-IntegritySummary', overlay='')
register_layout(source='EcalPreshower/ESIntegrityClient/ES Integrity Summary 1 Z 1 P 2', destination='00 Shift/EcalPreshower/ES Integrity Summary 1 Z 1 P 2', name='01-IntegritySummary', overlay='')
register_layout(source='EcalPreshower/ESIntegrityClient/ES Integrity Summary 1 Z -1 P 2', destination='00 Shift/EcalPreshower/ES Integrity Summary 1 Z -1 P 2', name='01-IntegritySummary', overlay='')
register_layout(source='EcalPreshower/ESOccupancyTask/ES Occupancy with selected hits Z 1 P 1', destination='00 Shift/EcalPreshower/ES Occupancy with selected hits Z 1 P 1', name='02-GoodRechitOccupancySummary', overlay='')
register_layout(source='EcalPreshower/ESOccupancyTask/ES Occupancy with selected hits Z -1 P 1', destination='00 Shift/EcalPreshower/ES Occupancy with selected hits Z -1 P 1', name='02-GoodRechitOccupancySummary', overlay='')
register_layout(source='EcalPreshower/ESOccupancyTask/ES Occupancy with selected hits Z 1 P 2', destination='00 Shift/EcalPreshower/ES Occupancy with selected hits Z 1 P 2', name='02-GoodRechitOccupancySummary', overlay='')
register_layout(source='EcalPreshower/ESOccupancyTask/ES Occupancy with selected hits Z -1 P 2', destination='00 Shift/EcalPreshower/ES Occupancy with selected hits Z -1 P 2', name='02-GoodRechitOccupancySummary', overlay='')
register_layout(source='EcalPreshower/ESOccupancyTask/ES RecHit Energy with selected hits Z 1 P 1', destination='00 Shift/EcalPreshower/ES RecHit Energy with selected hits Z 1 P 1', name='03-GoodRechitEnergySummary', overlay='')
register_layout(source='EcalPreshower/ESOccupancyTask/ES RecHit Energy with selected hits Z -1 P 1', destination='00 Shift/EcalPreshower/ES RecHit Energy with selected hits Z -1 P 1', name='03-GoodRechitEnergySummary', overlay='')
register_layout(source='EcalPreshower/ESOccupancyTask/ES RecHit Energy with selected hits Z 1 P 2', destination='00 Shift/EcalPreshower/ES RecHit Energy with selected hits Z 1 P 2', name='03-GoodRechitEnergySummary', overlay='')
register_layout(source='EcalPreshower/ESOccupancyTask/ES RecHit Energy with selected hits Z -1 P 2', destination='00 Shift/EcalPreshower/ES RecHit Energy with selected hits Z -1 P 2', name='03-GoodRechitEnergySummary', overlay='')
register_layout(source='EcalPreshower/ESTimingTask/ES Timing Z 1 P 1', destination='00 Shift/EcalPreshower/ES Timing Z 1 P 1', name='04-ESTimingTaskSummary-EcalPreshower', overlay='')
register_layout(source='EcalPreshower/ESTimingTask/ES Timing Z -1 P 1', destination='00 Shift/EcalPreshower/ES Timing Z -1 P 1', name='04-ESTimingTaskSummary-EcalPreshower', overlay='')
register_layout(source='EcalPreshower/ESTimingTask/ES Timing Z 1 P 2', destination='00 Shift/EcalPreshower/ES Timing Z 1 P 2', name='04-ESTimingTaskSummary-EcalPreshower', overlay='')
register_layout(source='EcalPreshower/ESTimingTask/ES Timing Z -1 P 2', destination='00 Shift/EcalPreshower/ES Timing Z -1 P 2', name='04-ESTimingTaskSummary-EcalPreshower', overlay='')
register_layout(source='EcalPreshower/ESIntegrityTask/ES Gain used for data taking', destination='00 Shift/EcalPreshower/ES Gain used for data taking', name='05-ESGain-EcalPreshower', overlay='')
register_layout(source='EcalPreshower/ESIntegrityTask/ES Fiber Error Code', destination='00 Shift/EcalPreshower/ES Fiber Error Code', name='06-ES-Fiber-Error-Code', overlay='')
