from ..layouts.layout_manager import register_layout

register_layout(source='SiStrip/MechanicalView/TEC/MINUS/Summary_ClusterStoNCorr_OnTrack__TEC__MINUS', destination='DataLayouts/Tk/Summary_ClusterStoNCorr_OnTrack__TEC__MINUS', name='01 - TEC-', overlay='')
register_layout(source='SiStrip/MechanicalView/TEC/MINUS/Summary_TotalNumberOfClusters_OnTrack__TEC__MINUS', destination='DataLayouts/Tk/Summary_TotalNumberOfClusters_OnTrack__TEC__MINUS', name='01 - TEC-', overlay='')
register_layout(source='SiStrip/MechanicalView/TEC/MINUS/Summary_ClusterCharge_OffTrack__TEC__MINUS', destination='DataLayouts/Tk/Summary_ClusterCharge_OffTrack__TEC__MINUS', name='01 - TEC-', overlay='')
register_layout(source='SiStrip/MechanicalView/TEC/MINUS/Summary_TotalNumberOfClusters_OffTrack__TEC__MINUS', destination='DataLayouts/Tk/Summary_TotalNumberOfClusters_OffTrack__TEC__MINUS', name='01 - TEC-', overlay='')
register_layout(source='SiStrip/MechanicalView/TEC/PLUS/Summary_ClusterStoNCorr_OnTrack__TEC__PLUS', destination='DataLayouts/Tk/Summary_ClusterStoNCorr_OnTrack__TEC__PLUS', name='02 - TEC+', overlay='')
register_layout(source='SiStrip/MechanicalView/TEC/PLUS/Summary_TotalNumberOfClusters_OnTrack__TEC__PLUS', destination='DataLayouts/Tk/Summary_TotalNumberOfClusters_OnTrack__TEC__PLUS', name='02 - TEC+', overlay='')
register_layout(source='SiStrip/MechanicalView/TEC/PLUS/Summary_ClusterCharge_OffTrack__TEC__PLUS', destination='DataLayouts/Tk/Summary_ClusterCharge_OffTrack__TEC__PLUS', name='02 - TEC+', overlay='')
register_layout(source='SiStrip/MechanicalView/TEC/PLUS/Summary_TotalNumberOfClusters_OffTrack__TEC__PLUS', destination='DataLayouts/Tk/Summary_TotalNumberOfClusters_OffTrack__TEC__PLUS', name='02 - TEC+', overlay='')
register_layout(source='SiStrip/MechanicalView/TIB/Summary_ClusterStoNCorr_OnTrack__TIB', destination='DataLayouts/Tk/Summary_ClusterStoNCorr_OnTrack__TIB', name='03 - TIB', overlay='')
register_layout(source='SiStrip/MechanicalView/TIB/Summary_TotalNumberOfClusters_OnTrack__TIB', destination='DataLayouts/Tk/Summary_TotalNumberOfClusters_OnTrack__TIB', name='03 - TIB', overlay='')
register_layout(source='SiStrip/MechanicalView/TIB/Summary_ClusterCharge_OffTrack__TIB', destination='DataLayouts/Tk/Summary_ClusterCharge_OffTrack__TIB', name='03 - TIB', overlay='')
register_layout(source='SiStrip/MechanicalView/TIB/Summary_TotalNumberOfClusters_OffTrack__TIB', destination='DataLayouts/Tk/Summary_TotalNumberOfClusters_OffTrack__TIB', name='03 - TIB', overlay='')
register_layout(source='SiStrip/MechanicalView/TID/MINUS/Summary_ClusterStoNCorr_OnTrack__TID__MINUS', destination='DataLayouts/Tk/Summary_ClusterStoNCorr_OnTrack__TID__MINUS', name='04 - TID-', overlay='')
register_layout(source='SiStrip/MechanicalView/TID/MINUS/Summary_TotalNumberOfClusters_OnTrack__TID__MINUS', destination='DataLayouts/Tk/Summary_TotalNumberOfClusters_OnTrack__TID__MINUS', name='04 - TID-', overlay='')
register_layout(source='SiStrip/MechanicalView/TID/MINUS/Summary_ClusterCharge_OffTrack__TID__MINUS', destination='DataLayouts/Tk/Summary_ClusterCharge_OffTrack__TID__MINUS', name='04 - TID-', overlay='')
register_layout(source='SiStrip/MechanicalView/TID/MINUS/Summary_TotalNumberOfClusters_OffTrack__TID__MINUS', destination='DataLayouts/Tk/Summary_TotalNumberOfClusters_OffTrack__TID__MINUS', name='04 - TID-', overlay='')
register_layout(source='SiStrip/MechanicalView/TID/PLUS/Summary_ClusterStoNCorr_OnTrack__TID__PLUS', destination='DataLayouts/Tk/Summary_ClusterStoNCorr_OnTrack__TID__PLUS', name='05 - TID+', overlay='')
register_layout(source='SiStrip/MechanicalView/TID/PLUS/Summary_TotalNumberOfClusters_OnTrack__TID__PLUS', destination='DataLayouts/Tk/Summary_TotalNumberOfClusters_OnTrack__TID__PLUS', name='05 - TID+', overlay='')
register_layout(source='SiStrip/MechanicalView/TID/PLUS/Summary_ClusterCharge_OffTrack__TID__PLUS', destination='DataLayouts/Tk/Summary_ClusterCharge_OffTrack__TID__PLUS', name='05 - TID+', overlay='')
register_layout(source='SiStrip/MechanicalView/TID/PLUS/Summary_TotalNumberOfClusters_OffTrack__TID__PLUS', destination='DataLayouts/Tk/Summary_TotalNumberOfClusters_OffTrack__TID__PLUS', name='05 - TID+', overlay='')
register_layout(source='SiStrip/MechanicalView/TOB/Summary_ClusterStoNCorr_OnTrack__TOB', destination='DataLayouts/Tk/Summary_ClusterStoNCorr_OnTrack__TOB', name='06 - TOB', overlay='')
register_layout(source='SiStrip/MechanicalView/TOB/Summary_TotalNumberOfClusters_OnTrack__TOB', destination='DataLayouts/Tk/Summary_TotalNumberOfClusters_OnTrack__TOB', name='06 - TOB', overlay='')
register_layout(source='SiStrip/MechanicalView/TOB/Summary_ClusterCharge_OffTrack__TOB', destination='DataLayouts/Tk/Summary_ClusterCharge_OffTrack__TOB', name='06 - TOB', overlay='')
register_layout(source='SiStrip/MechanicalView/TOB/Summary_TotalNumberOfClusters_OffTrack__TOB', destination='DataLayouts/Tk/Summary_TotalNumberOfClusters_OffTrack__TOB', name='06 - TOB', overlay='')
register_layout(source='PixelPhase1/Phase1_MechanicalView/num_digis_PXBarrel', destination='DataLayouts/Tk/num_digis_PXBarrel', name='07 - Pixel Digis ADC Barrel', overlay='')
register_layout(source='PixelPhase1/Phase1_MechanicalView/adc_PXBarrel', destination='DataLayouts/Tk/adc_PXBarrel', name='07 - Pixel Digis ADC Barrel', overlay='')
register_layout(source='PixelPhase1/Phase1_MechanicalView/num_digis_per_LumiBlock_PXBarrel', destination='DataLayouts/Tk/num_digis_per_LumiBlock_PXBarrel', name='07 - Pixel Digis ADC Barrel', overlay='')
register_layout(source='PixelPhase1/Phase1_MechanicalView/adc_per_LumiBlock_PXBarrel', destination='DataLayouts/Tk/adc_per_LumiBlock_PXBarrel', name='07 - Pixel Digis ADC Barrel', overlay='')
register_layout(source='PixelPhase1/Phase1_MechanicalView/num_digis_PXForward', destination='DataLayouts/Tk/num_digis_PXForward', name='08 - Pixel Digis ADC Endcap', overlay='')
register_layout(source='PixelPhase1/Phase1_MechanicalView/adc_PXForward', destination='DataLayouts/Tk/adc_PXForward', name='08 - Pixel Digis ADC Endcap', overlay='')
register_layout(source='PixelPhase1/Phase1_MechanicalView/num_digis_per_LumiBlock_PXForward', destination='DataLayouts/Tk/num_digis_per_LumiBlock_PXForward', name='08 - Pixel Digis ADC Endcap', overlay='')
register_layout(source='PixelPhase1/Phase1_MechanicalView/adc_per_LumiBlock_PXForward', destination='DataLayouts/Tk/adc_per_LumiBlock_PXForward', name='08 - Pixel Digis ADC Endcap', overlay='')
register_layout(source='PixelPhase1/Phase1_MechanicalView/PXBarrel/digi_occupancy_per_SignedModuleCoord_per_SignedLadderCoord_PXLayer_1', destination='DataLayouts/Tk/digi_occupancy_per_SignedModuleCoord_per_SignedLadderCoord_PXLayer_1', name='09 - Pixel Occupancy', overlay='')
register_layout(source='PixelPhase1/Phase1_MechanicalView/PXBarrel/digi_occupancy_per_SignedModuleCoord_per_SignedLadderCoord_PXLayer_2', destination='DataLayouts/Tk/digi_occupancy_per_SignedModuleCoord_per_SignedLadderCoord_PXLayer_2', name='09 - Pixel Occupancy', overlay='')
register_layout(source='PixelPhase1/Phase1_MechanicalView/PXBarrel/digi_occupancy_per_SignedModuleCoord_per_SignedLadderCoord_PXLayer_3', destination='DataLayouts/Tk/digi_occupancy_per_SignedModuleCoord_per_SignedLadderCoord_PXLayer_3', name='09 - Pixel Occupancy', overlay='')
register_layout(source='PixelPhase1/Phase1_MechanicalView/PXBarrel/digi_occupancy_per_SignedModuleCoord_per_SignedLadderCoord_PXLayer_4', destination='DataLayouts/Tk/digi_occupancy_per_SignedModuleCoord_per_SignedLadderCoord_PXLayer_4', name='09 - Pixel Occupancy', overlay='')
register_layout(source='PixelPhase1/Phase1_MechanicalView/PXForward/digi_occupancy_per_SignedDiskCoord_per_SignedBladePanelCoord_PXRing_1', destination='DataLayouts/Tk/digi_occupancy_per_SignedDiskCoord_per_SignedBladePanelCoord_PXRing_1', name='09 - Pixel Occupancy', overlay='')
register_layout(source='PixelPhase1/Phase1_MechanicalView/PXForward/digi_occupancy_per_SignedDiskCoord_per_SignedBladePanelCoord_PXRing_2', destination='DataLayouts/Tk/digi_occupancy_per_SignedDiskCoord_per_SignedBladePanelCoord_PXRing_2', name='09 - Pixel Occupancy', overlay='')
register_layout(source='PixelPhase1/Tracks/PXBarrel/charge_PXLayer_1', destination='DataLayouts/Tk/charge_PXLayer_1', name='10 - PXBarrel OnTk Clusters Charge', overlay='')
register_layout(source='PixelPhase1/Tracks/PXBarrel/charge_PXLayer_2', destination='DataLayouts/Tk/charge_PXLayer_2', name='10 - PXBarrel OnTk Clusters Charge', overlay='')
register_layout(source='PixelPhase1/Tracks/PXBarrel/charge_PXLayer_3', destination='DataLayouts/Tk/charge_PXLayer_3', name='10 - PXBarrel OnTk Clusters Charge', overlay='')
register_layout(source='PixelPhase1/Tracks/PXBarrel/charge_PXLayer_4', destination='DataLayouts/Tk/charge_PXLayer_4', name='10 - PXBarrel OnTk Clusters Charge', overlay='')
register_layout(source='PixelPhase1/Tracks/PXForward/charge_PXDisk_-3', destination='DataLayouts/Tk/charge_PXDisk_-3', name='11 - PXEndcap OnTk Clusters Charge', overlay='')
register_layout(source='PixelPhase1/Tracks/PXForward/charge_PXDisk_-2', destination='DataLayouts/Tk/charge_PXDisk_-2', name='11 - PXEndcap OnTk Clusters Charge', overlay='')
register_layout(source='PixelPhase1/Tracks/PXForward/charge_PXDisk_-1', destination='DataLayouts/Tk/charge_PXDisk_-1', name='11 - PXEndcap OnTk Clusters Charge', overlay='')
register_layout(source='PixelPhase1/Tracks/PXForward/charge_PXDisk_+1', destination='DataLayouts/Tk/charge_PXDisk_+1', name='11 - PXEndcap OnTk Clusters Charge', overlay='')
register_layout(source='PixelPhase1/Tracks/PXForward/charge_PXDisk_+2', destination='DataLayouts/Tk/charge_PXDisk_+2', name='11 - PXEndcap OnTk Clusters Charge', overlay='')
register_layout(source='PixelPhase1/Tracks/PXForward/charge_PXDisk_+3', destination='DataLayouts/Tk/charge_PXDisk_+3', name='11 - PXEndcap OnTk Clusters Charge', overlay='')
register_layout(source='PixelPhase1/Tracks/PXBarrel/size_PXLayer_1', destination='DataLayouts/Tk/size_PXLayer_1', name='12 - PXBarrel OnTk Clusters Size', overlay='')
register_layout(source='PixelPhase1/Tracks/PXBarrel/size_PXLayer_2', destination='DataLayouts/Tk/size_PXLayer_2', name='12 - PXBarrel OnTk Clusters Size', overlay='')
register_layout(source='PixelPhase1/Tracks/PXBarrel/size_PXLayer_3', destination='DataLayouts/Tk/size_PXLayer_3', name='12 - PXBarrel OnTk Clusters Size', overlay='')
register_layout(source='PixelPhase1/Tracks/PXBarrel/size_PXLayer_4', destination='DataLayouts/Tk/size_PXLayer_4', name='12 - PXBarrel OnTk Clusters Size', overlay='')
register_layout(source='PixelPhase1/Tracks/PXForward/size_PXDisk_-3', destination='DataLayouts/Tk/size_PXDisk_-3', name='13 - PXEndcap OnTk Clusters Size', overlay='')
register_layout(source='PixelPhase1/Tracks/PXForward/size_PXDisk_-2', destination='DataLayouts/Tk/size_PXDisk_-2', name='13 - PXEndcap OnTk Clusters Size', overlay='')
register_layout(source='PixelPhase1/Tracks/PXForward/size_PXDisk_-1', destination='DataLayouts/Tk/size_PXDisk_-1', name='13 - PXEndcap OnTk Clusters Size', overlay='')
register_layout(source='PixelPhase1/Tracks/PXForward/size_PXDisk_+1', destination='DataLayouts/Tk/size_PXDisk_+1', name='13 - PXEndcap OnTk Clusters Size', overlay='')
register_layout(source='PixelPhase1/Tracks/PXForward/size_PXDisk_+2', destination='DataLayouts/Tk/size_PXDisk_+2', name='13 - PXEndcap OnTk Clusters Size', overlay='')
register_layout(source='PixelPhase1/Tracks/PXForward/size_PXDisk_+3', destination='DataLayouts/Tk/size_PXDisk_+3', name='13 - PXEndcap OnTk Clusters Size', overlay='')
