/********************************************************************
* TCellDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TCellDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableTCellDict();
extern void G__cpp_setup_inheritanceTCellDict();
extern void G__cpp_setup_typetableTCellDict();
extern void G__cpp_setup_memvarTCellDict();
extern void G__cpp_setup_globalTCellDict();
extern void G__cpp_setup_memfuncTCellDict();
extern void G__cpp_setup_funcTCellDict();
extern void G__set_cpp_environmentTCellDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TCell.h"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TCellDictLN_TClass;
extern G__linked_taginfo G__TCellDictLN_TBuffer;
extern G__linked_taginfo G__TCellDictLN_TMemberInspector;
extern G__linked_taginfo G__TCellDictLN_TObject;
extern G__linked_taginfo G__TCellDictLN_TCell;

/* STUB derived class for protected member access */
