
#include "FWCore/Integration/interface/ESTestRecords.h"
#include "FWCore/Framework/interface/eventsetuprecord_registration_macro.h"

EVENTSETUP_RECORD_REG(ESTestRecordA);
EVENTSETUP_RECORD_REG(ESTestRecordB);
EVENTSETUP_RECORD_REG(ESTestRecordC);
EVENTSETUP_RECORD_REG(ESTestRecordD);
EVENTSETUP_RECORD_REG(ESTestRecordE);
EVENTSETUP_RECORD_REG(ESTestRecordF);
EVENTSETUP_RECORD_REG(ESTestRecordG);
EVENTSETUP_RECORD_REG(ESTestRecordH);
EVENTSETUP_RECORD_REG(ESTestRecordI);
EVENTSETUP_RECORD_REG(ESTestRecordJ);
EVENTSETUP_RECORD_REG(ESTestRecordK);
EVENTSETUP_RECORD_REG(ESTestRecordZ);
