#! /bin/sh
if [ "$2" == "" ]; then
  NAME=`basename $0`
   echo "Usage: $NAME <connect> <treename>"
   echo
   echo "Examples"
   echo
   echo "Read the PHYS14_25_V1 global tag from Oracle:"
   echo "    $NAME oracle://cms_orcon_adg/CMS_COND_31X_GLOBALTAG PHYS14_25_V1"
   echo
   echo "Read the PHYS14_25_V1 global tag from Frontier:"
   echo "    $NAME frontier://FrontierProd/CMS_COND_31X_GLOBALTAG PHYS14_25_V1"
   exit 1
fi

CONNECT=$1
TREE=$2
cmscond_tagtree_list -c $CONNECT -P /afs/cern.ch/cms/DB/conddb -T $TREE \
  | grep 'leafnode' \
  | awk '{print $4,$6,$1,$3}' \
  | sed -e 's/\<record://' -e's/ *\<label:None//' -e's/ *\<label:/#/' -e's/\<leafnode://' -e's/\<tag://' \
  | sort \
  | column -t
