import FWCore.ParameterSet.Config as cms

from ..modules.hltDiEG23EtL1SeededFilter_cfi import *
from ..modules.hltDiEG3023IsoCaloIdClusterShapeL1SeededFilter_cfi import *
from ..modules.hltDiEG3023IsoCaloIdClusterShapeSigmavvL1SeededFilter_cfi import *
from ..modules.hltDiEG3023IsoCaloIdClusterShapeSigmawwL1SeededFilter_cfi import *
from ..modules.hltDiEG3023IsoCaloIdEcalIsoL1SeededFilter_cfi import *
from ..modules.hltDiEG3023IsoCaloIdHcalIsoL1SeededFilter_cfi import *
from ..modules.hltDiEG3023IsoCaloIdHEL1SeededFilter_cfi import *
from ..modules.hltDiEG3023IsoCaloIdHgcalHEL1SeededFilter_cfi import *
from ..modules.hltDiEG3023IsoCaloIdHgcalIsoL1SeededFilter_cfi import *
from ..modules.hltEG30EtL1SeededFilter_cfi import *
from ..modules.hltEgammaCandidatesWrapperL1Seeded_cfi import *
from ..modules.hltEGL1SeedsForDoublePhotonIsolatedFilter_cfi import *
from ..sequences.HLTDiphoton3023IsoCaloIdL1SeededInnerSequence_cfi import *
from ..sequences.HLTDoFullUnpackingEgammaEcalL1SeededSequence_cfi import *
from ..sequences.HLTEGammaDoLocalHcalSequence_cfi import *
from ..sequences.HLTFastJetForEgammaSequence_cfi import *
from ..sequences.HLTHgcalTiclPFClusteringForEgammaL1SeededSequence_cfi import *
from ..sequences.HLTL1Sequence_cfi import *
from ..sequences.HLTPFClusteringForEgammaL1SeededSequence_cfi import *
from ..sequences.HLTPFHcalClusteringForEgammaSequence_cfi import *

HLTDiphoton3023IsoCaloIdL1SeededSequence = cms.Sequence(HLTL1Sequence+hltEGL1SeedsForDoublePhotonIsolatedFilter+HLTDoFullUnpackingEgammaEcalL1SeededSequence+HLTEGammaDoLocalHcalSequence+HLTPFClusteringForEgammaL1SeededSequence+HLTHgcalTiclPFClusteringForEgammaL1SeededSequence+HLTFastJetForEgammaSequence+HLTPFHcalClusteringForEgammaSequence+HLTDiphoton3023IsoCaloIdL1SeededInnerSequence+hltEgammaCandidatesWrapperL1Seeded+hltEG30EtL1SeededFilter+hltDiEG23EtL1SeededFilter+hltDiEG3023IsoCaloIdClusterShapeL1SeededFilter+hltDiEG3023IsoCaloIdClusterShapeSigmavvL1SeededFilter+hltDiEG3023IsoCaloIdClusterShapeSigmawwL1SeededFilter+hltDiEG3023IsoCaloIdHgcalHEL1SeededFilter+hltDiEG3023IsoCaloIdHEL1SeededFilter+hltDiEG3023IsoCaloIdEcalIsoL1SeededFilter+hltDiEG3023IsoCaloIdHgcalIsoL1SeededFilter+hltDiEG3023IsoCaloIdHcalIsoL1SeededFilter)
