import FWCore.ParameterSet.Config as cms

from ..modules.hltFixedGridRhoFastjetAll_cfi import *
from ..modules.hltHpsPFTauBasicDiscriminatorsdR03ForDeepTau_cfi import *
from ..modules.hltHpsPFTauBasicDiscriminatorsForDeepTau_cfi import *
from ..modules.hltHpsPFTauDeepTauProducer_cfi import *
from ..modules.hltHpsPFTauDiscriminationByDecayModeFindingNewDMs_cfi import *
from ..modules.hltHpsPFTauPrimaryVertexProducerForDeepTau_cfi import *
from ..modules.hltHpsPFTauSecondaryVertexProducerForDeepTau_cfi import *
from ..modules.hltHpsPFTauTransverseImpactParametersForDeepTau_cfi import *

HLTHPSDeepTauPFTauSequence = cms.Sequence(hltHpsPFTauDiscriminationByDecayModeFindingNewDMs+hltHpsPFTauPrimaryVertexProducerForDeepTau+hltHpsPFTauSecondaryVertexProducerForDeepTau+hltHpsPFTauTransverseImpactParametersForDeepTau+hltFixedGridRhoFastjetAll+hltHpsPFTauBasicDiscriminatorsForDeepTau+hltHpsPFTauBasicDiscriminatorsdR03ForDeepTau+hltHpsPFTauDeepTauProducer)
