rfrm /castor/cern.ch/user/p/pjanot/CMSSW350pre3/aod_QCDForPF_Full_30.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW350pre3/aod_QCDForPF_Full_31.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW350pre3/aod_QCDForPF_Full_32.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW350pre3/aod_QCDForPF_Full_33.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW350pre3/aod_QCDForPF_Full_34.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW350pre3/aod_QCDForPF_Full_35.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW350pre3/aod_QCDForPF_Full_36.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW350pre3/aod_QCDForPF_Full_37.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW350pre3/aod_QCDForPF_Full_38.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW350pre3/aod_QCDForPF_Full_39.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW350pre3/aod_QCDForPF_Full_40.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW350pre3/aod_QCDForPF_Full_41.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW350pre3/aod_QCDForPF_Full_42.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW350pre3/aod_QCDForPF_Full_43.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW350pre3/aod_QCDForPF_Full_44.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW350pre3/aod_QCDForPF_Full_45.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW350pre3/aod_QCDForPF_Full_46.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW350pre3/aod_QCDForPF_Full_47.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW350pre3/aod_QCDForPF_Full_48.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW350pre3/aod_QCDForPF_Full_49.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW350pre3/aod_QCDForPF_Full_50.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW350pre3/aod_QCDForPF_Full_51.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW350pre3/aod_QCDForPF_Full_52.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW350pre3/aod_QCDForPF_Full_53.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW350pre3/aod_QCDForPF_Full_54.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW350pre3/aod_QCDForPF_Full_55.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW350pre3/aod_QCDForPF_Full_56.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW350pre3/aod_QCDForPF_Full_57.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW350pre3/aod_QCDForPF_Full_58.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW350pre3/aod_QCDForPF_Full_59.root

