rfrm /castor/cern.ch/user/p/pjanot/CMSSW312/aod_QCDForPF_Full_60.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW312/aod_QCDForPF_Full_61.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW312/aod_QCDForPF_Full_62.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW312/aod_QCDForPF_Full_63.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW312/aod_QCDForPF_Full_64.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW312/aod_QCDForPF_Full_65.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW312/aod_QCDForPF_Full_66.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW312/aod_QCDForPF_Full_67.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW312/aod_QCDForPF_Full_68.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW312/aod_QCDForPF_Full_69.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW312/aod_QCDForPF_Full_70.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW312/aod_QCDForPF_Full_71.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW312/aod_QCDForPF_Full_72.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW312/aod_QCDForPF_Full_73.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW312/aod_QCDForPF_Full_74.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW312/aod_QCDForPF_Full_75.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW312/aod_QCDForPF_Full_76.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW312/aod_QCDForPF_Full_77.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW312/aod_QCDForPF_Full_78.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW312/aod_QCDForPF_Full_79.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW312/aod_QCDForPF_Full_80.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW312/aod_QCDForPF_Full_81.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW312/aod_QCDForPF_Full_82.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW312/aod_QCDForPF_Full_83.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW312/aod_QCDForPF_Full_84.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW312/aod_QCDForPF_Full_85.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW312/aod_QCDForPF_Full_86.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW312/aod_QCDForPF_Full_87.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW312/aod_QCDForPF_Full_88.root
rfrm /castor/cern.ch/user/p/pjanot/CMSSW312/aod_QCDForPF_Full_89.root

