import FWCore.ParameterSet.Config as cms

isolatedTracksNxN = cms.EDAnalyzer("IsolatedTracksNxN",
                                   FlagMC        = cms.untracked.bool(False),
                                   Verbosity     = cms.untracked.int32( 1 ),

                                   PVTracksPtMin = cms.untracked.double(1.0),
                                   DebugTracks   = cms.untracked.int32(0),
                                   PrintTrkHitPattern=cms.untracked.bool(True),
                                   minTrackP     = cms.untracked.double(1.0),
                                   maxTrackEta   = cms.untracked.double(2.6),
                                   
                                   DebugL1Info   = cms.untracked.bool(False),
                                   L1extraTauJetSource   = cms.InputTag("l1extraParticles", "Tau"),
                                   L1extraCenJetSource   = cms.InputTag("l1extraParticles", "Central"),
                                   L1extraFwdJetSource   = cms.InputTag("l1extraParticles", "Forward"),
                                   L1extraMuonSource     = cms.InputTag("l1extraParticles"),
                                   L1extraIsoEmSource    = cms.InputTag("l1extraParticles","Isolated"),
                                   L1extraNonIsoEmSource = cms.InputTag("l1extraParticles","NonIsolated"),
                                   L1GTReadoutRcdSource  = cms.InputTag("gtDigis"),
                                   L1GTObjectMapRcdSource= cms.InputTag("hltL1GtObjectMap"),
                                   JetSource             = cms.InputTag("iterativeCone5CaloJets"),
                                   JetExtender           = cms.InputTag("iterativeCone5JetExtender"),

                                   TrackAssociatorParameters = cms.PSet(
                                       muonMaxDistanceSigmaX = cms.double(0.0),
                                       muonMaxDistanceSigmaY = cms.double(0.0),
                                       CSCSegmentCollectionLabel = cms.InputTag("cscSegments"),
                                       dRHcal = cms.double(9999.0),
                                       dREcal = cms.double(9999.0),
                                       CaloTowerCollectionLabel = cms.InputTag("towerMaker"),
                                       useEcal = cms.bool(True),
                                       dREcalPreselection = cms.double(0.05),
                                       HORecHitCollectionLabel = cms.InputTag("horeco"),
                                       dRMuon = cms.double(9999.0),
                                       crossedEnergyType = cms.string('SinglePointAlongTrajectory'),
                                       muonMaxDistanceX = cms.double(5.0),
                                       muonMaxDistanceY = cms.double(5.0),
                                       useHO = cms.bool(False),
                                       accountForTrajectoryChangeCalo = cms.bool(False),
                                       DTRecSegment4DCollectionLabel = cms.InputTag("dt4DSegments"),
                                       EERecHitCollectionLabel = cms.InputTag("ecalRecHit","EcalRecHitsEE"),
                                       dRHcalPreselection = cms.double(0.2),
                                       useMuon = cms.bool(False),
                                       useCalo = cms.bool(True),
                                       EBRecHitCollectionLabel = cms.InputTag("ecalRecHit","EcalRecHitsEB"),
                                       dRMuonPreselection = cms.double(0.2),
                                       truthMatch = cms.bool(False),
                                       HBHERecHitCollectionLabel = cms.InputTag("hbhereco"),
                                       useHcal = cms.bool(True),
                                       usePreshower = cms.bool(False),
                                       dRPreshowerPreselection = cms.double(0.2),
                                       trajectoryUncertaintyTolerance = cms.double(-1.0)
                                       )
)
