import FWCore.ParameterSet.Config as cms

leptonJetsChecker= cms.EDAnalyzer('LeptonJetsChecker',
        leptonType                  = cms.string('muon'),
	outputFileName              = cms.string('TopMCValidation_test.root'),	
	labelMuons                  = cms.InputTag('muons'),
	labelElectrons              = cms.InputTag('gsfElectrons'),
        labelJets                   = cms.InputTag('ak5CaloJets'),
        labelMETs                   = cms.InputTag('metJESCorAK5CaloJet'),
        labelBeamSpot               = cms.InputTag('offlineBeamSpot'),
        #labelTriggerResults         = cms.InputTag('hltTriggerSummaryAOD'),
        labelTriggerResults         = cms.InputTag("TriggerResults","","HLT"),
	jetCorrector                = cms.string('L2L3JetCorrectorAK5Calo'),
        useJES                      = cms.bool(True),   
	useTrigger                  = cms.bool(True),
	NofJets	  	            = cms.int32(4),
	PtThrJets                   = cms.double(30.),
        EtaThrJets                  = cms.double(2.4),
        EHThrJets                   = cms.double(0.0),
	JetDeltaRLeptonJetThreshold = cms.double(0.0),
	applyLeptonJetDeltaRCut     = cms.bool(False),
	PtThrMuons                  = cms.double(20.),
        EtaThrMuons                 = cms.double(2.1),
	MuonRelIso                  = cms.double(0.1),
	MuonVetoEM                  = cms.double(4),
	MuonVetoHad                 = cms.double(6),
        useElectronID               = cms.bool(False),
	electronIDLabel             = cms.string('eidLoose'),
	PtThrElectrons              = cms.double(20.),
        EtaThrElectrons	            = cms.double(2.5),
	ElectronRelIso              = cms.double(0.1),
        ElectronD0Cut               = cms.double(0.02), 
	MuonD0Cut                   = cms.double(0.02), 
	Chi2Cut                     = cms.int32(10), 
        NofValidHits                = cms.int32(11),
	METThreshold                = cms.double(20),
	ApplyMETCut                 = cms.bool(False),
	triggerPath                 = cms.string('HLT_Mu9'),
	Xsection                    = cms.double(414),   #Xsection X BR if sample of specific decay
	Luminosity                  = cms.int32(100),    #pb-1
        vetoEBEETransitionRegion    = cms.bool(False),
        verbose                     = cms.bool(False),
        VetoLooseLepton             = cms.bool(False),
        PtThrMuonLoose              = cms.double(10.0),
	EtaThrMuonLoose             = cms.double(2.1),
	RelIsoThrMuonLoose          = cms.double(0.1),
	PtThrElectronLoose          = cms.double(10.0),
	EtaThrElectronLoose         = cms.double(2.5),
	RelIsoThrElectronLoose      = cms.double(1.0),
	electronIDLabelLoose        = cms.string('eidRobustLoose'),
	includeBtagInfo             = cms.bool(False), # if true also fill the list of algos! If False the following two parameters are actually not parsed.
        btaggingAlgoLabels          = cms.vstring(""),   # for example: btaggingAlgoLabels = cms.vstring("trackCountingHighPurBJetTag","trackCountingHighEffBJetTag","simpleSecondaryVertexBJetTag")                                 
        btaggingMatchDr             = cms.double(0.5), # match jet used for b-tagging to jet in jet collection                                  
        
	PerformOctoberXDeltaRStep   = cms.bool(False),
        saveDQMMEs                  = cms.bool(True)
) 
