#!/bin/sh
eval `scramv1 runtime -sh`

export XDAQ_DOCUMENT_ROOT=/opt/xdaq/htdocs
export XDAQ_ROOT=/opt/xdaq
echo "initializePixelDQM"
./initializePixelDQM
echo " Start Application "
./start &
sleep 30
echo "Started the application and Configuring"
./configure
sleep 60
echo "Configured..."
./enable
echo "Enabled ..."


