#!/usr/bin/env python
import os,string
from optparse import OptionParser

def main():
   parser = OptionParser()
   parser.add_option("-v","--verbose",action="store_true",dest="verbose",
                          help="verbose mode")
   parser.add_option("-f","--filename",action="store",dest="filename", help="filename")
   parser.add_option("-c","--connect",action="store",dest="connect", help="database connection string")
   parser.add_option("-P","--authpath",action="store",dest="authpath",help="authentication file path")
   parser.add_option("-t","--tag",action="store",dest="tag",help="iov tag")
   (options, args) = parser.parse_args()
   
if __name__ == '__main__':
   main()

