import SimCalorimetry.EcalEBTrigPrimProducers.ecalEBTrigPrimPhase2Producer_cfi as _mod

simEcalEBTriggerPrimitivePhase2Digis = _mod.ecalEBTrigPrimPhase2Producer.clone()

from Configuration.ProcessModifiers.premix_stage2_cff import premix_stage2
premix_stage2.toModify(simEcalEBTriggerPrimitivePhase2Digis, barrelEcalDigis = 'mixData')
