LOAD DATA
INFILE 'data/BOXES.dat'
BADFILE 'data/BOXES.bad'
DISCARDFILE 'data/BOXES.dsc'
INSERT INTO TABLE CMSINTEGRATION.BOXES
FIELDS TERMINATED by ","
(
 DZ INTEGER EXTERNAL,
 SOL_NAME CHAR,
 DX INTEGER EXTERNAL,
 DY INTEGER EXTERNAL
) 
