LOAD DATA
INFILE './data/CONES'
BADFILE './data/CONES.bad'
DISCARDFILE './data/CONES.dsc'
INSERT INTO TABLE CMS_DTCTR_GEOMETRY_OWNER.CONES
FIELDS TERMINATED by ","
(
 SOL_NAME CHAR,
 RADIUSMIN1 INTEGER EXTERNAL,
 RADIUSMAX1 INTEGER EXTERNAL,
 RADIUSMAX2 INTEGER EXTERNAL,
 DZ INTEGER EXTERNAL,
 DELTAPHI  INTEGER EXTERNAL,
 STARTPHI INTEGER EXTERNAL,
 RADIUSMIN2 INTEGER EXTERNAL
)
