LOAD DATA
INFILE './data/LOGICALPARTS.dat'
BADFILE './data/LOGICALPARTS.bad'
DISCARDFILE './data/LOGICALPARTS.dsc'
APPEND INTO TABLE CMSINTEGRATION.LOGICALPARTTYPES
FIELDS TERMINATED by ","
(
 LPNAME POSITION(1) CHAR,
 skip_field2 FILLER,
 skip_field3 FILLER,
 CAT_NAME CHAR
)

INTO TABLE CMSINTEGRATION.DETECTORPARTS
FIELDS TERMINATED by "," 
(
 SOL_NAME POSITION(2) CHAR,
 MAT_NAME CHAR,
 skip_field5 FILLER,
 ITEM_ID CHAR
)

