LOAD DATA
INFILE './data/LOGICALPARTS.dat'
BADFILE './data/LOGICALPARTTYPES.bad'
DISCARDFILE './data/LOGICALPARTTYPES.dsc'
APPEND INTO TABLE CMSINTEGRATION.LOGICALPARTTYPES
FIELDS TERMINATED by ","
(
 LPNAME POSITION(1) CHAR,
 skip_field2 FILLER,
 skip_field3 FILLER,
 CAT_NAME CHAR
)

