LOAD DATA
INFILE './data/MATERIALFRACTIONS.dat'
BADFILE './data/MATERIALFRACTIONS.bad'
DISCARDFILE './data/MATERIALFRACTIONS.dsc'
INSERT INTO TABLE CMSINTEGRATION.MATERIALFRACTIONS 
FIELDS TERMINATED by ","
(
 COMPOS_NAME  CHAR,
 MAT_NAME     CHAR,
 FRACTION     INTEGER EXTERNAL
)     
