LOAD DATA
INFILE './data/PHYSICALPARTSTREE' 
BADFILE './data/physicalpartstree.bad'
DISCARDFILE './data/physicalpartstree.dsc'
INSERT INTO TABLE CMS_DTCTR_GEOMETRY_OWNER.PHYSICALPARTSTREE
FIELDS TERMINATED by ","
(
 PHYSICALPART_ID CHAR,
 CONTAINERPART_ID CHAR NULLIF CONTAINERPART_ID='',
 LPNAME CHAR
)
