LOAD DATA
INFILE './data/POLYCONES'
BADFILE './data/POLYCONES.bad'
DISCARDFILE './data/POLYCONES.dsc'
INSERT INTO TABLE CMS_DTCTR_GEOMETRY_OWNER.POLYCONES
FIELDS TERMINATED by ","
(
 DELTAPHI INTEGER EXTERNAL,  
 SOL_NAME  CHAR,
 STARTPHI INTEGER EXTERNAL,
 RZ_ZS  CHAR 
)
