LOAD DATA
INFILE './data/POLYHEDRAS'
BADFILE './data/POLYHEDRAS.bad'
DISCARDFILE './data/POLYHEDRAS.dsc'
INSERT INTO TABLE CMS_DTCTR_GEOMETRY_OWNER.POLYHEDRA
FIELDS TERMINATED by ","
(
 DELTAPHI INTEGER EXTERNAL,  
 SOL_NAME CHAR,
 NUMSIDE INTEGER EXTERNAL,  
 STARTPHI INTEGER EXTERNAL,  
 RZ_ZS CHAR    
)
