LOAD DATA
INFILE './data/PSEUDOTRAPEZOIDS.dat' 
BADFILE './data/PSEUDOTRAPEZOIDS.bad'
DISCARDFILE './data/PSEUDOTRAPEZOIDS.dsc'
INSERT INTO TABLE CMSINTEGRATION.PSEUDOTRAPEZOIDS
FIELDS TERMINATED by ","
(
 SOL_NAME CHAR,
 DY1 INTEGER EXTERNAL,
 DY2 INTEGER EXTERNAL,
 DX2 INTEGER EXTERNAL,
 DZ INTEGER EXTERNAL,
 DX1 INTEGER EXTERNAL,
 ATMINZ CHAR,
 RADIUS INTEGER EXTERNAL
)
