LOAD DATA
INFILE './data/TUBESECTIONS'
BADFILE './data/TUBESECTIONS.bad'
DISCARDFILE './data/TUBESECTIONS.dsc'
INSERT INTO TABLE CMS_DTCTR_GEOMETRY_OWNER.TUBESECTIONS
FIELDS TERMINATED by ","
(
 RADIUSMIN INTEGER EXTERNAL,
 SOL_NAME  CHAR,
 RADIUSMAX INTEGER EXTERNAL,
 DELTAPHI  INTEGER EXTERNAL,
 DZ        INTEGER EXTERNAL,
 STARTPHI  INTEGER EXTERNAL
)
