LOAD DATA
INFILE './data/ZSECTIONS.dat'
BADFILE './data/ZSECTIONS.bad'
DISCARDFILE './data/ZSECTIONS.dsc'
INSERT INTO TABLE CMSINTEGRATION.ZSECTIONS
FIELDS TERMINATED by ","
TRAILING NULLCOLS
(
  ZSECTIONID INTEGER EXTERNAL,
  RADIUSMIN   INTEGER EXTERNAL,
  Z           INTEGER EXTERNAL,
  RADIUSMAX   INTEGER EXTERNAL,
  POL_SOL_NAME  CHAR,
  POLH_SOL_NAME  CHAR
)
