import FWCore.ParameterSet.Config as cms

from DQMServices.Core.DQMEDAnalyzer import DQMEDAnalyzer
JPsiMuMuValidation = DQMEDAnalyzer('BPhysicsValidation',
                                    genparticleCollection = cms.InputTag("genParticles",""),
                                    name = cms.string("JPsiMuMuValidation"),
                                    pname = cms.string("J/#Psi"),
                                    pdgid = cms.int32(443),
                                    massmin = cms.double(3.0),
                                    massmax = cms.double(4.0),
                                    daughters = cms.vstring("muminus","muplus"),
                                    muminus = dict(pname = "#mu^{-}",
                                                   pdgid = 13,
                                                   massmin = 0.1,
                                                   massmax = 0.2,
                                        ),
                                    muplus = dict(pname = "#mu^{+}",
                                                  pdgid = -13,
                                                  massmin = 0.1,
                                                  massmax = 0.2,
                                              )
                                    )

LambdabPiPiMuMuValidation = DQMEDAnalyzer('BPhysicsValidation',
                                           genparticleCollection = cms.InputTag("genParticles",""),
                                           name = cms.string("LambdabPiPiMuMuValidation"),
                                           pname = cms.string("#Lambda_{b}"),
                                           pdgid = cms.int32(5122),
                                           massmin = cms.double(5.5),
                                           massmax = cms.double(6.0),
                                           daughters = cms.vstring("muminus","muplus","piminus","piplus","pminus","pplus","Lambda","Lambdabar"),
                                           muminus = dict(pname = "#mu^{-}",
                                                          pdgid = 13,
                                                          massmin = 0.1,
                                                          massmax = 0.2,
                                                      ),
                                           muplus = dict(pname = "#mu^{+}",
                                                         pdgid = -13,
                                                         massmin = 0.1,
                                                         massmax = 0.2,
                                                     ),
                                           piminus = dict(pname = "#pi^{-}",
                                                          pdgid = -211,
                                                          massmin = 0.1,
                                                          massmax = 0.2,
                                                      ),
                                           piplus = dict(pname = "#pi^{+}",
                                                         pdgid = 211,
                                                         massmin = 0.1,
                                                         massmax = 0.2,
                                                     ),
                                           pminus = dict(pname = "p^{-}",
                                                         pdgid = -2212,
                                                         massmin = 0.9,
                                                         massmax = 1.1,
                                                     ),
                                           pplus = dict(pname = "p^{+}",
                                                        pdgid = 2212,
                                                        massmin = 0.9,
                                                        massmax = 1.1,
                                                    ),
                                           Lambda = dict(pname = "#Lambda",
                                                         pdgid = 3122,
                                                         massmin = 1.0,
                                                         massmax = 1.2,
                                                     ),
                                           Lambdabar = dict(pname = "#bar{#Lambda}",
                                                            pdgid = -3122,
                                                            massmin = 1.0,
                                                            massmax = 1.2,
                                                        )
                                      )



PsiSpectrum = DQMEDAnalyzer('BPhysicsSpectrum',
                             genparticleCollection = cms.InputTag("genParticles",""),
                             name = cms.string("JPsiSpectrum"),
                             pdgids = cms.vint32(443,100443,30443,9000443,9010443,9020443),
                             massmin = cms.double(3.0),
                             massmax = cms.double(4.5)
                             )

LambdaSpectrum = DQMEDAnalyzer('BPhysicsSpectrum',
                             genparticleCollection = cms.InputTag("genParticles",""),
                             name = cms.string("LambdaSpectrum"),
                             pdgids = cms.vint32(5122),
                             massmin = cms.double(5.5),
                             massmax = cms.double(6.0)
                             )
