import FWCore.ParameterSet.Config as cms
from DQMServices.Core.DQMEDHarvester import DQMEDHarvester

hltTauPostProcessor = DQMEDHarvester("DQMGenericClient",
    subDirs=cms.untracked.vstring("HLT/Tau/TauValidation/", 
                                  "HLT/Tau/TauValidation/Cut*",
                                  "HLT/Tau/TauValidation_DeltaR/DeltaR*",
                                  "HLT/Tau/TauValidation_DeltaR/DeltaR*/Cut*", ),
    efficiency = cms.vstring(
        # Efficiency
        "Eff_vs_pt_eta 'Efficiency vs p_{T},#eta' genTauMatched_pt_eta genTau_pt_eta",
        "Eff_vs_pt_phi 'Efficiency vs p_{T},#phi' genTauMatched_pt_phi genTau_pt_phi",
        "Eff_vs_pt_mass 'Efficiency vs p_{T},mass' genTauMatched_pt_mass genTau_pt_mass",
        "Eff_vs_mass_eta 'Efficiency vs mass,#eta' genTauMatched_mass_eta genTau_mass_eta",
        "Eff_vs_mass_phi 'Efficiency vs mass,#phi' genTauMatched_mass_phi genTau_mass_phi",
        # Fake rate
        "Fake_vs_pt_eta 'Fake Rate vs p_{T},#eta' recoTauMatched_pt_eta recoTau_pt_eta fake",
        "Fake_vs_pt_phi 'Fake Rate vs p_{T},#phi' recoTauMatched_pt_phi recoTau_pt_phi fake",
        "Fake_vs_pt_mass 'Fake Rate vs p_{T},mass' recoTauMatched_pt_mass recoTau_pt_mass fake",
        "Fake_vs_mass_eta 'Fake Rate vs mass,#eta' recoTauMatched_mass_eta recoTau_mass_eta fake",
        "Fake_vs_mass_phi 'Fake Rate vs mass,#phi' recoTauMatched_mass_phi recoTau_mass_phi fake",
        "Fake_vs_idVSjet_pt 'Fake Rate vs ID vs Jet,p_{T}' recoTauMatched_idVSjet_pt recoTau_idVSjet_pt fake",
        "Fake_vs_idVSjet_eta 'Fake Rate vs ID vs Jet,#eta' recoTauMatched_idVSjet_eta recoTau_idVSjet_eta fake",
        "Fake_vs_idVSjet_phi 'Fake Rate vs ID vs Jet,#phi' recoTauMatched_idVSjet_phi recoTau_idVSjet_phi fake",
        "Fake_vs_idVSjet_mass 'Fake Rate vs ID vs Jet,mass' recoTauMatched_idVSjet_mass recoTau_idVSjet_mass fake",
        "Fake_vs_idVSe_pt 'Fake Rate vs ID vs Electron,p_{T}' recoTauMatched_idVSe_pt recoTau_idVSe_pt fake",
        "Fake_vs_idVSe_eta 'Fake Rate vs ID vs Electron,#eta' recoTauMatched_idVSe_eta recoTau_idVSe_eta fake",
        "Fake_vs_idVSe_phi 'Fake Rate vs ID vs Electron,#phi' recoTauMatched_idVSe_phi recoTau_idVSe_phi fake",
        "Fake_vs_idVSe_mass 'Fake Rate vs ID vs Electron,mass' recoTauMatched_idVSe_mass recoTau_idVSe_mass fake",
        "Fake_vs_idVSmu_pt 'Fake Rate vs ID vs Muon,p_{T}' recoTauMatched_idVSmu_pt recoTau_idVSmu_pt fake",
        "Fake_vs_idVSmu_eta 'Fake Rate vs ID vs Muon,#eta' recoTauMatched_idVSmu_eta recoTau_idVSmu_eta fake",
        "Fake_vs_idVSmu_phi 'Fake Rate vs ID vs Muon,#phi' recoTauMatched_idVSmu_phi recoTau_idVSmu_phi fake",
        "Fake_vs_idVSmu_mass 'Fake Rate vs ID vs Muon,mass' recoTauMatched_idVSmu_mass recoTau_idVSmu_mass fake",
        # Split rate
        "Split_vs_pt_eta 'Split Rate vs p_{T},#eta' genTauMultiMatched_pt_eta genTau_pt_eta",
        "Split_vs_pt_phi 'Split Rate vs p_{T},#phi' genTauMultiMatched_pt_phi genTau_pt_phi",
        "Split_vs_pt_mass 'Split Rate vs p_{T},mass' genTauMultiMatched_pt_mass genTau_pt_mass",
        "Split_vs_mass_eta 'Split Rate vs mass,#eta' genTauMultiMatched_mass_eta genTau_mass_eta",
        "Split_vs_mass_phi 'Split Rate vs mass,#phi' genTauMultiMatched_mass_phi genTau_mass_phi",
        # Duplicate rate
        "Dup_vs_pt_eta 'Duplicate Rate vs p_{T},#eta' recoTauMultiMatched_pt_eta recoTau_pt_eta",
        "Dup_vs_pt_phi 'Duplicate Rate vs p_{T},#phi' recoTauMultiMatched_pt_phi recoTau_pt_phi",
        "Dup_vs_pt_mass 'Duplicate Rate vs p_{T},mass' recoTauMultiMatched_pt_mass recoTau_pt_mass",
        "Dup_vs_mass_eta 'Duplicate Rate vs mass,#eta' recoTauMultiMatched_mass_eta recoTau_mass_eta",
        "Dup_vs_mass_phi 'Duplicate Rate vs mass,#phi' recoTauMultiMatched_mass_phi recoTau_mass_phi",
        "Dup_vs_idVSjet_pt 'Duplicate Rate vs ID vs Jet,p_{T}' recoTauMultiMatched_idVSjet_pt recoTau_idVSjet_pt",
        "Dup_vs_idVSjet_eta 'Duplicate Rate vs ID vs Jet,#eta' recoTauMultiMatched_idVSjet_eta recoTau_idVSjet_eta",
        "Dup_vs_idVSjet_phi 'Duplicate Rate vs ID vs Jet,#phi' recoTauMultiMatched_idVSjet_phi recoTau_idVSjet_phi",
        "Dup_vs_idVSjet_mass 'Duplicate Rate vs ID vs Jet,mass' recoTauMultiMatched_idVSjet_mass recoTau_idVSjet_mass",
        "Dup_vs_idVSe_pt 'Duplicate Rate vs ID vs Electron,p_{T}' recoTauMultiMatched_idVSe_pt recoTau_idVSe_pt",
        "Dup_vs_idVSe_eta 'Duplicate Rate vs ID vs Electron,#eta' recoTauMultiMatched_idVSe_eta recoTau_idVSe_eta",
        "Dup_vs_idVSe_phi 'Duplicate Rate vs ID vs Electron,#phi' recoTauMultiMatched_idVSe_phi recoTau_idVSe_phi",
        "Dup_vs_idVSe_mass 'Duplicate Rate vs ID vs Electron,mass' recoTauMultiMatched_idVSe_mass recoTau_idVSe_mass",
        "Dup_vs_idVSmu_pt 'Duplicate Rate vs ID vs Muon,p_{T}' recoTauMultiMatched_idVSmu_pt recoTau_idVSmu_pt",
        "Dup_vs_idVSmu_eta 'Duplicate Rate vs ID vs Muon,#eta' recoTauMultiMatched_idVSmu_eta recoTau_idVSmu_eta",
        "Dup_vs_idVSmu_phi 'Duplicate Rate vs ID vs Muon,#phi' recoTauMultiMatched_idVSmu_phi recoTau_idVSmu_phi",
        "Dup_vs_idVSmu_mass 'Duplicate Rate vs ID vs Muon,mass' recoTauMultiMatched_idVSmu_mass recoTau_idVSmu_mass",
    ),
    efficiencyProfile = cms.untracked.vstring( # for smoother rebinning
        # Efficiency
        "Eff_vs_eta 'Efficiency vs #eta' genTauMatched_eta genTau_eta",
        "Eff_vs_phi 'Efficiency vs #phi' genTauMatched_phi genTau_phi",
        "Eff_vs_pt 'Efficiency vs p_{T}' genTauMatched_pt genTau_pt",
        "Eff_vs_mass 'Efficiency vs mass' genTauMatched_mass genTau_mass",
        # Fake rate (note: the flag 'fake' coputes 1 - ratio only for the globalEfficiency histogram)
        "Fake_vs_eta 'Fake Rate vs #eta' recoTauMatched_eta recoTau_eta fake",
        "Fake_vs_phi 'Fake Rate vs #phi' recoTauMatched_phi recoTau_phi fake",
        "Fake_vs_pt 'Fake Rate vs p_{T}' recoTauMatched_pt recoTau_pt fake",
        "Fake_vs_mass 'Fake Rate vs mass' recoTauMatched_mass recoTau_mass fake",
        "Fake_vs_idVSjet 'Fake Rate vs ID vs Jet' recoTauMatched_idVSjet recoTau_idVSjet fake",
        "Fake_vs_idVSe 'Fake Rate vs ID vs E' recoTauMatched_idVSe recoTau_idVSe fake",
        "Fake_vs_idVSmu 'Fake Rate vs ID vs Mu' recoTauMatched_idVSmu recoTau_idVSmu fake",
        # Split rate
        "Split_vs_eta 'Split Rate vs #eta' genTauMultiMatched_eta genTau_eta",
        "Split_vs_phi 'Split Rate vs #phi' genTauMultiMatched_phi genTau_phi",
        "Split_vs_pt 'Split Rate vs p_{T}' genTauMultiMatched_pt genTau_pt",
        "Split_vs_mass 'Split Rate vs mass' genTauMultiMatched_mass genTau_mass",
        # Duplicate rate
        "Dup_vs_eta 'Duplicate Rate vs #eta' recoTauMultiMatched_eta recoTau_eta",
        "Dup_vs_phi 'Duplicate Rate vs #phi' recoTauMultiMatched_phi recoTau_phi",
        "Dup_vs_pt 'Duplicate Rate vs p_{T}' recoTauMultiMatched_pt recoTau_pt",
        "Dup_vs_mass 'Duplicate Rate vs mass' recoTauMultiMatched_mass recoTau_mass",
        "Dup_vs_idVSjet 'Duplicate Rate vs ID vs Jet' recoTauMultiMatched_idVSjet recoTau_idVSjet",
        "Dup_vs_idVSe 'Duplicate Rate vs ID vs E' recoTauMultiMatched_idVSe recoTau_idVSe",
        "Dup_vs_idVSmu 'Duplicate Rate vs ID vs Mu' recoTauMultiMatched_idVSmu recoTau_idVSmu",
    ),
    resolution = cms.vstring(),
    resolutionProfile = cms.untracked.vstring(
        "ResponsePt_RecoOverGen_vs_pt 'Response RecoOverGen vs p_{T}^{gen}' responsePt_pt rms",
        "ResponsePt_RecoOverGen_vs_eta 'Response RecoOverGen vs #eta^{gen}' responsePt_eta rms",
        "ResponsePt_RecoOverGen_vs_phi 'Response RecoOverGen vs #phi^{gen}' responsePt_phi rms",
        "ResponsePt_RecoOverGen_vs_mass 'Response RecoOverGen vs mass^{gen}' responsePt_mass rms",
        "ResponseMass_RecoOverGen_vs_pt 'Response RecoOverGen vs p_{T}^{gen}' responseMass_pt rms",
        "ResponseMass_RecoOverGen_vs_eta 'Response RecoOverGen vs #eta^{gen}' responseMass_eta rms",
        "ResponseMass_RecoOverGen_vs_phi 'Response RecoOverGen vs #phi^{gen}' responseMass_phi rms",
        "ResponseMass_RecoOverGen_vs_mass 'Response RecoOverGen vs mass^{gen}' responseMass_mass rms",
    ),
    verbose = cms.untracked.uint32(2), 
    outputFileName = cms.untracked.string("")
)
