#!/bin/bash
link=$1
first=$2
last=$3
arg1=''
arg2=''

source $1/musecal/setup $1


if [ -z $first ]; then
  echo
else
  arg1="-f $first"
fi
if [ -z $last ]; then
    echo
else
  arg2="-l $last"
fi
psdir="`whoami`_`date +%d%m%y%H%M`"
mkdir $psdir
export MEPSDIR=${PWD}/$psdir;
echo 'postscript files will be written in ' $MEPSDIR
runGUI -d $arg1 $arg2
ls $MEPSDIR

