#!/bin/bash
#
#	/etc/rc.d/init.d/fff_deleter
#
# Init file for fff_deleter.py
# Copy it to /etc/rc.d/init.d/fff_deleter
#
# chkconfig: 345 80 20
# description: FFF Deletion daemon for DQM

# Source function library.
. /etc/rc.d/init.d/functions

DAEMON_BIN=/usr/local/bin/fff_deleter.py
PIDFILE=/var/run/fff_deleter.pid
RETVAL=0

start() {
	echo -n $"Starting fff_deleter daemon: "	
	daemon $DAEMON_BIN
	RETVAL=$?
	echo

	return $RETVAL
}

stop() {
	echo -n $"Stopping fff_deleter daemon: "
	killproc -p $PIDFILE
	RETVAL=$?
	echo

    return $RETVAL
}


restart() {
	stop
	start
}	

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
reload)
	echo "$0: Unimplemented feature."
	RETVAL=3
	;;
force-reload)
	echo "$0: Unimplemented feature."
	RETVAL=3
	;;
restart)
	restart
	;;
status)
	status -p $PIDFILE
	RETVAL=$?
	;;
*)
	echo $"Usage: $0 {start|stop|status|restart}"
	RETVAL=2
esac

exit $RETVAL
