#!/bin/bash
#
#	/etc/rc.d/init.d/fff_monitoring
#
# Init file for fff_monitoring.py
# Copy it to /etc/rc.d/init.d/fff_monitoring
#
# chkconfig: 345 80 20
# description: FFF Monitoring daemon for DQM

# Source function library.
. /etc/rc.d/init.d/functions

DAEMON_BIN=/usr/local/bin/fff_monitoring.py
PIDFILE=/var/run/fff_monitoring.pid
RETVAL=0

start() {
	echo -n $"Starting fff_monitoring daemon: "	
	daemon $DAEMON_BIN
	RETVAL=$?
	echo

	return $RETVAL
}

stop() {
	echo -n $"Stopping fff_monitoring daemon: "
	killproc -p $PIDFILE
	RETVAL=$?
	echo

    return $RETVAL
}


restart() {
	stop
	start
}

reindex() {
	stop
	$DAEMON_BIN reindex
	start
}

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
reload)
	echo "$0: Unimplemented feature."
	RETVAL=3
	;;
reindex)
	reindex
	;;
force-reload)
	echo "$0: Unimplemented feature."
	RETVAL=3
	;;
restart)
	restart
	;;
status)
	status -p $PIDFILE
	RETVAL=$?
	;;
*)
	echo $"Usage: $0 {start|stop|status|restart}"
	RETVAL=2
esac

exit $RETVAL
