#!/bin/bash

## Quickly check if all python files in PhysicsTools/PatAlgos are well formed

for py in $(find $CMSSW_BASE/src/PhysicsTools/PatAlgos -name '*.py' -type f); do
    pyn=$(echo $py | sed "s#$CMSSW_BASE/src/PhysicsTools/PatAlgos/##g")
    echo "Checking $pyn..."
    python $py && echo -ne "\e[F\e[M";
    done
