from .adapt_to_new_backend import *
dqmitems={}

def ecallayout(i, p, *rows): i[p] = rows

ecallayout(dqmitems, 'DataLayouts/Ecal/00 Number of Ecal RecHits',[{'path': 'EcalBarrel/EBOccupancyTask/EBOT number of filtered rec hits in event', 'description': 'Occupancy of rec hits with GOOD reconstruction flag and E > 0.5 GeV.'}],[{'path': 'EcalEndcap/EEOccupancyTask/EEOT number of filtered rec hits in event', 'description': 'Occupancy of rec hits with GOOD reconstruction flag and E > 0.5 GeV.'}])
ecallayout(dqmitems, 'DataLayouts/Ecal/01 Number of ES RecHits',[{'path': 'EcalPreshower/ESOccupancyTask/ES Num of RecHits Z 1 P 1'}, {'path': 'EcalPreshower/ESOccupancyTask/ES Num of RecHits Z -1 P 1'}],[{'path': 'EcalPreshower/ESOccupancyTask/ES Num of RecHits Z 1 P 2'}, {'path': 'EcalPreshower/ESOccupancyTask/ES Num of RecHits Z -1 P 2'}])
ecallayout(dqmitems, 'DataLayouts/Ecal/02 Ecal RecHit Occupancy EB',[{'path': 'EcalBarrel/EBOccupancyTask/EBOT rec hit thr occupancy', 'description': 'Occupancy for rec hits with GOOD reconstruction flag and E > 0.5 GeV.'}],[{'path': 'EcalBarrel/EBOccupancyTask/EBOT rec hit thr occupancy projection eta', 'description': 'Projection of the occupancy of rec hits with GOOD reconstruction flag and E > 0.5 GeV.'}, {'path': 'EcalBarrel/EBOccupancyTask/EBOT rec hit thr occupancy projection phi', 'description': 'Projection of the occupancy of rec hits with GOOD reconstruction flag and E > 0.5 GeV.'}])
ecallayout(dqmitems, 'DataLayouts/Ecal/03 Ecal RecHit Occupancy EE -',[{'path': 'EcalEndcap/EEOccupancyTask/EEOT rec hit thr occupancy EE -', 'description': 'Occupancy for rec hits with GOOD reconstruction flag and E > 0.5 GeV.'}],[{'path': 'EcalEndcap/EEOccupancyTask/EEOT rec hit thr occupancy EE - projection eta', 'description': 'Projection of the occupancy of rec hits with GOOD reconstruction flag and E > 0.5 GeV.'}, {'path': 'EcalEndcap/EEOccupancyTask/EEOT rec hit thr occupancy EE - projection phi', 'description': 'Projection of the occupancy of rec hits with GOOD reconstruction flag and E > 0.5 GeV.'}])
ecallayout(dqmitems, 'DataLayouts/Ecal/04 Ecal RecHit Occupancy EE +',[{'path': 'EcalEndcap/EEOccupancyTask/EEOT rec hit thr occupancy EE +', 'description': 'Occupancy for rec hits with GOOD reconstruction flag and E > 0.5 GeV.'}],[{'path': 'EcalEndcap/EEOccupancyTask/EEOT rec hit thr occupancy EE + projection eta', 'description': 'Projection of the occupancy of rec hits with GOOD reconstruction flag and E > 0.5 GeV.'}, {'path': 'EcalEndcap/EEOccupancyTask/EEOT rec hit thr occupancy EE + projection phi', 'description': 'Projection of the occupancy of rec hits with GOOD reconstruction flag and E > 0.5 GeV.'}])
ecallayout(dqmitems, 'DataLayouts/Ecal/05 Ecal Spectrum',[{'path': 'EcalBarrel/EBOccupancyTask/EBOT rec hit spectrum', 'description': 'Rec hit energy distribution.'}],[{'path': 'EcalEndcap/EEOccupancyTask/EEOT rec hit spectrum EE -', 'description': 'Rec hit energy distribution.'}, {'path': 'EcalEndcap/EEOccupancyTask/EEOT rec hit spectrum EE +', 'description': 'Rec hit energy distribution.'}])
ecallayout(dqmitems, 'DataLayouts/Ecal/06 ES Spectrum',[{'path': 'EcalPreshower/ESOccupancyTask/ES RecHit Energy Z 1 P 1'}, {'path': 'EcalPreshower/ESOccupancyTask/ES RecHit Energy Z -1 P 1'}],[{'path': 'EcalPreshower/ESOccupancyTask/ES RecHit Energy Z 1 P 2'}, {'path': 'EcalPreshower/ESOccupancyTask/ES RecHit Energy Z -1 P 2'}])
ecallayout(dqmitems, 'DataLayouts/Ecal/07 Ecal Max Energy',[{'path': 'EcalBarrel/EBRecoSummary/recHits_EB_energyMax'}],[{'path': 'EcalEndcap/EERecoSummary/recHits_EEP_energyMax'}, {'path': 'EcalEndcap/EERecoSummary/recHits_EEM_energyMax'}])
ecallayout(dqmitems, 'DataLayouts/Ecal/08 ES Max Energy',[{'path': 'EcalPreshower/ESRecoSummary/recHits_ES_energyMax'}])
ecallayout(dqmitems, 'DataLayouts/Ecal/09 Ecal Timing',[{'path': 'EcalBarrel/EBRecoSummary/recHits_EB_time'}],[{'path': 'EcalEndcap/EERecoSummary/recHits_EEP_time'}, {'path': 'EcalEndcap/EERecoSummary/recHits_EEM_time'}])
ecallayout(dqmitems, 'DataLayouts/Ecal/10 ES Timing',[{'path': 'EcalPreshower/ESRecoSummary/recHits_ES_time'}])
ecallayout(dqmitems, 'DataLayouts/Ecal/11 Ecal Chi2',[{'path': 'EcalBarrel/EBRecoSummary/recHits_EB_Chi2'}],[{'path': 'EcalEndcap/EERecoSummary/recHits_EEP_Chi2'}, {'path': 'EcalEndcap/EERecoSummary/recHits_EEM_Chi2'}])
ecallayout(dqmitems, 'DataLayouts/Ecal/12 EB SwissCross',[{'path': 'EcalBarrel/EBRecoSummary/recHits_EB_E1oE4'}])
ecallayout(dqmitems, 'DataLayouts/Ecal/13 RecHit Flags',[{'path': 'EcalBarrel/EBRecoSummary/recHits_EB_recoFlag'}],[{'path': 'EcalEndcap/EERecoSummary/recHits_EE_recoFlag'}])
ecallayout(dqmitems, 'DataLayouts/Ecal/14 ReducedRecHit Flags',[{'path': 'EcalBarrel/EBRecoSummary/redRecHits_EB_recoFlag'}],[{'path': 'EcalEndcap/EERecoSummary/redRecHits_EE_recoFlag'}])
ecallayout(dqmitems, 'DataLayouts/Ecal/15 Basic Cluster RecHit Flags',[{'path': 'EcalBarrel/EBRecoSummary/basicClusters_recHits_EB_recoFlag'}],[{'path': 'EcalEndcap/EERecoSummary/basicClusters_recHits_EE_recoFlag'}])
ecallayout(dqmitems, 'DataLayouts/Ecal/16 Number of Basic Clusters',[{'path': 'EcalBarrel/EBClusterTask/EBCLT BC number', 'description': 'Distribution of the number of basic clusters per event.'}],[{'path': 'EcalEndcap/EEClusterTask/EECLT BC number', 'description': 'Distribution of the number of basic clusters per event.'}])
ecallayout(dqmitems, 'DataLayouts/Ecal/17 Number of Super Clusters',[{'path': 'EcalBarrel/EBClusterTask/EBCLT SC number', 'description': 'Distribution of the number of super clusters per event in EB/EE.'}],[{'path': 'EcalEndcap/EEClusterTask/EECLT SC number', 'description': 'Distribution of the number of super clusters per event in EB/EE.'}])
ecallayout(dqmitems, 'DataLayouts/Ecal/18 Super Cluster Energy',[{'path': 'EcalBarrel/EBClusterTask/EBCLT SC energy', 'description': 'Super cluster energy distribution.'}],[{'path': 'EcalEndcap/EEClusterTask/EECLT SC energy', 'description': 'Super cluster energy distribution.'}])
ecallayout(dqmitems, 'DataLayouts/Ecal/19 Super Cluster Occupancy Eta',[{'path': 'EcalBarrel/EBRecoSummary/superClusters_EB_eta'}],[{'path': 'EcalEndcap/EERecoSummary/superClusters_EE_eta'}])
ecallayout(dqmitems, 'DataLayouts/Ecal/20 Super Cluster Occupancy Phi',[{'path': 'EcalBarrel/EBRecoSummary/superClusters_EB_phi'}],[{'path': 'EcalEndcap/EERecoSummary/superClusters_EE_phi'}])
ecallayout(dqmitems, 'DataLayouts/Ecal/21 Super Cluster Size (Crystals)',[{'path': 'EcalBarrel/EBClusterTask/EBCLT SC size (crystal)', 'description': 'Distribution of the super cluster size (number of crystals).'}],[{'path': 'EcalEndcap/EEClusterTask/EECLT SC size (crystal)', 'description': 'Distribution of the super cluster size (number of crystals).'}])
ecallayout(dqmitems, 'DataLayouts/Ecal/22 Super Cluster Size (Basic Clusters)',[{'path': 'EcalBarrel/EBClusterTask/EBCLT SC size', 'description': 'Distribution of the super cluster size (number of basic clusters)'}],[{'path': 'EcalEndcap/EEClusterTask/EECLT SC size', 'description': 'Distribution of the super cluster size (number of basic clusters)'}])
ecallayout(dqmitems, 'DataLayouts/Ecal/23 Super Cluster Seed SwissCross',[{'path': 'EcalBarrel/EBRecoSummary/superClusters_EB_E1oE4'}])
ecallayout(dqmitems, 'DataLayouts/Ecal/24 Preshower Planes Energy',[{'path': 'EcalPreshower/ESRecoSummary/esClusters_energy_plane1'}, {'path': 'EcalPreshower/ESRecoSummary/esClusters_energy_plane2'}],[{'path': 'EcalPreshower/ESRecoSummary/esClusters_energy_ratio'}])

apply_dqm_items_to_new_back_end(dqmitems, __file__)
