from .adapt_to_new_backend import *
dqmitems={}

def sistriplayout(i, p, *rows): i["SiStrip/Layouts/" + p] = rows

sistriplayout(dqmitems, "00 - SiStrip ReportSummary",
 [{ 'path': "SiStrip/MechanicalView/detFractionReportMap",
    'description': "Fraction of Good Detector Modules plotted in different parts of the Tracker - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no" }},
  { 'path': "SiStrip/MechanicalView/sToNReportMap",
    'description': "Accepted S/N Ratios in different parts of the Tracker. The values are 1 if the ratio is within the accepted range otherwise it is 0  - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes" }}],
 [{ 'path': "SiStrip/EventInfo/reportSummaryMap",
    'description': "Overall Report Summary where detector fraction and S/N flags are combined together -  <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no" }}])
sistriplayout(dqmitems, "01 - FED-Detected Errors Summary",
 [{ 'path': "SiStrip/ReadoutView/FED/nFEDErrors",
     'description': "# of FEDs with any FED level error per event - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a>", 'draw': { 'withref': "no" }}],
  [{ 'path': "SiStrip/ReadoutView/Fiber/nBadActiveChannelStatusBits",
      'description': "# of active channels with bad status bits per event - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a>", 'draw': { 'withref': "no" }}])
sistriplayout(dqmitems, "02 - FED-Detected Errors Trend",
 [{ 'path': "SiStrip/ReadoutView/Trends/nTotalBadActiveChannelsvsTime",
     'description': "Number of Connected FED Channels with detected tickmark, with APV/Link errors vs Time - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no" }},
  { 'path': "SiStrip/ReadoutView/Trends/nTotalBadChannelsvsTime",
      'description': "Number of connected FED Channels with APV/Link Errors vs time - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no" }},
  { 'path': "SiStrip/ReadoutView/Trends/FED/nFEDErrorsvsTime",
      'description': "Number FEDs having any FED or Front-End-Unit Error vs Time - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no" }}],
 [{ 'path': "SiStrip/ReadoutView/Trends/Fiber/nUnlockedvsTime",
     'description': "Number of connected channels per event being without a detected tickmark vs Time - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no" }},
  { 'path': "SiStrip/ReadoutView/Trends/Fiber/nOutOfSyncvsTime",
      'description': "Number of connected channels per event being out-of-sync vs Time - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no" }},
  { 'path': "SiStrip/ReadoutView/Trends/APV/nAPVAddressErrorvsTime",
      'description': "Number of connected APVs per event having wrong pipeline address tickmark vs Time - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no" }}])
sistriplayout(dqmitems, "03 - # of Digi Trend",
  [{ 'path': "SiStrip/MechanicalView/TIB/TotalNumberOfDigiProfile__TIB",
      'description': "Total # of Digis in TIB with event time in Seconds - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no" }},
   { 'path': "SiStrip/MechanicalView/TOB/TotalNumberOfDigiProfile__TOB",
       'description': "Total # of Digis in TOB with event time in Seconds  - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no" }}],
  [{ 'path': "SiStrip/MechanicalView/TID/MINUS/TotalNumberOfDigiProfile__TID__MINUS",
      'description': "Total # of Digis in TID -ve side with event time in Seconds  - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no" }},
   { 'path': "SiStrip/MechanicalView/TID/PLUS/TotalNumberOfDigiProfile__TID__PLUS",
       'description': "Total # of Digis in TID +ve side with event time in Seconds  - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no" }}],
  [{  'path':"SiStrip/MechanicalView/TEC/MINUS/TotalNumberOfDigiProfile__TEC__MINUS",
      'description': "Total # of Digis in TEC -ve side with event time in Seconds   - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no" }},
   {  'path':"SiStrip/MechanicalView/TEC/PLUS/TotalNumberOfDigiProfile__TEC__PLUS",
       'description': "Total # of Digis in TEC +ve side with event time in Seconds   - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no" }}])
sistriplayout(dqmitems, "04 - # of Cluster Trend",
  [{ 'path': "SiStrip/MechanicalView/TIB/TotalNumberOfClusterProfile__TIB",
      'description': "Total # of Clusters in TIB with event time in Seconds  - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no" }},
   { 'path': "SiStrip/MechanicalView/TOB/TotalNumberOfClusterProfile__TOB",
       'description': "Total # of Clusters in TOB with event time in Seconds  - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no" }}],
  [{ 'path': "SiStrip/MechanicalView/TID/MINUS/TotalNumberOfClusterProfile__TID__MINUS",
      'description': "Total # of Clusters in TID -ve side with event time in Seconds  - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no" }},
   { 'path': "SiStrip/MechanicalView/TID/PLUS/TotalNumberOfClusterProfile__TID__PLUS",
       'description': "Total # of Clusters in TID +ve side with event time in Seconds  - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no" }}],
  [{  'path':"SiStrip/MechanicalView/TEC/MINUS/TotalNumberOfClusterProfile__TEC__MINUS",
      'description': "Total # of Clusters in TEC -ve side with event time in Seconds  - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no" }},
   {  'path':"SiStrip/MechanicalView/TEC/PLUS/TotalNumberOfClusterProfile__TEC__PLUS",
       'description': "Total # of Clusters in TEC +ve side with event time in Seconds  - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no" }}])
sistriplayout(dqmitems, "05 - OnTrackCluster (StoN)",
  [{ 'path': "SiStrip/MechanicalView/TIB/Summary_ClusterStoNCorr_OnTrack__TIB",
     'description': "Signal-to-Noise (corrected for the angle) for On-Track clusters in TIB  - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes" }},
   { 'path': "SiStrip/MechanicalView/TOB/Summary_ClusterStoNCorr_OnTrack__TOB",
     'description': "Signal-to-Noise (corrected for the angle) for On-Track clusters in TOB  - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes" }}],
  [{ 'path': "SiStrip/MechanicalView/TID/MINUS/Summary_ClusterStoNCorr_OnTrack__TID__MINUS",
     'description': "Signal-to-Noise (corrected for the angle) for On-Track clusters in TID -ve side  - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes" }},
   { 'path': "SiStrip/MechanicalView/TID/PLUS/Summary_ClusterStoNCorr_OnTrack__TID__PLUS",
     'description': "Signal-to-Noise (corrected for the angle) for On-Track clusters in TID +ve side  - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes" }}],
  [{ 'path':"SiStrip/MechanicalView/TEC/MINUS/Summary_ClusterStoNCorr_OnTrack__TEC__MINUS",
     'description': "Signal-to-Noise (corrected for the angle) for On-Track clusters in TEC -ve side - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes" }},
   { 'path':"SiStrip/MechanicalView/TEC/PLUS/Summary_ClusterStoNCorr_OnTrack__TEC__PLUS",
     'description': "Signal-to-Noise (corrected for the angle) for On-Track clusters in TEC +ve side - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes" }}])
sistriplayout(dqmitems, "06 - OffTrackCluster (Total Number)",
  [{ 'path': "SiStrip/MechanicalView/TIB/Summary_TotalNumberOfClusters_OffTrack__TIB",
     'description': "Total Number of Off-Track clusters in TIB  - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no" }},
   { 'path': "SiStrip/MechanicalView/TOB/Summary_TotalNumberOfClusters_OffTrack__TOB",
     'description': "Total Number of Off-Track clusters in TOB  - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no" }}],
  [{ 'path': "SiStrip/MechanicalView/TID/MINUS/Summary_TotalNumberOfClusters_OffTrack__TID__MINUS",
     'description': "Total Number of Off-Track clusters in TID -ve side - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no" }},
   { 'path': "SiStrip/MechanicalView/TID/PLUS/Summary_TotalNumberOfClusters_OffTrack__TID__PLUS",
     'description': "Total Number of Off-Track clusters in TID +ve side - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no" }}],
  [{ 'path':"SiStrip/MechanicalView/TEC/MINUS/Summary_TotalNumberOfClusters_OffTrack__TEC__MINUS",
     'description': "TotalNumberOf Off-Track clusters in TEC -ve side - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no" }},
   { 'path':"SiStrip/MechanicalView/TEC/PLUS/Summary_TotalNumberOfClusters_OffTrack__TEC__PLUS",
     'description': "TotalNumberOf Off-Track clusters in TEC +ve side - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no" }}])
sistriplayout(dqmitems, "07 - Tracking ReportSummary",
 [{ 'path': "Tracking/EventInfo/reportSummaryMap",
    'description': " Quality Test results plotted for Tracking parameters : Chi2, TrackRate, #of Hits in Track - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no" }}])
sistriplayout(dqmitems, "08 - Tracks (pp collisions)",
              [{ 'path': "Tracking/TrackParameters/GeneralProperties/NumberOfTracks_GenTk",
                 'description': "Number of Reconstructed Tracks with high purity selection and pt > 1 GeV - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes" }},
               { 'path': "Tracking/TrackParameters/HitProperties/NumberOfRecHitsPerTrack_GenTk",
                 'description': "Number of RecHits per Track with high purity selection and pt > 1 GeV  - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes" }},
               { 'path': "Tracking/TrackParameters/GeneralProperties/TrackPt_ImpactPoint_GenTk",
                 'description': "Pt of Reconstructed Track with high purity selection and pt > 1 GeV  - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes" }}],
              [{ 'path': "Tracking/TrackParameters/GeneralProperties/Chi2oNDF_GenTk",
                 'description': "Chi Square per DoF with high purity selection and pt > 1 GeV  -  <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes" }},
               { 'path': "Tracking/TrackParameters/GeneralProperties/TrackPhi_ImpactPoint_GenTk",
                  'description': "Phi distribution of Reconstructed Tracks with high purity selection and pt > 1 GeV -  <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes" }},
               { 'path': "Tracking/TrackParameters/GeneralProperties/TrackEta_ImpactPoint_GenTk",
                  'description': " Eta distribution of Reconstructed Tracks with high purity selection and pt > 1 GeV - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes" }}])
sistriplayout(dqmitems, "09 - Tracks (Cosmic Tracking)",
 [{ 'path': "Tracking/TrackParameters/GeneralProperties/NumberOfTracks_CKFTk",
    'description': "Number of Reconstructed Tracks  - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes" }},
  { 'path': "Tracking/TrackParameters/HitProperties/NumberOfRecHitsPerTrack_CKFTk",
    'description': "Number of RecHits per Track  - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes" }},
  { 'path': "Tracking/TrackParameters/GeneralProperties/TrackPt_CKFTk",
    'description': "Pt of Reconstructed Tracks  - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes" }}],
 [{ 'path': "Tracking/TrackParameters/GeneralProperties/Chi2oNDF_CKFTk",
    'description': "Chi Square per DoF  -  <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes" }},
  { 'path': "Tracking/TrackParameters/GeneralProperties/TrackPhi_CKFTk",
    'description': "Phi distribution of Reconstructed Tracks  -  <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes" }},
  { 'path': "Tracking/TrackParameters/GeneralProperties/TrackEta_CKFTk",
    'description': " Eta distribution of Reconstructed Tracks - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes" }}])
sistriplayout(dqmitems, "10 - Tracks (HI run)",
 [{ 'path': "Tracking/TrackParameters/GeneralProperties/NumberOfTracks_HeavyIonTk",
    'description': "Number of Reconstructed Tracks  - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes" }},
  { 'path': "Tracking/TrackParameters/HitProperties/NumberOfRecHitsPerTrack_HeavyIonTk",
    'description': "Number of RecHits per Track  - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes" }},
  { 'path': "Tracking/TrackParameters/GeneralProperties/TrackPt_ImpactPoint_HeavyIonTk",
    'description': "Pt of Reconstructed Tracks  - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes" }}],
 [{ 'path': "Tracking/TrackParameters/GeneralProperties/Chi2oNDF_HeavyIonTk",
    'description': "Chi Square per DoF  -  <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes" }},
  { 'path': "Tracking/TrackParameters/GeneralProperties/TrackPhi_ImpactPoint_HeavyIonTk",
    'description': "Phi distribution of Reconstructed Tracks  -  <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes" }},
  { 'path': "Tracking/TrackParameters/GeneralProperties/TrackEta_ImpactPoint_HeavyIonTk",
    'description': " Eta distribution of Reconstructed Tracks - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes" }}])
sistriplayout(dqmitems, "11a - FED Errors vs FED ID",
 [{ 'path': "SiStrip/ReadoutView/FEDErrorsVsId",
    'description': "Type of FED errors vs FED ID",
    'draw': {'withref': "no" }}])
sistriplayout(dqmitems, "11b - Detailed FED-Detected Errors",
 [{ 'path': "SiStrip/ReadoutView/Fiber/VsId/BadActiveChannelStatusBits",
     'description': "FED IDs having connected channels, with a detected tickmark, with APV/Link errors - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no" }},
  { 'path': "SiStrip/ReadoutView/Fiber/VsId/BadChannelStatusBits",
      'description': "FED IDs having connected channels with APV/Link Errors - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no" }},
  { 'path': "SiStrip/ReadoutView/FED/VsId/AnyFEDErrors",
      'description': "FED IDs having any FED level error - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no" }},
  { 'path': "SiStrip/ReadoutView/FED/VsId/AnyDAQProblems",
      'description': "FED IDs having DAQ problem - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no" }}],
 [{ 'path': "SiStrip/ReadoutView/FED/VsId/CorruptBuffers",
     'description': "FED IDs having corrupt FED buffers - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no" }},
  { 'path': "SiStrip/ReadoutView/FE/VsId/AnyFEProblems",
      'description': "FED IDs having overflowed, missing or with bad majority address FE units - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no" }},
  { 'path': "SiStrip/ReadoutView/FE/VsId/FEOverflows",
      'description': "FED IDs having overflowed FE units - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no" }},
  { 'path': "SiStrip/ReadoutView/FE/VsId/FEMissing",
      'description': "FED IDs having missing FE units - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no" }},
  { 'path': "SiStrip/ReadoutView/FED/VsId/DataMissing",
      'description': "FED IDs having missing data but connected channels - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no" }}])
sistriplayout(dqmitems, "12 - OnTrackClusters(Total Number)",
  [{ 'path': "SiStrip/MechanicalView/TIB/Summary_TotalNumberOfClusters_OnTrack__TIB",
     'description': "Total Number of On-Track clusters in TIB  - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes" }},
   { 'path': "SiStrip/MechanicalView/TOB/Summary_TotalNumberOfClusters_OnTrack__TOB",
     'description': "Total Number of On-Track clusters in TOB  - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes" }}],
  [{ 'path': "SiStrip/MechanicalView/TID/MINUS/Summary_TotalNumberOfClusters_OnTrack__TID__MINUS",
     'description': "Total Number of On-Track clusters in TID -ve side - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes" }},
   { 'path': "SiStrip/MechanicalView/TID/PLUS/Summary_TotalNumberOfClusters_OnTrack__TID__PLUS",
     'description': "Total Number of On-Track clusters in TID +ve side - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes" }}],
  [{ 'path':"SiStrip/MechanicalView/TEC/MINUS/Summary_TotalNumberOfClusters_OnTrack__TEC__MINUS",
     'description': "TotalNumberOf On-Track clusters in TEC -ve side - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes" }},
   { 'path':"SiStrip/MechanicalView/TEC/PLUS/Summary_TotalNumberOfClusters_OnTrack__TEC__PLUS",
     'description': "TotalNumberOf On-Track clusters in TEC +ve side - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes" }}])
sistriplayout(dqmitems, "13 - OffTrackCluster (Charge)",
  [{ 'path': "SiStrip/MechanicalView/TIB/Summary_ClusterCharge_OffTrack__TIB",
     'description': "Charge for Off-Track clusters in TIB - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no"}},
   { 'path': "SiStrip/MechanicalView/TOB/Summary_ClusterCharge_OffTrack__TOB",
     'description': "Charge for Off-Track clusters in TOB - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no"}}],
  [{ 'path': "SiStrip/MechanicalView/TID/MINUS/Summary_ClusterCharge_OffTrack__TID__MINUS",
     'description': "Charge for Off-Track clusters in TID -ve side - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no"}},
   { 'path': "SiStrip/MechanicalView/TID/PLUS/Summary_ClusterCharge_OffTrack__TID__PLUS",
     'description': "Charge for Off-Track clusters in TID +ve side - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no"}}],
  [{ 'path':"SiStrip/MechanicalView/TEC/MINUS/Summary_ClusterCharge_OffTrack__TEC__MINUS",
     'description': "Charge for Off-Track clusters in TEC -ve - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no"}},
   { 'path':"SiStrip/MechanicalView/TEC/PLUS/Summary_ClusterCharge_OffTrack__TEC__PLUS",
     'description': "Charge for Off-Track clusters in TEC +ve - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "no"}}])
sistriplayout(dqmitems, "14 - TIB Summary",
  [{ 'path': "SiStrip/MechanicalView/TIB/Summary_MeanNumberOfDigis__TIB",
      'description': "Number of Digis from all TIB modules - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TIB/Summary_MeanNumberOfClusters__TIB",
       'description': "Number of Clusters from all TIB modules - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}},
  { 'path': "SiStrip/MechanicalView/TIB/Summary_MeanClusterWidth__TIB",
      'description': "Cluster width from all TIB modules - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}}],
  [{ 'path': "SiStrip/MechanicalView/TIB/layer_1/Summary_ClusterStoNCorr__OnTrack__TIB__layer__1",
      'description': "Corrected S/N ratio for TIB Layer #1 - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TIB/layer_2/Summary_ClusterStoNCorr__OnTrack__TIB__layer__2",
       'description': "Corrected S/N ratio for TIB Layer #2 - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TIB/layer_3/Summary_ClusterStoNCorr__OnTrack__TIB__layer__3",
       'description': "Corrected S/N ratio for TIB Layer #3 - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TIB/layer_4/Summary_ClusterStoNCorr__OnTrack__TIB__layer__4",
       'description': "Corrected S/N ratio for TIB Layer #4 - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}}])
sistriplayout(dqmitems, "15 - TID+ Summary",
  [{ 'path': "SiStrip/MechanicalView/TID/PLUS/Summary_MeanNumberOfDigis__PLUS",
      'description': "Number of Digis from all TID+ modules - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TID/PLUS/Summary_MeanNumberOfClusters__PLUS",
       'description': "Number of Clusters from all TID+ modules - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TID/PLUS/Summary_MeanClusterWidth__PLUS",
       'description': "Cluster width from all TID+ modules - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}}],
  [{ 'path': "SiStrip/MechanicalView/TID/PLUS/wheel_1/Summary_ClusterStoNCorr__OnTrack__TID__PLUS__wheel__1",
      'description': "Corrected S/N ratio for TID+ Wheel #1 - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TID/PLUS/wheel_2/Summary_ClusterStoNCorr__OnTrack__TID__PLUS__wheel__2",
       'description': "Corrected S/N ratio for TID+ Wheel #2 - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TID/PLUS/wheel_3/Summary_ClusterStoNCorr__OnTrack__TID__PLUS__wheel__3",
       'description': "Corrected S/N ratio for TID+ Wheel #3 - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}}])
sistriplayout(dqmitems, "16 - TID- Summary",
  [{ 'path': "SiStrip/MechanicalView/TID/MINUS/Summary_MeanNumberOfDigis__MINUS",
      'description': "Number of Digis from all TID- modules - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TID/MINUS/Summary_MeanNumberOfClusters__MINUS",
       'description': "Number of Clusters from all TID- modules - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TID/MINUS/Summary_MeanClusterWidth__MINUS",
       'description': "Cluster width from all TID- modules - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}}],
  [{ 'path': "SiStrip/MechanicalView/TID/MINUS/wheel_1/Summary_ClusterStoNCorr__OnTrack__TID__MINUS__wheel__1",
      'description': "Corrected S/N ratio for TID- Wheel #1 - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TID/MINUS/wheel_2/Summary_ClusterStoNCorr__OnTrack__TID__MINUS__wheel__2",
       'description': "Corrected S/N ratio for TID- Wheel #2 - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TID/MINUS/wheel_3/Summary_ClusterStoNCorr__OnTrack__TID__MINUS__wheel__3",
       'description': "Corrected S/N ratio for TID- Wheel #3 - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}}])
sistriplayout(dqmitems, "17 - TOB Summary",
  [{ 'path': "SiStrip/MechanicalView/TOB/Summary_MeanNumberOfDigis__TOB",
      'description': "Number of Digis from all TOB modules - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TOB/Summary_MeanNumberOfClusters__TOB",
       'description': "Number of Clusters from all TOB modules - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}},
  { 'path': "SiStrip/MechanicalView/TOB/Summary_MeanClusterWidth__TOB",
      'description': "Cluster width from all TOB modules - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}}],
  [{ 'path': "SiStrip/MechanicalView/TOB/layer_1/Summary_ClusterStoNCorr__OnTrack__TOB__layer__1",
      'description': "Corrected S/N ratio for TIB Layer #1 - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TOB/layer_2/Summary_ClusterStoNCorr__OnTrack__TOB__layer__2",
       'description': "Corrected S/N ratio for TIB Layer #2 - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TOB/layer_3/Summary_ClusterStoNCorr__OnTrack__TOB__layer__3",
       'description': "Corrected S/N ratio for TIB Layer #3 - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}}],
  [{ 'path': "SiStrip/MechanicalView/TOB/layer_4/Summary_ClusterStoNCorr__OnTrack__TOB__layer__4",
      'description': "Corrected S/N ratio for TIB Layer #4 - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TOB/layer_5/Summary_ClusterStoNCorr__OnTrack__TOB__layer__5",
       'description': "Corrected S/N ratio for TIB Layer #1 - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TOB/layer_6/Summary_ClusterStoNCorr__OnTrack__TOB__layer__6",
       'description': "Corrected S/N ratio for TIB Layer #2 - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}}])
sistriplayout(dqmitems, "18 - TEC+ Summary",
  [{ 'path': "SiStrip/MechanicalView/TEC/PLUS/Summary_MeanNumberOfDigis__PLUS",
      'description': "Number of Digis from all TEC+ modules - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TEC/PLUS/Summary_MeanNumberOfClusters__PLUS",
       'description': "Number of Clusters from all TEC+ modules - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TEC/PLUS/Summary_MeanClusterWidth__PLUS",
       'description': "Cluster Width from all TEC+ modules - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TEC/PLUS/wheel_1/Summary_ClusterStoNCorr__OnTrack__TEC__PLUS__wheel__1",
       'description': "Corrected S/N ratio for TEC+ Wheel #1 - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}}],
  [{ 'path': "SiStrip/MechanicalView/TEC/PLUS/wheel_2/Summary_ClusterStoNCorr__OnTrack__TEC__PLUS__wheel__2",
      'description': "Corrected S/N ratio for TEC+ Wheel #2 - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TEC/PLUS/wheel_3/Summary_ClusterStoNCorr__OnTrack__TEC__PLUS__wheel__3",
       'description': "Corrected S/N ratio for TEC+ Wheel #3 - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TEC/PLUS/wheel_4/Summary_ClusterStoNCorr__OnTrack__TEC__PLUS__wheel__4",
       'description': "Corrected S/N ratio for TEC+ Wheel #4 - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TEC/PLUS/wheel_5/Summary_ClusterStoNCorr__OnTrack__TEC__PLUS__wheel__5",
       'description': "Corrected S/N ratio for TEC+ Wheel #5 - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}}],
  [{ 'path': "SiStrip/MechanicalView/TEC/PLUS/wheel_6/Summary_ClusterStoNCorr__OnTrack__TEC__PLUS__wheel__6",
      'description': "Corrected S/N ratio for TEC+ Wheel #6 - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TEC/PLUS/wheel_7/Summary_ClusterStoNCorr__OnTrack__TEC__PLUS__wheel__7",
       'description': "Corrected S/N ratio for TEC+ Wheel #7 - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TEC/PLUS/wheel_8/Summary_ClusterStoNCorr__OnTrack__TEC__PLUS__wheel__8",
       'description': "Corrected S/N ratio for TEC+ Wheel #8 - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TEC/PLUS/wheel_9/Summary_ClusterStoNCorr__OnTrack__TEC__PLUS__wheel__9",
       'description': "Corrected S/N ratio for TEC+ Wheel #9 - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}}])
sistriplayout(dqmitems, "19 - TEC- Summary",
  [{ 'path': "SiStrip/MechanicalView/TEC/MINUS/Summary_MeanNumberOfDigis__MINUS",
      'description': "Number of Digis from all TEC- modules - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TEC/MINUS/Summary_MeanNumberOfClusters__MINUS",
       'description': "Number of Clusters from all TEC- modules - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TEC/MINUS/Summary_MeanClusterWidth__MINUS",
       'description': "Cluster width from all TEC- modules - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TEC/MINUS/wheel_1/Summary_ClusterStoNCorr__OnTrack__TEC__MINUS__wheel__1",
       'description': "Corrected S/N ratio for TEC- Wheel #1 - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}}],
  [{ 'path': "SiStrip/MechanicalView/TEC/MINUS/wheel_2/Summary_ClusterStoNCorr__OnTrack__TEC__MINUS__wheel__2",
      'description': "Corrected S/N ratio for TEC- Wheel #2 - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TEC/MINUS/wheel_3/Summary_ClusterStoNCorr__OnTrack__TEC__MINUS__wheel__3",
       'description': "Corrected S/N ratio for TEC- Wheel #3 - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TEC/MINUS/wheel_4/Summary_ClusterStoNCorr__OnTrack__TEC__MINUS__wheel__4",
       'description': "Corrected S/N ratio for TEC- Wheel #4 - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TEC/MINUS/wheel_5/Summary_ClusterStoNCorr__OnTrack__TEC__MINUS__wheel__5",
       'description': "Corrected S/N ratio for TEC- Wheel #5 - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}}],
  [{ 'path': "SiStrip/MechanicalView/TEC/MINUS/wheel_6/Summary_ClusterStoNCorr__OnTrack__TEC__MINUS__wheel__6",
      'description': "Corrected S/N ratio for TEC- Wheel #6 - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TEC/MINUS/wheel_7/Summary_ClusterStoNCorr__OnTrack__TEC__MINUS__wheel__7",
       'description': "Corrected S/N ratio for TEC- Wheel #7 - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TEC/MINUS/wheel_8/Summary_ClusterStoNCorr__OnTrack__TEC__MINUS__wheel__8",
       'description': "Corrected S/N ratio for TEC- Wheel #8 - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TEC/MINUS/wheel_9/Summary_ClusterStoNCorr__OnTrack__TEC__MINUS__wheel__9",
       'description': "Corrected S/N ratio for TEC- Wheel #9 - <a href=https://twiki.cern.ch/twiki/bin/view/CMS/SiStripOnlineDQMInstructions>SiStripOnlineDQMInstructions</a> ", 'draw': { 'withref': "yes"}}])
sistriplayout(dqmitems, "20 - TIB Cluster TkHMap",
  [{ 'path': "SiStrip/MechanicalView/TIB/layer_1/TkHMap_NumberOfOnTrackCluster_TIB_L1",
     'description': "Cluster TkHistoMap  in TIB Layer #1"},
   { 'path': "SiStrip/MechanicalView/TIB/layer_2/TkHMap_NumberOfOnTrackCluster_TIB_L2",
     'description': "Cluster TkHistoMap  in TIB Layer #2"}],
  [{ 'path': "SiStrip/MechanicalView/TIB/layer_3/TkHMap_NumberOfOnTrackCluster_TIB_L3",
     'description': "Cluster TkHistoMap  in TIB Layer #3"},
   { 'path': "SiStrip/MechanicalView/TIB/layer_4/TkHMap_NumberOfOnTrackCluster_TIB_L4",
     'description': "Cluster TkHistoMap  in TIB Layer #4"}])
sistriplayout(dqmitems, "21 - TOB Cluster TkHMap",
  [{ 'path': "SiStrip/MechanicalView/TOB/layer_1/TkHMap_NumberOfOnTrackCluster_TOB_L1",
     'description': "Cluster TkHistoMap  in TOB Layer #1"},
   { 'path': "SiStrip/MechanicalView/TOB/layer_2/TkHMap_NumberOfOnTrackCluster_TOB_L2",
     'description': "Cluster TkHistoMap  in TOB Layer #2"},
   { 'path': "SiStrip/MechanicalView/TOB/layer_3/TkHMap_NumberOfOnTrackCluster_TOB_L3",
     'description': "Cluster TkHistoMap  in TOB Layer #3"}],
  [{ 'path': "SiStrip/MechanicalView/TOB/layer_4/TkHMap_NumberOfOnTrackCluster_TOB_L4",
     'description': "Cluster TkHistoMap  in TOB Layer #4"},
   { 'path': "SiStrip/MechanicalView/TOB/layer_5/TkHMap_NumberOfOnTrackCluster_TOB_L5",
     'description': "Cluster TkHistoMap  in TOB Layer #5"},
   { 'path': "SiStrip/MechanicalView/TOB/layer_6/TkHMap_NumberOfOnTrackCluster_TOB_L6",
     'description': "Cluster TkHistoMap  in TOB Layer #6"}])
sistriplayout(dqmitems, "22 - TID+ Cluster TkHMap",
  [{ 'path': "SiStrip/MechanicalView/TID/PLUS/wheel_1/TkHMap_NumberOfOnTrackCluster_TIDP_D1",
     'description': "Cluster TkHistoMap s in TID+ Wheel #1"},
   { 'path': "SiStrip/MechanicalView/TID/PLUS/wheel_2/TkHMap_NumberOfOnTrackCluster_TIDP_D2",
     'description': "Cluster TkHistoMap s in TID+ Wheel #2"},
   { 'path': "SiStrip/MechanicalView/TID/PLUS/wheel_3/TkHMap_NumberOfOnTrackCluster_TIDP_D3",
     'description': "Cluster TkHistoMap s in TID+ Wheel #3 "}])
sistriplayout(dqmitems, "23 - TID- Cluster TkHMap",
  [{ 'path': "SiStrip/MechanicalView/TID/MINUS/wheel_1/TkHMap_NumberOfOnTrackCluster_TIDM_D1",
     'description': "Cluster TkHistoMap s in TID- Wheel #1"},
   { 'path': "SiStrip/MechanicalView/TID/MINUS/wheel_2/TkHMap_NumberOfOnTrackCluster_TIDM_D2",
     'description': "Cluster TkHistoMap s in TID- Wheel #2"},
   { 'path': "SiStrip/MechanicalView/TID/MINUS/wheel_3/TkHMap_NumberOfOnTrackCluster_TIDM_D3",
     'description': "Cluster TkHistoMap s in TID- Wheel #3 "}])
sistriplayout(dqmitems, "24 - TEC+ Cluster TkHMap",
  [{ 'path': "SiStrip/MechanicalView/TEC/PLUS/wheel_1/TkHMap_NumberOfOnTrackCluster_TECP_W1",
     'description': "Cluster TkHistoMap  in TEC+ Wheel #1"},
   { 'path': "SiStrip/MechanicalView/TEC/PLUS/wheel_2/TkHMap_NumberOfOnTrackCluster_TECP_W2",
     'description': "Cluster TkHistoMap  in TEC+ Wheel #2"},
   { 'path': "SiStrip/MechanicalView/TEC/PLUS/wheel_3/TkHMap_NumberOfOnTrackCluster_TECP_W3",
     'description': "Cluster TkHistoMap  in TEC+ Wheel #3"}],
  [{ 'path': "SiStrip/MechanicalView/TEC/PLUS/wheel_4/TkHMap_NumberOfOnTrackCluster_TECP_W4",
     'description': "Cluster TkHistoMap  in TEC+ Wheel #4"},
   { 'path': "SiStrip/MechanicalView/TEC/PLUS/wheel_5/TkHMap_NumberOfOnTrackCluster_TECP_W5",
     'description': "Cluster TkHistoMap  in TEC+ Wheel #5"},
   { 'path': "SiStrip/MechanicalView/TEC/PLUS/wheel_6/TkHMap_NumberOfOnTrackCluster_TECP_W6",
     'description': "Cluster TkHistoMap  in TEC+ Wheel #6"}],
  [{ 'path': "SiStrip/MechanicalView/TEC/PLUS/wheel_7/TkHMap_NumberOfOnTrackCluster_TECP_W7",
     'description': "Cluster TkHistoMap  in TEC+ Wheel #7"},
   { 'path': "SiStrip/MechanicalView/TEC/PLUS/wheel_8/TkHMap_NumberOfOnTrackCluster_TECP_W8",
     'description': "Cluster TkHistoMap  in TEC+ Wheel #8"},
   { 'path': "SiStrip/MechanicalView/TEC/PLUS/wheel_9/TkHMap_NumberOfOnTrackCluster_TECP_W9",
     'description': "Cluster TkHistoMap  in TEC+ Wheel #9"}])
sistriplayout(dqmitems, "25 - TEC- Cluster TkHMap",
  [{ 'path': "SiStrip/MechanicalView/TEC/MINUS/wheel_1/TkHMap_NumberOfOnTrackCluster_TECM_W1",
     'description': "Cluster TkHistoMap  in TEC- Wheel #1"},
   { 'path': "SiStrip/MechanicalView/TEC/MINUS/wheel_2/TkHMap_NumberOfOnTrackCluster_TECM_W2",
     'description': "Cluster TkHistoMap  in TEC- Wheel #2"},
   { 'path': "SiStrip/MechanicalView/TEC/MINUS/wheel_3/TkHMap_NumberOfOnTrackCluster_TECM_W3",
     'description': "Cluster TkHistoMap  in TEC- Wheel #3"}],
  [{ 'path': "SiStrip/MechanicalView/TEC/MINUS/wheel_4/TkHMap_NumberOfOnTrackCluster_TECM_W4",
     'description': "Cluster TkHistoMap  in TEC- Wheel #4"},
   { 'path': "SiStrip/MechanicalView/TEC/MINUS/wheel_5/TkHMap_NumberOfOnTrackCluster_TECM_W5",
     'description': "Cluster TkHistoMap  in TEC- Wheel #5"},
   { 'path': "SiStrip/MechanicalView/TEC/MINUS/wheel_6/TkHMap_NumberOfOnTrackCluster_TECM_W6",
     'description': "Cluster TkHistoMap  in TEC- Wheel #6"}],
  [{ 'path': "SiStrip/MechanicalView/TEC/MINUS/wheel_7/TkHMap_NumberOfOnTrackCluster_TECM_W7",
     'description': "Cluster TkHistoMap  in TEC- Wheel #7"},
   { 'path': "SiStrip/MechanicalView/TEC/MINUS/wheel_8/TkHMap_NumberOfOnTrackCluster_TECM_W8",
     'description': "Cluster TkHistoMap  in TEC- Wheel #8"},
   { 'path': "SiStrip/MechanicalView/TEC/MINUS/wheel_9/TkHMap_NumberOfOnTrackCluster_TECM_W9",
     'description': "Cluster TkHistoMap  in TEC- Wheel #9"}])
sistriplayout(dqmitems, "26 - APVe Timing",
  [{ 'path': "SiStrip/ReadoutView/FE/APVe/FETimeDiffTECB",
      'description': "Timing difference FE - TEC-", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/ReadoutView/FE/APVe/FETimeDiffTECF",
       'description': "Timing difference FE - TEC+", 'draw': { 'withref': "yes"}}],
  [{ 'path': "SiStrip/ReadoutView/FE/APVe/FETimeDiffTIB",
      'description': "Timing difference FE - TIB", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/ReadoutView/FE/APVe/FETimeDiffTOB",
       'description': "Timing difference FE - TOB", 'draw': { 'withref': "yes"}}])
sistriplayout(dqmitems, "27 - TIB Residuals",
  [{ 'path': "SiStrip/MechanicalView/TIB/layer_1/HitResiduals_TIB__Layer__1",
      'description': "Hit Residual in TIB Layer #1", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TIB/layer_2/HitResiduals_TIB__Layer__2",
       'description': "Hit Residual in TIB Layer #2", 'draw': { 'withref': "yes"}}],
  [{ 'path': "SiStrip/MechanicalView/TIB/layer_3/HitResiduals_TIB__Layer__3",
      'description': "Hit Residual in TIB Layer #3", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TIB/layer_4/HitResiduals_TIB__Layer__4",
       'description': "Hit Residual in TIB Layer #4", 'draw': { 'withref': "yes"}}])
sistriplayout(dqmitems, "28 - TOB Residuals",
  [{ 'path': "SiStrip/MechanicalView/TOB/layer_1/HitResiduals_TOB__Layer__1",
      'description': "Hit Residual in TOB Layer #1", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TOB/layer_2/HitResiduals_TOB__Layer__2",
       'description': "Hit Residual in TOB Layer #2", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TOB/layer_3/HitResiduals_TOB__Layer__3",
       'description': "Hit Residual in TOB Layer #3", 'draw': { 'withref': "yes"}}],
  [{ 'path': "SiStrip/MechanicalView/TOB/layer_4/HitResiduals_TOB__Layer__4",
      'description': "Hit Residual in TOB Layer #4", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TOB/layer_5/HitResiduals_TOB__Layer__5",
       'description': "Hit Residual in TOB Layer #5", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TOB/layer_6/HitResiduals_TOB__Layer__6",
       'description': "Hit Residual in TOB Layer #6", 'draw': { 'withref': "yes"}}])
sistriplayout(dqmitems, "29 - TID+ Residuals",
  [{ 'path': "SiStrip/MechanicalView/TID/PLUS/wheel_1/HitResiduals_TID__wheel__1",
      'description': "Hit Residuals in TID+ Wheel #1", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TID/PLUS/wheel_2/HitResiduals_TID__wheel__2",
       'description': "Hit Residuals in TID+ Wheel #2", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TID/PLUS/wheel_3/HitResiduals_TID__wheel__3",
       'description': "Hit Residuals in TID+ Wheel #3 ", 'draw': { 'withref': "yes"}}])
sistriplayout(dqmitems, "30 - TID- Residuals",
  [{ 'path': "SiStrip/MechanicalView/TID/MINUS/wheel_1/HitResiduals_TID__wheel__1",
      'description': "Hit Residuals in TID- Wheel #1", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TID/MINUS/wheel_2/HitResiduals_TID__wheel__2",
       'description': "Hit Residuals in TID- Wheel #2", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TID/MINUS/wheel_3/HitResiduals_TID__wheel__3",
       'description': "Hit Residuals in TID- Wheel #3 ", 'draw': { 'withref': "yes"}}])
sistriplayout(dqmitems, "31 - TEC+ Residual",
  [{ 'path': "SiStrip/MechanicalView/TEC/PLUS/wheel_1/HitResiduals_TEC__wheel__1",
      'description': "Hit Residual in TEC+ Wheel #1", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TEC/PLUS/wheel_2/HitResiduals_TEC__wheel__2",
       'description': "Hit Residual in TEC+ Wheel #2", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TEC/PLUS/wheel_3/HitResiduals_TEC__wheel__3",
       'description': "Hit Residual in TEC+ Wheel #3", 'draw': { 'withref': "yes"}}],
  [{ 'path': "SiStrip/MechanicalView/TEC/PLUS/wheel_4/HitResiduals_TEC__wheel__4",
      'description': "Hit Residual in TEC+ Wheel #4", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TEC/PLUS/wheel_5/HitResiduals_TEC__wheel__5",
       'description': "Hit Residual in TEC+ Wheel #5", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TEC/PLUS/wheel_6/HitResiduals_TEC__wheel__6",
       'description': "Hit Residual in TEC+ Wheel #6", 'draw': { 'withref': "yes"}}],
  [{ 'path': "SiStrip/MechanicalView/TEC/PLUS/wheel_7/HitResiduals_TEC__wheel__7",
      'description': "Hit Residual in TEC+ Wheel #7", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TEC/PLUS/wheel_8/HitResiduals_TEC__wheel__8",
       'description': "Hit Residual in TEC+ Wheel #8", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TEC/PLUS/wheel_9/HitResiduals_TEC__wheel__9",
       'description': "Hit Residual in TEC+ Wheel #9", 'draw': { 'withref': "yes"}}])
sistriplayout(dqmitems, "32 - TEC- Residual",
  [{ 'path': "SiStrip/MechanicalView/TEC/MINUS/wheel_1/HitResiduals_TEC__wheel__1",
      'description': "Hit Residual in TEC- Wheel #1", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TEC/MINUS/wheel_2/HitResiduals_TEC__wheel__2",
       'description': "Hit Residual in TEC- Wheel #2", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TEC/MINUS/wheel_3/HitResiduals_TEC__wheel__3",
       'description': "Hit Residual in TEC- Wheel #3", 'draw': { 'withref': "yes"}}],
  [{ 'path': "SiStrip/MechanicalView/TEC/MINUS/wheel_4/HitResiduals_TEC__wheel__4",
      'description': "Hit Residual in TEC- Wheel #4", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TEC/MINUS/wheel_5/HitResiduals_TEC__wheel__5",
       'description': "Hit Residual in TEC- Wheel #5", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TEC/MINUS/wheel_6/HitResiduals_TEC__wheel__6",
       'description': "Hit Residual in TEC- Wheel #6", 'draw': { 'withref': "yes"}}],
  [{ 'path': "SiStrip/MechanicalView/TEC/MINUS/wheel_7/HitResiduals_TEC__wheel__7",
      'description': "Hit Residual in TEC- Wheel #7", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TEC/MINUS/wheel_8/HitResiduals_TEC__wheel__8",
       'description': "Hit Residual in TEC- Wheel #8", 'draw': { 'withref': "yes"}},
   { 'path': "SiStrip/MechanicalView/TEC/MINUS/wheel_9/HitResiduals_TEC__wheel__9",
       'description': "Hit Residual in TEC- Wheel #9", 'draw': { 'withref': "yes"}}])
sistriplayout(dqmitems, "33 - Cluster & Digi occupancy per FED",
 [{ 'path': "SiStrip/MechanicalView/NumberOfDigisinFED_v_FEDID",
    'description': "Digi occupancy per FED in the Strip detector", 'draw': { 'withref': "no" }},
  { 'path': "SiStrip/MechanicalView/NumberOfClustersinFED_v_FEDID",
    'description': "Cluster occupancy per FED in the Strip detector", 'draw': { 'withref': "no" }}])
sistriplayout(dqmitems, "34 - FED Errors Vs Id Vs Lumi",
 [{ 'path': "SiStrip/ReadoutView/Trends/FED/fedErrorsVsIdVsLumi",
    'description': "Digi occupancy per FED in the Strip detector", 'draw': { 'withref': "no" }}])

apply_dqm_items_to_new_back_end(dqmitems, __file__)
