#include "HeterogeneousCore/AlpakaCore/interface/alpaka/typelookup.h"
#include "RecoLocalTracker/SiStripClusterizer/interface/alpaka/SiStripClusterizerConditionsDevice.h"

TYPELOOKUP_ALPAKA_DATA_REG(sistrip::SiStripClusterizerConditionsDetToFedsDevice);
TYPELOOKUP_ALPAKA_DATA_REG(sistrip::SiStripClusterizerConditionsDataDevice);
