#!/bin/bash
### simple script to add information to the database. takes two arguments: the name of the calib.dat file (full path pls) and the desired tag name.

filename=$1
tagname=$2
runnumber=1
oldtag=PIXELTAG  # these should be identical to definition in inputfile
oldname=PIXELFILENAME  #these should be identical to definition in inputfile
oldrunnumber=PIXELRUNNUMBER
inputfile=${CMSSW_BASE}/src/CondTools/SiPixel/test/calibconfiguration_write_template_cfg.py
outputfile=`echo "dbinput_"$tagname"_scripted_cfg.py"`
rm -rf $outputfile
cat $inputfile | replace $oldname $filename $oldtag $tagname $oldrunnumber $runnumber>$outputfile
echo "****** THIS IS THE INPUT FILE:"
echo ""
cat $outputfile
echo "****** starting DB fill:"
cmsRun $outputfile
echo "removing temporary files..."

