import FWCore.ParameterSet.Config as cms

from SimFastTiming.MtdAssociatorProducers.mtdRecoMergedClusterToSimMergedClusterAssociationDefault_cfi import mtdRecoMergedClusterToSimMergedClusterAssociationDefault as _mtdRecoMergedClusterToSimMergedClusterAssociationDefault
mtdRecoMergedClusterToSimMergedClusterAssociation = _mtdRecoMergedClusterToSimMergedClusterAssociationDefault.clone()