#include "SimG4Core/Physics/interface/PhysicsListFactory.h"

#include "DummyPhysics.hh"
#include "FTFPCMS.hh"
#include "LHEPCMS.hh"
#include "QGSCCMS.hh"
#include "QGSPCMS.hh"
#include "QGSPCMS_EMV.hh"
#include "QGSPCMS_G4v52.hh"
#include "QGSPCMS_BERT.hh"
#include "QGSPCMS_BERT_HP.hh"

DEFINE_PHYSICSLIST(DummyPhysics);
typedef FTFPCMS FTFP;
DEFINE_PHYSICSLIST(FTFP);
typedef LHEPCMS LHEP;
DEFINE_PHYSICSLIST(LHEP);
typedef QGSCCMS QGSC;
DEFINE_PHYSICSLIST(QGSC);
typedef QGSPCMS QGSP;
DEFINE_PHYSICSLIST(QGSP);
typedef QGSPCMS_EMV QGSP_EMV;
DEFINE_PHYSICSLIST(QGSP_EMV);
typedef QGSPCMS_G4v52 QGSP_G4v52;
DEFINE_PHYSICSLIST(QGSP_G4v52);
typedef QGSPCMS_BERT QGSP_BERT;
DEFINE_PHYSICSLIST(QGSP_BERT);
typedef QGSPCMS_BERT_HP QGSP_BERT_HP;
DEFINE_PHYSICSLIST(QGSP_BERT_HP);
