#!/usr/bin/env python3


# Takes as input the dependency graph (json) generated by DumpDependencyGraph
# from test_dumpDependencyGraph_cfg.py, and checks that the dependencies
# extracted from the json match the ones in the original config.


import json
import sys

failures = []


def check(condition, message):
    if not condition:
        failures.append(message)


graph = json.load(open(sys.argv[1]))
modules = graph["modules"]

# Check the process name
check(graph["process"] == "DEPGRAPH", "wrong process name: " + graph["process"])

# Check process types and classes
check(modules["source"]["type"] == "Source", "the source is missing or mistyped")
check(modules["gate"]["type"] == "EDFilter", "gate should be an EDFilter")
check(modules["second"]["class"] == "AddIntsProducer", "wrong class for second")

# Check an ordinary consumes() dependency
check(modules["second"]["consumes"] == ["first"], "second should consume first")

# Check a dependency reached through an EDAlias
check(
    modules["viaAlias"]["consumes"] == ["second"],
    "viaAlias consumes aliasOfSecond, which should resolve to 'second'",
)

# Check that an EDAlias is resolved per data product, and not by label
check(modules["moduleA"]["consumes"] == ["moduleD"], "moduleA consumes T, from moduleD")
check(modules["moduleB"]["consumes"] == ["moduleE"], "moduleB consumes U, from moduleE")

# Check that a module with no dependencies reports none
check("consumes" not in modules["first"], "first should consume nothing")

# Check a product of the Source consumed directly
check(
    modules["fromSource"]["consumes"] == ["source"],
    "fromSource should consume the source",
)

# Check the same product consumed through an EDAlias
check(
    modules["viaSourceAlias"]["consumes"] == ["source"],
    "viaSourceAlias consumes aliasOfSource, which should resolve to 'source'",
)

# Check that a non-event dependency is not reported as an event-level one
check(
    "consumes" not in modules["runConsumer"],
    "runConsumer consumes only a run product, so it should have no event dependency",
)
check(
    modules["runConsumer"]["consumesNonEvent"] == ["runProducer"],
    "runConsumer should depend on runProducer on a non-event transition",
)

# Check that process.second has no non-event dependency
check(
    "consumesNonEvent" not in modules["second"],
    "second should have no non-event dependency",
)

# Check that process.DumpDependencyGraph reports unresolved dependencies as
# consumesUnresolved, not as a normal edge
check(
    modules["unknownLabel"]["consumesUnresolved"] == ["noSuchModule"],
    "an unresolved label should be reported as such",
)
check("consumes" not in modules["unknownLabel"], "an unresolved label is not an edge")

# Check that a data product asked from an earlier process is reported as
# unresolved, even though a module of this process carries that label
check(
    modules["fromEarlierProcess"]["consumesUnresolved"] == ["first"],
    "a product asked from an earlier process should be reported as unresolved",
)
check(
    "consumes" not in modules["fromEarlierProcess"],
    "a product asked from an earlier process is not an edge within this process",
)

# Check that no other module has an unresolved dependency
check(
    not any(
        "consumesUnresolved" in module
        for label, module in modules.items()
        if label not in ("unknownLabel", "fromEarlierProcess")
    ),
    "no other module should have unresolved labels",
)

# Check which Paths and EndPaths exist, and that the modules on each of them are
# sorted in schedule order.
check(
    graph["paths"]
    == {
        "p": ["first", "second", "viaAlias", "gate", "behindGate"],
        "q": [
            "fromSource",
            "viaSourceAlias",
            "runProducer",
            "runConsumer",
            "unknownLabel",
            "fromEarlierProcess",
        ],
        "r": ["moduleD", "moduleE", "moduleA", "moduleB"],
    },
    "wrong paths: " + str(graph["paths"]),
)
check(
    graph["endpaths"] == {"e": ["watcher"]}, "wrong endpaths: " + str(graph["endpaths"])
)

# Check that a module reachable only through a Task, but not part of any path,
# is still listed in "modules"...
check("unscheduled" in modules, "an unscheduled module should still be listed")

# ... but it's not part of any path
check(
    not any("unscheduled" in labels for labels in graph["paths"].values()),
    "an unscheduled module should be on no path",
)

if failures:
    sys.exit("\n".join("FAILED: " + failure for failure in failures))
