#!/usr/bin/env perl
#
# $Id $
###########################################################################
#  simple little script to make EDProducer skeletons
# 
#  execution:  mkedprod producername
# 
#  output:  producername/
#                         BuildFile.xml
#                         producername_cfg.py
#                         interface/
#                         src/producername.cc
#                         doc/
#                         test/
#                         python/producername_cfi.py
#  required input:
# 
#  producername = name of the producer
# 
#  optional input:
# 
#  none
# 
#  example:
#  mkedprod MyProducer
#        --> write  MyProducer/
#                               BuildFile.xml
#                               myproducer_cfg.py
#                               interface/
#                               src/MyProducer.cc
#                               doc/
#                               test/
#                               python/myproducer_cfi.py
#  
#   the script tries to read in
#   a filename .tmpl in users HOME directory which contains the following lines
#             First : your first name
#             Last : your last name
#   if .tmpl is not found and firstname and lastname are blank the
#   enviroment variable LOGNAME is used to obtain the "real life" name
#   from the output of finger.
#
#   Enviroment variable CMS_SKEL may point to a directory that
#   contains the skeleton files.
#
#   mkedprod will not overwrite existing files
#
#   Skeleton Keywords (Case matters):
#      prodname  :  overwritten with routine name
#      John Doe  :  overwritten with author's name
#      day-mon-xx:  overwritten with todays date
#      RCS(key)  :  becomes $key$
#
#   author of the script: Chris Jones
#                         (based on scripts used by the CLEO experiment)
#   
###########################################################################


#  if the routine name is blank, 'h' or '?' go to help
$name = "";
$author1 = "";
$author2 = "";
$recordname = "";

use FindBin;
use lib "$FindBin::Bin";

$commandFullPath = $0;

&read_args(@ARGV);

use SkelParser;

# environment variables
$home = $ENV{"HOME"};
$skel_dir = &find_mkTemplate_dir($commandFullPath);


$skeletons{"$skel_dir/EDProducer/edproducer.cc"} =
    "$name/src/" . $name . '.cc';
$skeletons{"$skel_dir/EDProducer/BuildFile.temp"} =
    "$name/BuildFile.xml";
$skeletons{"$skel_dir/EDProducer/ConfFile_cfg.py"} =
    "$name/" . lc($name) . '_cfg.py';
$skeletons{"$skel_dir/EDProducer/CfiFile_cfi.py"} =
    "$name/python/" . lc($name) . '_cfi.py';


if ( ! $do_list )
{
    # create the directories
    &mk_package_structure( $name );

    #based on the current directory, find the 'subsystem'
    my $gSUBSYS = "";
    ($gROOT, $gSUBSYS) = &grandparent_parent_dir;

    #define special substitution rules
    my @subs  = ( "s/prodname/$name/g",
		  "s/skelsubsys/$gSUBSYS/g",
		  "s/PRODNAME/\\U$name/g" );
    

    # make the source files from the skeletons
    foreach $skeleton_key ( keys(%skeletons) )
    {
	&make_file($skeleton_key, $skeletons{$skeleton_key}, \@subs, \@magic_tokens, $author1, $author2 );
    }
}
else
{
    &list_tokens;
    exit 0;
}

# read the command line arguments
sub read_args
{
    while ( @_ )
    {
	$curr_arg = shift @_;
	if ( $curr_arg eq "\?" 
	    || $curr_arg eq "h" 
	    || $curr_arg eq "-h" 
	    || $curr_arg eq "-help" )
	{
	    &wrt_help; 
	}
	elsif ( $curr_arg eq "-skeldir" )
	{
	    $next_arg = shift @_;
	    die "$next_arg is not a directory\n"
		unless ( -d $next_arg );
	    $skel_dir = $next_arg;
	}
	elsif ( $curr_arg eq "-author" )
	{
	    $next_arg = shift @_;
	    $author1 = $next_arg;
	    $next_arg = shift @_;
	    $author2 = $next_arg;
	}
	elsif ( $curr_arg =~ /^\w+$/ )
	{
	    if ( ! $name )
	    {
		$name = $curr_arg;

		# Names must begin with capital letters.
		if ( ! ( $name =~ /^[A-Z]/ ) )
		{
		    print "
mkedprod  E: ESProducer names must begin with capital letters, and each
mkedprod  E: separate 'word' in the name should also start with a capital
mkedprod  E: letter.  For example, MyTrackingTestProducer is a valid name,
mkedprod  E: but myTrackingTestProducer and MyTrackingtestProducer are not.\n\n";
		    exit 1;
		}
	    }
	}
	elsif ( $curr_arg =~ /^-(\w+)=?(\w*)$/ )
	{
	    push(@magic_tokens,$1);
	    if( $2 ) {
		$magic_values{$1}=$2;
	    }
	}
	else
	{
	    &wrt_help;
	}
    }
    &wrt_help unless ( ( $name ) || $do_list );
}


# help package
sub wrt_help {

    print <<'ENDHELP';
mkedprod  h: simple little script to make producer skeletons
mkedprod  h:
mkedprod  h: execution:  mkedprod producername
mkedprod  h:
mkedprod  h: output:  producername/
mkedprod  h:                       BuildFile.xml
mkedprod  h:                       producername_cfg.py
mkedprod  h:                       interface/
mkedprod  h:                       src/producername.cc
mkedprod  h:                       doc/
mkedprod  h:                       test/
mkedprod  h:                       python/poducername_cfi.py
mkedprod  h:
mkedprod  h: required input:
mkedprod  h:
mkedprod  h: producername = name of the producer
mkedprod  h:
mkedprod  h: optional input:
mkedprod  h:
mkedprod  h:   -author firstname lastname
mkedprod  h:
mkedprod  h: example:
mkedprod  h: mkedprod MyProducer
mkedprod  h:       --> write  MyProducer/
mkedprod  h:                              BuildFile.xml
mkedprod  h:                              myproducer_cfg.py
mkedprod  h:                              interface/
mkedprod  h:                              src/MyProducer.cc
mkedprod  h:                              doc/
mkedprod  h:                              test/
mkedprod  h:                              python/myproducer_cfi.py
ENDHELP

    print "mkedprod  Q: Please enter producer name: ";
    $ARGV[0] = <STDIN>;
    chop($ARGV[0]);

}
