import FWCore.ParameterSet.Config as cms
from DQMServices.Core.DQMEDHarvester import DQMEDHarvester

gemTnPEfficiencyClient = DQMEDHarvester("TnPEfficiencyClient",
                                       #Histogram names listed as "passProbeHistoName:failProbeHistoName"
                                       subsystem = cms.untracked.string("GEM"),
                                       histoNames = cms.untracked.vstring("GE11_nPassingProbe_Ch_region:GE11_nFailingProbe_Ch_region",
                                                                          "GE21_nPassingProbe_Ch_region:GE21_nFailingProbe_Ch_region",
                                                                          "GEM_nPassingProbe_Ch_region_GE1:GEM_nFailingProbe_Ch_region_GE1",
                                                                          "GEM_nPassingProbe_Ch_region_GE1_NoL:GEM_nFailingProbe_Ch_region_GE1_NoL",
                                                                          "GE11_nPassingProbe_Ch_ieta:GE11_nFailingProbe_Ch_ieta",
                                                                          "GE11_nPassingProbe_Ch_phi:GE11_nFailingProbe_Ch_phi",
                                                                          "GE11_nPassingProbe_allCh_1D:GE11_nFailingProbe_allCh_1D",
                                                                          "GE11_nPassingProbe_chamber_1D:GE11_nFailingProbe_chamber_1D",
                                                                          "GE21_nPassingProbe_Ch_ieta:GE21_nFailingProbe_Ch_ieta",
                                                                          "GE21_nPassingProbe_Ch_phi:GE21_nFailingProbe_Ch_phi",
                                                                          "GE21_nPassingProbe_allCh_1D:GE21_nFailingProbe_allCh_1D",
                                                                          "GE21_nPassingProbe_chamber_1D:GE21_nFailingProbe_chamber_1D",
                                                                          "GEM_nPassingProbe_chamber_P-L1_1D:GEM_nFailingProbe_chamber_P-L1_1D",
                                                                          "GEM_nPassingProbe_chamber_P-L2_1D:GEM_nFailingProbe_chamber_P-L2_1D",
                                                                          "GEM_nPassingProbe_chamber_M-L1_1D:GEM_nFailingProbe_chamber_M-L1_1D",
                                                                          "GEM_nPassingProbe_chamber_M-L2_1D:GEM_nFailingProbe_chamber_M-L2_1D",
                                                                          "GEM_nPassingProbe_pt_1D:GEM_nFailingProbe_pt_1D",
                                                                          "GEM_nPassingProbe_eta_1D:GEM_nFailingProbe_eta_1D",
                                                                          "GEM_nPassingProbe_phi_1D:GEM_nFailingProbe_phi_1D",
                                                                          "GEM_nPassingProbe_pt_P-L1_1D:GEM_nFailingProbe_pt_P-L1_1D",
                                                                          "GEM_nPassingProbe_eta_P-L1_1D:GEM_nFailingProbe_eta_P-L1_1D",
                                                                          "GEM_nPassingProbe_phi_P-L1_1D:GEM_nFailingProbe_phi_P-L1_1D",
                                                                          "GEM_nPassingProbe_pt_P-L2_1D:GEM_nFailingProbe_pt_P-L2_1D",
                                                                          "GEM_nPassingProbe_eta_P-L2_1D:GEM_nFailingProbe_eta_P-L2_1D",
                                                                          "GEM_nPassingProbe_phi_P-L2_1D:GEM_nFailingProbe_phi_P-L2_1D",
                                                                          "GEM_nPassingProbe_pt_M-L1_1D:GEM_nFailingProbe_pt_M-L1_1D",
                                                                          "GEM_nPassingProbe_eta_M-L1_1D:GEM_nFailingProbe_eta_M-L1_1D",
                                                                          "GEM_nPassingProbe_phi_M-L1_1D:GEM_nFailingProbe_phi_M-L1_1D",
                                                                          "GEM_nPassingProbe_pt_M-L2_1D:GEM_nFailingProbe_pt_M-L2_1D",
                                                                          "GEM_nPassingProbe_eta_M-L2_1D:GEM_nFailingProbe_eta_M-L2_1D",
                                                                          "GEM_nPassingProbe_phi_M-L2_1D:GEM_nFailingProbe_phi_M-L2_1D",
                                                                          "ME0_nPassingProbe_chamber_1D:ME0_nFailingProbe_chamber_1D",
                                                                          "GE11_nPassingProbe_Ch_ieta_P-L1:GE11_nFailingProbe_Ch_ieta_P-L1",
                                                                          "GE11_nPassingProbe_Ch_ieta_P-L2:GE11_nFailingProbe_Ch_ieta_P-L2",
                                                                          "GE11_nPassingProbe_Ch_ieta_M-L1:GE11_nFailingProbe_Ch_ieta_M-L1",
                                                                          "GE11_nPassingProbe_Ch_ieta_M-L2:GE11_nFailingProbe_Ch_ieta_M-L2",
                                                                          "GE11_nPassingProbe_VFATMask_allCh_1D:GE11_nFailingProbe_VFATMask_allCh_1D",
                                                                          "GEM_nPassingProbe_VFATMask_chamber_P-L1_1D:GEM_nFailingProbe_VFATMask_chamber_P-L1_1D",
                                                                          "GEM_nPassingProbe_VFATMask_chamber_P-L2_1D:GEM_nFailingProbe_VFATMask_chamber_P-L2_1D",
                                                                          "GEM_nPassingProbe_VFATMask_chamber_M-L1_1D:GEM_nFailingProbe_VFATMask_chamber_M-L1_1D",
                                                                          "GEM_nPassingProbe_VFATMask_chamber_M-L2_1D:GEM_nFailingProbe_VFATMask_chamber_M-L2_1D",
                                                                          "GEM_nPassingProbe_VFATMask_pt_1D:GEM_nFailingProbe_VFATMask_pt_1D",
                                                                          "GEM_nPassingProbe_VFATMask_eta_1D:GEM_nFailingProbe_VFATMask_eta_1D",
                                                                          "GEM_nPassingProbe_VFATMask_phi_1D:GEM_nFailingProbe_VFATMask_phi_1D",
                                                                          "GE11_nPassingProbe_VFATMask_Ch_ieta_P-L1:GE11_nFailingProbe_VFATMask_Ch_ieta_P-L1",
                                                                          "GE11_nPassingProbe_VFATMask_Ch_ieta_P-L2:GE11_nFailingProbe_VFATMask_Ch_ieta_P-L2",
                                                                          "GE11_nPassingProbe_VFATMask_Ch_ieta_M-L1:GE11_nFailingProbe_VFATMask_Ch_ieta_M-L1",
                                                                          "GE11_nPassingProbe_VFATMask_Ch_ieta_M-L2:GE11_nFailingProbe_VFATMask_Ch_ieta_M-L2",
                                                                          "GEM_nPassingProbe_Ch_region_layer_phase2:GEM_nFailingProbe_Ch_region_layer_phase2"),
                                       diagnosticPrescale = cms.untracked.int32(1))
