#!/bin/csh
cd ../..
cvs co Configuration/StandardSequences/data/Reconstruction.cff
cp -r ~cbern/public/CMSSW/CMSSW_1_2_0_pre9/Reconstruction.cff Configuration/StandardSequences/data/Reconstruction.cff
