#ifndef HLTriggerOffline_Scouting_interface_Run3ScoutingTrackDQMVariables_h
#define HLTriggerOffline_Scouting_interface_Run3ScoutingTrackDQMVariables_h

#include "DQMServices/Components/interface/GenericObjectDQMSource.h"
#include "DataFormats/Scouting/interface/Run3ScoutingTrack.h"

template <>
struct DQMVariableTraits<Run3ScoutingTrack> {
  static std::vector<DQMVariable<Run3ScoutingTrack>> variables() {
    return {
        {"tk_pt", "p_{T} [GeV]", 100, 0., 200., [](Run3ScoutingTrack const& t) { return t.tk_pt(); }},
        {"tk_eta", "#eta", 100, -4., 4., [](Run3ScoutingTrack const& t) { return t.tk_eta(); }},
        {"tk_phi", "#phi", 100, -3.15, 3.15, [](Run3ScoutingTrack const& t) { return t.tk_phi(); }},
        {"tk_chi2", "#chi^{2}", 100, 0., 100., [](Run3ScoutingTrack const& t) { return t.tk_chi2(); }},
        {"tk_ndof", "ndof", 50, 0., 50., [](Run3ScoutingTrack const& t) { return t.tk_ndof(); }},
        {"tk_charge", "charge", 5, -2.5, 2.5, [](Run3ScoutingTrack const& t) { return t.tk_charge(); }},
        {"tk_dxy", "d_{xy} [cm]", 100, -1., 1., [](Run3ScoutingTrack const& t) { return t.tk_dxy(); }},
        {"tk_dz", "d_{z} [cm]", 100, -20., 20., [](Run3ScoutingTrack const& t) { return t.tk_dz(); }},
        {"tk_nValidPixelHits",
         "N_{valid pixel hits}",
         20,
         0.,
         20.,
         [](Run3ScoutingTrack const& t) { return t.tk_nValidPixelHits(); }},
        {"tk_nTrackerLayersWithMeasurement",
         "N_{tracker layers}",
         25,
         0.,
         25.,
         [](Run3ScoutingTrack const& t) { return t.tk_nTrackerLayersWithMeasurement(); }},
        {"tk_nValidStripHits",
         "N_{valid strip hits}",
         30,
         0.,
         30.,
         [](Run3ScoutingTrack const& t) { return t.tk_nValidStripHits(); }},
        {"tk_qoverp", "q/p [1/GeV]", 100, -1., 1., [](Run3ScoutingTrack const& t) { return t.tk_qoverp(); }},
        {"tk_lambda", "#lambda", 100, -2., 2., [](Run3ScoutingTrack const& t) { return t.tk_lambda(); }},
        {"tk_dxy_Error",
         "#sigma(d_{xy}) [cm]",
         100,
         0.,
         0.5,
         [](Run3ScoutingTrack const& t) { return t.tk_dxy_Error(); }},
        {"tk_dz_Error", "#sigma(d_{z}) [cm]", 100, 0., 0.5, [](Run3ScoutingTrack const& t) { return t.tk_dz_Error(); }},
        {"tk_qoverp_Error",
         "#sigma(q/p) [1/GeV]",
         100,
         0.,
         0.5,
         [](Run3ScoutingTrack const& t) { return t.tk_qoverp_Error(); }},
        {"tk_lambda_Error",
         "#sigma(#lambda)",
         100,
         0.,
         0.1,
         [](Run3ScoutingTrack const& t) { return t.tk_lambda_Error(); }},
        {"tk_phi_Error", "#sigma(#phi)", 100, 0., 0.1, [](Run3ScoutingTrack const& t) { return t.tk_phi_Error(); }},
        {"tk_dsz", "d_{sz} [cm]", 100, -20., 20., [](Run3ScoutingTrack const& t) { return t.tk_dsz(); }},
        {"tk_dsz_Error",
         "#sigma(d_{sz}) [cm]",
         100,
         0.,
         0.5,
         [](Run3ScoutingTrack const& t) { return t.tk_dsz_Error(); }},
        {"tk_qoverp_lambda_cov",
         "cov(q/p, #lambda)",
         100,
         -1e-3,
         1e-3,
         [](Run3ScoutingTrack const& t) { return t.tk_qoverp_lambda_cov(); }},
        {"tk_qoverp_phi_cov",
         "cov(q/p, #phi)",
         100,
         -1e-3,
         1e-3,
         [](Run3ScoutingTrack const& t) { return t.tk_qoverp_phi_cov(); }},
        {"tk_qoverp_dxy_cov",
         "cov(q/p, d_{xy})",
         100,
         -1e-3,
         1e-3,
         [](Run3ScoutingTrack const& t) { return t.tk_qoverp_dxy_cov(); }},
        {"tk_qoverp_dsz_cov",
         "cov(q/p, d_{sz})",
         100,
         -1e-3,
         1e-3,
         [](Run3ScoutingTrack const& t) { return t.tk_qoverp_dsz_cov(); }},
        {"tk_lambda_phi_cov",
         "cov(#lambda, #phi)",
         100,
         -1e-3,
         1e-3,
         [](Run3ScoutingTrack const& t) { return t.tk_lambda_phi_cov(); }},
        {"tk_lambda_dxy_cov",
         "cov(#lambda, d_{xy})",
         100,
         -1e-3,
         1e-3,
         [](Run3ScoutingTrack const& t) { return t.tk_lambda_dxy_cov(); }},
        {"tk_lambda_dsz_cov",
         "cov(#lambda, d_{sz})",
         100,
         -1e-3,
         1e-3,
         [](Run3ScoutingTrack const& t) { return t.tk_lambda_dsz_cov(); }},
        {"tk_phi_dxy_cov",
         "cov(#phi, d_{xy})",
         100,
         -1e-3,
         1e-3,
         [](Run3ScoutingTrack const& t) { return t.tk_phi_dxy_cov(); }},
        {"tk_phi_dsz_cov",
         "cov(#phi, d_{sz})",
         100,
         -1e-3,
         1e-3,
         [](Run3ScoutingTrack const& t) { return t.tk_phi_dsz_cov(); }},
        {"tk_dxy_dsz_cov",
         "cov(d_{xy}, d_{sz})",
         100,
         -0.1,
         0.1,
         [](Run3ScoutingTrack const& t) { return t.tk_dxy_dsz_cov(); }},
        {"tk_vtxInd", "vertex index", 20, -1.5, 18.5, [](Run3ScoutingTrack const& t) { return t.tk_vtxInd(); }},
        {"tk_vx", "v_{x} [cm]", 100, -1., 1., [](Run3ScoutingTrack const& t) { return t.tk_vx(); }},
        {"tk_vy", "v_{y} [cm]", 100, -1., 1., [](Run3ScoutingTrack const& t) { return t.tk_vy(); }},
        {"tk_vz", "v_{z} [cm]", 100, -20., 20., [](Run3ScoutingTrack const& t) { return t.tk_vz(); }},
    };
  }
};

#endif
