#! /usr/bin/env python3

from FWCore.ParameterSet.TreeCrawler import getImportTree
import sys, os

from argparse import ArgumentParser
parser = ArgumentParser()
parser.add_argument("config_file",type=str)
options = parser.parse_args()

sys.path.append(os.environ["PWD"])
path = sys.path[:]

# get the dependencies
importTree = getImportTree(options.config_file, path)

# finally dump the tree
importTree.dump(0)
