from L1TriggerConfig.CSCTFConfigProducers.CSCTFConfigOnline_cfi import *
#from L1TriggerConfig.CSCTFConfigProducers.CSCTFAlignmentOnline_cfi import *
from L1TriggerConfig.CSCTFConfigProducers.L1MuCSCPtLutConfigOnline_cfi import *

from L1TriggerConfig.DTTrackFinder.L1MuDTEtaPatternLutOnline_cfi import *
from L1TriggerConfig.DTTrackFinder.L1MuDTExtLutOnline_cfi import *
from L1TriggerConfig.DTTrackFinder.L1MuDTPhiLutOnline_cfi import *
from L1TriggerConfig.DTTrackFinder.L1MuDTPtaLutOnline_cfi import *
from L1TriggerConfig.DTTrackFinder.L1MuDTQualPatternLutOnline_cfi import *
from L1TriggerConfig.DTTrackFinder.L1MuDTTFParametersOnline_cfi import *

from L1TriggerConfig.RPCTriggerConfig.L1RPCConfigOnline_cfi import *
from L1TriggerConfig.RPCTriggerConfig.L1RPCConeDefinitionOnline_cfi import *
from L1TriggerConfig.RPCTriggerConfig.L1RPCBxOrConfigOnline_cfi import *
from L1TriggerConfig.RPCTriggerConfig.L1RPCHsbConfigOnline_cfi import *

from L1TriggerConfig.GMTConfigProducers.L1MuGMTParametersOnlineProducer_cfi import *
from L1TriggerConfig.L1ScalesProducers.L1MuTriggerPtScaleOnlineProducer_cfi import *
from L1TriggerConfig.L1ScalesProducers.L1MuTriggerScalesOnlineProducer_cfi import *
L1MuGMTParametersOnlineProducer.ignoreVersionMismatch = True

from L1TriggerConfig.RCTConfigProducers.L1RCTParametersOnline_cfi import *
from L1TriggerConfig.L1ScalesProducers.L1EmEtScaleConfigOnline_cfi import *
from L1TriggerConfig.L1ScalesProducers.L1CaloEcalScaleConfigOnline_cfi import *
from L1TriggerConfig.L1ScalesProducers.L1CaloHcalScaleConfigOnline_cfi import *

from L1TriggerConfig.GctConfigProducers.L1GctJetFinderParamsOnline_cfi import *
from L1TriggerConfig.L1ScalesProducers.L1HtMissScaleOnline_cfi import *
from L1TriggerConfig.L1ScalesProducers.L1HfRingEtScaleOnline_cfi import *
from L1TriggerConfig.L1ScalesProducers.L1JetEtScaleOnline_cfi import *

from L1TriggerConfig.L1GtConfigProducers.l1GtParametersOnline_cfi import *
from L1TriggerConfig.L1GtConfigProducers.l1GtPsbSetupOnline_cfi import *
from L1TriggerConfig.L1GtConfigProducers.l1GtTriggerMenuOnline_cfi import *
