#!/bin/bash
first=$1
last=$2
arg1=''
arg2=''
if [ -z $first ]; then
  echo
else
  arg1="-f $first"
fi
if [ -z $last ]; then
    echo
else
  arg2="-l $last"
fi
psdir="`whoami`_`date +%d%m%y%H%M`"
mkdir $psdir
export MEPSDIR=${PWD}/$psdir;
echo 'postscript files will be written in ' $MEPSDIR
runGUI -d $arg1 $arg2
ls $MEPSDIR

