#! /bin/bash
#

#
# script to run the complete phisym calibration exercise
# S.A. Sept 22, 2008
#

if [ $# -ne 2 ] 
then
    echo "Usage $0 conffile runlist"
    exit 
fi

conffile=$1
runlist=$2

#evaluate number of jobs, 10 files per job
nfiles=`wc $runlist | awk '{print $1}'` 
njobs=`echo $[nfiles/10]` 

echo "$0: starting at `date`"
echo "$0: $nfiles files to process in $njobs jobs" 

#were to store output
datadir=/data/argiro/$1-$2
echo "$0: output will be stored in $datadir"

#generated by 'scram runt -sh > cmsenv.sh' 
source cmsenv.sh 
#create target dir
ssh pccmsto03 mkdir -p $datadir

echo "$0: Removing old files"
rm -rf *.dat 
rm -rf *.root
rm -rf *.log

echo "$0: Submitting jobs"
./phisym-submit.py -c $conffile -r $runlist -n $njobs -e pccmsto03:$datadir


#wait for jobs to finish (look if there's any config file left)
while [ "`ls config* 2>/dev/null`" != "" ] ; do  
   sleep 1
done

cat etsum_barl_*.dat > etsum_barl.dat
cat etsum_endc_*.dat > etsum_endc.dat



#run calibration job
cmsRun csa08PhiSymCalibration_Output.cfg > output-$1-$2.log
scp -r *.root output-$1-$2.log pccmsto03:$datadir
scp -r ../src pccmsto03:$datadir

#cleanup*
rm -rf etsum_barl_*.dat
rm -rf etsum_endc_*.dat

echo "$0: finishing at `date`"
