#!/bin/bash

function RunOne()
{
	local thSize="$1"
	local level="$2"

	local tag="th_${thSize}_level_${level}"

	local cfgFile="${tag}_cfg.py"
	local logFile="${tag}.log"

	cp "template_cfg.py" "$dir/$cfgFile"

	(
		echo "process.maxEvents.input = $events"
		echo "Set${thSize}Theta()"
		echo "SetLevel${level}()"
		echo "process.ctppsProtonReconstructionSimulationValidator.outputFile = \"${tag}_validation.root\""
	) >> "$dir/$cfgFile"

	cd "$dir"

	cmsRun "$cfgFile" &> "$logFile" &

	cd - &> /dev/null
}


#----------------------------------------------------------------------------------------------------

function Run()
{
	events="$1"
	dir="$2"

	rm -rf "$dir"
	mkdir "$dir"

	#RunOne "Low" "1"
	#RunOne "Low" "2"
	#RunOne "Low" "3"
	#RunOne "Low" "4"

	RunOne "Large" "1"
	RunOne "Large" "2"
	RunOne "Large" "3"
	RunOne "Large" "4"
}

#----------------------------------------------------------------------------------------------------

#Run "100" "1E2"

Run "10000" "1E4"
