import FWCore.ParameterSet.Config as cms

import FastSimulation.Tracking.TrackCandidateProducer_cfi
iterativeSecondTrackCandidatesWithTriplets = FastSimulation.Tracking.TrackCandidateProducer_cfi.trackCandidateProducer.clone()
iterativeSecondTrackCandidates = cms.Sequence(iterativeSecondTrackCandidatesWithTriplets)
iterativeSecondTrackCandidatesWithTriplets.SeedProducer = cms.InputTag("iterativeSecondSeeds","SecondPixelTriplets")
iterativeSecondTrackCandidatesWithTriplets.TrackProducers = ['firstfilter']
iterativeSecondTrackCandidatesWithTriplets.KeepFittedTracks = False
iterativeSecondTrackCandidatesWithTriplets.MinNumberOfCrossedLayers = 3


