import FWCore.ParameterSet.Config as cms

import FastSimulation.Tracking.TrackCandidateProducer_cfi
iterativeSecondTrackCandidatesWithTriplets = FastSimulation.Tracking.TrackCandidateProducer_cfi.trackCandidateProducer.clone()
import FastSimulation.Tracking.TrackCandidateProducer_cfi
iterativeSecondTrackCandidatesWithPairs = FastSimulation.Tracking.TrackCandidateProducer_cfi.trackCandidateProducer.clone()
iterativeSecondTrackCandidates = cms.Sequence(iterativeSecondTrackCandidatesWithTriplets+iterativeSecondTrackCandidatesWithPairs)
iterativeSecondTrackCandidatesWithTriplets.SeedProducer = cms.InputTag("iterativeSecondSeeds","SecondMixedTriplets")
iterativeSecondTrackCandidatesWithTriplets.TrackProducers = ['firstfilter']
iterativeSecondTrackCandidatesWithTriplets.KeepFittedTracks = False
iterativeSecondTrackCandidatesWithTriplets.MinNumberOfCrossedLayers = 3
iterativeSecondTrackCandidatesWithPairs.SeedProducer = cms.InputTag("iterativeSecondSeeds","SecondMixedPairs")
iterativeSecondTrackCandidatesWithPairs.TrackProducers = ['firstfilter']
iterativeSecondTrackCandidatesWithPairs.KeepFittedTracks = False
iterativeSecondTrackCandidatesWithPairs.MinNumberOfCrossedLayers = 3

