maxSections = 5

commonDict = {
    "abbrev" : "O",
    "name" : "common",
    "default" : 9,
    "O8" : {
        1 : [
            'Geometry/CMSCommonData/data/materials/2021/v1/materials.xml',
            'Geometry/CMSCommonData/data/rotations.xml',
            'Geometry/CMSCommonData/data/extend/v2/cmsextent.xml',
            'Geometry/CMSCommonData/data/cavernData/2021/v1/cavernData.xml',
            'Geometry/CMSCommonData/data/cms/2026/v5/cms.xml',
            'Geometry/CMSCommonData/data/cmsMother.xml',
            'Geometry/CMSCommonData/data/eta3/etaMax.xml',
            'Geometry/CMSCommonData/data/cmsTracker.xml',
            'Geometry/CMSCommonData/data/caloBase/2026/v6/caloBase.xml',
            'Geometry/CMSCommonData/data/cmsCalo.xml',
            'Geometry/CMSCommonData/data/muonBase/2026/v5/muonBase.xml',
            'Geometry/CMSCommonData/data/cmsMuon.xml',
            'Geometry/CMSCommonData/data/mgnt.xml',
            'Geometry/CMSCommonData/data/beampipe/2026/v3/beampipe.xml',
            'Geometry/CMSCommonData/data/cmsBeam/2026/v1/cmsBeam.xml',
            'Geometry/CMSCommonData/data/muonMB.xml',
            'Geometry/CMSCommonData/data/muonMagnet.xml',
            'Geometry/CMSCommonData/data/cavern/2021/v1/cavern.xml',
            'Geometry/CMSCommonData/data/cavernFloor/2017/v1/cavernFloor.xml',
        ],
        5 : [
            'Geometry/CMSCommonData/data/FieldParameters.xml',
        ],
        "era" : "phase2_common, phase2_trigger",
    },
    "O9" : {
        1 : [
            'Geometry/CMSCommonData/data/materials/2021/v1/materials.xml',
            'Geometry/CMSCommonData/data/rotations.xml',
            'Geometry/CMSCommonData/data/extend/v2/cmsextent.xml',
            'Geometry/CMSCommonData/data/cavernData/2021/v1/cavernData.xml',
            'Geometry/CMSCommonData/data/cms/2026/v5/cms.xml',
            'Geometry/CMSCommonData/data/cmsMother.xml',
            'Geometry/CMSCommonData/data/eta3/etaMax.xml',
            'Geometry/CMSCommonData/data/cmsTracker.xml',
            'Geometry/CMSCommonData/data/caloBase/2026/v7/caloBase.xml',
            'Geometry/CMSCommonData/data/cmsCalo.xml',
            'Geometry/CMSCommonData/data/muonBase/2026/v5/muonBase.xml',
            'Geometry/CMSCommonData/data/cmsMuon.xml',
            'Geometry/CMSCommonData/data/mgnt.xml',
            'Geometry/CMSCommonData/data/beampipe/2026/v3/beampipe.xml',
            'Geometry/CMSCommonData/data/cmsBeam/2026/v1/cmsBeam.xml',
            'Geometry/CMSCommonData/data/muonMB.xml',
            'Geometry/CMSCommonData/data/muonMagnet.xml',
            'Geometry/CMSCommonData/data/cavern/2021/v1/cavern.xml',
            'Geometry/CMSCommonData/data/cavernFloor/2017/v1/cavernFloor.xml',
        ],
        5 : [
            'Geometry/CMSCommonData/data/FieldParameters.xml',
        ],
        "era" : "phase2_common, phase2_trigger",
    },
}

trackerDict = {
    "abbrev" : "T",
    "name" : "tracker",
    "default" : 32,
    "T24" : {
        1 : [
            'Geometry/TrackerCommonData/data/PhaseII/trackerParameters.xml',
            'Geometry/TrackerCommonData/data/pixfwdCommon.xml',
            'Geometry/TrackerCommonData/data/PhaseII/Tracker_DD4hep_compatible_2021_02/pixfwd.xml',
            'Geometry/TrackerCommonData/data/PhaseII/OuterTracker616_2020_04/pixbar.xml',
            'Geometry/TrackerCommonData/data/trackermaterial.xml',
            'Geometry/TrackerCommonData/data/PhaseII/Tracker_DD4hep_compatible_2021_02/tracker.xml',
            'Geometry/TrackerCommonData/data/PhaseII/OuterTracker616_2020_04/otst.xml',
            'Geometry/TrackerCommonData/data/PhaseII/Tracker_DD4hep_compatible_2021_02/pixel.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/trackerbar.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/trackerfwd.xml',
            'Geometry/TrackerCommonData/data/PhaseII/Tracker_DD4hep_compatible_2021_02/trackerStructureTopology.xml',
            'Geometry/TrackerCommonData/data/PhaseII/Tracker_DD4hep_compatible_2021_02/pixelStructureTopology.xml',
            'Geometry/TrackerSimData/data/PhaseII/Tracker_DD4hep_compatible_2021_02/trackersens.xml',
            'Geometry/TrackerSimData/data/PhaseII/Tracker_DD4hep_compatible_2021_02/pixelsens.xml',
            'Geometry/TrackerRecoData/data/PhaseII/Tracker_DD4hep_compatible_2021_02/trackerRecoMaterial.xml',
            'SimTracker/TrackerMaterialAnalysis/data/trackingMaterialGroups_ForPhaseII/v1/trackingMaterialGroups_ForPhaseII.xml',
            'Geometry/TrackerSimData/data/PhaseII/Tracker_DD4hep_compatible_2021_02/trackerProdCuts.xml',
            'Geometry/TrackerSimData/data/PhaseII/Tracker_DD4hep_compatible_2021_02/pixelProdCuts.xml',
            'Geometry/TrackerSimData/data/trackerProdCutsBEAM.xml',
        ],
        "sim" : [
            'from Geometry.TrackerNumberingBuilder.trackerNumberingGeometry_cff import *',
            'from SLHCUpgradeSimulations.Geometry.fakePhase2OuterTrackerConditions_cff import *',
        ],
        "reco" : [
            'from Geometry.CommonTopologies.globalTrackingGeometry_cfi import *',
            'from RecoTracker.GeometryESProducer.TrackerRecoGeometryESProducer_cfi import *',
            'from Geometry.TrackerGeometryBuilder.trackerParameters_cff import *',
            'from Geometry.TrackerNumberingBuilder.trackerTopology_cfi import *',
            'from Geometry.TrackerGeometryBuilder.idealForDigiTrackerGeometry_cff import *',
            'trackerGeometry.applyAlignment = True',
        ],
        "era" : "phase2_tracker, trackingPhase2PU140",
    },
    "T25" : {
        1 : [
            'Geometry/TrackerCommonData/data/PhaseII/trackerParameters.xml',
            'Geometry/TrackerCommonData/data/pixfwdCommon.xml',
            'Geometry/TrackerCommonData/data/PhaseII/Tracker_DD4hep_compatible_2021_02/pixfwd.xml',
            'Geometry/TrackerCommonData/data/PhaseII/OuterTracker616_2020_04/pixbar.xml',
            'Geometry/TrackerCommonData/data/trackermaterial.xml',
            'Geometry/TrackerCommonData/data/PhaseII/Tracker_DD4hep_compatible_2021_02/tracker.xml',
            'Geometry/TrackerCommonData/data/PhaseII/OuterTracker616_2020_04/otst.xml',
            'Geometry/TrackerCommonData/data/PhaseII/Tracker_DD4hep_compatible_IT702_2021_03/pixel.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/trackerbar.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/trackerfwd.xml',
            'Geometry/TrackerCommonData/data/PhaseII/Tracker_DD4hep_compatible_2021_02/trackerStructureTopology.xml',
            'Geometry/TrackerCommonData/data/PhaseII/Tracker_DD4hep_compatible_IT702_2021_03/pixelStructureTopology.xml',
            'Geometry/TrackerSimData/data/PhaseII/Tracker_DD4hep_compatible_2021_02/trackersens.xml',
            'Geometry/TrackerSimData/data/PhaseII/Tracker_DD4hep_compatible_IT702_2021_03/pixelsens.xml',
            'Geometry/TrackerRecoData/data/PhaseII/Tracker_DD4hep_compatible_IT702_2021_03/trackerRecoMaterial.xml',
            'Geometry/TrackerSimData/data/PhaseII/Tracker_DD4hep_compatible_2021_02/trackerProdCuts.xml',
            'Geometry/TrackerSimData/data/PhaseII/Tracker_DD4hep_compatible_IT702_2021_03/pixelProdCuts.xml',
            'Geometry/TrackerSimData/data/trackerProdCutsBEAM.xml',
        ],
        "sim" : [
            'from Geometry.TrackerNumberingBuilder.trackerNumberingGeometry_cff import *',
            'from SLHCUpgradeSimulations.Geometry.fakePhase2OuterTrackerConditions_cff import *',
        ],
        "reco" : [
            'from Geometry.CommonTopologies.globalTrackingGeometry_cfi import *',
            'from RecoTracker.GeometryESProducer.TrackerRecoGeometryESProducer_cfi import *',
            'from Geometry.TrackerGeometryBuilder.trackerParameters_cff import *',
            'from Geometry.TrackerNumberingBuilder.trackerTopology_cfi import *',
            'from Geometry.TrackerGeometryBuilder.idealForDigiTrackerGeometry_cff import *',
            'trackerGeometry.applyAlignment = True',
        ],
        "era" : "phase2_tracker, phase2_3DPixels, trackingPhase2PU140",
    },
    "T30" : {
        1 : [
            'Geometry/TrackerCommonData/data/PhaseII/TFPXTEPXReordered/trackerParameters.xml',
            'Geometry/TrackerCommonData/data/pixfwdCommon.xml',
            'Geometry/TrackerCommonData/data/PhaseII/Tracker_DD4hep_compatible_2021_02/pixfwd.xml',
            'Geometry/TrackerCommonData/data/PhaseII/OuterTracker616_2020_04/pixbar.xml',
            'Geometry/TrackerCommonData/data/trackermaterial.xml',
            'Geometry/TrackerCommonData/data/PhaseII/Tracker_DD4hep_compatible_OT801_IT640/tracker.xml',
            'Geometry/TrackerCommonData/data/PhaseII/OuterTracker616_2020_04/otst.xml',
            'Geometry/TrackerCommonData/data/PhaseII/Tracker_DD4hep_compatible_OT801_IT640/pixel.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/trackerbar.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/trackerfwd.xml',
            'Geometry/TrackerCommonData/data/PhaseII/Tracker_DD4hep_compatible_2021_02/trackerStructureTopology.xml',
            'Geometry/TrackerCommonData/data/PhaseII/Tracker_DD4hep_compatible_OT801_IT640/pixelStructureTopology.xml',
            'Geometry/TrackerSimData/data/PhaseII/Tracker_DD4hep_compatible_2021_02/trackersens.xml',
            'Geometry/TrackerSimData/data/PhaseII/Tracker_DD4hep_compatible_OT801_IT640/pixelsens.xml',
            'Geometry/TrackerRecoData/data/PhaseII/Tracker_DD4hep_compatible_OT801_IT640/trackerRecoMaterial.xml',
            'Geometry/TrackerSimData/data/PhaseII/Tracker_DD4hep_compatible_2021_02/trackerProdCuts.xml',
            'Geometry/TrackerSimData/data/PhaseII/Tracker_DD4hep_compatible_OT801_IT640/pixelProdCuts.xml',
            'Geometry/TrackerSimData/data/trackerProdCutsBEAM.xml',
        ],
        "sim" : [
            'from Geometry.TrackerNumberingBuilder.trackerNumberingGeometry_cff import *',
            'from SLHCUpgradeSimulations.Geometry.fakePhase2OuterTrackerConditions_cff import *',
        ],
        "reco" : [
            'from Geometry.CommonTopologies.globalTrackingGeometry_cfi import *',
            'from RecoTracker.GeometryESProducer.TrackerRecoGeometryESProducer_cfi import *',
            'from Geometry.TrackerGeometryBuilder.trackerParameters_cff import *',
            'from Geometry.TrackerNumberingBuilder.trackerTopology_cfi import *',
            'from Geometry.TrackerGeometryBuilder.idealForDigiTrackerGeometry_cff import *',
            'trackerGeometry.applyAlignment = True',
        ],
        "era" : "phase2_tracker, trackingPhase2PU140",
    }, 
    "T31" : {
        1 : [
            'Geometry/TrackerCommonData/data/PhaseII/trackerParameters.xml',
            'Geometry/TrackerCommonData/data/pixfwdCommon.xml',
            'Geometry/TrackerCommonData/data/PhaseII/Tracker_DD4hep_compatible_2021_02/pixfwd.xml',
            'Geometry/TrackerCommonData/data/PhaseII/Tracker_DD4hep_compatible_OT800_IT615_2022_10/pixbar.xml',
            'Geometry/TrackerCommonData/data/trackermaterial.xml',
            'Geometry/TrackerCommonData/data/PhaseII/Tracker_DD4hep_compatible_2021_02/tracker.xml',
            'Geometry/TrackerCommonData/data/PhaseII/OuterTracker616_2020_04/otst.xml',
            'Geometry/TrackerCommonData/data/PhaseII/Tracker_DD4hep_compatible_2021_02/pixel.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/trackerbar.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/trackerfwd.xml',
            'Geometry/TrackerCommonData/data/PhaseII/Tracker_DD4hep_compatible_2021_02/trackerStructureTopology.xml',
            'Geometry/TrackerCommonData/data/PhaseII/Tracker_DD4hep_compatible_2021_02/pixelStructureTopology.xml',
            'Geometry/TrackerSimData/data/PhaseII/Tracker_DD4hep_compatible_2021_02/trackersens.xml',
            'Geometry/TrackerSimData/data/PhaseII/Tracker_DD4hep_compatible_2021_02/pixelsens.xml',
            'Geometry/TrackerRecoData/data/PhaseII/Tracker_DD4hep_compatible_2021_02/trackerRecoMaterial.xml',
            'SimTracker/TrackerMaterialAnalysis/data/trackingMaterialGroups_ForPhaseII/v1/trackingMaterialGroups_ForPhaseII.xml',
            'Geometry/TrackerSimData/data/PhaseII/Tracker_DD4hep_compatible_2021_02/trackerProdCuts.xml',
            'Geometry/TrackerSimData/data/PhaseII/Tracker_DD4hep_compatible_2021_02/pixelProdCuts.xml',
            'Geometry/TrackerSimData/data/trackerProdCutsBEAM.xml',
        ],
        "sim" : [
            'from Geometry.TrackerNumberingBuilder.trackerNumberingGeometry_cff import *',
            'from SLHCUpgradeSimulations.Geometry.fakePhase2OuterTrackerConditions_cff import *',
        ],
        "reco" : [
            'from Geometry.CommonTopologies.globalTrackingGeometry_cfi import *',
            'from RecoTracker.GeometryESProducer.TrackerRecoGeometryESProducer_cfi import *',
            'from Geometry.TrackerGeometryBuilder.trackerParameters_cff import *',
            'from Geometry.TrackerNumberingBuilder.trackerTopology_cfi import *',
            'from Geometry.TrackerGeometryBuilder.idealForDigiTrackerGeometry_cff import *',
            'trackerGeometry.applyAlignment = True',
        ],
        "era" : "phase2_tracker, trackingPhase2PU140",
    },
    "T32" : {
        1 : [
            'Geometry/TrackerCommonData/data/PhaseII/trackerParameters.xml',
            'Geometry/TrackerCommonData/data/pixfwdCommon.xml',
            'Geometry/TrackerCommonData/data/PhaseII/Tracker_DD4hep_compatible_2021_02/pixfwd.xml',
            'Geometry/TrackerCommonData/data/PhaseII/Tracker_DD4hep_compatible_OT800_IT615_2022_10/pixbar.xml',
            'Geometry/TrackerCommonData/data/trackermaterial.xml',
            'Geometry/TrackerCommonData/data/PhaseII/Tracker_DD4hep_compatible_2021_02/tracker.xml',
            'Geometry/TrackerCommonData/data/PhaseII/OuterTracker616_2020_04/otst.xml',
            'Geometry/TrackerCommonData/data/PhaseII/Tracker_DD4hep_compatible_IT702_2021_03/pixel.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/trackerbar.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/trackerfwd.xml',
            'Geometry/TrackerCommonData/data/PhaseII/Tracker_DD4hep_compatible_2021_02/trackerStructureTopology.xml',
            'Geometry/TrackerCommonData/data/PhaseII/Tracker_DD4hep_compatible_IT702_2021_03/pixelStructureTopology.xml',
            'Geometry/TrackerSimData/data/PhaseII/Tracker_DD4hep_compatible_2021_02/trackersens.xml',
            'Geometry/TrackerSimData/data/PhaseII/Tracker_DD4hep_compatible_IT702_2021_03/pixelsens.xml',
            'Geometry/TrackerRecoData/data/PhaseII/Tracker_DD4hep_compatible_IT702_2021_03/trackerRecoMaterial.xml',
            'SimTracker/TrackerMaterialAnalysis/data/trackingMaterialGroups_ForPhaseII/v2/trackingMaterialGroups_ForPhaseII.xml',
            'Geometry/TrackerSimData/data/PhaseII/Tracker_DD4hep_compatible_2021_02/trackerProdCuts.xml',
            'Geometry/TrackerSimData/data/PhaseII/Tracker_DD4hep_compatible_IT702_2021_03/pixelProdCuts.xml',
            'Geometry/TrackerSimData/data/trackerProdCutsBEAM.xml',
        ],
        "sim" : [
            'from Geometry.TrackerNumberingBuilder.trackerNumberingGeometry_cff import *',
            'from SLHCUpgradeSimulations.Geometry.fakePhase2OuterTrackerConditions_cff import *',
        ],
        "reco" : [
            'from Geometry.CommonTopologies.globalTrackingGeometry_cfi import *',
            'from RecoTracker.GeometryESProducer.TrackerRecoGeometryESProducer_cfi import *',
            'from Geometry.TrackerGeometryBuilder.trackerParameters_cff import *',
            'from Geometry.TrackerNumberingBuilder.trackerTopology_cfi import *',
            'from Geometry.TrackerGeometryBuilder.idealForDigiTrackerGeometry_cff import *',
            'trackerGeometry.applyAlignment = True',
        ],
        "era" : "phase2_tracker, phase2_3DPixels, trackingPhase2PU140",
    },
    "T33" : {
        1 : [
            'Geometry/TrackerCommonData/data/PhaseII/trackerParameters.xml',
            'Geometry/TrackerCommonData/data/pixfwdCommon.xml',
            'Geometry/TrackerCommonData/data/PhaseII/Tracker_DD4hep_compatible_2021_02/pixfwd.xml',
            'Geometry/TrackerCommonData/data/PhaseII/Tracker_DD4hep_compatible_OT800_IT615_2022_10/pixbar.xml',
            'Geometry/TrackerCommonData/data/trackermaterial.xml',
            'Geometry/TrackerCommonData/data/PhaseII/Tracker_DD4hep_compatible_2021_02/tracker.xml',
            'Geometry/TrackerCommonData/data/PhaseII/OuterTracker616_2020_04/otst.xml',
            'Geometry/TrackerCommonData/data/PhaseII/Tracker_DD4hep_compatible_IT711_2023_05V1/pixel.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/trackerbar.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/trackerfwd.xml',
            'Geometry/TrackerCommonData/data/PhaseII/Tracker_DD4hep_compatible_2021_02/trackerStructureTopology.xml',
            'Geometry/TrackerCommonData/data/PhaseII/Tracker_DD4hep_compatible_IT711_2023_05/pixelStructureTopology.xml',
            'Geometry/TrackerSimData/data/PhaseII/Tracker_DD4hep_compatible_2021_02/trackersens.xml',
            'Geometry/TrackerSimData/data/PhaseII/Tracker_DD4hep_compatible_IT711_2023_05/pixelsens.xml',
            'Geometry/TrackerRecoData/data/PhaseII/Tracker_DD4hep_compatible_IT711_2023_05/trackerRecoMaterial.xml',
            'Geometry/TrackerSimData/data/PhaseII/Tracker_DD4hep_compatible_2021_02/trackerProdCuts.xml',
            'Geometry/TrackerSimData/data/PhaseII/Tracker_DD4hep_compatible_IT711_2023_05/pixelProdCuts.xml',
            'Geometry/TrackerSimData/data/trackerProdCutsBEAM.xml',
        ],
        "sim" : [
            'from Geometry.TrackerNumberingBuilder.trackerNumberingGeometry_cff import *',
            'from SLHCUpgradeSimulations.Geometry.fakePhase2OuterTrackerConditions_cff import *',
        ],
        "reco" : [
            'from Geometry.CommonTopologies.globalTrackingGeometry_cfi import *',
            'from RecoTracker.GeometryESProducer.TrackerRecoGeometryESProducer_cfi import *',
            'from Geometry.TrackerGeometryBuilder.trackerParameters_cff import *',
            'from Geometry.TrackerNumberingBuilder.trackerTopology_cfi import *',
            'from Geometry.TrackerGeometryBuilder.idealForDigiTrackerGeometry_cff import *',
            'trackerGeometry.applyAlignment = True',
        ],
        "era" : "phase2_tracker, phase2_3DPixels, trackingPhase2PU140",
    },

}


caloDict = {
    "abbrev" : "C",
    "name" : "calo",
    "default" : 18,
    "C17" : {
        1 : [
            'Geometry/EcalCommonData/data/eregalgo/2026/v2/eregalgo.xml',
            'Geometry/EcalCommonData/data/ectkcable/2026/v1/ectkcable.xml',
            'Geometry/EcalCommonData/data/ectkcablemat/2026/v2/ectkcablemat.xml',
            'Geometry/EcalCommonData/data/ebalgo.xml',
            'Geometry/EcalCommonData/data/ebcon/2021/v1/ebcon.xml',
            'Geometry/EcalCommonData/data/ebrot.xml',
            'Geometry/HcalCommonData/data/hcalrotations.xml',
            'Geometry/HcalCommonData/data/hcal/v2/hcalalgo.xml',
            'Geometry/HcalCommonData/data/hcalbarrelalgo.xml',
            'Geometry/HcalCommonData/data/hcalcablealgo/v2/hcalcablealgo.xml',
            'Geometry/HcalCommonData/data/hcalouteralgo/v1/hcalouteralgo.xml',
            'Geometry/HcalCommonData/data/hcalforwardalgo.xml',
            'Geometry/HcalCommonData/data/hcalSimNumbering/NoHE/v1/hcalSimNumbering.xml',
            'Geometry/HcalCommonData/data/hcalRecNumbering/NoHE/v2/hcalRecNumbering.xml',
            'Geometry/HcalCommonData/data/average/hcalforwardmaterial.xml',
            'Geometry/HGCalCommonData/data/hgcalMaterial/v2/hgcalMaterial.xml',
            'Geometry/HGCalCommonData/data/hgcal/v16/hgcal.xml',
            'Geometry/HGCalCommonData/data/hgcalcell/v16/hgcalcell.xml',
            'Geometry/HGCalCommonData/data/hgcalwafer/v16/hgcalwafer.xml',
            'Geometry/HGCalCommonData/data/hgcalEE/v16/hgcalEE.xml',
            'Geometry/HGCalCommonData/data/hgcalHEsil/v16/hgcalHEsil.xml',
            'Geometry/HGCalCommonData/data/hgcalHEmix/v16/hgcalHEmix.xml',
            'Geometry/HGCalCommonData/data/hgcalCons/v16/hgcalCons.xml',
            'Geometry/HGCalCommonData/data/hgcalConsData/v16/hgcalConsData.xml',
        ],
        3 : [
            'Geometry/EcalSimData/data/PhaseII/ecalsens.xml',
            'Geometry/HcalCommonData/data/hcalsens/NoHE/v1/hcalsenspmf.xml',
            'Geometry/HcalSimData/data/hf.xml',
            'Geometry/HcalSimData/data/hfpmt.xml',
            'Geometry/HcalSimData/data/hffibrebundle.xml',
            'Geometry/HcalSimData/data/CaloUtil/2026/v2c/CaloUtil.xml',
            'Geometry/HGCalSimData/data/hgcsensv15.xml',
        ],
        4 : [
            'Geometry/HcalSimData/data/HcalProdCuts/2026/v1/HcalProdCuts.xml',
            'Geometry/EcalSimData/data/EcalProdCuts.xml',
            'Geometry/HGCalSimData/data/hgcProdCutsv15.xml',
        ],
        "sim" : [
            'from Geometry.EcalCommonData.ecalSimulationParameters_cff import *',
            'from Geometry.HcalCommonData.hcalDDDSimConstants_cff import *',
            'from Geometry.HGCalCommonData.hgcalParametersInitialization_cfi import *',
            'from Geometry.HGCalCommonData.hgcalNumberingInitialization_cfi import *'
        ],
        "reco" : [
            'from Geometry.CaloEventSetup.HGCalTopology_cfi import *',
            'from Geometry.HGCalGeometry.HGCalGeometryESProducer_cfi import *',
            'from Geometry.CaloEventSetup.CaloTopology_cfi import *',
            'from Geometry.CaloEventSetup.CaloGeometryBuilder_cfi import *',
            'CaloGeometryBuilder = cms.ESProducer("CaloGeometryBuilder",',
            '    SelectedCalos = cms.vstring("HCAL",',
            '                                "ZDC",',
            '                                "EcalBarrel",',
            '                                "TOWER",',
            '                                "HGCalEESensitive",',
            '                                "HGCalHESiliconSensitive",',
            '                                "HGCalHEScintillatorSensitive"',
            '    )',
            ')',
            'from Geometry.EcalAlgo.EcalBarrelGeometry_cfi import *',
            'from Geometry.HcalEventSetup.HcalGeometry_cfi import *',
            'from Geometry.HcalEventSetup.CaloTowerGeometry_cfi import *',
            'from Geometry.HcalEventSetup.CaloTowerTopology_cfi import *',
            'from Geometry.HcalCommonData.hcalDDDRecConstants_cfi import *',
            'from Geometry.HcalEventSetup.hcalTopologyIdeal_cfi import *',
            'from Geometry.CaloEventSetup.EcalTrigTowerConstituents_cfi import *',
            'from Geometry.EcalMapping.EcalMapping_cfi import *',
            'from Geometry.EcalMapping.EcalMappingRecord_cfi import *',
        ],
        "era" : "phase2_ecal, phase2_hcal, phase2_hgcal, hcalHardcodeConditions, phase2_hgcalV10, phase2_hgcalV11, phase2_hgcalV16, phase2_hfnose",
    },
    "C18" : {
        1 : [
            'Geometry/EcalCommonData/data/eregalgo/2026/v2/eregalgo.xml',
            'Geometry/EcalCommonData/data/ectkcable/2026/v1/ectkcable.xml',
            'Geometry/EcalCommonData/data/ectkcablemat/2026/v2/ectkcablemat.xml',
            'Geometry/EcalCommonData/data/ebalgo.xml',
            'Geometry/EcalCommonData/data/ebcon/2021/v1/ebcon.xml',
            'Geometry/EcalCommonData/data/ebrot.xml',
            'Geometry/HcalCommonData/data/hcalrotations.xml',
            'Geometry/HcalCommonData/data/average/hcalforwardmaterial.xml',
            'Geometry/HcalCommonData/data/hcal/v2/hcalalgo.xml',
            'Geometry/HcalCommonData/data/hcalbarrelalgo.xml',
            'Geometry/HcalCommonData/data/hcalcablealgo/v2/hcalcablealgo.xml',
            'Geometry/HcalCommonData/data/hcalouteralgo/v1/hcalouteralgo.xml',
            'Geometry/HcalCommonData/data/hcalforwardalgo.xml',
            'Geometry/HcalCommonData/data/hcalSimNumbering/NoHE/v1/hcalSimNumbering.xml',
            'Geometry/HcalCommonData/data/hcalRecNumbering/NoHE/v2/hcalRecNumbering.xml',
            'Geometry/HGCalCommonData/data/hgcalMaterial/v2/hgcalMaterial.xml',
            'Geometry/HGCalCommonData/data/hgcal/v17/hgcal.xml',
            'Geometry/HGCalCommonData/data/hgcalcell/v17/hgcalcell.xml',
            'Geometry/HGCalCommonData/data/hgcalwafer/v17/hgcalwafer.xml',
            'Geometry/HGCalCommonData/data/hgcalEE/v17/hgcalEE.xml',
            'Geometry/HGCalCommonData/data/hgcalHEsil/v17/hgcalHEsil.xml',
            'Geometry/HGCalCommonData/data/hgcalHEmix/v17/hgcalHEmix.xml',
            'Geometry/HGCalCommonData/data/hgcalCons/v17/hgcalCons.xml',
            'Geometry/HGCalCommonData/data/hgcalConsData/v17/hgcalConsData.xml',
        ],
        3 : [
            'Geometry/EcalSimData/data/PhaseII/ecalsens.xml',
            'Geometry/HcalCommonData/data/hcalsens/NoHE/v1/hcalsenspmf.xml',
            'Geometry/HcalSimData/data/hf.xml',
            'Geometry/HcalSimData/data/hfpmt.xml',
            'Geometry/HcalSimData/data/hffibrebundle.xml',
            'Geometry/HcalSimData/data/CaloUtil/2026/v2c/CaloUtil.xml',
            'Geometry/HGCalSimData/data/hgcsensv15.xml',
        ],
        4 : [
            'Geometry/HcalSimData/data/HcalProdCuts/2026/v1/HcalProdCuts.xml',
            'Geometry/EcalSimData/data/EcalProdCuts.xml',
            'Geometry/HGCalSimData/data/hgcProdCutsv15.xml',
        ],
        "sim" : [
            'from Geometry.EcalCommonData.ecalSimulationParameters_cff import *',
            'from Geometry.HcalCommonData.hcalDDDSimConstants_cff import *',
            'from Geometry.HGCalCommonData.hgcalParametersInitialization_cfi import *',
            'from Geometry.HGCalCommonData.hgcalNumberingInitialization_cfi import *'
        ],
        "reco" : [
            'from Geometry.CaloEventSetup.HGCalTopology_cfi import *',
            'from Geometry.HGCalGeometry.HGCalGeometryESProducer_cfi import *',
            'from Geometry.CaloEventSetup.CaloTopology_cfi import *',
            'from Geometry.CaloEventSetup.CaloGeometryBuilder_cfi import *',
            'CaloGeometryBuilder = cms.ESProducer("CaloGeometryBuilder",',
            '    SelectedCalos = cms.vstring("HCAL",',
            '                                "ZDC",',
            '                                "EcalBarrel",',
            '                                "TOWER",',
            '                                "HGCalEESensitive",',
            '                                "HGCalHESiliconSensitive",',
            '                                "HGCalHEScintillatorSensitive"',
            '    )',
            ')',
            'from Geometry.EcalAlgo.EcalBarrelGeometry_cfi import *',
            'from Geometry.HcalEventSetup.HcalGeometry_cfi import *',
            'from Geometry.HcalEventSetup.CaloTowerGeometry_cfi import *',
            'from Geometry.HcalEventSetup.CaloTowerTopology_cfi import *',
            'from Geometry.HcalCommonData.hcalDDDRecConstants_cfi import *',
            'from Geometry.HcalEventSetup.hcalTopologyIdeal_cfi import *',
            'from Geometry.CaloEventSetup.EcalTrigTowerConstituents_cfi import *',
            'from Geometry.EcalMapping.EcalMapping_cfi import *',
            'from Geometry.EcalMapping.EcalMappingRecord_cfi import *',
        ],
        "era" : "phase2_ecal, phase2_hcal, phase2_hgcal, hcalHardcodeConditions, phase2_hgcalV10, phase2_hgcalV11, phase2_hgcalV16, phase2_hfnose",
    },
    "C19" : {
        1 : [
            'Geometry/EcalCommonData/data/eregalgo/2026/v2/eregalgo.xml',
            'Geometry/EcalCommonData/data/ectkcable/2026/v1/ectkcable.xml',
            'Geometry/EcalCommonData/data/ectkcablemat/2026/v2/ectkcablemat.xml',
            'Geometry/EcalCommonData/data/ebalgo.xml',
            'Geometry/EcalCommonData/data/ebcon/2021/v1/ebcon.xml',
            'Geometry/EcalCommonData/data/ebrot.xml',
            'Geometry/HcalCommonData/data/hcalrotations.xml',
            'Geometry/HcalCommonData/data/average/hcalforwardmaterial.xml',
            'Geometry/HcalCommonData/data/hcal/v2/hcalalgo.xml',
            'Geometry/HcalCommonData/data/hcalbarrelalgo.xml',
            'Geometry/HcalCommonData/data/hcalcablealgo/v2/hcalcablealgo.xml',
            'Geometry/HcalCommonData/data/hcalouteralgo/v1/hcalouteralgo.xml',
            'Geometry/HcalCommonData/data/hcalforwardalgo.xml',
            'Geometry/HcalCommonData/data/hcalSimNumbering/NoHE/v1/hcalSimNumbering.xml',
            'Geometry/HcalCommonData/data/hcalRecNumbering/NoHE/v2/hcalRecNumbering.xml',
            'Geometry/HGCalCommonData/data/hgcalMaterial/v2/hgcalMaterial.xml',
            'Geometry/HGCalCommonData/data/hgcal/v17/hgcal.xml',
            'Geometry/HGCalCommonData/data/hgcalwafer/v17n/hgcalwafer.xml',
            'Geometry/HGCalCommonData/data/hgcalEE/v17/hgcalEE.xml',
            'Geometry/HGCalCommonData/data/hgcalHEsil/v17/hgcalHEsil.xml',
            'Geometry/HGCalCommonData/data/hgcalHEmix/v17/hgcalHEmix.xml',
            'Geometry/HGCalCommonData/data/hgcalCons/v17n/hgcalCons.xml',
            'Geometry/HGCalCommonData/data/hgcalConsData/v17/hgcalConsData.xml',
        ],
        3 : [
            'Geometry/EcalSimData/data/PhaseII/ecalsens.xml',
            'Geometry/HcalCommonData/data/hcalsens/NoHE/v1/hcalsenspmf.xml',
            'Geometry/HcalSimData/data/hf.xml',
            'Geometry/HcalSimData/data/hfpmt.xml',
            'Geometry/HcalSimData/data/hffibrebundle.xml',
            'Geometry/HcalSimData/data/CaloUtil/2026/v2c/CaloUtil.xml',
            'Geometry/HGCalSimData/data/hgcsensv17n.xml',
        ],
        4 : [
            'Geometry/HcalSimData/data/HcalProdCuts/2026/v1/HcalProdCuts.xml',
            'Geometry/EcalSimData/data/EcalProdCuts.xml',
            'Geometry/HGCalSimData/data/hgcProdCutsv15.xml',
        ],
        "sim" : [
            'from Geometry.EcalCommonData.ecalSimulationParameters_cff import *',
            'from Geometry.HcalCommonData.hcalDDDSimConstants_cff import *',
            'from Geometry.HGCalCommonData.hgcalParametersInitialization_cfi import *',
            'from Geometry.HGCalCommonData.hgcalNumberingInitialization_cfi import *'
        ],
        "reco" : [
            'from Geometry.CaloEventSetup.HGCalTopology_cfi import *',
            'from Geometry.HGCalGeometry.HGCalGeometryESProducer_cfi import *',
            'from Geometry.CaloEventSetup.CaloTopology_cfi import *',
            'from Geometry.CaloEventSetup.CaloGeometryBuilder_cfi import *',
            'CaloGeometryBuilder = cms.ESProducer("CaloGeometryBuilder",',
            '    SelectedCalos = cms.vstring("HCAL",',
            '                                "ZDC",',
            '                                "EcalBarrel",',
            '                                "TOWER",',
            '                                "HGCalEESensitive",',
            '                                "HGCalHESiliconSensitive",',
            '                                "HGCalHEScintillatorSensitive"',
            '    )',
            ')',
            'from Geometry.EcalAlgo.EcalBarrelGeometry_cfi import *',
            'from Geometry.HcalEventSetup.HcalGeometry_cfi import *',
            'from Geometry.HcalEventSetup.CaloTowerGeometry_cfi import *',
            'from Geometry.HcalEventSetup.CaloTowerTopology_cfi import *',
            'from Geometry.HcalCommonData.hcalDDDRecConstants_cfi import *',
            'from Geometry.HcalEventSetup.hcalTopologyIdeal_cfi import *',
            'from Geometry.CaloEventSetup.EcalTrigTowerConstituents_cfi import *',
            'from Geometry.EcalMapping.EcalMapping_cfi import *',
            'from Geometry.EcalMapping.EcalMappingRecord_cfi import *',
        ],
        "era" : "phase2_ecal, phase2_hcal, phase2_hgcal, hcalHardcodeConditions, phase2_hgcalV10, phase2_hgcalV11, phase2_hgcalV16, phase2_hfnose",
    },
    "C20" : {
        1 : [
            'Geometry/EcalCommonData/data/eregalgo/2026/v2/eregalgo.xml',
            'Geometry/EcalCommonData/data/ectkcable/2026/v1/ectkcable.xml',
            'Geometry/EcalCommonData/data/ectkcablemat/2026/v2/ectkcablemat.xml',
            'Geometry/EcalCommonData/data/ebalgo.xml',
            'Geometry/EcalCommonData/data/ebcon/2021/v1/ebcon.xml',
            'Geometry/EcalCommonData/data/ebrot.xml',
            'Geometry/HcalCommonData/data/hcalrotations.xml',
            'Geometry/HcalCommonData/data/average/hcalforwardmaterial.xml',
            'Geometry/HcalCommonData/data/hcal/v2/hcalalgo.xml',
            'Geometry/HcalCommonData/data/hcalbarrelalgo.xml',
            'Geometry/HcalCommonData/data/hcalcablealgo/v2/hcalcablealgo.xml',
            'Geometry/HcalCommonData/data/hcalouteralgo/v1/hcalouteralgo.xml',
            'Geometry/HcalCommonData/data/hcalforwardalgo.xml',
            'Geometry/HcalCommonData/data/hcalSimNumbering/NoHE/v1/hcalSimNumbering.xml',
            'Geometry/HcalCommonData/data/hcalRecNumbering/NoHE/v2/hcalRecNumbering.xml',
            'Geometry/HGCalCommonData/data/hgcalMaterial/v2/hgcalMaterial.xml',
            'Geometry/HGCalCommonData/data/hgcal/v17/hgcal.xml',
            'Geometry/HGCalCommonData/data/hgcalcell/v17/hgcalcell.xml',
            'Geometry/HGCalCommonData/data/hgcalwafer/v17/hgcalwafer.xml',
            'Geometry/HGCalCommonData/data/hgcalEE/v17/hgcalEE.xml',
            'Geometry/HGCalCommonData/data/hgcalHEsil/v17/hgcalHEsil.xml',
            'Geometry/HGCalCommonData/data/hgcalHEmix/v17/hgcalHEmix.xml',
            'Geometry/HGCalCommonData/data/hgcalCons/v17/hgcalCons.xml',
            'Geometry/HGCalCommonData/data/hgcalConsData/v17/hgcalConsData.xml',
            'Geometry/ForwardCommonData/data/hfnose/v4/hfnose.xml',
            'Geometry/ForwardCommonData/data/hfnoseCell/v1/hfnoseCell.xml',
            'Geometry/ForwardCommonData/data/hfnoseWafer/v1/hfnoseWafer.xml',
            'Geometry/ForwardCommonData/data/hfnoseLayer/v2/hfnoseLayer.xml',
            'Geometry/ForwardCommonData/data/hfnoseCons/v1m/hfnoseCons.xml',
        ],
        3 : [
            'Geometry/EcalSimData/data/PhaseII/ecalsens.xml',
            'Geometry/HcalCommonData/data/hcalsens/NoHE/v1/hcalsenspmf.xml',
            'Geometry/HcalSimData/data/hf.xml',
            'Geometry/HcalSimData/data/hfpmt.xml',
            'Geometry/HcalSimData/data/hffibrebundle.xml',
            'Geometry/HcalSimData/data/CaloUtil/2026/v5c/CaloUtil.xml',
            'Geometry/HGCalSimData/data/hgcsensv15.xml',
            'Geometry/ForwardSimData/data/hfnosesens.xml',
        ],
        4 : [
            'Geometry/HcalSimData/data/HcalProdCuts/2026/v1/HcalProdCuts.xml',
            'Geometry/EcalSimData/data/EcalProdCuts.xml',
            'Geometry/HGCalSimData/data/hgcProdCutsv15.xml',
            'Geometry/ForwardSimData/data/hfnoseProdCuts.xml',
        ],
        "sim" : [
            'from Geometry.EcalCommonData.ecalSimulationParameters_cff import *',
            'from Geometry.HcalCommonData.hcalDDDSimConstants_cff import *',
            'from Geometry.HGCalCommonData.hgcalParametersInitialization_cfi import *',
            'from Geometry.HGCalCommonData.hgcalNumberingInitialization_cfi import *',
            'from Geometry.ForwardCommonData.hfnoseParametersInitialization_cfi import *',
            'from Geometry.ForwardCommonData.hfnoseNumberingInitialization_cfi  import *',
        ],
        "reco" : [
            'from Geometry.CaloEventSetup.HGCalTopology_cfi import *',
            'from Geometry.HGCalGeometry.HGCalGeometryESProducer_cfi import *',
            'from Geometry.CaloEventSetup.HFNoseTopology_cfi import *',
            'from Geometry.ForwardGeometry.HFNoseGeometryESProducer_cfi import *',
            'from Geometry.CaloEventSetup.CaloTopology_cfi import *',
            'from Geometry.CaloEventSetup.CaloGeometryBuilder_cfi import *',
            'CaloGeometryBuilder = cms.ESProducer("CaloGeometryBuilder",',
            '    SelectedCalos = cms.vstring("HCAL",',
            '                                "ZDC",',
            '                                "EcalBarrel",',
            '                                "TOWER",',
            '                                "HGCalEESensitive",',
            '                                "HGCalHESiliconSensitive",',
            '                                "HGCalHEScintillatorSensitive",',
            '                                "HGCalHFNoseSensitive",',
            '    )',
            ')',
            'from Geometry.EcalAlgo.EcalBarrelGeometry_cfi import *',
            'from Geometry.HcalEventSetup.HcalGeometry_cfi import *',
            'from Geometry.HcalEventSetup.CaloTowerGeometry_cfi import *',
            'from Geometry.HcalEventSetup.CaloTowerTopology_cfi import *',
            'from Geometry.HcalCommonData.hcalDDDRecConstants_cfi import *',
            'from Geometry.HcalEventSetup.hcalTopologyIdeal_cfi import *',
            'from Geometry.CaloEventSetup.EcalTrigTowerConstituents_cfi import *',
            'from Geometry.EcalMapping.EcalMapping_cfi import *',
            'from Geometry.EcalMapping.EcalMappingRecord_cfi import *',
        ],
        "era" : "phase2_ecal, phase2_hcal, phase2_hgcal, hcalHardcodeConditions, phase2_hgcalV10, phase2_hgcalV11, phase2_hgcalV16, phase2_hfnose",
    },
    "C21" : {
        1 : [
            'Geometry/EcalCommonData/data/eregalgo/2026/v2/eregalgo.xml',
            'Geometry/EcalCommonData/data/ectkcable/2026/v1/ectkcable.xml',
            'Geometry/EcalCommonData/data/ectkcablemat/2026/v2/ectkcablemat.xml',
            'Geometry/EcalCommonData/data/ebalgo.xml',
            'Geometry/EcalCommonData/data/ebcon/2021/v1/ebcon.xml',
            'Geometry/EcalCommonData/data/ebrot.xml',
            'Geometry/HcalCommonData/data/hcalrotations.xml',
            'Geometry/HcalCommonData/data/average/hcalforwardmaterial.xml',
            'Geometry/HcalCommonData/data/hcal/v2/hcalalgo.xml',
            'Geometry/HcalCommonData/data/hcalbarrelalgo.xml',
            'Geometry/HcalCommonData/data/hcalcablealgo/v2/hcalcablealgo.xml',
            'Geometry/HcalCommonData/data/hcalouteralgo/v1/hcalouteralgo.xml',
            'Geometry/HcalCommonData/data/hcalforwardalgo.xml',
            'Geometry/HcalCommonData/data/hcalSimNumbering/NoHE/v1/hcalSimNumbering.xml',
            'Geometry/HcalCommonData/data/hcalRecNumbering/NoHE/v2/hcalRecNumbering.xml',
            'Geometry/HGCalCommonData/data/hgcalMaterial/v2/hgcalMaterial.xml',
            'Geometry/HGCalCommonData/data/hgcal/v17ng/hgcal.xml',
            'Geometry/HGCalCommonData/data/hgcalwafer/v17ng/hgcalwafer.xml',
            'Geometry/HGCalCommonData/data/hgcalEE/v17/hgcalEE.xml',
            'Geometry/HGCalCommonData/data/hgcalHEsil/v17/hgcalHEsil.xml',
            'Geometry/HGCalCommonData/data/hgcalHEmix/v17/hgcalHEmix.xml',
            'Geometry/HGCalCommonData/data/hgcalCons/v17n/hgcalCons.xml',
            'Geometry/HGCalCommonData/data/hgcalConsData/v17/hgcalConsData.xml',
        ],
        3 : [
            'Geometry/EcalSimData/data/PhaseII/ecalsens.xml',
            'Geometry/HcalCommonData/data/hcalsens/NoHE/v1/hcalsenspmf.xml',
            'Geometry/HcalSimData/data/hf.xml',
            'Geometry/HcalSimData/data/hfpmt.xml',
            'Geometry/HcalSimData/data/hffibrebundle.xml',
            'Geometry/HcalSimData/data/CaloUtil/2026/v2c/CaloUtil.xml',
            'Geometry/HGCalSimData/data/hgcsensv17n.xml',
        ],
        4 : [
            'Geometry/HcalSimData/data/HcalProdCuts/2026/v1/HcalProdCuts.xml',
            'Geometry/EcalSimData/data/EcalProdCuts.xml',
            'Geometry/HGCalSimData/data/hgcProdCutsv15.xml',
        ],
        "sim" : [
            'from Geometry.EcalCommonData.ecalSimulationParameters_cff import *',
            'from Geometry.HcalCommonData.hcalDDDSimConstants_cff import *',
            'from Geometry.HGCalCommonData.hgcalParametersInitialization_cfi import *',
            'from Geometry.HGCalCommonData.hgcalNumberingInitialization_cfi import *'
        ],
        "reco" : [
            'from Geometry.CaloEventSetup.HGCalTopology_cfi import *',
            'from Geometry.HGCalGeometry.HGCalGeometryESProducer_cfi import *',
            'from Geometry.CaloEventSetup.CaloTopology_cfi import *',
            'from Geometry.CaloEventSetup.CaloGeometryBuilder_cfi import *',
            'CaloGeometryBuilder = cms.ESProducer("CaloGeometryBuilder",',
            '    SelectedCalos = cms.vstring("HCAL",',
            '                                "ZDC",',
            '                                "EcalBarrel",',
            '                                "TOWER",',
            '                                "HGCalEESensitive",',
            '                                "HGCalHESiliconSensitive",',
            '                                "HGCalHEScintillatorSensitive"',
            '    )',
            ')',
            'from Geometry.EcalAlgo.EcalBarrelGeometry_cfi import *',
            'from Geometry.HcalEventSetup.HcalGeometry_cfi import *',
            'from Geometry.HcalEventSetup.CaloTowerGeometry_cfi import *',
            'from Geometry.HcalEventSetup.CaloTowerTopology_cfi import *',
            'from Geometry.HcalCommonData.hcalDDDRecConstants_cfi import *',
            'from Geometry.HcalEventSetup.hcalTopologyIdeal_cfi import *',
            'from Geometry.CaloEventSetup.EcalTrigTowerConstituents_cfi import *',
            'from Geometry.EcalMapping.EcalMapping_cfi import *',
            'from Geometry.EcalMapping.EcalMappingRecord_cfi import *',
        ],
        "era" : "phase2_ecal, phase2_hcal, phase2_hgcal, hcalHardcodeConditions, phase2_hgcalV10, phase2_hgcalV11, phase2_hgcalV16, phase2_hfnose",
    },

}

muonDict = {
    "abbrev" : "M",
    "name" : "muon",
    "default" : 10,
    "M10" : {
        1 : [
            'Geometry/MuonCommonData/data/mbCommon/2021/v1/mbCommon.xml',
            'Geometry/MuonCommonData/data/mb1/2015/v2/mb1.xml',
            'Geometry/MuonCommonData/data/mb2/2015/v2/mb2.xml',
            'Geometry/MuonCommonData/data/mb3/2015/v2/mb3.xml',
            'Geometry/MuonCommonData/data/mb4/2015/v2/mb4.xml',
            'Geometry/MuonCommonData/data/mb4Shield/2021/v1/mb4Shield.xml',
            'Geometry/MuonCommonData/data/muonYoke/2026/v3/muonYoke.xml',
            'Geometry/MuonCommonData/data/mf/2026/v8/mf.xml',
            'Geometry/MuonCommonData/data/csc/2021/v2/csc.xml',
            'Geometry/MuonCommonData/data/rpcf/2026/v3/rpcf.xml',
            'Geometry/MuonCommonData/data/gemf/TDR_BaseLine/gemf.xml',
            'Geometry/MuonCommonData/data/gem11/TDR_BaseLine/gem11.xml',
            'Geometry/MuonCommonData/data/gem21/TDR_Eta16/gem21.xml',
            'Geometry/MuonCommonData/data/mfshield/2026/v6/mfshield.xml',
            'Geometry/MuonCommonData/data/ge0/TDR_Dev/v4/ge0.xml',
            'Geometry/MuonCommonData/data/ge0shield/2026/v1/ge0shield.xml',
         ],
        2 : [
            'Geometry/MuonCommonData/data/muonNumbering/TDR_DeV/v5/muonNumbering.xml',
        ],
        3 : [
            'Geometry/MuonSimData/data/PhaseII/v2/muonSens.xml',
            'Geometry/DTGeometryBuilder/data/dtSpecsFilter/2021/v1/dtSpecsFilter.xml',
            'Geometry/CSCGeometryBuilder/data/cscSpecsFilter.xml',
            'Geometry/CSCGeometryBuilder/data/cscSpecs.xml',
            'Geometry/RPCGeometryBuilder/data/2026/v1/RPCSpecs.xml',
            'Geometry/GEMGeometryBuilder/data/v12/GEMSpecsFilter.xml',
            'Geometry/GEMGeometryBuilder/data/v12/GEMSpecs.xml',
        ],
        4 : [
            'Geometry/MuonSimData/data/muonProdCuts/2026/v2/muonProdCuts.xml',
        ],
        "sim" : [
            'from Geometry.MuonNumbering.muonGeometryConstants_cff import *',
            'from Geometry.MuonNumbering.muonOffsetESProducer_cff import *',
        ],
        "reco" : [
            'from Geometry.MuonNumbering.muonNumberingInitialization_cfi import *',
            'from RecoMuon.DetLayers.muonDetLayerGeometry_cfi import *',
            'from Geometry.GEMGeometryBuilder.gemGeometry_cff import *',
            'from Geometry.CSCGeometryBuilder.idealForDigiCscGeometry_cff import *',
            'from Geometry.DTGeometryBuilder.idealForDigiDtGeometry_cff import *',
        ],
        "era" : "phase2_muon, phase2_GEM, phase2_GE0",
    },
}

forwardDict = {
    "abbrev" : "F",
    "name" : "forward",
    "default" : 8,
    "F8" : {
        1 : [
            'Geometry/ForwardCommonData/data/forwardshield/2026/v4/forwardshield.xml',
            'Geometry/ForwardCommonData/data/zdcmaterials/2021/v1/zdcmaterials.xml',
            'Geometry/ForwardCommonData/data/lumimaterials.xml',
            'Geometry/ForwardCommonData/data/zdcrotations.xml',
            'Geometry/ForwardCommonData/data/lumirotations.xml',
            'Geometry/ForwardCommonData/data/zdc/2026/v1/zdc.xml',
            'Geometry/ForwardCommonData/data/zdclumi/2021/v2/zdclumi.xml',
            'Geometry/ForwardCommonData/data/cmszdc.xml',
        ],
        3 : [
            'Geometry/ForwardSimData/data/zdcsens.xml',
        ],
        4 : [
            'Geometry/ForwardSimData/data/zdcProdCuts/2021/v2/zdcProdCuts.xml',
            'Geometry/ForwardSimData/data/ForwardShieldProdCuts.xml',
        ],
        "reco" :[
            'from Geometry.ForwardGeometry.ZdcGeometry_cfi import *',
        ]
    },
}

timingDict = {
    "abbrev" : "I",
    "name" : "timing",
    "default" : 15,
    "I14" : {
        1 : [
           'Geometry/MTDCommonData/data/mtdMaterial/v3/mtdMaterial.xml',
           'Geometry/MTDCommonData/data/btl/v1/btl.xml',
           'Geometry/MTDCommonData/data/etl/v6/etl.xml',
           'Geometry/MTDCommonData/data/mtdParameters/v3/mtdStructureTopology.xml',
           'Geometry/MTDCommonData/data/mtdParameters/v2/mtdParameters.xml',
           ],
       3 : [
           'Geometry/MTDSimData/data/v2/mtdsens.xml'
           ],
       4 : [
           'Geometry/MTDSimData/data/v2/mtdProdCuts.xml'
           ],
       "sim" : [
           'from Geometry.MTDNumberingBuilder.mtdNumberingGeometry_cff import *',
           ],
       "reco" :[
           'from RecoMTD.DetLayers.mtdDetLayerGeometry_cfi import *',
           'from Geometry.MTDGeometryBuilder.mtdParameters_cff import *',
           'from Geometry.MTDNumberingBuilder.mtdNumberingGeometry_cff import *',
           'from Geometry.MTDNumberingBuilder.mtdTopology_cfi import *',
           'from Geometry.MTDGeometryBuilder.mtdGeometry_cfi import *',
           'from Geometry.MTDGeometryBuilder.idealForDigiMTDGeometry_cff import *',
           'mtdGeometry.applyAlignment = False'
           ],
       "era" : "phase2_timing, phase2_timing_layer, phase2_etlV4",
    },
    "I15" : {
        1 : [
           'Geometry/MTDCommonData/data/mtdMaterial/v3/mtdMaterial.xml',
           'Geometry/MTDCommonData/data/btl/v1/btl.xml',
           'Geometry/MTDCommonData/data/etl/v7/etl.xml',
           'Geometry/MTDCommonData/data/mtdParameters/v3/mtdStructureTopology.xml',
           'Geometry/MTDCommonData/data/mtdParameters/v2/mtdParameters.xml',
           ],
       3 : [
           'Geometry/MTDSimData/data/v2/mtdsens.xml'
           ],
       4 : [
           'Geometry/MTDSimData/data/v2/mtdProdCuts.xml'
           ],
       "sim" : [
           'from Geometry.MTDNumberingBuilder.mtdNumberingGeometry_cff import *',
           ],
       "reco" :[
           'from RecoMTD.DetLayers.mtdDetLayerGeometry_cfi import *',
           'from Geometry.MTDGeometryBuilder.mtdParameters_cff import *',
           'from Geometry.MTDNumberingBuilder.mtdNumberingGeometry_cff import *',
           'from Geometry.MTDNumberingBuilder.mtdTopology_cfi import *',
           'from Geometry.MTDGeometryBuilder.mtdGeometry_cfi import *',
           'from Geometry.MTDGeometryBuilder.idealForDigiMTDGeometry_cff import *',
           'mtdGeometry.applyAlignment = False'
           ],
       "era" : "phase2_timing, phase2_timing_layer, phase2_etlV4",
    },
    "I16" : {
        1 : [
           'Geometry/MTDCommonData/data/mtdMaterial/v3/mtdMaterial.xml',
           'Geometry/MTDCommonData/data/btl/v2/btl.xml',
           'Geometry/MTDCommonData/data/etl/v7/etl.xml',
           'Geometry/MTDCommonData/data/mtdParameters/v4/mtdStructureTopology.xml',
           'Geometry/MTDCommonData/data/mtdParameters/v4/mtdParameters.xml',
           ],
       3 : [
           'Geometry/MTDSimData/data/v4/mtdsens.xml'
           ],
       4 : [
           'Geometry/MTDSimData/data/v4/mtdProdCuts.xml'
           ],
       "sim" : [
           'from Geometry.MTDNumberingBuilder.mtdNumberingGeometry_cff import *',
           ],
       "reco" :[
           'from RecoMTD.DetLayers.mtdDetLayerGeometry_cfi import *',
           'from Geometry.MTDGeometryBuilder.mtdParameters_cff import *',
           'from Geometry.MTDNumberingBuilder.mtdNumberingGeometry_cff import *',
           'from Geometry.MTDNumberingBuilder.mtdTopology_cfi import *',
           'from Geometry.MTDGeometryBuilder.mtdGeometry_cfi import *',
           'from Geometry.MTDGeometryBuilder.idealForDigiMTDGeometry_cff import *',
           'mtdGeometry.applyAlignment = False'
           ],
       "era" : "phase2_timing, phase2_timing_layer, phase2_etlV4",
    },
}

allDicts = [ commonDict, trackerDict, caloDict, muonDict, forwardDict, timingDict ]

detectorVersionDict = {
    ("O8","T24","C17","M10","F8","I14") : "D86",
    ("O9","T24","C17","M10","F8","I15") : "D88",
    ("O9","T30","C17","M10","F8","I15") : "D91",
    ("O9","T24","C18","M10","F8","I15") : "D92",
    ("O9","T24","C19","M10","F8","I15") : "D93",
    ("O9","T24","C20","M10","F8","I15") : "D94",
    ("O9","T31","C17","M10","F8","I16") : "D95",
    ("O9","T31","C18","M10","F8","I16") : "D96",
    ("O9","T25","C17","M10","F8","I15") : "D97",
    ("O9","T32","C17","M10","F8","I16") : "D98",
    ("O9","T32","C18","M10","F8","I16") : "D99",
    ("O9","T33","C17","M10","F8","I15") : "D100",
    ("O9","T32","C21","M10","F8","I15") : "D101",
}

deprecatedDets = set([ "D1", "D2", "D3", "D5", "D6" , "D7", "D4", "D8" , "D9", "D12", "D13", "D15", "D10", "D11", "D14", "D16", "D17", "D18", "D19", "D20", "D21", "D22", "D23", "D24", "D25", "D26", "D27", "D28", "D29", "D30", "D31", "D32", "D33", "D34", "D36", "D37", "D38", "D39", "D40", "D42", "D35", "D41", "D43", "D44", "D45", "D46", "D48", "D47", "D50", "D51", "D52", "D53", "D54", "D55", "D56", "D57", "D58", "D59", "D61", "D62", "D63", "D64", "D65", "D66", "D67", "D69", "D71", "D72", "D73", "D74", "D75", "D78", "D79", "D87", "D89", "D90", "D49", "D60", "D68", "D70", "D76", "D77", "D80", "D81", "D82", "D83", "D84", "D85"])
deprecatedSubdets = set([ "T1", "T2" ,"T3", "T4", "T5", "T6", "T7", "T8", "T9", "T10", "T11", "T12", "T13", "T14", "T15", "T16", "T17", "T18", "T19", "T20", "T21", "T22", "T23", "T26", "T27", "T28", "T29", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "C10", "C11", "C12", "C13", "C14", "C15", "C16", "M1", "M2", "M3", "M4", "M5", "M6", "M7", "M8", "M9", "I1", "I2", "I3", "I4", "I5", "I6", "I7", "I8", "I9", "I10", "I11", "I12", "I13", "O1", "O2", "O3", "O4", "O5", "O6", "O7", "F1", "F2", "F3", "F4", "F5", "F6", "F7"])
