maxsections = 5

commonDict = {
    "abbrev" : "O",
    "name" : "common",
    "default" : 2,
    "O2" : {
        1 : [
            'Geometry/CMSCommonData/data/materials.xml',
            'Geometry/CMSCommonData/data/rotations.xml',
            'Geometry/CMSCommonData/data/extend/v2/cmsextent.xml',
            'Geometry/CMSCommonData/data/cms/2023/v1/cms.xml',
            'Geometry/CMSCommonData/data/eta3/etaMax.xml',        
            'Geometry/CMSCommonData/data/cmsMother.xml',
            'Geometry/CMSCommonData/data/cmsTracker.xml',
            'Geometry/CMSCommonData/data/caloBase/2023/v1/caloBase.xml',
            'Geometry/CMSCommonData/data/cmsCalo.xml',
            'Geometry/CMSCommonData/data/muonBase/2023/v2/muonBase.xml',
            'Geometry/CMSCommonData/data/cmsMuon.xml',
            'Geometry/CMSCommonData/data/mgnt.xml',
            'Geometry/CMSCommonData/data/beampipe/2023/v1/beampipe.xml',
            'Geometry/CMSCommonData/data/cmsBeam/2023/v1/cmsBeam.xml',
            'Geometry/CMSCommonData/data/muonMB.xml',
            'Geometry/CMSCommonData/data/muonMagnet.xml',
            'Geometry/CMSCommonData/data/cavern/2017/v2/cavern.xml',
            'Geometry/CMSCommonData/data/cavernData/2017/v1/cavernData.xml',
            'Geometry/CMSCommonData/data/cavernFloor/2017/v1/cavernFloor.xml',
        ],
        5 : [
            'Geometry/CMSCommonData/data/FieldParameters.xml',
        ],
        "era" : "run2_common, run3_common, phase2_common",
    }    
}

trackerDict = {
    "abbrev" : "T",
    "name" : "tracker",
    "default" : 5,
    "T5" : {
        1 : [
            'Geometry/TrackerCommonData/data/PhaseII/trackerParameters.xml',
            'Geometry/TrackerCommonData/data/pixfwdCommon.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker4025/pixfwd.xml', 
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker4025/pixbar.xml', 
            'Geometry/TrackerCommonData/data/trackermaterial.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker4025/tracker.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker4025/pixel.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker4025/trackerbar.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker4025/trackerfwd.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker4025/trackerStructureTopology.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker4025/pixelStructureTopology.xml',
            'Geometry/TrackerSimData/data/PhaseII/TiltedTracker4025/trackersens.xml',
            'Geometry/TrackerSimData/data/PhaseII/TiltedTracker4025/pixelsens.xml',
            'Geometry/TrackerRecoData/data/PhaseII/TiltedTracker4025/trackerRecoMaterial.xml',
            'Geometry/TrackerSimData/data/PhaseII/TiltedTracker4025/trackerProdCuts.xml',
            'Geometry/TrackerSimData/data/PhaseII/TiltedTracker4025/pixelProdCuts.xml',
            'Geometry/TrackerSimData/data/trackerProdCutsBEAM.xml',
        ],
        "sim" : [
            'from Geometry.TrackerNumberingBuilder.trackerNumberingGeometry_cfi import *',
            'from SLHCUpgradeSimulations.Geometry.fakeConditions_phase2TkT5_cff import *',
        ],
        "reco" : [
            'from Geometry.CommonDetUnit.globalTrackingGeometry_cfi import *',
            'from RecoTracker.GeometryESProducer.TrackerRecoGeometryESProducer_cfi import *',
            'from Geometry.TrackerGeometryBuilder.trackerParameters_cfi import *',
            'from Geometry.TrackerNumberingBuilder.trackerTopology_cfi import *',
            'from Geometry.TrackerGeometryBuilder.idealForDigiTrackerGeometry_cff import *',
            'trackerGeometry.applyAlignment = cms.bool(False)',
        ],
        "era" : "phase2_tracker, trackingPhase2PU140",
    },
    "T6" : {
        1 : [
            'Geometry/TrackerCommonData/data/PhaseII/trackerParameters.xml',
            'Geometry/TrackerCommonData/data/pixfwdCommon.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/pixfwd.xml', 
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/pixbar.xml', 
            'Geometry/TrackerCommonData/data/trackermaterial.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/otst.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/tracker.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/pixel.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/trackerbar.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/trackerfwd.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/trackerStructureTopology.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/pixelStructureTopology.xml',
            'Geometry/TrackerSimData/data/PhaseII/TiltedTracker404/trackersens.xml',
            'Geometry/TrackerSimData/data/PhaseII/TiltedTracker404/pixelsens.xml',
            'Geometry/TrackerRecoData/data/PhaseII/TiltedTracker404/trackerRecoMaterial.xml',
            'Geometry/TrackerSimData/data/PhaseII/TiltedTracker404/trackerProdCuts.xml',
            'Geometry/TrackerSimData/data/PhaseII/TiltedTracker404/pixelProdCuts.xml',
            'Geometry/TrackerSimData/data/trackerProdCutsBEAM.xml',
        ],
        "sim" : [
            'from Geometry.TrackerNumberingBuilder.trackerNumberingGeometry_cfi import *',
            'from SLHCUpgradeSimulations.Geometry.fakeConditions_phase2TkT6_cff import *',
        ],
        "reco" : [
            'from Geometry.CommonDetUnit.globalTrackingGeometry_cfi import *',
            'from RecoTracker.GeometryESProducer.TrackerRecoGeometryESProducer_cfi import *',
            'from Geometry.TrackerGeometryBuilder.trackerParameters_cfi import *',
            'from Geometry.TrackerNumberingBuilder.trackerTopology_cfi import *',
            'from Geometry.TrackerGeometryBuilder.idealForDigiTrackerGeometry_cff import *',
            'trackerGeometry.applyAlignment = cms.bool(False)',
        ],
        "era" : "phase2_tracker, trackingPhase2PU140",
    },       
    "T7" : {
        1 : [
            'Geometry/TrackerCommonData/data/PhaseII/trackerParameters.xml',
            'Geometry/TrackerCommonData/data/pixfwdCommon.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/pixfwd.xml', 
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/pixbar.xml', 
            'Geometry/TrackerCommonData/data/trackermaterial.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/tracker.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker420/pixel.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/trackerbar.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/trackerfwd.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/trackerStructureTopology.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker420/pixelStructureTopology.xml',
            'Geometry/TrackerSimData/data/PhaseII/TiltedTracker404/trackersens.xml',
            'Geometry/TrackerSimData/data/PhaseII/TiltedTracker404/pixelsens.xml',
            'Geometry/TrackerRecoData/data/PhaseII/TiltedTracker420/trackerRecoMaterial.xml',
            'Geometry/TrackerSimData/data/PhaseII/TiltedTracker404/trackerProdCuts.xml',
            'Geometry/TrackerSimData/data/PhaseII/TiltedTracker404/pixelProdCuts.xml',
            'Geometry/TrackerSimData/data/trackerProdCutsBEAM.xml',
        ],
        "sim" : [
            'from Geometry.TrackerNumberingBuilder.trackerNumberingGeometry_cfi import *',
            'from SLHCUpgradeSimulations.Geometry.fakeConditions_phase2TkT7_cff import *',
        ],
        "reco" : [
            'from Geometry.CommonDetUnit.globalTrackingGeometry_cfi import *',
            'from RecoTracker.GeometryESProducer.TrackerRecoGeometryESProducer_cfi import *',
            'from Geometry.TrackerGeometryBuilder.trackerParameters_cfi import *',
            'from Geometry.TrackerNumberingBuilder.trackerTopology_cfi import *',
            'from Geometry.TrackerGeometryBuilder.idealForDigiTrackerGeometry_cff import *',
            'trackerGeometry.applyAlignment = cms.bool(False)',
        ],
        "era" : "phase2_tracker, trackingPhase2PU140",
    },       
    "T8" : {
        1 : [
            'Geometry/TrackerCommonData/data/PhaseII/trackerParameters.xml',
            'Geometry/TrackerCommonData/data/pixfwdCommon.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/pixfwd.xml', 
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/pixbar.xml', 
            'Geometry/TrackerCommonData/data/trackermaterial.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/tracker.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker421/pixel.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/trackerbar.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/trackerfwd.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/trackerStructureTopology.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker421/pixelStructureTopology.xml',
            'Geometry/TrackerSimData/data/PhaseII/TiltedTracker404/trackersens.xml',
            'Geometry/TrackerSimData/data/PhaseII/TiltedTracker404/pixelsens.xml',
            'Geometry/TrackerRecoData/data/PhaseII/TiltedTracker421/trackerRecoMaterial.xml',
            'Geometry/TrackerSimData/data/PhaseII/TiltedTracker404/trackerProdCuts.xml',
            'Geometry/TrackerSimData/data/PhaseII/TiltedTracker404/pixelProdCuts.xml',
            'Geometry/TrackerSimData/data/trackerProdCutsBEAM.xml',
        ],
        "sim" : [
            'from Geometry.TrackerNumberingBuilder.trackerNumberingGeometry_cfi import *',
            'from SLHCUpgradeSimulations.Geometry.fakeConditions_phase2TkT8_cff import *',
        ],
        "reco" : [
            'from Geometry.CommonDetUnit.globalTrackingGeometry_cfi import *',
            'from RecoTracker.GeometryESProducer.TrackerRecoGeometryESProducer_cfi import *',
            'from Geometry.TrackerGeometryBuilder.trackerParameters_cfi import *',
            'from Geometry.TrackerNumberingBuilder.trackerTopology_cfi import *',
            'from Geometry.TrackerGeometryBuilder.idealForDigiTrackerGeometry_cff import *',
            'trackerGeometry.applyAlignment = cms.bool(False)',
        ],
        "era" : "phase2_tracker, trackingPhase2PU140",
    },       
    "T9" : {
        1 : [
            'Geometry/TrackerCommonData/data/PhaseII/trackerParameters.xml',
            'Geometry/TrackerCommonData/data/pixfwdCommon.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker4025/pixfwd.xml', 
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker4025/pixbar.xml', 
            'Geometry/TrackerCommonData/data/trackermaterial.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker4025TwentyPercent/tracker.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker4025TwentyPercent/pixel.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker4025/trackerbar.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker4025/trackerfwd.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker4025/trackerStructureTopology.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker4025/pixelStructureTopology.xml',
            'Geometry/TrackerSimData/data/PhaseII/TiltedTracker4025/trackersens.xml',
            'Geometry/TrackerSimData/data/PhaseII/TiltedTracker4025/pixelsens.xml',
            'Geometry/TrackerRecoData/data/PhaseII/TiltedTracker4025TwentyPercent/trackerRecoMaterial.xml',
            'Geometry/TrackerSimData/data/PhaseII/TiltedTracker4025/trackerProdCuts.xml',
            'Geometry/TrackerSimData/data/PhaseII/TiltedTracker4025/pixelProdCuts.xml',
            'Geometry/TrackerSimData/data/trackerProdCutsBEAM.xml',
        ],
        "sim" : [
            'from Geometry.TrackerNumberingBuilder.trackerNumberingGeometry_cfi import *',
            'from SLHCUpgradeSimulations.Geometry.fakeConditions_phase2TkT5_cff import *',
        ],
        "reco" : [
            'from Geometry.CommonDetUnit.globalTrackingGeometry_cfi import *',
            'from RecoTracker.GeometryESProducer.TrackerRecoGeometryESProducer_cfi import *',
            'from Geometry.TrackerGeometryBuilder.trackerParameters_cfi import *',
            'from Geometry.TrackerNumberingBuilder.trackerTopology_cfi import *',
            'from Geometry.TrackerGeometryBuilder.idealForDigiTrackerGeometry_cff import *',
            'trackerGeometry.applyAlignment = cms.bool(False)',
        ],
        "era" : "phase2_tracker, trackingPhase2PU140",
    },
    "T10" : {
        1 : [
            'Geometry/TrackerCommonData/data/PhaseII/trackerParameters.xml',
            'Geometry/TrackerCommonData/data/pixfwdCommon.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker4025/pixfwd.xml', 
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker4025/pixbar.xml', 
            'Geometry/TrackerCommonData/data/trackermaterial.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker4025FiftyPercent/tracker.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker4025FiftyPercent/pixel.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker4025/trackerbar.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker4025/trackerfwd.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker4025/trackerStructureTopology.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker4025/pixelStructureTopology.xml',
            'Geometry/TrackerSimData/data/PhaseII/TiltedTracker4025/trackersens.xml',
            'Geometry/TrackerSimData/data/PhaseII/TiltedTracker4025/pixelsens.xml',
            'Geometry/TrackerRecoData/data/PhaseII/TiltedTracker4025FiftyPercent/trackerRecoMaterial.xml',
            'Geometry/TrackerSimData/data/PhaseII/TiltedTracker4025/trackerProdCuts.xml',
            'Geometry/TrackerSimData/data/PhaseII/TiltedTracker4025/pixelProdCuts.xml',
            'Geometry/TrackerSimData/data/trackerProdCutsBEAM.xml',
        ],
        "sim" : [
            'from Geometry.TrackerNumberingBuilder.trackerNumberingGeometry_cfi import *',
            'from SLHCUpgradeSimulations.Geometry.fakeConditions_phase2TkT5_cff import *',
        ],
        "reco" : [
            'from Geometry.CommonDetUnit.globalTrackingGeometry_cfi import *',
            'from RecoTracker.GeometryESProducer.TrackerRecoGeometryESProducer_cfi import *',
            'from Geometry.TrackerGeometryBuilder.trackerParameters_cfi import *',
            'from Geometry.TrackerNumberingBuilder.trackerTopology_cfi import *',
            'from Geometry.TrackerGeometryBuilder.idealForDigiTrackerGeometry_cff import *',
            'trackerGeometry.applyAlignment = cms.bool(False)',
        ],
        "era" : "phase2_tracker, trackingPhase2PU140",
    },
    "T11" : {
        1 : [
            'Geometry/TrackerCommonData/data/PhaseII/trackerParameters.xml',
            'Geometry/TrackerCommonData/data/pixfwdCommon.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/pixfwd.xml', 
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/pixbar.xml', 
            'Geometry/TrackerCommonData/data/trackermaterial.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/otst.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/tracker.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/pixel.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/trackerbar.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/trackerfwd.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/trackerStructureTopology.xml',
            'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker405/pixelStructureTopology.xml',
            'Geometry/TrackerSimData/data/PhaseII/TiltedTracker404/trackersens.xml',
            'Geometry/TrackerSimData/data/PhaseII/TiltedTracker404/pixelsens.xml',
            'Geometry/TrackerRecoData/data/PhaseII/TiltedTracker404/trackerRecoMaterial.xml',
            'Geometry/TrackerSimData/data/PhaseII/TiltedTracker404/trackerProdCuts.xml',
            'Geometry/TrackerSimData/data/PhaseII/TiltedTracker404/pixelProdCuts.xml',
            'Geometry/TrackerSimData/data/trackerProdCutsBEAM.xml',
        ],
        "sim" : [
            'from Geometry.TrackerNumberingBuilder.trackerNumberingGeometry_cfi import *',
            'from SLHCUpgradeSimulations.Geometry.fakeConditions_phase2TkT6_cff import *',
        ],
        "reco" : [
            'from Geometry.CommonDetUnit.globalTrackingGeometry_cfi import *',
            'from RecoTracker.GeometryESProducer.TrackerRecoGeometryESProducer_cfi import *',
            'from Geometry.TrackerGeometryBuilder.trackerParameters_cfi import *',
            'from Geometry.TrackerNumberingBuilder.trackerTopology_cfi import *',
            'from Geometry.TrackerGeometryBuilder.idealForDigiTrackerGeometry_cff import *',
            'trackerGeometry.applyAlignment = cms.bool(False)',
        ],
        "era" : "phase2_tracker, trackingPhase2PU140",
    }       
}

caloDict = {
    "abbrev" : "C",
    "name" : "calo",
    "default" : 3,
    "C3" : {
        1 : [
            'Geometry/EcalCommonData/data/ectkcable.xml',
            'Geometry/EcalCommonData/data/PhaseII/eregalgo.xml',
            'Geometry/EcalCommonData/data/ebalgo.xml',
            'Geometry/EcalCommonData/data/ebcon.xml',
            'Geometry/EcalCommonData/data/ebrot.xml',
            'Geometry/EcalCommonData/data/eecon.xml',
            'Geometry/EcalCommonData/data/PhaseII/escon.xml',
            'Geometry/EcalCommonData/data/PhaseII/esalgo.xml',
            'Geometry/HcalCommonData/data/hcalrotations.xml',
            'Geometry/HcalCommonData/data/hcal/HGCal/hcalalgo.xml',
            'Geometry/HcalCommonData/data/hcalbarrelalgo.xml',
            'Geometry/HcalCommonData/data/hcalendcap/SSAbsorber/hcalendcapalgo.xml',
            'Geometry/HcalCommonData/data/hcalouteralgo.xml',
            'Geometry/HcalCommonData/data/hcalforwardalgo.xml',
            'Geometry/HcalCommonData/data/hcalSimNumbering/2023/hcalSimNumbering.xml',
            'Geometry/HcalCommonData/data/hcalRecNumbering/2023/hcalRecNumbering.xml',
            'Geometry/HcalCommonData/data/average/hcalforwardmaterial.xml',
            'Geometry/HGCalCommonData/data/hgcal/v8/hgcal.xml',
            'Geometry/HGCalCommonData/data/hgcalEE/v8/hgcalEE.xml',
            'Geometry/HGCalCommonData/data/hgcalHEsil/v8/hgcalHEsil.xml',
            'Geometry/HGCalCommonData/data/hgcalwafer/v7/hgcalwafer.xml',
            'Geometry/HGCalCommonData/data/hgcalCons/v8/hgcalCons.xml',
        ],
        3 : [
            'Geometry/EcalSimData/data/PhaseII/ecalsens.xml',
            'Geometry/HcalCommonData/data/hcalsens/HGCal/hcalsenspmf.xml',
            'Geometry/HcalSimData/data/hf.xml',
            'Geometry/HcalSimData/data/hfpmt.xml',
            'Geometry/HcalSimData/data/hffibrebundle.xml',
            'Geometry/HcalSimData/data/CaloUtil.xml',
            'Geometry/HGCalSimData/data/hgcsensv8.xml',
            'Geometry/HGCalSimData/data/hgccons.xml',
            'Geometry/HGCalSimData/data/hgcProdCuts.xml',
        ],
        4 : [
            'Geometry/HcalSimData/data/HcalProdCuts.xml',
            'Geometry/EcalSimData/data/EcalProdCuts.xml',
        ],
        "sim" : [
            'from Geometry.HcalCommonData.hcalParameters_cfi      import *',
            'from Geometry.HcalCommonData.hcalDDDSimConstants_cfi import *',
            'from Geometry.HGCalCommonData.hgcalV6ParametersInitialization_cfi import *',
            'from Geometry.HGCalCommonData.hgcalV6NumberingInitialization_cfi import *'
        ],
        "reco" : [
            'from Geometry.CaloEventSetup.HGCalV6Topology_cfi import *',
            'from Geometry.HGCalGeometry.HGCalV6GeometryESProducer_cfi import *',
            'from Geometry.CaloEventSetup.CaloTopology_cfi import *',
            'from Geometry.CaloEventSetup.CaloGeometryBuilder_cfi import *',
            'CaloGeometryBuilder = cms.ESProducer("CaloGeometryBuilder",',
            '    SelectedCalos = cms.vstring("HCAL"                   ,',
            '                                "ZDC"                    ,',
            '                                "EcalBarrel"             ,',
            '                                "TOWER"                  ,',
            '                                "HGCalEESensitive"       ,',
            '                                "HGCalHESiliconSensitive" ',
            '    )',
            ')',
            'from Geometry.EcalAlgo.EcalBarrelGeometry_cfi import *',
            'from Geometry.HcalEventSetup.HcalGeometry_cfi import *',
            'from Geometry.HcalEventSetup.CaloTowerGeometry_cfi import *',
            'from Geometry.HcalEventSetup.CaloTowerTopology_cfi import *',
            'from Geometry.HcalCommonData.hcalDDDRecConstants_cfi import *',
            'from Geometry.HcalEventSetup.hcalTopologyIdeal_cfi import *',
            'from Geometry.CaloEventSetup.EcalTrigTowerConstituents_cfi import *',
            'from Geometry.EcalMapping.EcalMapping_cfi import *',
            'from Geometry.EcalMapping.EcalMappingRecord_cfi import *',
        ],
        "era" : "run2_HE_2017, run2_HF_2017, run2_HCAL_2017, run3_HB, phase2_hcal, phase2_hgcal, hcalHardcodeConditions, hcalSkipPacker",
    },

    "C4" : {
        1 : [
            'Geometry/EcalCommonData/data/ectkcable.xml',
            'Geometry/EcalCommonData/data/PhaseII/eregalgo.xml',
            'Geometry/EcalCommonData/data/ebalgo.xml',
            'Geometry/EcalCommonData/data/ebcon.xml',
            'Geometry/EcalCommonData/data/ebrot.xml',
            'Geometry/EcalCommonData/data/eecon.xml',
            'Geometry/EcalCommonData/data/PhaseII/escon.xml',
            'Geometry/EcalCommonData/data/PhaseII/esalgo.xml',
            'Geometry/HcalCommonData/data/hcalrotations.xml',
            'Geometry/HcalCommonData/data/hcal/NoHE/hcalalgo.xml',
            'Geometry/HcalCommonData/data/hcalbarrelalgo.xml',
            'Geometry/HcalCommonData/data/hcalouteralgo.xml',
            'Geometry/HcalCommonData/data/hcalforwardalgo.xml',
            'Geometry/HcalCommonData/data/hcalSimNumbering/NoHE/hcalSimNumbering.xml',
            'Geometry/HcalCommonData/data/hcalRecNumbering/NoHE/hcalRecNumbering.xml',
            'Geometry/HcalCommonData/data/average/hcalforwardmaterial.xml',
            'Geometry/HGCalCommonData/data/hgcal/v9/hgcal.xml',
            'Geometry/HGCalCommonData/data/hgcalEE/v9/hgcalEE.xml',
            'Geometry/HGCalCommonData/data/hgcalHEsil/v9/hgcalHEsil.xml',
            'Geometry/HGCalCommonData/data/hgcalHEmix/v9/hgcalHEmix.xml',
            'Geometry/HGCalCommonData/data/hgcalwafer/v9/hgcalwafer.xml',
            'Geometry/HGCalCommonData/data/hgcalcell/v9/hgcalcell.xml',
            'Geometry/HGCalCommonData/data/hgcalCons/v9/hgcalCons.xml',
        ],
        3 : [
            'Geometry/EcalSimData/data/PhaseII/ecalsens.xml',
            'Geometry/HcalCommonData/data/hcalsens/NoHE/hcalsenspmf.xml',
            'Geometry/HcalSimData/data/hf.xml',
            'Geometry/HcalSimData/data/hfpmt.xml',
            'Geometry/HcalSimData/data/hffibrebundle.xml',
            'Geometry/HcalSimData/data/CaloUtil.xml',
            'Geometry/HGCalSimData/data/hgcsensv9.xml',
        ],
        4 : [
            'Geometry/HcalSimData/data/HcalProdCuts.xml',
            'Geometry/EcalSimData/data/EcalProdCuts.xml',
            'Geometry/HGCalSimData/data/hgcProdCutsv9.xml',
        ],
        "sim" : [
            'from Geometry.HcalCommonData.hcalParameters_cfi      import *',
            'from Geometry.HcalCommonData.hcalDDDSimConstants_cfi import *',
            'from Geometry.HGCalCommonData.hgcalParametersInitialization_cfi import *',
            'from Geometry.HGCalCommonData.hgcalNumberingInitialization_cfi import *'
        ],
        "reco" : [
            'from Geometry.CaloEventSetup.HGCalV9Topology_cfi import *',
            'from Geometry.HGCalGeometry.HGCalGeometryESProducer_cfi import *',
            'from Geometry.CaloEventSetup.CaloTopology_cfi import *',
            'from Geometry.CaloEventSetup.CaloGeometryBuilder_cfi import *',
            'CaloGeometryBuilder = cms.ESProducer("CaloGeometryBuilder",',
            '    SelectedCalos = cms.vstring("HCAL",',
            '                                "ZDC",',
            '                                "EcalBarrel",',
            '                                "TOWER",',
            '                                "HGCalEESensitive",',
            '                                "HGCalHESiliconSensitive",',
            '                                "HGCalHEScintillatorSensitive"',
            '    )',
            ')',
            'from Geometry.EcalAlgo.EcalBarrelGeometry_cfi import *',
            'from Geometry.HcalEventSetup.HcalGeometry_cfi import *',
            'from Geometry.HcalEventSetup.CaloTowerGeometry_cfi import *',
            'from Geometry.HcalEventSetup.CaloTowerTopology_cfi import *',
            'from Geometry.HcalCommonData.hcalDDDRecConstants_cfi import *',
            'from Geometry.HcalEventSetup.hcalTopologyIdeal_cfi import *',
            'from Geometry.CaloEventSetup.EcalTrigTowerConstituents_cfi import *',
            'from Geometry.EcalMapping.EcalMapping_cfi import *',
            'from Geometry.EcalMapping.EcalMappingRecord_cfi import *',
        ],
        "era" : "run2_HE_2017, run2_HF_2017, run2_HCAL_2017, run3_HB, phase2_hcal, phase2_hgcal, hcalHardcodeConditions, hcalSkipPacker",
    },

    "C5" : {
        1 : [
            'Geometry/EcalCommonData/data/ectkcable.xml',
            'Geometry/EcalCommonData/data/PhaseII/eregalgo.xml',
            'Geometry/EcalCommonData/data/ebalgo.xml',
            'Geometry/EcalCommonData/data/ebcon.xml',
            'Geometry/EcalCommonData/data/ebrot.xml',
            'Geometry/EcalCommonData/data/eecon.xml',
            'Geometry/EcalCommonData/data/PhaseII/escon.xml',
            'Geometry/EcalCommonData/data/PhaseII/esalgo.xml',
            'Geometry/HcalCommonData/data/hcalrotations.xml',
            'Geometry/HcalCommonData/data/hcal/NoHE/hcalalgo.xml',
            'Geometry/HcalCommonData/data/hcalbarrelalgo.xml',
            'Geometry/HcalCommonData/data/hcalouteralgo.xml',
            'Geometry/HcalCommonData/data/hcalforwardalgo.xml',
            'Geometry/HcalCommonData/data/hcalSimNumbering/NoHE/hcalSimNumbering.xml',
            'Geometry/HcalCommonData/data/hcalRecNumbering/NoHE/hcalRecNumbering.xml',
            'Geometry/HcalCommonData/data/average/hcalforwardmaterial.xml',
            'Geometry/HGCalCommonData/data/hgcal/v9/hgcal.xml',
            'Geometry/HGCalCommonData/data/hgcalEE/v9/hgcalEE.xml',
            'Geometry/HGCalCommonData/data/hgcalHEsil/v9/hgcalHEsil.xml',
            'Geometry/HGCalCommonData/data/hgcalHEmix/v9/hgcalHEmix.xml',
            'Geometry/HGCalCommonData/data/hgcalwafer/v9/hgcalwafer.xml',
            'Geometry/HGCalCommonData/data/hgcalcell/v9/hgcalcell.xml',
            'Geometry/HGCalCommonData/data/hgcalCons/v9p/hgcalCons.xml',
        ],
        3 : [
            'Geometry/EcalSimData/data/PhaseII/ecalsens.xml',
            'Geometry/HcalCommonData/data/hcalsens/NoHE/hcalsenspmf.xml',
            'Geometry/HcalSimData/data/hf.xml',
            'Geometry/HcalSimData/data/hfpmt.xml',
            'Geometry/HcalSimData/data/hffibrebundle.xml',
            'Geometry/HcalSimData/data/CaloUtil.xml',
            'Geometry/HGCalSimData/data/hgcsensv9.xml',
        ],
        4 : [
            'Geometry/HcalSimData/data/HcalProdCuts.xml',
            'Geometry/EcalSimData/data/EcalProdCuts.xml',
            'Geometry/HGCalSimData/data/hgcProdCutsv9.xml',
        ],
        "sim" : [
            'from Geometry.HcalCommonData.hcalParameters_cfi      import *',
            'from Geometry.HcalCommonData.hcalDDDSimConstants_cfi import *',
            'from Geometry.HGCalCommonData.hgcalParametersInitialization_cfi import *',
            'from Geometry.HGCalCommonData.hgcalNumberingInitialization_cfi import *'
        ],
        "reco" : [
            'from Geometry.CaloEventSetup.HGCalV9Topology_cfi import *',
            'from Geometry.HGCalGeometry.HGCalGeometryESProducer_cfi import *',
            'from Geometry.CaloEventSetup.CaloTopology_cfi import *',
            'from Geometry.CaloEventSetup.CaloGeometryBuilder_cfi import *',
            'CaloGeometryBuilder = cms.ESProducer("CaloGeometryBuilder",',
            '    SelectedCalos = cms.vstring("HCAL",',
            '                                "ZDC",',
            '                                "EcalBarrel",',
            '                                "TOWER",',
            '                                "HGCalEESensitive",',
            '                                "HGCalHESiliconSensitive",',
            '                                "HGCalHEScintillatorSensitive"',
            '    )',
            ')',
            'from Geometry.EcalAlgo.EcalBarrelGeometry_cfi import *',
            'from Geometry.HcalEventSetup.HcalGeometry_cfi import *',
            'from Geometry.HcalEventSetup.CaloTowerGeometry_cfi import *',
            'from Geometry.HcalEventSetup.CaloTowerTopology_cfi import *',
            'from Geometry.HcalCommonData.hcalDDDRecConstants_cfi import *',
            'from Geometry.HcalEventSetup.hcalTopologyIdeal_cfi import *',
            'from Geometry.CaloEventSetup.EcalTrigTowerConstituents_cfi import *',
            'from Geometry.EcalMapping.EcalMapping_cfi import *',
            'from Geometry.EcalMapping.EcalMappingRecord_cfi import *',
        ],
        "era" : "run2_HE_2017, run2_HF_2017, run2_HCAL_2017, run3_HB, phase2_hcal, phase2_hgcal, hcalHardcodeConditions, hcalSkipPacker",
    },

    "C6" : {
        1 : [
            'Geometry/EcalCommonData/data/ectkcable.xml',
            'Geometry/EcalCommonData/data/PhaseII/eregalgo.xml',
            'Geometry/EcalCommonData/data/ebalgo.xml',
            'Geometry/EcalCommonData/data/ebcon.xml',
            'Geometry/EcalCommonData/data/ebrot.xml',
            'Geometry/EcalCommonData/data/eecon.xml',
            'Geometry/EcalCommonData/data/PhaseII/escon.xml',
            'Geometry/EcalCommonData/data/PhaseII/esalgo.xml',
            'Geometry/HcalCommonData/data/hcalrotations.xml',
            'Geometry/HcalCommonData/data/hcal/NoHE/hcalalgo.xml',
            'Geometry/HcalCommonData/data/hcalbarrelalgo.xml',
            'Geometry/HcalCommonData/data/hcalouteralgo.xml',
            'Geometry/HcalCommonData/data/hcalforwardalgo.xml',
            'Geometry/HcalCommonData/data/hcalSimNumbering/NoHE/hcalSimNumbering.xml',
            'Geometry/HcalCommonData/data/hcalRecNumbering/NoHE/hcalRecNumbering.xml',
            'Geometry/HcalCommonData/data/average/hcalforwardmaterial.xml',
            'Geometry/HGCalCommonData/data/hgcal/v9/hgcal.xml',
            'Geometry/HGCalCommonData/data/hgcalEE/v9/hgcalEE.xml',
            'Geometry/HGCalCommonData/data/hgcalHEsil/v9/hgcalHEsil.xml',
            'Geometry/HGCalCommonData/data/hgcalHEmix/v9/hgcalHEmix.xml',
            'Geometry/HGCalCommonData/data/hgcalwafer/v9/hgcalwafer.xml',
            'Geometry/HGCalCommonData/data/hgcalcell/v9/hgcalcell.xml',
            'Geometry/HGCalCommonData/data/hgcalCons/v9/hgcalCons.xml',
            'Geometry/ForwardCommonData/data/hfnose/v1/hfnose.xml',
            'Geometry/ForwardCommonData/data/hfnoseWafer/v1/hfnoseWafer.xml',
            'Geometry/ForwardCommonData/data/hfnoseCell/v1/hfnoseCell.xml',
            'Geometry/ForwardCommonData/data/hfnoseCons/v1/hfnoseCons.xml',
        ],
        3 : [
            'Geometry/EcalSimData/data/PhaseII/ecalsens.xml',
            'Geometry/HcalCommonData/data/hcalsens/NoHE/hcalsenspmf.xml',
            'Geometry/HcalSimData/data/hf.xml',
            'Geometry/HcalSimData/data/hfpmt.xml',
            'Geometry/HcalSimData/data/hffibrebundle.xml',
            'Geometry/HcalSimData/data/CaloUtil.xml',
            'Geometry/HGCalSimData/data/hgcsensv9.xml',
            'Geometry/ForwardSimData/data/hfnosesens.xml',
        ],
        4 : [
            'Geometry/HcalSimData/data/HcalProdCuts.xml',
            'Geometry/EcalSimData/data/EcalProdCuts.xml',
            'Geometry/HGCalSimData/data/hgcProdCutsv9.xml',
            'Geometry/ForwardSimData/data/hfnoseProdCuts.xml',
        ],
        "sim" : [
            'from Geometry.HcalCommonData.hcalParameters_cfi      import *',
            'from Geometry.HcalCommonData.hcalDDDSimConstants_cfi import *',
            'from Geometry.HGCalCommonData.hgcalParametersInitialization_cfi import *',
            'from Geometry.HGCalCommonData.hgcalNumberingInitialization_cfi import *',
            'from Geometry.ForwardCommonData.hfnoseParametersInitialization_cfi import *',
            'from Geometry.ForwardCommonData.hfnoseNumberingInitialization_cfi  import *',
        ],
        "reco" : [
            'from Geometry.CaloEventSetup.HGCalV9Topology_cfi import *',
            'from Geometry.HGCalGeometry.HGCalGeometryESProducer_cfi import *',
            'from Geometry.CaloEventSetup.HFNoseTopology_cfi import *',
            'from Geometry.ForwardGeometry.HFNoseGeometryESProducer_cfi import *',
            'from Geometry.CaloEventSetup.CaloTopology_cfi import *',
            'from Geometry.CaloEventSetup.CaloGeometryBuilder_cfi import *',
            'CaloGeometryBuilder = cms.ESProducer("CaloGeometryBuilder",',
            '    SelectedCalos = cms.vstring("HCAL",',
            '                                "ZDC",',
            '                                "EcalBarrel",',
            '                                "TOWER",',
            '                                "HGCalEESensitive",',
            '                                "HGCalHESiliconSensitive",',
            '                                "HGCalHEScintillatorSensitive",',
            '                                "HGCalHFNoseSensitive",',
            '    )',
            ')',
            'from Geometry.EcalAlgo.EcalBarrelGeometry_cfi import *',
            'from Geometry.HcalEventSetup.HcalGeometry_cfi import *',
            'from Geometry.HcalEventSetup.CaloTowerGeometry_cfi import *',
            'from Geometry.HcalEventSetup.CaloTowerTopology_cfi import *',
            'from Geometry.HcalCommonData.hcalDDDRecConstants_cfi import *',
            'from Geometry.HcalEventSetup.hcalTopologyIdeal_cfi import *',
            'from Geometry.CaloEventSetup.EcalTrigTowerConstituents_cfi import *',
            'from Geometry.EcalMapping.EcalMapping_cfi import *',
            'from Geometry.EcalMapping.EcalMappingRecord_cfi import *',
        ],
        "era" : "run2_HE_2017, run2_HF_2017, run2_HCAL_2017, run3_HB, phase2_hcal, phase2_hgcal, hcalHardcodeConditions, hcalSkipPacker, phase2_hfnose",
    },

    "C7" : {
        1 : [
            'Geometry/EcalCommonData/data/ectkcable.xml',
            'Geometry/EcalCommonData/data/PhaseII/eregalgo.xml',
            'Geometry/EcalCommonData/data/ebalgo.xml',
            'Geometry/EcalCommonData/data/ebcon.xml',
            'Geometry/EcalCommonData/data/ebrot.xml',
            'Geometry/EcalCommonData/data/eecon.xml',
            'Geometry/EcalCommonData/data/PhaseII/escon.xml',
            'Geometry/EcalCommonData/data/PhaseII/esalgo.xml',
            'Geometry/HcalCommonData/data/hcalrotations.xml',
            'Geometry/HcalCommonData/data/hcal/NoHE/hcalalgo.xml',
            'Geometry/HcalCommonData/data/hcalbarrelalgo.xml',
            'Geometry/HcalCommonData/data/hcalouteralgo.xml',
            'Geometry/HcalCommonData/data/hcalforwardalgo.xml',
            'Geometry/HcalCommonData/data/hcalSimNumbering/NoHE/hcalSimNumbering.xml',
            'Geometry/HcalCommonData/data/hcalRecNumbering/NoHE/hcalRecNumbering.xml',
            'Geometry/HcalCommonData/data/average/hcalforwardmaterial.xml',
            'Geometry/HGCalCommonData/data/hgcal/v9a/hgcal.xml',
            'Geometry/HGCalCommonData/data/hgcalEE/v9a/hgcalEE.xml',
            'Geometry/HGCalCommonData/data/hgcalHEsil/v9a/hgcalHEsil.xml',
            'Geometry/HGCalCommonData/data/hgcalHEmix/v9a/hgcalHEmix.xml',
            'Geometry/HGCalCommonData/data/hgcalwafer/v9/hgcalwafer.xml',
            'Geometry/HGCalCommonData/data/hgcalcell/v9/hgcalcell.xml',
            'Geometry/HGCalCommonData/data/hgcalCons/v9a/hgcalCons.xml',
        ],
        3 : [
            'Geometry/EcalSimData/data/PhaseII/ecalsens.xml',
            'Geometry/HcalCommonData/data/hcalsens/NoHE/hcalsenspmf.xml',
            'Geometry/HcalSimData/data/hf.xml',
            'Geometry/HcalSimData/data/hfpmt.xml',
            'Geometry/HcalSimData/data/hffibrebundle.xml',
            'Geometry/HcalSimData/data/CaloUtil.xml',
            'Geometry/HGCalSimData/data/hgcsensv9.xml',
        ],
        4 : [
            'Geometry/HcalSimData/data/HcalProdCuts.xml',
            'Geometry/EcalSimData/data/EcalProdCuts.xml',
            'Geometry/HGCalSimData/data/hgcProdCutsv9.xml',
        ],
        "sim" : [
            'from Geometry.HcalCommonData.hcalParameters_cfi      import *',
            'from Geometry.HcalCommonData.hcalDDDSimConstants_cfi import *',
            'from Geometry.HGCalCommonData.hgcalParametersInitialization_cfi import *',
            'from Geometry.HGCalCommonData.hgcalNumberingInitialization_cfi import *'
        ],
        "reco" : [
            'from Geometry.CaloEventSetup.HGCalV9Topology_cfi import *',
            'from Geometry.HGCalGeometry.HGCalGeometryESProducer_cfi import *',
            'from Geometry.CaloEventSetup.CaloTopology_cfi import *',
            'from Geometry.CaloEventSetup.CaloGeometryBuilder_cfi import *',
            'CaloGeometryBuilder = cms.ESProducer("CaloGeometryBuilder",',
            '    SelectedCalos = cms.vstring("HCAL",',
            '                                "ZDC",',
            '                                "EcalBarrel",',
            '                                "TOWER",',
            '                                "HGCalEESensitive",',
            '                                "HGCalHESiliconSensitive",',
            '                                "HGCalHEScintillatorSensitive"',
            '    )',
            ')',
            'from Geometry.EcalAlgo.EcalBarrelGeometry_cfi import *',
            'from Geometry.HcalEventSetup.HcalGeometry_cfi import *',
            'from Geometry.HcalEventSetup.CaloTowerGeometry_cfi import *',
            'from Geometry.HcalEventSetup.CaloTowerTopology_cfi import *',
            'from Geometry.HcalCommonData.hcalDDDRecConstants_cfi import *',
            'from Geometry.HcalEventSetup.hcalTopologyIdeal_cfi import *',
            'from Geometry.CaloEventSetup.EcalTrigTowerConstituents_cfi import *',
            'from Geometry.EcalMapping.EcalMapping_cfi import *',
            'from Geometry.EcalMapping.EcalMappingRecord_cfi import *',
        ],
        "era" : "run2_HE_2017, run2_HF_2017, run2_HCAL_2017, run3_HB, phase2_hcal, phase2_hgcal, hcalHardcodeConditions, hcalSkipPacker",
    },

}

muonDict = {
    "abbrev" : "M",
    "name" : "muon",
    "default" : 2,
    "M2" : {
        1 : [
            'Geometry/MuonCommonData/data/mbCommon/2017/v2/mbCommon.xml',
            'Geometry/MuonCommonData/data/mb1/2015/v1/mb1.xml',
            'Geometry/MuonCommonData/data/mb2/2015/v1/mb2.xml',
            'Geometry/MuonCommonData/data/mb3/2015/v1/mb3.xml',
            'Geometry/MuonCommonData/data/mb4/2015/v1/mb4.xml',
            'Geometry/MuonCommonData/data/design/muonYoke.xml',
            'Geometry/MuonCommonData/data/mf/2023/v2/mf.xml',
            'Geometry/MuonCommonData/data/rpcf/2023/v1/rpcf.xml',
            'Geometry/MuonCommonData/data/gemf/TDR_BaseLine/gemf.xml',
            'Geometry/MuonCommonData/data/gem11/TDR_BaseLine/gem11.xml',
            'Geometry/MuonCommonData/data/gem21/TDR_Dev/gem21.xml',
            'Geometry/MuonCommonData/data/csc/2015/v1/csc.xml',
            'Geometry/MuonCommonData/data/mfshield/2023/v1/mfshield.xml',
            'Geometry/MuonCommonData/data/me0/TDR_Dev/me0.xml',
        ],
        2 : [
            'Geometry/MuonCommonData/data/muonNumbering/TDR_DeV/muonNumbering.xml',
        ],
        3 : [
            'Geometry/MuonSimData/data/PhaseII/ME0EtaPart/muonSens.xml',
            'Geometry/DTGeometryBuilder/data/dtSpecsFilter.xml',
            'Geometry/CSCGeometryBuilder/data/cscSpecsFilter.xml',
            'Geometry/CSCGeometryBuilder/data/cscSpecs.xml',
            'Geometry/RPCGeometryBuilder/data/PhaseII/RPCSpecs.xml',
            'Geometry/GEMGeometryBuilder/data/v7/GEMSpecsFilter.xml',
            'Geometry/GEMGeometryBuilder/data/v7/GEMSpecs.xml',
        ],
        4 : [
            'Geometry/MuonSimData/data/PhaseII/muonProdCuts.xml',
        ],
        "reco" : [
            'from Geometry.MuonNumbering.muonNumberingInitialization_cfi import *',
            'from RecoMuon.DetLayers.muonDetLayerGeometry_cfi import *',
            'from Geometry.GEMGeometryBuilder.gemGeometry_cfi import *',
            'from Geometry.GEMGeometryBuilder.me0Geometry_cfi import *',
            'from Geometry.CSCGeometryBuilder.idealForDigiCscGeometry_cff import *',
            'from Geometry.DTGeometryBuilder.idealForDigiDtGeometry_cff import *',
        ],
        "era" : "phase2_muon, run3_GEM",
    }

}

forwardDict = {
    "abbrev" : "F",
    "name" : "forward",
    "default" : 2,
    "F2" : {
        1 : [
            'Geometry/ForwardCommonData/data/forwardshield/2017/v1/forwardshield.xml',
            'Geometry/ForwardCommonData/data/brmrotations.xml',
            'Geometry/ForwardCommonData/data/PostLS2/brm.xml',
            'Geometry/ForwardCommonData/data/zdcmaterials.xml',
            'Geometry/ForwardCommonData/data/lumimaterials.xml',
            'Geometry/ForwardCommonData/data/zdcrotations.xml',
            'Geometry/ForwardCommonData/data/lumirotations.xml',
            'Geometry/ForwardCommonData/data/zdc.xml',
            'Geometry/ForwardCommonData/data/zdclumi.xml',
            'Geometry/ForwardCommonData/data/cmszdc.xml',
        ],
        3 : [
            'Geometry/ForwardCommonData/data/brmsens.xml',
            'Geometry/ForwardSimData/data/zdcsens.xml',
        ],
        4 : [
            'Geometry/ForwardSimData/data/zdcProdCuts.xml',
            'Geometry/ForwardSimData/data/ForwardShieldProdCuts.xml',
        ],
        "reco" :[
            'from Geometry.ForwardGeometry.ForwardGeometry_cfi import *',
        ]
    },

    "F3" : {
        1 : [
            'Geometry/ForwardCommonData/data/forwardshield/2023/v1/forwardshield.xml',
            'Geometry/ForwardCommonData/data/brmrotations.xml',
            'Geometry/ForwardCommonData/data/brm/2023/v2/brm.xml',
            'Geometry/ForwardCommonData/data/zdcmaterials.xml',
            'Geometry/ForwardCommonData/data/lumimaterials.xml',
            'Geometry/ForwardCommonData/data/zdcrotations.xml',
            'Geometry/ForwardCommonData/data/lumirotations.xml',
            'Geometry/ForwardCommonData/data/zdc.xml',
            'Geometry/ForwardCommonData/data/zdclumi.xml',
            'Geometry/ForwardCommonData/data/cmszdc.xml',
        ],
        3 : [
            'Geometry/ForwardCommonData/data/brmsens.xml',
            'Geometry/ForwardSimData/data/zdcsens.xml',
        ],
        4 : [
            'Geometry/ForwardSimData/data/zdcProdCuts.xml',
            'Geometry/ForwardSimData/data/ForwardShieldProdCuts.xml',
        ],
        "sim" : [
        ],
        "reco" :[
            'from Geometry.ForwardGeometry.ForwardGeometry_cfi import *',
        ]
    }    

}

timingDict = {
    "abbrev" : "I",
    "name" : "timing",
    "default" : 1,
    "I1" : {},
    "I2" : {
        1 : [
            'Geometry/HGCalCommonData/data/fastTimingBarrel.xml',
            'Geometry/HGCalCommonData/data/fastTimingEndcap.xml',
            'Geometry/HGCalCommonData/data/fastTimingElement.xml',
            ],
        3 : [
            'Geometry/HGCalSimData/data/fasttimesens.xml'
            ],
        4 : [
            'Geometry/HGCalSimData/data/fasttimeProdCuts.xml'
            ],
        "sim" : [
            'from Geometry.HGCalCommonData.fastTimeParametersInitialization_cfi import *',
            'from Geometry.HGCalCommonData.fastTimeNumberingInitialization_cfi import *',
        ],
        "reco" :[
            'from Geometry.CaloEventSetup.FastTimeTopology_cfi import *',
            'from Geometry.HGCalGeometry.FastTimeGeometryESProducer_cfi import *',
        ],
        "era" : "phase2_timing, phase2_timing_layer",
    },
    "I3" : {
        1 : [
            'Geometry/MTDCommonData/data/btl.xml',
            'Geometry/MTDCommonData/data/etl.xml',
            'Geometry/MTDCommonData/data/CrystalTile/mtd.xml',
            ],
        3 : [
            'Geometry/MTDSimData/data/CrystalTile/mtdsens.xml'
            ],
        4 : [
            'Geometry/MTDSimData/data/CrystalTile/mtdProdCuts.xml'
            ],
        "sim" : [
        ],
        "reco" :[
        ],
        "era" : "phase2_timing, phase2_timing_layer_new",
    },
    "I4" : {
        1 : [
            'Geometry/MTDCommonData/data/btl.xml',
            'Geometry/MTDCommonData/data/etl.xml',
            'Geometry/MTDCommonData/data/CrystalBar/mtd.xml',
            ],
        3 : [
            'Geometry/MTDSimData/data/CrystalBar/mtdsens.xml'
            ],
        4 : [
            'Geometry/MTDSimData/data/CrystalBar/mtdProdCuts.xml'
            ],
        "sim" : [
        ],
        "reco" :[
        ],
        "era" : "phase2_timing, phase2_timing_layer_new",
    }
}

allDicts = [ commonDict, trackerDict, caloDict, muonDict, forwardDict, timingDict ]

detectorVersionDict = {
    ("O2","T5","C3","M2","F2","I1") : "D17",
    ("O2","T5","C3","M2","F2","I2") : "D19",
    ("O2","T6","C3","M2","F2","I1") : "D21",
    ("O2","T7","C3","M2","F2","I1") : "D22",
    ("O2","T8","C3","M2","F2","I1") : "D23",
    ("O2","T6","C3","M2","F2","I3") : "D24",
    ("O2","T6","C3","M2","F2","I4") : "D25",
    ("O2","T9","C3","M2","F2","I1") : "D26",
    ("O2","T10","C3","M2","F2","I1") : "D27",
    ("O2","T6","C4","M2","F2","I1") : "D28",
    ("O2","T11","C3","M2","F2","I1") : "D29",
    ("O2","T6","C5","M2","F2","I1") : "D30",
    ("O2","T6","C6","M2","F3","I1") : "D31",
    ("O2","T6","C7","M2","F2","I1") : "D32",
}

deprecatedDets = set([ "D1", "D2", "D3", "D5", "D6" , "D7", "D4", "D8" , "D9", "D12", "D13", "D15", "D10", "D11", "D14", "D16", "D18","D20" ])
deprecatedSubdets = set([ "T1", "T2" ,"T3", "T4", "C1", "C2", "M1", "O1", "F1" ])
