import FWCore.ParameterSet.Config as cms

from Geometry.CMSCommonData.cmsExtendedGeometry2023SHCalNoTaper4EtaXML_cfi import *
from Geometry.TrackerNumberingBuilder.trackerNumbering2023Geometry_cfi import *
from Geometry.HcalCommonData.hcalSimNumberingInitialization_cfi import *
from Geometry.HGCalCommonData.shashlikNumberingInitialization_cfi import *
