import FWCore.ParameterSet.Config as cms

from Geometry.CMSCommonData.cmsExtendedGeometry2023SHCalNoTaperXML_cfi import *
from Geometry.TrackerNumberingBuilder.trackerNumberingSLHCGeometry_cfi import *
from Geometry.HcalCommonData.hcalSimNumberingInitialization_cfi import *
from Geometry.HGCalCommonData.shashlikNumberingInitialization_cfi import *
