import FWCore.ParameterSet.Config as cms

source = cms.Source("PoolSource",
                    fileNames = cms.untracked.vstring(
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_10.root",
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_11.root",
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_12.root",
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_13.root",
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_14.root",
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_15.root",
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_16.root",
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_1.root",
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_20.root",
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_21.root",
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_22.root",
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_23.root",
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_25.root",
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_26.root",
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_27.root",
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_28.root",
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_29.root",
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_2.root",
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_30.root",
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_31.root",
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_33.root",
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_35.root",
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_36.root",
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_37.root",
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_38.root",
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_39.root",
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_3.root",
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_40.root",
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_42.root",
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_44.root",
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_46.root",
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_47.root",
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_48.root",
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_49.root",
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_4.root",
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_50.root",
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_5.root",
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_6.root",
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_7.root",
    "file:/data2/demattia/Data/Upsilon2S/Filter_Upsilon2S_8.root"
    )
                    )
