#ifndef CondFormats_DataRecord_EcalShowerContainmentCorrectionsRcd_H
#define CondFormats_DataRecord_EcalShowerContainmentCorrectionsRcd_H

#include "FWCore/Framework/interface/EventSetupRecordImplementation.h"
class EcalShowerContainmentCorrectionsRcd : public edm::eventsetup::EventSetupRecordImplementation<EcalShowerContainmentCorrectionsRcd> {};
#endif
