#ifndef CondFormats_DataRecord_EcalGlobalShowerContainmentCorrectionsVsEtaRcd_H
#define CondFormats_DataRecord_EcalGlobalShowerContainmentCorrectionsVsEtaRcd_H

#include "FWCore/Framework/interface/EventSetupRecordImplementation.h"
class EcalGlobalShowerContainmentCorrectionsVsEtaRcd : public edm::eventsetup::EventSetupRecordImplementation<EcalGlobalShowerContainmentCorrectionsVsEtaRcd> {};
#endif
