#ifndef CondFormats_DataRecord_EcalClusterCrackCorrParametersRcd_h
#define CondFormats_DataRecord_EcalClusterCrackCorrParametersRcd_h

#include "FWCore/Framework/interface/EventSetupRecordImplementation.h"
class EcalClusterCrackCorrParametersRcd : public edm::eventsetup::EventSetupRecordImplementation<EcalClusterCrackCorrParametersRcd> {};
#endif
