#!/usr/bin/env perl

use strict "vars";
use vars qw( %opts );
use vars qw( %config );

use Getopt::Long;

Getopt::Long::config('bundling_override');
%opts = ();
GetOptions( \%opts,
                "location|l=s",
                "run|r=s",
                "read",
                "verify",
                "write",
                "debug|d",
                "help|h"
);
usage() if ( $opts{'help'} || $Getopt::Long::error );

my $location = $opts{'location'};
my $run = $opts{'run'};

my ($file) = @ARGV;

usage() if ( ! $location || ! $run || ! $file );

usage() if ( ! $opts{'read'} && ! $opts{'verify'} && ! $opts{'write'} );

use File::Basename;

unshift(@INC, dirname($0));
require "ec_mon_utils.pl";

ec_mon_conf_file();

my $dbName     = '';
my $dbHostName = '';
my $dbHostPort = 1521;
my $dbUserName = '';
my $dbPassword = '';

if ( -e "/nfshome0/ecalpro/DQM/online-DQM/.cms_tstore.conf" ) {
  open FILE, "</nfshome0/ecalpro/DQM/online-DQM/.cms_tstore.conf";
  while ( my $line = <FILE> ) {
    $dbName = (split(' ', $line))[2] if ( $line =~ /^dbName/ );
    $dbHostName = (split(' ', $line))[2] if ( $line =~ /^dbHostName/ );
    $dbHostPort = (split(' ', $line))[2] if ( $line =~ /^dbHostPort/ );
    $dbUserName = (split(' ', $line))[2] if ( $line =~ /^dbUserName/ );
    $dbPassword = (split(' ', $line))[2] if ( $line =~ /^dbPassword/ );
  }
  close FILE;
} else {
  print "DB config file not found, exit\n"
}

my $cmssw_arch = "slc5_ia32_gcc434";
my $cmssw_setup = "/cmssrv0/nfshome0/cmssw2/scripts/setup.sh";

my $cmssw_path = "/nfshome0/ecalpro/DQM/CMSSW_current";

exit 1 unless ( -e "$cmssw_path" );

my $task;

if ( $opts{'read'} ) {
  $task = "source $cmssw_setup ; cd $cmssw_path ; eval `scramv1 runtime -sh` ; TNS_ADMIN=/etc ; cd $config{'ec_mon_path'} ; readMaskFromDB --sid=$dbName --user-name=$dbUserName --password=$dbPassword --location=$location --run-number=$run $file";
  print "$task\n" if ( $opts{'debug'} );
  system("$task");
  exit 0;
}

if ( $opts{'verify'} ) {
  $task = "source $cmssw_setup ; cd $cmssw_path ; eval `scramv1 runtime -sh` ; TNS_ADMIN=/etc ; cd $config{'ec_mon_path'} ; writeMaskToDB --sid=$dbName --user-name=$dbUserName --password=$dbPassword --location=$location --run-number=$run --verify-syntax $file";
  print "$task\n" if ( $opts{'debug'} );
  system("$task");
  exit 0;
}

if ( $opts{'write'} ) {
  $task = "source $cmssw_setup ; cd $cmssw_path ; eval `scramv1 runtime -sh` ; TNS_ADMIN=/etc ; cd $config{'ec_mon_path'} ; writeMaskToDB --sid=$dbName --user-name=$dbUserName --password=$dbPassword --location=$location --run-number=$run $file";
  print "$task\n" if ( $opts{'debug'} );
  system("$task");
  exit 0;
}

############################################################################

sub usage {

        print STDERR <<INLINE_LITERAL_TEXT;
usage: ec_mon_masking --location <location> \
                      --run <run_number> \
                      --type <run_type> \
                      [options]
                      maskfile

Options are:
  --read     Read from DB and save as 'maskfile'
  --verify   Verify 'maskfile' syntax
  --write    Write 'maskfile' to DB

  --debug
INLINE_LITERAL_TEXT

        exit;
}

############################################################################

