autoPCL = {'PromptCalibProd' : 'BeamSpotByRun+BeamSpotByLumi',
           'PromptCalibProdBeamSpotHP' : 'BeamSpotHPByRun+BeamSpotHPByLumi',
           'PromptCalibProdBeamSpotHPLowPU' : 'BeamSpotHPLowPUByRun+BeamSpotHPLowPUByLumi',
           'PromptCalibProdSiStrip' : 'SiStripQuality',
           'PromptCalibProdSiStripGains' : 'SiStripGains',
           'PromptCalibProdSiStripGainsAAG' : 'SiStripGainsAAG',
           'PromptCalibProdSiPixelAli' : 'SiPixelAli',
           'PromptCalibProdSiPixel' : 'SiPixelQuality',
           'PromptCalibProdSiPixelLA' : 'SiPixelLA',
           'PromptCalibProdEcalPedestals': 'EcalPedestals',
           'PromptCalibProdLumiPCC': 'LumiPCC',
           'PromptCalibProdSiPixel' : 'SiPixelQuality',
           'PromptCalibProdPPS' : 'PPSTimingCalibration',
           'PromptCalibProdPPSDiamondSampic' : 'PPSDiamondSampicTimingCalibration'
           }
