#ifndef CondFormats_EcalObjects_EcalClusterEnergyCorrectionObjectSpecificParameters_h
#define CondFormats_EcalObjects_EcalClusterEnergyCorrectionObjectSpecificParameters_h

#include "CondFormats/EcalObjects/interface/EcalFunctionParameters.h"

typedef EcalFunParams EcalClusterEnergyCorrectionObjectSpecificParameters;

#endif
