#ifndef CondFormats_EcalObjects_EcalLocalContCorrParameters_h
#define CondFormats_EcalObjects_EcalLocalContCorrParameters_h

#include "CondFormats/EcalObjects/interface/EcalFunctionParameters.h"

typedef EcalFunParams EcalClusterLocalContCorrParameters;

#endif
