#ifndef CondFormats_EcalObjects_EcalClusterEnergyCorrectionParameters_h
#define CondFormats_EcalObjects_EcalClusterEnergyCorrectionParameters_h

#include "CondFormats/EcalObjects/interface/EcalFunctionParameters.h"

typedef EcalFunParams EcalClusterEnergyCorrectionParameters;

#endif
