// L1TGlobalPrescalesVetosFractRcd implementation

// automatically generated by make_records.pl

#include "CondFormats/DataRecord/interface/L1TGlobalPrescalesVetosFractRcd.h"
#include "FWCore/Framework/interface/eventsetuprecord_registration_macro.h"

EVENTSETUP_RECORD_REG(L1TGlobalPrescalesVetosFractRcd);
