// L1TUtmCutRcd implementation

// automatically generated by make_records.pl

#include "CondFormats/DataRecord/interface/L1TUtmCutRcd.h"
#include "FWCore/Framework/interface/eventsetuprecord_registration_macro.h"

EVENTSETUP_RECORD_REG(L1TUtmCutRcd);
