import FWCore.ParameterSet.Config as cms

from SimTracker.TrackAssociation.trackMCMatch_cfi import *
from SimTracker.TrackAssociation.standAloneMuonsMCMatch_cfi import *
from SimTracker.TrackAssociation.globalMuonsMCMatch_cfi import *
from SimTracker.TrackAssociation.allTrackMCMatch_cfi import *
from SimTracker.TrackAssociation.trackingParticleRecoTrackAsssociation_cff import *
from SimTracker.TrackAssociatorProducers.trackAssociatorByHits_cfi import trackAssociatorByHits
trackMCMatchSequence = cms.Sequence(quickTrackAssociatorByHits*trackAssociatorByHits*trackMCMatch*standAloneMuonsMCMatch*globalMuonsMCMatch*allTrackMCMatch*quickTrackAssociatorByHits*trackingParticleRecoTrackAsssociation*assoc2secStepTk*assoc2thStepTk*assoc2GsfTracks*assocOutInConversionTracks*assocInOutConversionTracks)

