import FWCore.ParameterSet.Config as cms

fragment = cms.ProcessFragment("HLT")

### ACCELERATORS, in case they are needed
## Load explicitly
# One ProcessAccelerator for each accelerator technology
fragment.load("Configuration.StandardSequences.Accelerators_cff")

### Accelerators

### Event-setup modules migrated from the RECO configuration
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/AnyDirectionAnalyticalPropagator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/caloDetIdAssociator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/CaloTowerConstituentsMapBuilder_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/ClusterShapeHitFilterESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/CSCChannelMapperESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/CSCIndexerESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/ecalDetIdAssociator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/ecalSeverityLevel_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hcalChannelPropertiesESProd_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hcalDetIdAssociator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hcalRecAlgos_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltCSCChannelMapperESSource_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltCSCIndexerESSource_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPAnalyticalPropagator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPBwdAnalyticalPropagator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPChi2MeasurementEstimatorForFitters_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPCloseComponentsMerger5D_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPElectronMaterialEffects_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPFlexibleKFFittingSmoother_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPGlobalDetLayerGeometry_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPGsfElectronFittingSmoother_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPGsfTrajectoryFitter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPGsfTrajectorySmoother_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPInitialStepTrajectoryCleanerBySharedHits_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPKFFittingSmootherForLoopers_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPKFFittingSmootherWithOutliersRejectionAndRK_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPKFTrajectoryFitterForLoopers_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPKFTrajectorySmootherForLoopers_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPKullbackLeiblerDistance5D_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPMeasurementTracker_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPPhase2StripCPE_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPPixelCPEGeneric_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPRKTrajectoryFitter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPRKTrajectorySmoother_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPTTRHBuilderWithoutAngle4PixelTriplets_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESSEcalSeverityLevel_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESSHcalSeverityLevel_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltGeneralTracksTrackAlgoPriorityOrder_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltOppositeMaterialPropagatorParabolicMF_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltPropagatorWithMaterialForLoopers_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hoDetIdAssociator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/MaterialPropagator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/MaterialPropagatorParabolicMF_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/muonDetIdAssociator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/navigationSchoolESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/OppositeMaterialPropagator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/preshowerDetIdAssociator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/SteppingHelixPropagatorAny_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/TransientTrackBuilderESProducer_cfi")

### Actual changes on top of Phase2
### It could come from RecoTracker/IterativeTracking/InitialStep_cff.py
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltTiclGeomESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltTiclGeomLookupESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltTiclGeomLayersESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltTiclGeomWithBarrelESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltTiclGeomWithBarrelLookupESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltInitialStepChi2Est_cfi")
### It could come from RecoTracker/IterativeTracking/python/HighPtTripletStep_cff.py
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltHighPtTripletStepChi2Est_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltHighPtTripletStepTrajectoryCleanerBySharedHits_cfi")
### It could come from RecoTracker/IterativeTracking/python/MuonSeededStep_cff.py
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltMuonSeededTrajectoryCleanerBySharedHits_cfi")

### Mostly comes from HLT-like configuration, not RECO-like configuration
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPBwdElectronPropagator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPChi2ChargeMeasurementEstimator2000_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPChi2ChargeMeasurementEstimator30_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPChi2MeasurementEstimator100_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPChi2MeasurementEstimator30_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPDummyDetLayerGeometry_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPFastSteppingHelixPropagatorAny_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPFastSteppingHelixPropagatorOpposite_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPFwdElectronPropagator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPKFTrajectorySmootherForMuonTrackLoader_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPKFUpdator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPL3MuKFTrajectoryFitter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPMuonTransientTrackingRecHitBuilder_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPRungeKuttaTrackerPropagator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPSmartPropagator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPSmartPropagatorAny_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPSmartPropagatorAnyOpposite_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPSteppingHelixPropagatorAlong_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPSteppingHelixPropagatorOpposite_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPTrackAlgoPriorityOrder_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPTrajectoryCleanerBySharedHits_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltPhase2L3MuonHighPtTripletStepChi2Est_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltPhase2L3MuonHighPtTripletStepTrajectoryCleanerBySharedHits_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltPhase2L3MuonInitialStepChi2Est_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltPhase2L3MuonPixelTrackCleanerBySharedHits_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltPhase2L3MuonTrackAlgoPriorityOrder_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPPixelCPEFastParams_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltPixelTracksCleanerBySharedHits_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPTTRHBuilderWithTrackAngle_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPMkFit_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPKFFittingSmootherForL2Muon_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPKFTrajectoryFitterForL2Muon_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPKFTrajectorySmootherForL2Muon_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPPixelCPEFastParams_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltLSTGeometry_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPModulesDevLST_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPTTRHBuilderWithoutRefit_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltMTDCPEESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltMTDTimeCalibESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltMTDTransientTrackingRecHitBuilder_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltPropagatorWithMaterialForMTD_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltKFFitterForRefitInsideOut_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltSmartPropagatorAnyRK_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltChi2EstimatorForRefit_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltKFSmootherForRefitInsideOut_cfi")

### Paths
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_AK4PFPuppiJet520_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_Diphoton30_23_IsoCaloId_L1Seeded_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_DoubleEle23_12_Iso_L1Seeded_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_DoubleEle25_CaloIdL_PMS2_L1Seeded_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_DoubleMediumChargedIsoPFTauHPS40_eta2p1_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_DoubleMediumDeepTauPFTauHPS35_eta2p1_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_DoublePFPuppiJets128_DoublePFPuppiBTagDeepFlavour_2p4_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_Ele115_NonIso_L1Seeded_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_Ele26_WP70_L1Seeded_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_Ele32_WPTight_L1Seeded_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_Ele30_WPTight_L1Seeded_LooseDeepTauPFTauHPS30_eta2p1_CrossL1_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_IsoMu20_eta2p1_LooseDeepTauPFTauHPS27_eta2p1_CrossL1_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_IsoMu24_FromL1TkMuon_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_LooseDeepTauPFTauHPS150_L1NN_eta2p1_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_FromL1TkMuon_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_Mu37_Mu27_FromL1TkMuon_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_Mu50_FromL1TkMuon_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_PFHT200PT30_QuadPFPuppiJet_70_40_30_30_TriplePFPuppiBTagDeepFlavour_2p4_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_PFHT330PT30_QuadPFPuppiJet_75_60_45_40_TriplePFPuppiBTagDeepFlavour_2p4_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_PFPuppiHT1070_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_PFPuppiMETTypeOne140_PFPuppiMHT140_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_Photon108EB_TightID_TightIso_L1Seeded_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_Photon187_L1Seeded_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_TriMu_10_5_5_DZ_FromL1TkMuon_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLTAnalyzerEndpath_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLTriggerFinalPath_cfi")

### Global PSets
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/ClusterShapeTrajectoryFilter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/HGCAL_chargeCollectionEfficiencies_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/HGCAL_noise_fC_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/HGCAL_noise_heback_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/highPtTripletStepTrajectoryBuilder_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/highPtTripletStepTrajectoryFilter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/highPtTripletStepTrajectoryFilterBase_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/highPtTripletStepTrajectoryFilterInOut_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/HLTIter0Phase2L3FromL1TkMuonGroupedCkfTrajectoryFilterIT_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/HLTIter0Phase2L3FromL1TkMuonPSetGroupedCkfTrajectoryBuilderIT_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/HLTIter2Phase2L3FromL1TkMuonPSetGroupedCkfTrajectoryBuilderIT_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/HLTIter2Phase2L3FromL1TkMuonPSetTrajectoryFilterIT_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/hltPhase2L3MuonHighPtTripletStepTrajectoryBuilder_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/hltPhase2L3MuonHighPtTripletStepTrajectoryFilter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/hltPhase2L3MuonHighPtTripletStepTrajectoryFilterBase_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/hltPhase2L3MuonHighPtTripletStepTrajectoryFilterInOut_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/hltPhase2L3MuonInitialStepTrajectoryBuilder_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/hltPhase2L3MuonInitialStepTrajectoryFilter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/hltPhase2L3MuonPSetPvClusterComparerForIT_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/hltPhase2L3MuonSeedFromProtoTracks_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/hltPhase2PSetPvClusterComparerForIT_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/hltPhase2SeedFromProtoTracks_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/HLTPSetMuonCkfTrajectoryBuilder_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/HLTPSetMuonCkfTrajectoryFilter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/HLTPSetTrajectoryBuilderForGsfElectrons_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/HLTPSetTrajectoryFilterForElectrons_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/HLTSiStripClusterChargeCutNone_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/initialStepTrajectoryBuilder_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/initialStepTrajectoryFilter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/pSetPvClusterComparerForIT_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/seedFromProtoTracks_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/SiStripClusterChargeCutLoose_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/SiStripClusterChargeCutNone_cfi")

### Sequences
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTCalolocalrecoSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTCaloTowersRecSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTCsclocalrecoSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTDtlocalrecoSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTGemLocalRecoSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTTICLLocalRecoSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTHighPtTripletStepSeedingSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTHighPtTripletStepSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTAK4PFJetsReconstruction_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTAK4PFPuppiJetsReconstruction_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTAK8PFJetsReconstruction_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTBeamSpotSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTBeginSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTBtagDeepFlavourSequencePFPuppi_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTBtagDeepFlavourSequencePFPuppiModEta2p4_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTCaloMETReconstruction_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTDiphoton3023IsoCaloIdL1SeededSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTDoFullUnpackingEgammaEcalL1SeededSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTDoFullUnpackingEgammaEcalSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTDoLocalHcalSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTDoLocalPixelSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTDoLocalStripSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTDoubleEle2312IsoL1SeededSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTDoubleEle25CaloIdLPMS2L1SeededSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTEcalDigisSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTEGammaDoLocalHcalSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTEle115NonIsoL1SeededGsfElectronL1SeededSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTEle115NonIsoL1SeededSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTEle26WP70L1SeededSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTEle32WPTightL1SeededSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTElePixelMatchL1SeededSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTEndSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTFastJetForEgammaSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTGsfElectronL1SeededSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTHgcalTiclPFClusteringForEgamma_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTHgcalTiclPFClusteringForEgammaL1SeededSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTHPSDeepTauPFTauSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTHPSMediumChargedIsoPFTauSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTIter0Phase2L3FromL1TkSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTIter2Phase2L3FromL1TkSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTJMESequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTL1Sequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTL1UnpackerSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTL2MuonsFromL1TkSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTMuonsSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTParticleFlowSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTPFClusteringForEgammaL1SeededSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTPFClusterJMEReconstruction_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTPFHcalClusteringForEgammaSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTPFJetsCHSReconstruction_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTPFMETsReconstruction_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTPFPuppiJMEReconstruction_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTPFPuppiMETReconstruction_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTPFTauHPS_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTPhase2L3FromL1TkSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTPhase2L3MuonsSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTPhase2L3OISequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTPhase2PixelVertexingSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTPhase2PixelTracksAndVerticesSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTPhoton108EBTightIDTightIsoL1SeededSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTPhoton187L1SeededSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTTrackingSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTInitialStepPVSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTInitialStepSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTIterTICLSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTItLocalRecoSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTLocalrecoSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTMuonlocalrecoSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTOtLocalRecoSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTParticleFlowClusterECALSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTParticleFlowClusterSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTParticleFlowRecoSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTParticleFlowSuperClusteringSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTPfClusteringECALSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTPfClusteringHBHEHFSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTPfClusteringHOSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTPfClusterRefsForJetsSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTRawToDigiSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTTiclLayerTileSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTTiclPFSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTTiclTrackstersCLUE3DHighStepSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/sequences/HLTVertexRecoSequence_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/services/FastTimerService_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/services/ThroughputService_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/services/PyTorchService_cfi")

fragment.schedule = cms.Schedule(*[

    fragment.HLT_AK4PFPuppiJet520,
    fragment.HLT_PFPuppiHT1070,
    fragment.HLT_PFPuppiMETTypeOne140_PFPuppiMHT140,

    fragment.HLT_PFHT330PT30_QuadPFPuppiJet_75_60_45_40_TriplePFPuppiBTagDeepFlavour_2p4,
    fragment.HLT_PFHT200PT30_QuadPFPuppiJet_70_40_30_30_TriplePFPuppiBTagDeepFlavour_2p4,
    fragment.HLT_DoublePFPuppiJets128_DoublePFPuppiBTagDeepFlavour_2p4,

    fragment.HLT_Mu50_FromL1TkMuon,
    fragment.HLT_IsoMu24_FromL1TkMuon,
    fragment.HLT_Mu37_Mu27_FromL1TkMuon,
    fragment.HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_FromL1TkMuon,
    fragment.HLT_TriMu_10_5_5_DZ_FromL1TkMuon,

    fragment.HLT_Ele32_WPTight_L1Seeded,
    fragment.HLT_Ele30_WPTight_L1Seeded_LooseDeepTauPFTauHPS30_eta2p1_CrossL1,
    fragment.HLT_Ele115_NonIso_L1Seeded,
    fragment.HLT_Ele26_WP70_L1Seeded,
    fragment.HLT_Photon108EB_TightID_TightIso_L1Seeded,
    fragment.HLT_Photon187_L1Seeded,
    fragment.HLT_DoubleEle25_CaloIdL_PMS2_L1Seeded,
    fragment.HLT_DoubleEle23_12_Iso_L1Seeded,
    fragment.HLT_Diphoton30_23_IsoCaloId_L1Seeded,

    fragment.HLT_DoubleMediumChargedIsoPFTauHPS40_eta2p1,
    fragment.HLT_DoubleMediumDeepTauPFTauHPS35_eta2p1,
    fragment.HLT_IsoMu20_eta2p1_LooseDeepTauPFTauHPS27_eta2p1_CrossL1,
    fragment.HLT_LooseDeepTauPFTauHPS150_L1NN_eta2p1,
    
    ### Removed temporarily until final decision on L1T tau Phase-2
    #fragment.L1T_DoubleNNTau52,
    #fragment.L1T_SingleNNTau150,

    fragment.HLTriggerFinalPath,
    fragment.HLTAnalyzerEndpath,
])
