import FWCore.ParameterSet.Config as cms

fragment = cms.ProcessFragment( "HLT" )

fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/alongMomElePropagator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/AnalyticalPropagator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/AnalyticalPropagatorParabolicMF_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/AnyDirectionAnalyticalPropagator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/BeamHaloMPropagatorAlong_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/BeamHaloMPropagatorOpposite_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/beamHaloNavigationSchoolESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/BeamHaloPropagatorAlong_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/BeamHaloPropagatorAny_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/BeamHaloPropagatorOpposite_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/BeamHaloSHPropagatorAlong_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/BeamHaloSHPropagatorAny_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/BeamHaloSHPropagatorOpposite_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/bmbtfParamsSource_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/BTagRecord_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/bwdAnalyticalPropagator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/bwdElectronPropagator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/bwdGsfElectronPropagator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/caloConfig_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/caloConfigSource_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/caloDetIdAssociator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/CaloGeometryBuilder_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/caloSimulationParameters_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/CaloTopologyBuilder_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/CaloTowerConstituentsMapBuilder_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/CaloTowerHardcodeGeometryEP_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/CaloTowerTopologyEP_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/CaloTPGTranscoder_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/candidateBoostedDoubleSecondaryVertexAK8Computer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/candidateBoostedDoubleSecondaryVertexCA15Computer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/candidateChargeBTagComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/candidateCombinedMVAV2Computer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/candidateCombinedSecondaryVertexSoftLeptonComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/candidateCombinedSecondaryVertexSoftLeptonCvsLComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/candidateCombinedSecondaryVertexV2Computer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/candidateGhostTrackComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/candidateJetBProbabilityComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/candidateJetProbabilityComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/candidateNegativeCombinedMVAV2Computer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/candidateNegativeCombinedSecondaryVertexV2Computer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/candidateNegativeOnlyJetBProbabilityComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/candidateNegativeOnlyJetProbabilityComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/candidateNegativeTrackCounting3D2ndComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/candidateNegativeTrackCounting3D3rdComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/candidatePositiveCombinedMVAV2Computer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/candidatePositiveCombinedSecondaryVertexV2Computer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/candidatePositiveOnlyJetBProbabilityComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/candidatePositiveOnlyJetProbabilityComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/candidateSimpleSecondaryVertex2TrkComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/candidateSimpleSecondaryVertex3TrkComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/candidateTrackCounting3D2ndComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/candidateTrackCounting3D3rdComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/CastorDbProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/CastorHardcodeGeometryEP_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/charmTagsComputerCvsB_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/charmTagsComputerCvsL_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/charmTagsNegativeComputerCvsB_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/charmTagsNegativeComputerCvsL_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/charmTagsPositiveComputerCvsB_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/charmTagsPositiveComputerCvsL_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/chi2CutForConversionTrajectoryBuilder_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/Chi2EstimatorForMuonTrackLoader_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/Chi2EstimatorForMuRefit_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/Chi2EstimatorForRefit_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/Chi2MeasurementEstimator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/Chi2MeasurementEstimatorForInOut_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/Chi2MeasurementEstimatorForOutIn_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/Chi2MeasurementEstimatorForP5_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/CloseComponentsMerger5D_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/CloseComponentsMerger_forPreId_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/ClusterShapeHitFilterESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/combinedMVAV2Computer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/combinedSecondaryVertexV2Computer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/conv2StepFitterSmoother_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/conv2StepRKTrajectorySmoother_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/convStepChi2Est_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/convStepFitterSmoother_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/convStepRKTrajectorySmoother_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/cosmicsNavigationSchoolESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/CSCChannelMapperESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/CSCChannelMapperESSource_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/CSCGeometryESModule_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/CSCIndexerESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/CSCIndexerESSource_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/ctppsBeamParametersESSource_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/ctppsGeometryESModule_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/ctppsInterpolatedOpticalFunctionsESSource_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/ctppsOpticalFunctionsESSource_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/detachedQuadStepChi2Est_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/detachedQuadStepTrajectoryCleanerBySharedHits_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/detachedTripletStepChi2Est_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/detachedTripletStepTrajectoryCleanerBySharedHits_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/doubleVertex2TrkComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/DTGeometryESModule_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/DummyDetLayerGeometry_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/duplicateDisplaceTrackCandidatesChi2Est_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/duplicateTrackCandidatesChi2Est_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/EcalBarrelGeometryEP_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/ecalDetIdAssociator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/EcalElectronicsMappingBuilder_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/EcalLaserCorrectionService_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/ecalNextToDeadChannelESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/ecalSeverityLevel_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/ecalSimulationParametersEB_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/ecalSimulationParametersEE_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/ecalSimulationParametersES_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/EcalTrigTowerConstituentsMapBuilder_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/eegeom_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/ElectronChi2_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/electronChi2_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/ElectronMaterialEffects_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/ElectronMaterialEffects_forPreId_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/electronTrajectoryCleanerBySharedHits_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/es_hardcode_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/es_prefer_es_hardcode_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/es_prefer_ppsDBESSource_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/essourceEcalNextToDead_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/essourceEcalSev_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/essourceSev_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/EstimatorForSTA_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/fakeForIdealAlignment_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/fakeTwinMuxParams_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/FittingSmootherRKP5_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/FlexibleKFFittingSmoother_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/fwdAnalyticalPropagator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/fwdElectronPropagator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/fwdGsfElectronPropagator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/GEMGeometryESModule_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/ghostTrackComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/GlbMuKFFitter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/GlobalDetLayerGeometry_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/GlobalParameters_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/GlobalParametersRcdSource_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/GlobalTrackingGeometryESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/GsfElectronFittingSmoother_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/GsfTrajectoryFitter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/GsfTrajectoryFitter_forPreId_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/GsfTrajectorySmoother_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/GsfTrajectorySmoother_forPreId_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/HBDarkeningEP_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hcal_db_producer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hcalDDDRecConstants_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hcalDDDSimConstants_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hcalDDDSimulationConstants_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hcalDetIdAssociator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/HcalHardcodeGeometryEP_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hcalOOTPileupESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hcalParameters_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hcalRecAlgos_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hcalSimulationParameters_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/HcalTimeSlewEP_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hcalTopologyIdeal_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/HcalTrigTowerGeometryESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/HEDarkeningEP_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/HepPDTESSource_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/HGCalEEGeometryESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hgcalEENumberingInitialize_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hgcalEEParametersInitialize_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/HGCalEETopologyBuilder_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/HGCalHESciGeometryESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/HGCalHESciTopologyBuilder_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hgcalHEScNumberingInitialize_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hgcalHEScParametersInitialize_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/HGCalHESilGeometryESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/HGCalHESilTopologyBuilder_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hgcalHESiNumberingInitialize_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hgcalHESiParametersInitialize_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hgcalTriggerGeometryESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/highPtTripletStepChi2Est_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/highPtTripletStepTrajectoryCleanerBySharedHits_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hitCollectorForCosmicDCSeeds_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hitCollectorForOutInMuonSeeds_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltCandidateJetBProbabilityComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltCandidateJetProbabilityComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPBwdElectronPropagator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPChi2ChargeMeasurementEstimator16_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPChi2ChargeMeasurementEstimator2000_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPChi2ChargeMeasurementEstimator30_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPChi2ChargeMeasurementEstimator9_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPChi2MeasurementEstimator100_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPChi2MeasurementEstimator30_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPDummyDetLayerGeometry_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPFastSteppingHelixPropagatorAny_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPFastSteppingHelixPropagatorOpposite_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPFwdElectronPropagator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPGlobalDetLayerGeometry_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPKFFittingSmootherWithOutliersRejectionAndRK_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPKFTrajectorySmootherForMuonTrackLoader_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPKFUpdator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPL3MuKFTrajectoryFitter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPMeasurementTracker_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPMuonTransientTrackingRecHitBuilder_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPRKTrajectoryFitter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPRKTrajectorySmoother_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPRungeKuttaTrackerPropagator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPSmartPropagator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPSmartPropagatorAny_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPSmartPropagatorAnyOpposite_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPSteppingHelixPropagatorAlong_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPSteppingHelixPropagatorOpposite_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPTrackAlgoPriorityOrder_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPTrajectoryCleanerBySharedHits_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltESPTTRHBuilderPixelOnly_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltPhase2L3MuonHighPtTripletStepChi2Est_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltPhase2L3MuonHighPtTripletStepTrajectoryCleanerBySharedHits_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltPhase2L3MuonInitialStepChi2Est_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltPhase2L3MuonPixelTrackCleanerBySharedHits_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltPhase2L3MuonTrackAlgoPriorityOrder_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltPixelTracksCleanerBySharedHits_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hltTTRBWR_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/hoDetIdAssociator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/idealForDigiCSCGeometry_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/idealForDigiDTGeometry_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/idealForDigiMTDGeometry_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/idealForDigiTrackerGeometry_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/impactParameterMVAComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/initialStepChi2Est_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/initialStepChi2EstPreSplitting_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/jetBProbabilityComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/jetCoreRegionalStepChi2Est_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/jetProbabilityComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/KFFitterForRefitInsideOut_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/KFFitterForRefitOutsideIn_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/KFFittingSmootheForSTA_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/KFFittingSmoother_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/KFFittingSmootherBeamHalo_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/KFFittingSmootherForInOut_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/KFFittingSmootherWithOutliersRejectionAndRK_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/KFSmootherForMuonTrackLoader_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/KFSmootherForMuonTrackLoaderL3_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/KFSmootherForRefitInsideOut_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/KFSmootherForRefitOutsideIn_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/KFSwitching1DUpdatorESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/KFTrajectoryFitter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/KFTrajectoryFitterBeamHalo_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/KFTrajectoryFitterForInOut_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/KFTrajectoryFitterForOutIn_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/KFTrajectoryFitterForSTA_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/KFTrajectorySmoother_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/KFTrajectorySmootherBeamHalo_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/KFTrajectorySmootherForInOut_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/KFTrajectorySmootherForSTA_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/KFUpdatorESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/KullbackLeiblerDistance5D_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/L1DTConfigFromDB_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/l1ugmtdb_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/LooperFittingSmoother_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/LooperTrajectoryFitter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/LooperTrajectorySmoother_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/lowPtGsfEleFittingSmoother_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/lowPtQuadStepChi2Est_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/lowPtQuadStepTrajectoryCleanerBySharedHits_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/lowPtTripletStepChi2Est_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/lowPtTripletStepTrajectoryCleanerBySharedHits_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/MaterialPropagator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/MaterialPropagatorParabolicMF_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/ME0GeometryESModule_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/MeasurementTracker_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/mixedTripletStepChi2Est_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/mixedTripletStepClusterShapeHitFilter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/mixedTripletStepPropagator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/mixedTripletStepPropagatorOpposite_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/mixedTripletStepTrajectoryCleanerBySharedHits_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/MRHChi2MeasurementEstimator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/MRHFittingSmoother_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/MRHTrajectoryFitter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/MRHTrajectorySmoother_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/MTDCPEESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/mtdDetLayerGeometry_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/mtdGeometry_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/mtdNumberingGeometry_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/mtdParameters_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/MTDTimeCalibESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/mtdTopology_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/MTDTransientTrackingRecHitBuilder_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/muonDetIdAssociator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/MuonDetLayerGeometryESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/muonGeometryConstants_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/MuonNumberingInitialization_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/muonSeededFittingSmootherWithOutliersRejectionAndRK_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/muonSeededMeasurementEstimatorForInOut_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/muonSeededMeasurementEstimatorForOutIn_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/muonSeededMeasurementEstimatorForOutInDisplaced_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/muonSeededTrajectoryCleanerBySharedHits_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/MuonTransientTrackingRecHitBuilderESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/myTTRHBuilderWithoutAngle_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/myTTRHBuilderWithoutAngle4MixedPairs_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/myTTRHBuilderWithoutAngle4MixedTriplets_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/myTTRHBuilderWithoutAngle4PixelPairs_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/myTTRHBuilderWithoutAngle4PixelTriplets_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/navigationSchoolESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/negativeCombinedMVAV2Computer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/negativeCombinedSecondaryVertexV2Computer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/negativeOnlyJetBProbabilityComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/negativeOnlyJetProbabilityComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/negativeSoftPFElectronByIP2dComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/negativeSoftPFElectronByIP3dComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/negativeSoftPFElectronByPtComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/negativeSoftPFElectronComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/negativeSoftPFMuonByIP2dComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/negativeSoftPFMuonByIP3dComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/negativeSoftPFMuonByPtComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/negativeSoftPFMuonComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/negativeTrackCounting3D2ndComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/negativeTrackCounting3D3rdComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/OppositeAnalyticalPropagator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/OppositeAnalyticalPropagatorParabolicMF_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/OppositeMaterialPropagator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/OppositeMaterialPropagatorParabolicMF_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/oppositeToMomElePropagator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/ParabolicParametrizedMagneticFieldProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/phase2StripCPEESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/phase2StripCPEGeometricESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/PixelCPEGenericESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/pixelLessStepChi2Est_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/pixelLessStepClusterShapeHitFilter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/pixelLessStepTrajectoryCleanerBySharedHits_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/pixelPairStepChi2Est_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/pixelPairStepTrajectoryCleanerBySharedHits_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/pixelTrackCleanerBySharedHits_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/positiveCombinedMVAV2Computer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/positiveCombinedSecondaryVertexV2Computer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/positiveOnlyJetBProbabilityComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/positiveOnlyJetProbabilityComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/positiveSoftPFElectronByIP2dComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/positiveSoftPFElectronByIP3dComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/positiveSoftPFElectronByPtComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/positiveSoftPFElectronComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/positiveSoftPFMuonByIP2dComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/positiveSoftPFMuonByIP3dComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/positiveSoftPFMuonByPtComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/positiveSoftPFMuonComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/ppsDBESSource_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/preshowerDetIdAssociator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/PropagatorWithMaterialForLoopers_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/PropagatorWithMaterialForLoopersOpposite_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/PropagatorWithMaterialForMTD_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/RK1DFittingSmoother_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/RK1DTrajectoryFitter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/RK1DTrajectorySmoother_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/RKFittingSmoother_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/RKOutliers1DFittingSmoother_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/RKTrajectoryFitter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/RKTrajectorySmoother_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/RPCConeBuilder_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/rpcconesrc_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/RPCGeometryESModule_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/RungeKuttaTrackerPropagator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/RungeKuttaTrackerPropagatorOpposite_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/simpleSecondaryVertex2TrkComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/simpleSecondaryVertex3TrkComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/siPixel2DTemplateDBObjectESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/siPixelFakeGainOfflineESSource_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/siPixelFakeGainOfflineESSource_prefer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/SiPixelFEDChannelContainerESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/siPixelQualityESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/siPixelTemplateDBObjectESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/siStripBackPlaneCorrectionDepESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/sistripconn_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/siStripGainESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/siStripGainSimESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/siStripLorentzAngleDepESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/siStripQualityESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/SiStripRecHitMatcherESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/SmartPropagator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/SmartPropagatorAny_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/SmartPropagatorAnyOpposite_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/SmartPropagatorAnyRK_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/SmartPropagatorAnyRKOpposite_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/SmartPropagatorOpposite_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/SmartPropagatorRK_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/SmartPropagatorRKOpposite_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/softPFElectronByIP2dComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/softPFElectronByIP3dComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/softPFElectronByPtComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/softPFElectronComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/softPFMuonByIP2dComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/softPFMuonByIP3dComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/softPFMuonByPtComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/softPFMuonComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/SteppingHelixPropagatorAlong_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/SteppingHelixPropagatorAlongNoError_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/SteppingHelixPropagatorAny_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/SteppingHelixPropagatorAnyNoError_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/SteppingHelixPropagatorL2Along_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/SteppingHelixPropagatorL2AlongNoError_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/SteppingHelixPropagatorL2Any_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/SteppingHelixPropagatorL2AnyNoError_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/SteppingHelixPropagatorL2Opposite_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/SteppingHelixPropagatorL2OppositeNoError_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/SteppingHelixPropagatorOpposite_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/SteppingHelixPropagatorOppositeNoError_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/StraightLinePropagator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/StripCPEESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/stripCPEESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/StripCPEfromTrackAngleESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/templates_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/templates2_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/tobTecFlexibleKFFittingSmoother_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/tobTecStepChi2Est_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/tobTecStepClusterShapeHitFilter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/tobTecStepFitterSmoother_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/tobTecStepFitterSmootherForLoopers_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/tobTecStepRKTrajectoryFitter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/tobTecStepRKTrajectoryFitterForLoopers_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/tobTecStepRKTrajectorySmoother_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/tobTecStepRKTrajectorySmootherForLoopers_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/tobTecStepTrajectoryCleanerBySharedHits_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/totemDAQMappingESSourceXML_TimingDiamond_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/totemDAQMappingESSourceXML_TotemTiming_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/totemDAQMappingESSourceXML_TrackingStrip_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/tpparams12_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/trackAlgoPriorityOrder_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/trackCleaner_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/trackCounting3D2ndComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/trackCounting3D3rdComputer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/trackerGeometry_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/trackerNumberingGeometry_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/trackerParameters_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/TrackerRecoGeometryESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/trackerTopology_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/trackSelectionLwtnn_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/TrackTriggerSetup_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/trajectoryCleanerBySharedHits_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/TrajectoryCleanerBySharedHitsForConversions_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/TransientTrackBuilderESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/TTClusterAlgorithm_neighbor_Phase2TrackerDigi__cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/TTClusterAlgorithm_official_Phase2TrackerDigi__cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/TTClusterAlgorithm_official_Phase2TrackerDigi__prefer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/TTRHBuilderAngleAndTemplate_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/ttrhbwor_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/ttrhbwr_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/TTStubAlgorithm_cbc3_Phase2TrackerDigi__cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/TTStubAlgorithm_official_Phase2TrackerDigi__cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/TTStubAlgorithm_official_Phase2TrackerDigi__prefer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/twinmuxParamsSource_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/VolumeBasedMagneticFieldESProducer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/XMLIdealGeometryESSource_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/XMLIdealGeometryESSource_CTPPS_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/eventsetup/ZdcHardcodeGeometryEP_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_AK4PFPuppiJet520_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_Diphoton30_23_IsoCaloId_L1Seeded_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_Diphoton30_23_IsoCaloId_Unseeded_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_DoubleEle23_12_Iso_L1Seeded_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_DoubleEle25_CaloIdL_PMS2_L1Seeded_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_DoubleEle25_CaloIdL_PMS2_Unseeded_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_DoublePFPuppiJets128_DoublePFPuppiBTagDeepCSV_2p4_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_DoublePFPuppiJets128_DoublePFPuppiBTagDeepFlavour_2p4_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_Ele26_WP70_L1Seeded_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_Ele26_WP70_Unseeded_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_Ele32_WPTight_L1Seeded_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_Ele32_WPTight_Unseeded_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_IsoMu24_FromL1TkMuon_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_FromL1TkMuon_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_Mu37_Mu27_FromL1TkMuon_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_Mu50_FromL1TkMuon_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_PFHT200PT30_QuadPFPuppiJet_70_40_30_30_TriplePFPuppiBTagDeepCSV_2p4_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_PFHT200PT30_QuadPFPuppiJet_70_40_30_30_TriplePFPuppiBTagDeepFlavour_2p4_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_PFHT330PT30_QuadPFPuppiJet_75_60_45_40_TriplePFPuppiBTagDeepCSV_2p4_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_PFHT330PT30_QuadPFPuppiJet_75_60_45_40_TriplePFPuppiBTagDeepFlavour_2p4_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_PFPuppiHT1070_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_PFPuppiMETTypeOne140_PFPuppiMHT140_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_Photon108EB_TightID_TightIso_L1Seeded_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_Photon108EB_TightID_TightIso_Unseeded_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_Photon187_L1Seeded_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_Photon187_Unseeded_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLT_TriMu_10_5_5_DZ_FromL1TkMuon_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/L1T_DoubleNNTau52_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/L1T_DoublePFPuppiJets112_2p4_DEta1p6_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/L1T_DoubleTkMuon_15_7_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/L1T_PFHT400PT30_QuadPFPuppiJet_70_55_40_40_2p4_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/L1T_PFPuppiHT450off_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/L1T_PFPuppiMET220off_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/L1T_SingleNNTau150_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/L1T_SinglePFPuppiJet230off_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/L1T_SingleTkMuon_22_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/L1T_TkEle25TkEle12_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/L1T_TkEle36_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/L1T_TkEm37TkEm24_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/L1T_TkEm51_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/L1T_TkIsoEle22TkEm12_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/L1T_TkIsoEle28_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/L1T_TkIsoEm22TkIsoEm12_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/L1T_TkIsoEm36_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/L1T_TripleTkMuon_5_3_3_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/MC_BTV_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/MC_Ele5_Open_L1Seeded_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/MC_Ele5_Open_Unseeded_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/MC_Ele5_WP70_Open_L1Seeded_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/MC_Ele5_WP70_Open_Unseeded_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/MC_JME_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/MC_Photon100EB_TightID_TightIso_Open_L1Seeded_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/MC_Photon100EB_TightID_TightIso_Open_Unseeded_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/MC_Photon100_Open_L1Seeded_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/MC_Photon100_Open_Unseeded_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/paths/l1tReconstructionPath_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/CkfBaseTrajectoryFilter_block_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/ckfBaseTrajectoryFilterP5_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/CkfTrajectoryBuilder_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/ckfTrajectoryFilterBeamHaloMuon_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/ClusterShapeTrajectoryFilter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/conv2CkfTrajectoryFilter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/convCkfTrajectoryFilter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/CSCSegAlgoDF_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/CSCSegAlgoRU_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/CSCSegAlgoSK_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/CSCSegAlgoST_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/CSCSegAlgoTC_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/detachedQuadStepTrajectoryFilter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/detachedQuadStepTrajectoryFilterBase_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/detachedTripletStepTrajectoryFilter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/detachedTripletStepTrajectoryFilterBase_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/DTLinearDriftFromDBAlgo_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/GlobalMuonTrackMatcher_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/GroupedCkfTrajectoryBuilder_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/HFRecalParameterBlock_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/HGCAL_cceParams_toUse_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/HGCAL_chargeCollectionEfficiencies_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/HGCAL_ileakParam_toUse_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/HGCAL_noise_fC_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/HGCAL_noise_heback_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/hgceeDigitizer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/hgchebackDigitizer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/hgchefrontDigitizer_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/highPtTripletStepTrajectoryBuilder_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/highPtTripletStepTrajectoryFilter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/highPtTripletStepTrajectoryFilterBase_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/highPtTripletStepTrajectoryFilterInOut_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/HLTIter0Phase2L3FromL1TkMuonGroupedCkfTrajectoryFilterIT_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/HLTIter0Phase2L3FromL1TkMuonPSetGroupedCkfTrajectoryBuilderIT_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/HLTIter2Phase2L3FromL1TkMuonPSetGroupedCkfTrajectoryBuilderIT_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/HLTIter2Phase2L3FromL1TkMuonPSetTrajectoryFilterIT_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/hltPhase2L3MuonHighPtTripletStepTrajectoryBuilder_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/hltPhase2L3MuonHighPtTripletStepTrajectoryFilter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/hltPhase2L3MuonHighPtTripletStepTrajectoryFilterBase_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/hltPhase2L3MuonHighPtTripletStepTrajectoryFilterInOut_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/hltPhase2L3MuonInitialStepTrajectoryBuilder_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/hltPhase2L3MuonInitialStepTrajectoryFilter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/hltPhase2L3MuonPSetPvClusterComparerForIT_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/hltPhase2L3MuonSeedFromProtoTracks_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/hltPhase2PSetPvClusterComparerForIT_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/hltPhase2SeedFromProtoTracks_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/HLTPSetMuonCkfTrajectoryBuilder_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/HLTPSetMuonCkfTrajectoryFilter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/HLTPSetTrajectoryBuilderForGsfElectrons_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/HLTPSetTrajectoryFilterForElectrons_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/HLTSiStripClusterChargeCutLoose_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/HLTSiStripClusterChargeCutNone_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/initialStepTrajectoryBuilder_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/initialStepTrajectoryFilter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/initialStepTrajectoryFilterBasePreSplitting_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/initialStepTrajectoryFilterPreSplitting_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/initialStepTrajectoryFilterShapePreSplitting_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/jetCoreRegionalStepTrajectoryFilter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/lowPtGsfEleTrajectoryFilter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/lowPtQuadStepTrajectoryFilter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/lowPtQuadStepTrajectoryFilterBase_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/lowPtTripletStepStandardTrajectoryFilter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/lowPtTripletStepTrajectoryFilter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/lowPtTripletStepTrajectoryFilterInOut_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/ME0SegAlgoRU_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/ME0SegmentAlgorithm_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/mixedTripletStepTrajectoryFilter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/muonSeededTrajectoryBuilderForInOut_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/muonSeededTrajectoryBuilderForOutInDisplaced_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/muonSeededTrajectoryFilterForInOut_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/muonSeededTrajectoryFilterForOutIn_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/muonSeededTrajectoryFilterForOutInDisplaced_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/pixelLessStepTrajectoryFilter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/pixelPairStepTrajectoryFilter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/pixelPairStepTrajectoryFilterBase_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/pixelPairStepTrajectoryFilterInOut_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/PixelTripletHLTGenerator_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/pSetPvClusterComparerForIT_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/seedFromProtoTracks_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/SiStripClusterChargeCutLoose_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/SiStripClusterChargeCutNone_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/SiStripClusterChargeCutTight_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/tobTecStepInOutTrajectoryFilter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/tobTecStepTrajectoryFilter_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/TrackAssociatorParameters_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/TrajectoryFilterForConversions_cfi")
fragment.load("HLTrigger/Configuration/HLT_75e33/psets/TrajectoryFilterForElectrons_cfi")

fragment.HLTSchedule = cms.Schedule(*[
    # simulation of the Trigger Primitivs and Level 1 Trigger
    fragment.l1tReconstructionPath,

    # Jets/MET L1T paths
    fragment.L1T_SinglePFPuppiJet230off,
    fragment.L1T_PFPuppiHT450off,
    fragment.L1T_PFPuppiMET220off,

    # Jets/MET HLT paths
    fragment.HLT_AK4PFPuppiJet520,
    fragment.HLT_PFPuppiHT1070,
    fragment.HLT_PFPuppiMETTypeOne140_PFPuppiMHT140,

    # b-tagging L1T paths
    fragment.L1T_PFHT400PT30_QuadPFPuppiJet_70_55_40_40_2p4,
    fragment.L1T_DoublePFPuppiJets112_2p4_DEta1p6,

    # b-tagging HLT paths
    fragment.HLT_PFHT330PT30_QuadPFPuppiJet_75_60_45_40_TriplePFPuppiBTagDeepCSV_2p4,
    fragment.HLT_PFHT200PT30_QuadPFPuppiJet_70_40_30_30_TriplePFPuppiBTagDeepCSV_2p4,
    fragment.HLT_DoublePFPuppiJets128_DoublePFPuppiBTagDeepCSV_2p4,
    fragment.HLT_PFHT330PT30_QuadPFPuppiJet_75_60_45_40_TriplePFPuppiBTagDeepFlavour_2p4,
    fragment.HLT_PFHT200PT30_QuadPFPuppiJet_70_40_30_30_TriplePFPuppiBTagDeepFlavour_2p4,
    fragment.HLT_DoublePFPuppiJets128_DoublePFPuppiBTagDeepFlavour_2p4,

    # Muons L1T paths
    fragment.L1T_SingleTkMuon_22,
    fragment.L1T_DoubleTkMuon_15_7,
    fragment.L1T_TripleTkMuon_5_3_3,

    # Muons HLT paths
    fragment.HLT_Mu50_FromL1TkMuon,
    fragment.HLT_IsoMu24_FromL1TkMuon,
    fragment.HLT_Mu37_Mu27_FromL1TkMuon,
    fragment.HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_FromL1TkMuon,
    fragment.HLT_TriMu_10_5_5_DZ_FromL1TkMuon,

    # E/Gamma L1T paths
    fragment.L1T_TkEm51,
    fragment.L1T_TkEle36,
    fragment.L1T_TkIsoEm36,
    fragment.L1T_TkIsoEle28,
    fragment.L1T_TkEm37TkEm24,
    fragment.L1T_TkEle25TkEle12,
    fragment.L1T_TkIsoEm22TkIsoEm12,
    fragment.L1T_TkIsoEle22TkEm12,

    # E/Gamma unseeded paths
    fragment.HLT_Ele32_WPTight_Unseeded,
    fragment.HLT_Ele26_WP70_Unseeded,
    fragment.HLT_Photon108EB_TightID_TightIso_Unseeded,
    fragment.HLT_Photon187_Unseeded,
    fragment.HLT_DoubleEle25_CaloIdL_PMS2_Unseeded,
    fragment.HLT_Diphoton30_23_IsoCaloId_Unseeded,
    # E/Gamma seeded paths
    fragment.HLT_Ele32_WPTight_L1Seeded,
    fragment.HLT_Ele26_WP70_L1Seeded,
    fragment.HLT_Photon108EB_TightID_TightIso_L1Seeded,
    fragment.HLT_Photon187_L1Seeded,
    fragment.HLT_DoubleEle25_CaloIdL_PMS2_L1Seeded,
    fragment.HLT_DoubleEle23_12_Iso_L1Seeded,
    fragment.HLT_Diphoton30_23_IsoCaloId_L1Seeded,

    # Taus L1T paths
    fragment.L1T_DoubleNNTau52,
    fragment.L1T_SingleNNTau150,

    # MC-like paths, without any filters
    fragment.MC_JME,
    fragment.MC_BTV,
    fragment.MC_Ele5_Open_Unseeded,
    fragment.MC_Ele5_WP70_Open_Unseeded,
    fragment.MC_Ele5_Open_L1Seeded,
    fragment.MC_Ele5_WP70_Open_L1Seeded,
    fragment.MC_Photon100_Open_Unseeded,
    fragment.MC_Photon100EB_TightID_TightIso_Open_Unseeded,
    fragment.MC_Photon100_Open_L1Seeded,
    fragment.MC_Photon100EB_TightID_TightIso_Open_L1Seeded,
])


# avoid redefinition errors when running in the same process as the L1T simulation

# beam spot
del fragment.offlineBeamSpot

# me0LocalRecoTask
del fragment.me0RecHits
del fragment.me0Segments

# l1tReconstructionTask
# Note: l1tReconstructionTask should still contain process.l1tSlwPFPuppiJets, process.l1tSlwPFPuppiJetsCorrected
del fragment.L1EGammaClusterEmuProducer
del fragment.L1TkElectronsEllipticMatchCrystal
del fragment.L1TkElectronsEllipticMatchHGC
del fragment.L1TkMuons
del fragment.L1TkPhotonsCrystal
del fragment.L1TkPhotonsHGC
del fragment.L1TkPrimaryVertex
del fragment.l1EGammaEEProducer
del fragment.l1NNTauProducerPuppi
del fragment.l1PFMetPuppi
del fragment.l1pfCandidates
del fragment.l1pfProducerBarrel
del fragment.l1pfProducerHF
del fragment.l1pfProducerHGCal
del fragment.l1pfProducerHGCalNoTK
del fragment.pfClustersFromCombinedCaloHCal
del fragment.pfClustersFromCombinedCaloHF
del fragment.pfClustersFromHGC3DClusters
del fragment.pfClustersFromL1EGClusters
del fragment.pfTracksFromL1TracksBarrel
del fragment.pfTracksFromL1TracksHGCal
del fragment.simCaloStage2Layer1Digis
del fragment.simCscTriggerPrimitiveDigis
del fragment.simDtTriggerPrimitiveDigis
del fragment.simEmtfDigis
del fragment.simGmtCaloSumDigis
del fragment.simGmtStage2Digis
del fragment.simKBmtfDigis
del fragment.simKBmtfStubs
del fragment.simMuonGEMPadDigiClusters
del fragment.simMuonGEMPadDigis
del fragment.simOmtfDigis
del fragment.simTwinMuxDigis
