#include <DataFormats/L1DTTrackFinder/interface/L1MuDTChambPhDigi.h>
#include <DataFormats/L1DTTrackFinder/interface/L1MuDTChambThDigi.h>
#include <DataFormats/L1DTTrackFinder/interface/L1MuDTTrackCand.h>
#include <DataFormats/L1DTTrackFinder/interface/L1MuDTChambPhContainer.h>
#include <DataFormats/L1DTTrackFinder/interface/L1MuDTChambThContainer.h>
#include <DataFormats/L1DTTrackFinder/interface/L1MuDTTrackContainer.h>
#include <DataFormats/L1DTTrackFinder/interface/L1Phase2MuDTPhDigi.h>
#include <DataFormats/L1DTTrackFinder/interface/L1Phase2MuDTPhContainer.h>
#include <DataFormats/L1DTTrackFinder/interface/L1Phase2MuDTThDigi.h>
#include <DataFormats/L1DTTrackFinder/interface/L1Phase2MuDTThContainer.h>
#include <DataFormats/Common/interface/Wrapper.h>
