import FWCore.ParameterSet.Config as cms

l1NtupleProducer = cms.EDAnalyzer("L1NtupleProducer",
    verbose              = cms.untracked.bool(False),
    physVal              = cms.bool(True),
    generatorSource      = cms.InputTag("none"),
    simulationSource     = cms.InputTag("none"),
    hltSource            = cms.InputTag("TriggerResults::HLT"),
    gmtSource            = cms.InputTag("gtDigis"),
    gtEvmSource          = cms.InputTag("gtEvmDigis"),
    gtSource             = cms.InputTag("gtDigis"),
    gctCentralJetsSource = cms.InputTag("gctDigis","cenJets"),
    gctNonIsoEmSource    = cms.InputTag("gctDigis","nonIsoEm"),
    gctForwardJetsSource = cms.InputTag("gctDigis","forJets"),
    gctIsoEmSource       = cms.InputTag("gctDigis","isoEm"),
    gctEnergySumsSource  = cms.InputTag("gctDigis",""),
    gctTauJetsSource     = cms.InputTag("gctDigis","tauJets"),
    rctSource            = cms.InputTag("gctDigis"),
    dttfSource           = cms.InputTag("dttfDigis"),
    csctfTrkSource       = cms.InputTag("csctfDigis"),
    csctfLCTSource       = cms.InputTag("csctfDigis"),
    csctfStatusSource    = cms.InputTag("csctfDigis"),
    csctfDTStubsSource   = cms.InputTag("csctfDigis:DT"),
    ecalSource           = cms.InputTag("ecalDigis:EcalTriggerPrimitives"),
    hcalSource           = cms.InputTag("hcalDigis"),
    maxRPC         = cms.uint32(12),
    maxDTBX        = cms.uint32(12),
    maxCSC         = cms.uint32(12),
    maxGMT         = cms.uint32(12),
    maxGT          = cms.uint32(12),
    maxRCTREG      = cms.uint32(400),
    maxDTPH        = cms.uint32(50),
    maxDTTH        = cms.uint32(50),
    maxDTTR        = cms.uint32(50),
    maxGEN         = cms.uint32(20),
    maxCSCTFTR           = cms.uint32(50),
    maxCSCTFLCTSTR       = cms.uint32(4),
    maxCSCTFLCTS         = cms.uint32(360),
    maxCSCTFSPS          = cms.uint32(12),
    puMCFile = cms.untracked.string(""),
    puDataFile = cms.untracked.string(""),
    puMCHist = cms.untracked.string(""),
    puDataHist = cms.untracked.string("")                         
)

