/********************************************************************
* SprAdapterDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error SprAdapterDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableSprAdapterDict();
extern void G__cpp_setup_inheritanceSprAdapterDict();
extern void G__cpp_setup_typetableSprAdapterDict();
extern void G__cpp_setup_memvarSprAdapterDict();
extern void G__cpp_setup_globalSprAdapterDict();
extern void G__cpp_setup_memfuncSprAdapterDict();
extern void G__cpp_setup_funcSprAdapterDict();
extern void G__set_cpp_environmentSprAdapterDict();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "PhysicsTools/StatPatternRecognition/interface/SprRootAdapter.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SprAdapterDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__SprAdapterDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SprAdapterDictLN_setlEstringcOlesslEstringgRcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__SprAdapterDictLN_SprAbsFilter;
extern G__linked_taginfo G__SprAdapterDictLN_SprAbsClassifier;
extern G__linked_taginfo G__SprAdapterDictLN_SprAbsTrainedClassifier;
extern G__linked_taginfo G__SprAdapterDictLN_SprPlotter;
extern G__linked_taginfo G__SprAdapterDictLN_SprMultiClassLearner;
extern G__linked_taginfo G__SprAdapterDictLN_SprTrainedMultiClassLearner;
extern G__linked_taginfo G__SprAdapterDictLN_SprMultiClassPlotter;
extern G__linked_taginfo G__SprAdapterDictLN_SprAbsTwoClassCriterion;
extern G__linked_taginfo G__SprAdapterDictLN_SprCoordinateMapper;
extern G__linked_taginfo G__SprAdapterDictLN_SprRootAdapter;
extern G__linked_taginfo G__SprAdapterDictLN_maplEstringcOSprAbsClassifiermUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOSprAbsClassifiermUgRsPgRsPgR;
extern G__linked_taginfo G__SprAdapterDictLN_maplEstringcOSprAbsTrainedClassifiermUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOSprAbsTrainedClassifiermUgRsPgRsPgR;
extern G__linked_taginfo G__SprAdapterDictLN_maplESprAbsTrainedClassifiermUcOSprCoordinateMappermUcOlesslESprAbsTrainedClassifiermUgRcOallocatorlEpairlESprAbsTrainedClassifiermUsPconstcOSprCoordinateMappermUgRsPgRsPgR;
extern G__linked_taginfo G__SprAdapterDictLN_vectorlEconstsPSprAbsTwoClassCriterionmUcOallocatorlEconstsPSprAbsTwoClassCriterionmUgRsPgR;
extern G__linked_taginfo G__SprAdapterDictLN_reverse_iteratorlEvectorlEconstsPSprAbsTwoClassCriterionmUcOallocatorlEconstsPSprAbsTwoClassCriterionmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SprAdapterDictLN_vectorlESprIntegerBootstrapmUcOallocatorlESprIntegerBootstrapmUgRsPgR;
extern G__linked_taginfo G__SprAdapterDictLN_reverse_iteratorlEvectorlESprIntegerBootstrapmUcOallocatorlESprIntegerBootstrapmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SprAdapterDictLN_setlESprAbsClassifiermUcOlesslESprAbsClassifiermUgRcOallocatorlESprAbsClassifiermUgRsPgR;
extern G__linked_taginfo G__SprAdapterDictLN_vectorlESprAverageLossmUcOallocatorlESprAverageLossmUgRsPgR;
extern G__linked_taginfo G__SprAdapterDictLN_reverse_iteratorlEvectorlESprAverageLossmUcOallocatorlESprAverageLossmUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
