#!/bin/bash

vtx_y_0s=(
	"0E-6"
	"100E-6"
	"200E-6"
	"250E-6"
	"300E-6"
	"400E-6"
	"550E-6"
)


#----------------------------------------------------------------------------------------------------

make "get_optical_functions" || exit 1

for vtx_y_0 in ${vtx_y_0s[*]}
do
	echo "* $vtx_y_0"

	./get_optical_functions -vtx-y-0 "$vtx_y_0" -output "get_optical_functions_${vtx_y_0}.root"
done

#for i in "${!tags[@]}"
#do 
#	tag="${tags[$i]}"
#	config="${configs[$i]}"
#
#	echo "* $tag"
#
#	./test_reconstruction $config \
#  		-events "$n_events" -seed "$seed" -output "simulations/$n_events/$tag.root" > "simulations/$n_events/$tag.log" 2> /dev/null &
#done
