#!/bin/bash

n_events="1E4"
if [ -n "$1" ]
then
	n_events="$1"
fi

inputDir="."
if [ -n "$SCRAM_TEST_PATH" ]
then
	inputDir="$SCRAM_TEST_PATH/simu"
	n_events="1E2"
fi

#----------------------------------------------------------------------------------------------------

pids=""

function RunOne()
{
	local config="$1"
	local era_mod_path="$2"
	local era="$3"

	local cfg="simu_${config}_cfg.py"
	local log="simu_${config}.log"
	local out_lhcInfo="simu_${config}_lhcInfo.root"
	local out_tracks="simu_${config}_tracks.root"
	local out_protons="simu_${config}_protons.root"

	cat "$inputDir/template_cfg.py" | sed "\
			s|\$ERA_MOD_PATH|$era_mod_path|;\
			s|\$ERA|$era|;\
			s|\$CONFIG|$config|;\
			s|\$N_EVENTS|$n_events|;\
			s|\$OUT_LHCINFO|$out_lhcInfo|;\
			s|\$OUT_TRACKS|$out_tracks|;\
			s|\$OUT_PROTONS|$out_protons|;\
		" > "$cfg"

	cmsRun "$cfg" &> "$log" &
	pids="$pids $!"
}

#----------------------------------------------------------------------------------------------------

# RunOne "2016" "Configuration.Eras" "Run2_2016"

# RunOne "2017" "Configuration.Eras" "Run2_2017"

RunOne "2018" "Configuration.Eras" "Run2_2018"

# RunOne "2022" "Configuration.ProcessModifiers" "Run3_CTPPS_directSim"

rc=0
for pid in $pids
do
	wait $pid
	if [ $? -ne 0 ]
	then
		rc=1
	fi
done

exit $rc
