#!/bin/bash

#----------------------------------------------------------------------------------------------------

function RunOne()
{
	local config="$1"
	local era="$2"

	local cfg="simu_${config}_cfg.py"
	local log="simu_${config}.log"
	local out_tracks="simu_${config}_tracks.root"
	local out_protons="simu_${config}_protons.root"

	cat "template_cfg.py" | sed "\
			s|\$ERA|$era|;\
			s|\$CONFIG|$config|;\
			s|\$OUT_TRACKS|$out_tracks|;\
			s|\$OUT_PROTONS|$out_protons|;\
		" > "$cfg"

	cmsRun "$cfg" &> "$log" &
}

#----------------------------------------------------------------------------------------------------

RunOne "2016_preTS2" "Run2_2016"
RunOne "2016_postTS2" "Run2_2016"

RunOne "2017_preTS2" "Run2_2017"
RunOne "2017_postTS2" "Run2_2017"

RunOne "2018_preTS1" "Run2_2018"
RunOne "2018_TS1_TS2" "Run2_2018"
RunOne "2018_postTS2" "Run2_2018"
