#ifndef RECOTRACKER_TRANSIENTRACKINGRECHIT_TSiStripRecHit1D_H
#define RECOTRACKER_TRANSIENTRACKINGRECHIT_TSiStripRecHit1D_H

#include "DataFormats/TrackerRecHit2D/interface/SiStripRecHit1D.h"
#include "RecoLocalTracker/ClusterParameterEstimator/interface/StripClusterParameterEstimator.h"

#endif
