#ifndef DQM_SiStripCommissioningAnalysis_ApvLatencyAnalysis_H
#define DQM_SiStripCommissioningAnalysis_ApvLatencyAnalysis_H

#include "CondFormats/SiStripObjects/interface/ApvLatencyAnalysis.h"

#endif // DQM_SiStripCommissioningAnalysis_ApvLatencyAnalysis_H



