import FWCore.ParameterSet.Config as cms
import sys

def chooseTrans(index):
    d = (
   ["Simple",
    cms.untracked.VPSet(
                        cms.PSet(type = cms.untracked.string("IsFile"),
                                 id = cms.untracked.EventID(0,0,0)),
                        cms.PSet(type = cms.untracked.string("IsRun"),
                                 id = cms.untracked.EventID(1,0,0)),
                        cms.PSet(type = cms.untracked.string("IsLumi"),
                                 id = cms.untracked.EventID(1,1,0)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,1,1)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,1,2)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,1,3)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,1,4)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,1,5)),
                        cms.PSet(type = cms.untracked.string("IsStop"),
                                 id = cms.untracked.EventID(0,0,0))
                        ) ],
   ["Less events than streams",
    cms.untracked.VPSet(
                        cms.PSet(type = cms.untracked.string("IsFile"),
                                 id = cms.untracked.EventID(0,0,0)),
                        cms.PSet(type = cms.untracked.string("IsRun"),
                                 id = cms.untracked.EventID(1,0,0)),
                        cms.PSet(type = cms.untracked.string("IsLumi"),
                                 id = cms.untracked.EventID(1,1,0)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,1,1)),
                        cms.PSet(type = cms.untracked.string("IsStop"),
                                 id = cms.untracked.EventID(0,0,0))
                        ) ],
   ["Multiple different Lumis",
    cms.untracked.VPSet(
                        cms.PSet(type = cms.untracked.string("IsFile"),
                                 id = cms.untracked.EventID(0,0,0)),
                        cms.PSet(type = cms.untracked.string("IsRun"),
                                 id = cms.untracked.EventID(1,0,0)),
                        cms.PSet(type = cms.untracked.string("IsLumi"),
                                 id = cms.untracked.EventID(1,1,0)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,1,1)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,1,2)),
                        cms.PSet(type = cms.untracked.string("IsLumi"),
                                 id = cms.untracked.EventID(1,2,0)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,2,3)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,2,4)),
                        cms.PSet(type = cms.untracked.string("IsStop"),
                                 id = cms.untracked.EventID(0,0,0))
                        ) ],
   ["Empty Lumi",
    cms.untracked.VPSet(
                        cms.PSet(type = cms.untracked.string("IsFile"),
                                 id = cms.untracked.EventID(0,0,0)),
                        cms.PSet(type = cms.untracked.string("IsRun"),
                                 id = cms.untracked.EventID(1,0,0)),
                        cms.PSet(type = cms.untracked.string("IsLumi"),
                                 id = cms.untracked.EventID(1,1,0)),
                        cms.PSet(type = cms.untracked.string("IsLumi"),
                                 id = cms.untracked.EventID(1,2,0)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,2,3)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,2,4)),
                        cms.PSet(type = cms.untracked.string("IsStop"),
                                 id = cms.untracked.EventID(0,0,0))
                        ) ],
   ["Empty Lumi at end",
    cms.untracked.VPSet(
                        cms.PSet(type = cms.untracked.string("IsFile"),
                                 id = cms.untracked.EventID(0,0,0)),
                        cms.PSet(type = cms.untracked.string("IsRun"),
                                 id = cms.untracked.EventID(1,0,0)),
                        cms.PSet(type = cms.untracked.string("IsLumi"),
                                 id = cms.untracked.EventID(1,1,0)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,1,3)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,1,4)),
                        cms.PSet(type = cms.untracked.string("IsLumi"),
                                 id = cms.untracked.EventID(1,2,0)),
                        cms.PSet(type = cms.untracked.string("IsStop"),
                                 id = cms.untracked.EventID(0,0,0))
                        ) ],
   ["Multiple different runs",
    cms.untracked.VPSet(
                        cms.PSet(type = cms.untracked.string("IsFile"),
                                 id = cms.untracked.EventID(0,0,0)),
                        cms.PSet(type = cms.untracked.string("IsRun"),
                                 id = cms.untracked.EventID(1,0,0)),
                        cms.PSet(type = cms.untracked.string("IsLumi"),
                                 id = cms.untracked.EventID(1,1,0)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,1,1)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,1,2)),
                        cms.PSet(type = cms.untracked.string("IsRun"),
                                 id = cms.untracked.EventID(2,0,0)),
                        cms.PSet(type = cms.untracked.string("IsLumi"),
                                 id = cms.untracked.EventID(2,1,0)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(2,1,1)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(2,1,2)),
                        cms.PSet(type = cms.untracked.string("IsStop"),
                                 id = cms.untracked.EventID(0,0,0))
                        ) ],
   ["Empty run",
    cms.untracked.VPSet(
                        cms.PSet(type = cms.untracked.string("IsFile"),
                                 id = cms.untracked.EventID(0,0,0)),
                        cms.PSet(type = cms.untracked.string("IsRun"),
                                 id = cms.untracked.EventID(1,0,0)),
                        cms.PSet(type = cms.untracked.string("IsRun"),
                                 id = cms.untracked.EventID(2,0,0)),
                        cms.PSet(type = cms.untracked.string("IsLumi"),
                                 id = cms.untracked.EventID(2,1,0)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(2,1,1)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(2,1,2)),
                        cms.PSet(type = cms.untracked.string("IsStop"),
                                 id = cms.untracked.EventID(0,0,0))
                        ) ],
   ["Empty run at end",
    cms.untracked.VPSet(
                        cms.PSet(type = cms.untracked.string("IsFile"),
                                 id = cms.untracked.EventID(0,0,0)),
                        cms.PSet(type = cms.untracked.string("IsRun"),
                                 id = cms.untracked.EventID(1,0,0)),
                        cms.PSet(type = cms.untracked.string("IsLumi"),
                                 id = cms.untracked.EventID(1,1,0)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,1,1)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,1,2)),
                        cms.PSet(type = cms.untracked.string("IsRun"),
                                 id = cms.untracked.EventID(2,0,0)),
                        cms.PSet(type = cms.untracked.string("IsStop"),
                                 id = cms.untracked.EventID(0,0,0))
                        ) ],
   ["Empty run no lumi",
    cms.untracked.VPSet(
                        cms.PSet(type = cms.untracked.string("IsFile"),
                                 id = cms.untracked.EventID(0,0,0)),
                        cms.PSet(type = cms.untracked.string("IsRun"),
                                 id = cms.untracked.EventID(1,0,0)),
                        cms.PSet(type = cms.untracked.string("IsStop"),
                                 id = cms.untracked.EventID(0,0,0))
                        ) ],
   ["Empty file at end",
    cms.untracked.VPSet(
                        cms.PSet(type = cms.untracked.string("IsFile"),
                                 id = cms.untracked.EventID(0,0,0)),
                        cms.PSet(type = cms.untracked.string("IsRun"),
                                 id = cms.untracked.EventID(1,0,0)),
                        cms.PSet(type = cms.untracked.string("IsLumi"),
                                 id = cms.untracked.EventID(1,1,0)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,1,1)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,1,2)),
                        cms.PSet(type = cms.untracked.string("IsFile"),
                                 id = cms.untracked.EventID(0,0,0)),
                        cms.PSet(type = cms.untracked.string("IsStop"),
                                 id = cms.untracked.EventID(0,0,0))
                        ) ],
   ["Empty file",
    cms.untracked.VPSet(
                        cms.PSet(type = cms.untracked.string("IsFile"),
                                 id = cms.untracked.EventID(0,0,0)),
                        cms.PSet(type = cms.untracked.string("IsFile"),
                                 id = cms.untracked.EventID(0,0,0)),
                        cms.PSet(type = cms.untracked.string("IsRun"),
                                 id = cms.untracked.EventID(1,0,0)),
                        cms.PSet(type = cms.untracked.string("IsLumi"),
                                 id = cms.untracked.EventID(1,1,0)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,1,1)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,1,2)),
                        cms.PSet(type = cms.untracked.string("IsStop"),
                                 id = cms.untracked.EventID(0,0,0))
                        ) ],
   ["Merge run across files",
    cms.untracked.VPSet(
                        cms.PSet(type = cms.untracked.string("IsFile"),
                                 id = cms.untracked.EventID(0,0,0)),
                        cms.PSet(type = cms.untracked.string("IsRun"),
                                 id = cms.untracked.EventID(1,0,0)),
                        cms.PSet(type = cms.untracked.string("IsLumi"),
                                 id = cms.untracked.EventID(1,1,0)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,1,1)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,1,2)),
                        cms.PSet(type = cms.untracked.string("IsFile"),
                                 id = cms.untracked.EventID(0,0,0)),
                        cms.PSet(type = cms.untracked.string("IsRun"),
                                 id = cms.untracked.EventID(1,0,0)),
                        cms.PSet(type = cms.untracked.string("IsLumi"),
                                 id = cms.untracked.EventID(1,2,0)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,2,3)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,2,4)),
                        cms.PSet(type = cms.untracked.string("IsStop"),
                                 id = cms.untracked.EventID(0,0,0))
                        ) ],
   ["Merge run & lumi across files",
    cms.untracked.VPSet(
                        cms.PSet(type = cms.untracked.string("IsFile"),
                                 id = cms.untracked.EventID(0,0,0)),
                        cms.PSet(type = cms.untracked.string("IsRun"),
                                 id = cms.untracked.EventID(1,0,0)),
                        cms.PSet(type = cms.untracked.string("IsLumi"),
                                 id = cms.untracked.EventID(1,1,0)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,1,1)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,1,2)),
                        cms.PSet(type = cms.untracked.string("IsFile"),
                                 id = cms.untracked.EventID(0,0,0)),
                        cms.PSet(type = cms.untracked.string("IsRun"),
                                 id = cms.untracked.EventID(1,0,0)),
                        cms.PSet(type = cms.untracked.string("IsLumi"),
                                 id = cms.untracked.EventID(1,1,0)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,1,3)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,1,4)),
                        cms.PSet(type = cms.untracked.string("IsStop"),
                                 id = cms.untracked.EventID(0,0,0))
                        ) ],
   ["Delayed lumi merge",
    cms.untracked.VPSet(
                        cms.PSet(type = cms.untracked.string("IsFile"),
                                 id = cms.untracked.EventID(0,0,0)),
                        cms.PSet(type = cms.untracked.string("IsRun"),
                                 id = cms.untracked.EventID(1,0,0)),
                        cms.PSet(type = cms.untracked.string("IsLumi"),
                                 id = cms.untracked.EventID(1,1,0)),
                        cms.PSet(type = cms.untracked.string("IsLumi"), #to merge
                                 id = cms.untracked.EventID(1,1,0)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,1,1)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,1,2)),
                        cms.PSet(type = cms.untracked.string("IsLumi"),
                                 id = cms.untracked.EventID(1,2,0)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,2,3)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,2,4)),
                        cms.PSet(type = cms.untracked.string("IsStop"),
                                 id = cms.untracked.EventID(0,0,0))
                        ) ],
   ["Delayed lumi merge 2",
    cms.untracked.VPSet(
                        cms.PSet(type = cms.untracked.string("IsFile"),
                                 id = cms.untracked.EventID(0,0,0)),
                        cms.PSet(type = cms.untracked.string("IsRun"),
                                 id = cms.untracked.EventID(1,0,0)),
                        cms.PSet(type = cms.untracked.string("IsLumi"),
                                 id = cms.untracked.EventID(1,1,0)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,1,1)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,1,2)),
                        cms.PSet(type = cms.untracked.string("IsLumi"),
                                 id = cms.untracked.EventID(1,2,0)),
                        cms.PSet(type = cms.untracked.string("IsLumi"),
                                 id = cms.untracked.EventID(1,2,0)), # to merge
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,2,3)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,2,4)),
                        cms.PSet(type = cms.untracked.string("IsStop"),
                                 id = cms.untracked.EventID(0,0,0))
                        ) ],
   ["Delayed run merge",
    cms.untracked.VPSet(
                        cms.PSet(type = cms.untracked.string("IsFile"),
                                 id = cms.untracked.EventID(0,0,0)),
                        cms.PSet(type = cms.untracked.string("IsRun"),
                                 id = cms.untracked.EventID(1,0,0)),
                        cms.PSet(type = cms.untracked.string("IsRun"), # to merge
                                 id = cms.untracked.EventID(1,0,0)),
                        cms.PSet(type = cms.untracked.string("IsLumi"),
                                 id = cms.untracked.EventID(1,1,0)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,1,1)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,1,2)),
                        cms.PSet(type = cms.untracked.string("IsRun"),
                                 id = cms.untracked.EventID(2,0,0)),
                        cms.PSet(type = cms.untracked.string("IsLumi"),
                                 id = cms.untracked.EventID(2,1,0)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(2,1,1)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(2,1,2)),
                        cms.PSet(type = cms.untracked.string("IsStop"),
                                 id = cms.untracked.EventID(0,0,0))
                        ) ],
  ["Delayed run merge 2",
    cms.untracked.VPSet(
                        cms.PSet(type = cms.untracked.string("IsFile"),
                                 id = cms.untracked.EventID(0,0,0)),
                        cms.PSet(type = cms.untracked.string("IsRun"),
                                 id = cms.untracked.EventID(1,0,0)),
                        cms.PSet(type = cms.untracked.string("IsLumi"),
                                 id = cms.untracked.EventID(1,1,0)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,1,1)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(1,1,2)),
                        cms.PSet(type = cms.untracked.string("IsRun"),
                                 id = cms.untracked.EventID(2,0,0)),
                        cms.PSet(type = cms.untracked.string("IsRun"), # to merge
                                 id = cms.untracked.EventID(2,0,0)),
                        cms.PSet(type = cms.untracked.string("IsLumi"),
                                 id = cms.untracked.EventID(2,1,0)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(2,1,1)),
                        cms.PSet(type = cms.untracked.string("IsEvent"),
                                 id = cms.untracked.EventID(2,1,2)),
                        cms.PSet(type = cms.untracked.string("IsStop"),
                                 id = cms.untracked.EventID(0,0,0))
                        ) ],
    )
    print '****************************************'
    print 'Test:', d[index][0]
    print '****************************************'
    return d[index][1]

trans = chooseTrans(int(sys.argv[2]))

process = cms.Process("TEST")
process.source = cms.Source("TestSource", 
                            transitions = trans)
#process.add_(cms.Service("Tracer"))
process.add_(cms.Service("CheckTransitions", 
                         transitions = trans))
process.options = cms.untracked.PSet(numberOfThreads = cms.untracked.uint32(2),
                                     numberOfStreams = cms.untracked.uint32(0))
