#! /usr/bin/env python
import sys, imp

# parse the HLT configuration from standard input or from the given file
hlt = imp.new_module('hlt')
try:
  configname = sys.argv[1]
except:
  config = sys.stdin
else:
  config = open(configname)
exec config in globals(), hlt.__dict__
config.close()
process = hlt.process

streams = process.streams._Parameterizable__parameterNames
streams.sort()

for stream in streams:
  print 'stream', stream
  pds = process.streams.__dict__[stream]
  pds.sort()
  for pd in pds:
    print '    dataset', pd
    if pd in process.datasets.__dict__:
      paths = [ path for path in process.datasets.__dict__[pd] ]
      paths.sort()
      for path in paths:
        print '        ', path
    else:
      print '        *** not found ***' 
