import FWCore.ParameterSet.Config as cms

Rethrow = cms.untracked.vstring(
  'CommandLineProcessing',
  'ConfigFileNotFound',
  'ConfigFileReadError',
  'OtherCMS',
  'StdException',
  'Unknown',
  'BadAlloc',
  'BadExceptionType',
  'ProductNotFound',
  'DictionaryNotFound',
  'InsertFailure',
  'Configuration',
  'LogicError',
  'UnimplementedFeature',
  'InvalidReference',
  'NullPointerError',
  'NoProductSpecified',
  'EventTimeout',
  'EventCorruption',
  'ScheduleExecutionFailure',
  'EventProcessorFailure',
  'FileInPathError',
  'FileOpenError',
  'FileReadError',
  'FatalRootError',
  'MismatchedInputFiles',
  'ProductDoesNotSupportViews',
  'ProductDoesNotSupportPtr',
  'NotFound',
  'FormatIncompatibility'
)
