#! /usr/bin/env python
import os.path
import sys
import logging

import signal

import ConfigParser
import optparse
import webbrowser
import math
import unittest
import time

try:
    distBaseDirectory=os.path.abspath(os.path.join(os.path.dirname(__file__),".."))
except Exception:
    distBaseDirectory=os.path.abspath(os.path.join(os.path.dirname(sys.argv[0]),".."))

sys.path.append(distBaseDirectory)
from Vispa.Main.Directories import *
setBaseDirectory(distBaseDirectory)
distBinaryBaseDirectory=os.path.join(distBaseDirectory,"dist")
sys.path.append(distBinaryBaseDirectory)

try:
    from sip import *
    from PyQt4.QtCore import *
    from PyQt4.QtGui import *
    from PyQt4.QtSvg import *
    from PyQt4.QtXml import *
except Exception,e:
    raise ImportError("Please run edmConfigBrowser, not edmConfigBrowser.py : "+str(e))

setWebsiteUrl('http://twiki.cern.ch/twiki/bin/view/CMS/SWGuideConfigBrowser')

from Vispa.Main.Application import *
from Vispa.Plugins.ConfigBrowser.ConfigBrowserPlugin import *

if __name__ == "__main__":
    app = Application(sys.argv)
    signal.signal(signal.SIGINT, signal.SIG_DFL)
    app.mainWindow().setWindowTitle("ConfigBrowser")
    app.mainWindow().setWindowIcon(QIcon())
    app.setVersion("Version 26.04.2009")
    app.run()
