from ..layouts.layout_manager import register_layout

register_layout(source='EcalEndcap/EETriggerTowerTask/EETTT Et spectrum Real Digis EE -', destination='Collisions/L1TFeedBack/EETTT Et spectrum Real Digis EE -', name='00 ECAL TP Spectra', overlay='')
register_layout(source='EcalBarrel/EBTriggerTowerTask/EBTTT Et spectrum Real Digis', destination='Collisions/L1TFeedBack/EBTTT Et spectrum Real Digis', name='00 ECAL TP Spectra', overlay='')
register_layout(source='EcalEndcap/EETriggerTowerTask/EETTT Et spectrum Real Digis EE +', destination='Collisions/L1TFeedBack/EETTT Et spectrum Real Digis EE +', name='00 ECAL TP Spectra', overlay='')
register_layout(source='EcalEndcap/EEOccupancyTask/EEOT TP digi thr occupancy EE -', destination='Collisions/L1TFeedBack/EEOT TP digi thr occupancy EE -', name='01 ECAL TP Occupancy', overlay='')
register_layout(source='EcalBarrel/EBOccupancyTask/EBOT TP digi thr occupancy', destination='Collisions/L1TFeedBack/EBOT TP digi thr occupancy', name='01 ECAL TP Occupancy', overlay='')
register_layout(source='EcalEndcap/EEOccupancyTask/EEOT TP digi thr occupancy EE +', destination='Collisions/L1TFeedBack/EEOT TP digi thr occupancy EE +', name='01 ECAL TP Occupancy', overlay='')
register_layout(source='EcalEndcap/EESummaryClient/EETTT EE - Trigger Primitives Timing summary', destination='Collisions/L1TFeedBack/EETTT EE - Trigger Primitives Timing summary', name='02 ECAL TP Emulator Comparison', overlay='')
register_layout(source='EcalBarrel/EBSummaryClient/EBTTT Trigger Primitives Timing summary', destination='Collisions/L1TFeedBack/EBTTT Trigger Primitives Timing summary', name='02 ECAL TP Emulator Comparison', overlay='')
register_layout(source='EcalEndcap/EESummaryClient/EETTT EE + Trigger Primitives Timing summary', destination='Collisions/L1TFeedBack/EETTT EE + Trigger Primitives Timing summary', name='02 ECAL TP Emulator Comparison', overlay='')
register_layout(source='L1T/L1TScalersSCAL/Level1TriggerRates/TechnicalRates/Rate_TechBit_040', destination='Collisions/L1TFeedBack/Rate_TechBit_040', name='03 Rate BSCL.BSCR', overlay='')
register_layout(source='L1T/L1TScalersSCAL/Level1TriggerRates/TechnicalRates/Rate_TechBit_042', destination='Collisions/L1TFeedBack/Rate_TechBit_042', name='04 Rate BSC splash right', overlay='')
register_layout(source='L1T/L1TScalersSCAL/Level1TriggerRates/TechnicalRates/Rate_TechBit_043', destination='Collisions/L1TFeedBack/Rate_TechBit_043', name='05 Rate BSC splash left', overlay='')
register_layout(source='L1T/L1TScalersSCAL/Level1TriggerRates/AlgorithmRates/Rate_AlgoBit_124', destination='Collisions/L1TFeedBack/Rate_AlgoBit_124', name='06 Rate BSCOR and BPTX', overlay='')
register_layout(source='L1T/L1TScalersSCAL/Level1TriggerRates/TechnicalRates/Rate_TechBit_Ratio_33_over_32', destination='Collisions/L1TFeedBack/Rate_TechBit_Ratio_33_over_32', name='07 Rate Ratio 33 over 32', overlay='')
register_layout(source='L1T/L1TScalersSCAL/Level1TriggerRates/TechnicalRates/Rate_TechBit_Ratio_41_over_40', destination='Collisions/L1TFeedBack/Rate_TechBit_Ratio_41_over_40', name='08 Rate Ratio 41 over 40', overlay='')
register_layout(source='L1T/L1TScalersSCAL/Level1TriggerRates/TechnicalRates/Integral_TechBit_040', destination='Collisions/L1TFeedBack/Integral_TechBit_040', name='09 Integ BSCL*BSCR Triggers vs LS', overlay='')
register_layout(source='L1T/L1TScalersSCAL/Level1TriggerRates/TechnicalRates/Integral_TechBit_042_OR_043', destination='Collisions/L1TFeedBack/Integral_TechBit_042_OR_043', name='10 Integ BSCL or BSCR Triggers vs LS', overlay='')
register_layout(source='L1T/L1TScalersSCAL/Level1TriggerRates/TechnicalRates/Integral_TechBit_009', destination='Collisions/L1TFeedBack/Integral_TechBit_009', name='11 Integ HF Triggers vs LS', overlay='')
register_layout(source='L1T/L1TScalersSCAL/Level1TriggerRates/AlgorithmRates/Integral_AlgoBit_124', destination='Collisions/L1TFeedBack/Integral_AlgoBit_124', name='12 Integ BSCOR and BPTX', overlay='')
