from ..layouts.layout_manager import register_layout

register_layout(source='EcalBarrel/EBSummaryClient/EB global summary', destination='00 Shift/Ecal/EB global summaryEB global summary', name='00 Summary', overlay='')
register_layout(source='EcalEndcap/EESummaryClient/EE global summary EE -', destination='00 Shift/Ecal/EE global summary EE -EE global summary EE -', name='00 Summary', overlay='')
register_layout(source='EcalEndcap/EESummaryClient/EE global summary EE +', destination='00 Shift/Ecal/EE global summary EE +EE global summary EE +', name='00 Summary', overlay='')
register_layout(source='EcalBarrel/EBSummaryClient/EBSFT front-end status summary', destination='00 Shift/Ecal/EBSFT front-end status summaryEBSFT front-end status summary', name='01 FE Status', overlay='')
register_layout(source='EcalEndcap/EESummaryClient/EESFT EE - front-end status summary', destination='00 Shift/Ecal/EESFT EE - front-end status summaryEESFT EE - front-end status summary', name='01 FE Status', overlay='')
register_layout(source='EcalEndcap/EESummaryClient/EESFT EE + front-end status summary', destination='00 Shift/Ecal/EESFT EE + front-end status summaryEESFT EE + front-end status summary', name='01 FE Status', overlay='')
register_layout(source='EcalBarrel/EBSummaryClient/EBIT integrity quality summary', destination='00 Shift/Ecal/EBIT integrity quality summaryEBIT integrity quality summary', name='02 Integrity', overlay='')
register_layout(source='EcalEndcap/EESummaryClient/EEIT EE - integrity quality summary', destination='00 Shift/Ecal/EEIT EE - integrity quality summaryEEIT EE - integrity quality summary', name='02 Integrity', overlay='')
register_layout(source='EcalEndcap/EESummaryClient/EEIT EE + integrity quality summary', destination='00 Shift/Ecal/EEIT EE + integrity quality summaryEEIT EE + integrity quality summary', name='02 Integrity', overlay='')
register_layout(source='EcalBarrel/EBOccupancyTask/EBOT digi occupancy', destination='00 Shift/Ecal/EBOT digi occupancyEBOT digi occupancy', name='03 Occupancy', overlay='')
register_layout(source='EcalEndcap/EEOccupancyTask/EEOT digi occupancy EE -', destination='00 Shift/Ecal/EEOT digi occupancy EE -EEOT digi occupancy EE -', name='03 Occupancy', overlay='')
register_layout(source='EcalEndcap/EEOccupancyTask/EEOT digi occupancy EE +', destination='00 Shift/Ecal/EEOT digi occupancy EE +EEOT digi occupancy EE +', name='03 Occupancy', overlay='')
register_layout(source='EcalBarrel/EBSummaryClient/EBPOT pedestal quality summary G12', destination='00 Shift/Ecal/EBPOT pedestal quality summary G12EBPOT pedestal quality summary G12', name='04 Noise', overlay='')
register_layout(source='EcalEndcap/EESummaryClient/EEPOT EE - pedestal quality summary G12', destination='00 Shift/Ecal/EEPOT EE - pedestal quality summary G12EEPOT EE - pedestal quality summary G12', name='04 Noise', overlay='')
register_layout(source='EcalEndcap/EESummaryClient/EEPOT EE + pedestal quality summary G12', destination='00 Shift/Ecal/EEPOT EE + pedestal quality summary G12EEPOT EE + pedestal quality summary G12', name='04 Noise', overlay='')
register_layout(source='EcalBarrel/EBSummaryClient/EBOT energy summary', destination='00 Shift/Ecal/EBOT energy summaryEBOT energy summary', name='05 RecHit Energy', overlay='')
register_layout(source='EcalEndcap/EESummaryClient/EEOT EE - energy summary', destination='00 Shift/Ecal/EEOT EE - energy summaryEEOT EE - energy summary', name='05 RecHit Energy', overlay='')
register_layout(source='EcalEndcap/EESummaryClient/EEOT EE + energy summary', destination='00 Shift/Ecal/EEOT EE + energy summaryEEOT EE + energy summary', name='05 RecHit Energy', overlay='')
register_layout(source='EcalBarrel/EBSummaryClient/EBTMT timing quality summary', destination='00 Shift/Ecal/EBTMT timing quality summaryEBTMT timing quality summary', name='06 Timing', overlay='')
register_layout(source='EcalEndcap/EESummaryClient/EETMT EE - timing quality summary', destination='00 Shift/Ecal/EETMT EE - timing quality summaryEETMT EE - timing quality summary', name='06 Timing', overlay='')
register_layout(source='EcalEndcap/EESummaryClient/EETMT EE + timing quality summary', destination='00 Shift/Ecal/EETMT EE + timing quality summaryEETMT EE + timing quality summary', name='06 Timing', overlay='')
register_layout(source='EcalBarrel/EBSummaryClient/EBTTT emulator error quality summary', destination='00 Shift/Ecal/EBTTT emulator error quality summaryEBTTT emulator error quality summary', name='07 TriggerPrimitives', overlay='')
register_layout(source='EcalEndcap/EESummaryClient/EETTT EE - emulator error quality summary', destination='00 Shift/Ecal/EETTT EE - emulator error quality summaryEETTT EE - emulator error quality summary', name='07 TriggerPrimitives', overlay='')
register_layout(source='EcalEndcap/EESummaryClient/EETTT EE + emulator error quality summary', destination='00 Shift/Ecal/EETTT EE + emulator error quality summaryEETTT EE + emulator error quality summary', name='07 TriggerPrimitives', overlay='')
register_layout(source='EcalBarrel/EBSummaryClient/EBOT hot cell quality summary', destination='00 Shift/Ecal/EBOT hot cell quality summaryEBOT hot cell quality summary', name='08 Hot Cells', overlay='')
register_layout(source='EcalEndcap/EESummaryClient/EEOT EE - hot cell quality summary', destination='00 Shift/Ecal/EEOT EE - hot cell quality summaryEEOT EE - hot cell quality summary', name='08 Hot Cells', overlay='')
register_layout(source='EcalEndcap/EESummaryClient/EEOT EE + hot cell quality summary', destination='00 Shift/Ecal/EEOT EE + hot cell quality summaryEEOT EE + hot cell quality summary', name='08 Hot Cells', overlay='')
