COND_SERIALIZATION_INSTANTIATE(EcalCondObjectContainer<EcalChannelStatusCode>);
COND_SERIALIZATION_INSTANTIATE(EcalCondObjectContainer<EcalDQMStatusCode>);
COND_SERIALIZATION_INSTANTIATE(EcalCondObjectContainer<EcalLaserAPDPNRatios::EcalLaserAPDPNpair>);
COND_SERIALIZATION_INSTANTIATE(EcalCondObjectContainer<EcalMappingElement>);
COND_SERIALIZATION_INSTANTIATE(EcalCondObjectContainer<EcalMGPAGainRatio>);
COND_SERIALIZATION_INSTANTIATE(EcalCondObjectContainer<EcalPedestal>);
COND_SERIALIZATION_INSTANTIATE(EcalCondObjectContainer<EcalPulseShape>);
COND_SERIALIZATION_INSTANTIATE(EcalCondObjectContainer<EcalPulseCovariance>);
COND_SERIALIZATION_INSTANTIATE(EcalCondObjectContainer<EcalTimeDependentCorrections::Values>);
COND_SERIALIZATION_INSTANTIATE(EcalCondObjectContainer<EcalTPGCrystalStatusCode>);
COND_SERIALIZATION_INSTANTIATE(EcalCondObjectContainer<EcalTPGLinearizationConstant>);
COND_SERIALIZATION_INSTANTIATE(EcalCondObjectContainer<EcalTPGPedestal>);
COND_SERIALIZATION_INSTANTIATE(EcalCondObjectContainer<EcalXtalGroupId>);
COND_SERIALIZATION_INSTANTIATE(EcalCondObjectContainer<float>);
COND_SERIALIZATION_INSTANTIATE(EcalCondTowerObjectContainer<EcalChannelStatusCode>);
COND_SERIALIZATION_INSTANTIATE(EcalCondTowerObjectContainer<EcalDAQStatusCode>);
COND_SERIALIZATION_INSTANTIATE(EcalCondTowerObjectContainer<EcalDQMStatusCode>);

