begin execute immediate 'drop table INTGLUMI';exception when others then null;end;
CREATE TABLE "INTGLUMI"
("RUNNUM" NUMBER(10,0),
 "STARTRUN" NUMBER(10,0),
 "INTGLUMI" BINARY_FLOAT,
 CONSTRAINT "PK_INTGLUMI" PRIMARY KEY ("RUNNUM", "STARTRUN")
)
PARTITION BY RANGE(RUNNUM)
(PARTITION THEREST VALUES LESS THAN(MAXVALUE)
);
GRANT SELECT ON "INTGLUMI" TO PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON "INTGLUMI" TO CMS_LUMI_WRITER;
