CREATE TABLE "INTGLUMIV2"
("RUNNUM" NUMBER(10,0),
 "STARTRUN" NUMBER(10,0),
 "INTGLUMI" BINARY_FLOAT,
 CONSTRAINT "PK_INTGLUMIV2" PRIMARY KEY ("RUNNUM", "STARTRUN")
)
PARTITION BY RANGE(RUNNUM)
(
PARTITION YEAR2011 VALUES LESS THAN(183338),
PARTITION THEREST VALUES LESS THAN(MAXVALUE)
);
GRANT SELECT ON "INTGLUMIV2" TO PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON "INTGLUMIV2" TO CMS_LUMI_WRITER;
