/*=========================LUMINORMSV2=======================*/
CREATE TABLE "LUMINORMSV2"
(
"DATA_ID" NUMBER(20,0),
"ENTRY_ID" NUMBER(20,0),
"ENTRY_NAME" VARCHAR2(56),
"LUMITYPE" VARCHAR2(56),
"ISTYPEDEFAULT" NUMBER(10,0),
"COMMENT" VARCHAR2(128),
"CTIME" TIMESTAMP(6),
CONSTRAINT "LUMINORMSV2_PK" PRIMARY KEY ("DATA_ID")
);
CREATE INDEX LUMINORMSV2_ENTRY_NAME_IDX ON LUMINORMSV2(ENTRY_NAME);
GRANT SELECT ON "LUMINORMSV2" TO PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON "LUMINORMSV2" TO CMS_LUMI_WRITER;
/*=========================LUMINORMSV2_ID=======================*/
CREATE TABLE "LUMINORMSV2_ID"
(	"NEXTID" NUMBER(20,0),
	 CONSTRAINT "LUMINORMSV2_ID_PK" PRIMARY KEY ("NEXTID")
);
INSERT INTO "LUMINORMSV2_ID"("NEXTID") VALUES(0);
GRANT SELECT ON "LUMINORMSV2_ID" TO PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON "LUMINORMSV2_ID" TO CMS_LUMI_WRITER;
/*=========================LUMINORMSV2_ENTRIES=======================*/
CREATE TABLE "LUMINORMSV2_ENTRIES"
(	"ENTRY_ID" NUMBER(20,0),
	"REVISION_ID" NUMBER(20,0),
	"NAME" VARCHAR2(56),
	 CONSTRAINT "LUMINORMSV2_ENTRIES_PK" PRIMARY KEY ("ENTRY_ID")
);
GRANT SELECT ON "LUMINORMSV2_ENTRIES" TO PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON "LUMINORMSV2_ENTRIES" TO CMS_LUMI_WRITER;
/*=========================LUMINORMSV2_ENTRIES_ID=======================*/
CREATE TABLE "LUMINORMSV2_ENTRIES_ID"
(	"NEXTID" NUMBER(20,0),
	 CONSTRAINT "LUMINORMSV2_ENTRIES_ID_PK" PRIMARY KEY ("NEXTID")
);
INSERT INTO "LUMINORMSV2_ENTRIES_ID"("NEXTID") VALUES(0);
GRANT SELECT ON "LUMINORMSV2_ENTRIES_ID" TO PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON "LUMINORMSV2_ENTRIES_ID" TO CMS_LUMI_WRITER;
/*=========================LUMINORMSV2_REV=======================*/
CREATE TABLE "LUMINORMSV2_REV"
(	"DATA_ID" NUMBER(20,0),
	"REVISION_ID" NUMBER(20,0),
	 CONSTRAINT "LUMINORMSV2_REV_PK" PRIMARY KEY("DATA_ID","REVISION_ID")
);
GRANT SELECT ON "LUMINORMSV2_REV" TO PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON "LUMINORMSV2_REV" TO CMS_LUMI_WRITER;
/*=========================LUMINORMSV2DATA=======================*/
CREATE TABLE "LUMINORMSV2DATA"
(
"DATA_ID" NUMBER(20,0),
"CORRECTOR" VARCHAR2(1000) NOT NULL,
"SINCE" NUMBER(10,0),
"AMODETAG" VARCHAR2(56),
"NOMINALEGEV" NUMBER(10,0),
"A0" BINARY_FLOAT,
"NORM_OCC2" BINARY_FLOAT,
"NORM_ET" BINARY_FLOAT,
"DRIFT" BINARY_FLOAT,
"AFTERGLOW" VARCHAR2(1000),
"A1" BINARY_FLOAT,
"A2" BINARY_FLOAT,
"A3" BINARY_FLOAT,
"A4" BINARY_FLOAT,
"A5" BINARY_FLOAT,
"C1" BINARY_FLOAT,
"C2" BINARY_FLOAT,
"COMMENT" VARCHAR2(1000),
CONSTRAINT "LUMINORMSV2DATA_PK" PRIMARY KEY ("DATA_ID","SINCE")
);
GRANT SELECT ON "LUMINORMSV2DATA" TO PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON "LUMINORMSV2DATA" TO CMS_LUMI_WRITER;
