
CREATE OR REPLACE TRIGGER RUN_FILES_INSERT
  BEFORE INSERT ON RUN_FILES
  FOR EACH ROW
BEGIN
  SELECT RUN_FILES_ID_NO.NEXTVAL INTO :NEW.ID FROM DUAL;
  :NEW.CREATE_TIME := SYSTIMESTAMP;
END RUN_FILES_INSERT;
/


CREATE OR REPLACE TRIGGER RUN_FILES_UPDATE
  BEFORE UPDATE ON RUN_FILES
  FOR EACH ROW
BEGIN
  :NEW.UPDATE_TIME := SYSTIMESTAMP;
END RUN_FILES_UPDATE;
/


