VtxSmeared = {
    'NoSmear':                       'Configuration.StandardSequences.VtxSmearedNoSmear_cff',              
    'BetafuncEarlyCollision':        'IOMC.EventVertexGenerators.VtxSmearedBetafuncEarlyCollision_cfi',    
    'BeamProfile':                   'IOMC.EventVertexGenerators.VtxSmearedBeamProfile_cfi',               
    'BetafuncEarlyCollision':        'IOMC.EventVertexGenerators.VtxSmearedBetafuncEarlyCollision_cfi',    
    'BetafuncNominalCollision':      'IOMC.EventVertexGenerators.VtxSmearedBetafuncNominalCollision_cfi',  
    'Early10TeVCollision':           'IOMC.EventVertexGenerators.VtxSmearedEarly10TeVCollision_cfi',       
    'Early10TeVX322Y10000':          'IOMC.EventVertexGenerators.VtxSmearedEarly10TeVX322Y10000_cfi',      
    'Early10TeVX322Y1000':           'IOMC.EventVertexGenerators.VtxSmearedEarly10TeVX322Y1000_cfi',       
    'Early10TeVX322Y100':            'IOMC.EventVertexGenerators.VtxSmearedEarly10TeVX322Y100_cfi',        
    'Early10TeVX322Y250':            'IOMC.EventVertexGenerators.VtxSmearedEarly10TeVX322Y250_cfi',        
    'Early10TeVX322Y5000':           'IOMC.EventVertexGenerators.VtxSmearedEarly10TeVX322Y5000_cfi',       
    'Early10TeVX322Y500':            'IOMC.EventVertexGenerators.VtxSmearedEarly10TeVX322Y500_cfi',        
    'Early2p2TeVCollision':          'IOMC.EventVertexGenerators.VtxSmearedEarly2p2TeVCollision_cfi',      
    'Early7TeVCollision':            'IOMC.EventVertexGenerators.VtxSmearedEarly7TeVCollision_cfi',        
    'Early900GeVCollision':          'IOMC.EventVertexGenerators.VtxSmearedEarly900GeVCollision_cfi',      
    'Flat':                          'IOMC.EventVertexGenerators.VtxSmearedFlat_cfi',                      
    'Gauss':                         'IOMC.EventVertexGenerators.VtxSmearedGauss_cfi',                     
    'Realistic7TeVCollision':        'IOMC.EventVertexGenerators.VtxSmearedRealistic7TeVCollision_cfi',    
    'Realistic7TeVCollision2010B':   'IOMC.EventVertexGenerators.VtxSmearedRealistic7TeVCollision2010B_cfi',
    'Realistic7TeVCollisionComm10':  'IOMC.EventVertexGenerators.VtxSmearedRealistic7TeVCollisionComm10_cfi',
    'Realistic900GeVCollision':      'IOMC.EventVertexGenerators.VtxSmearedRealistic900GeVCollision_cfi',  
    'Realistic8TeVCollision':        'IOMC.EventVertexGenerators.VtxSmearedRealistic8TeVCollision_cfi',
    'Realistic8TeV2012Collision':    'IOMC.EventVertexGenerators.VtxSmearedRealistic8TeV2012Collision_cfi',    
    'Realistic7TeV2011Collision':    'IOMC.EventVertexGenerators.VtxSmearedRealistic7TeV2011Collision_cfi',
    'Realistic2p76TeV2011Collision': 'IOMC.EventVertexGenerators.VtxSmearedRealistic2p76TeV2011Collision_cfi',
    'Realistic2p76TeV2013Collision': 'IOMC.EventVertexGenerators.VtxSmearedRealistic2p76TeV2013Collision_cfi',
    'Centered7TeV2011Collision':     'IOMC.EventVertexGenerators.VtxSmearedCentered7TeV2011Collision_cfi',
    'RealisticHI2011Collision':      'IOMC.EventVertexGenerators.VtxSmearedRealisticHI2011Collision_cfi',
    'Realistic5TeVPPbBoost':         'GeneratorInterface.HiGenCommon.VtxSmearedRealistic5TeVPPbBoost_cff',
    'Realistic5TeVPPbBoostReversed': 'GeneratorInterface.HiGenCommon.VtxSmearedRealistic5TeVPPbBoostReversed_cff',
    'MatchHI':                       'GeneratorInterface.HiGenCommon.VtxSmearedMatchHI_cff',
    'Match5TeVPPbBoost':             'GeneratorInterface.HiGenCommon.VtxSmearedMatch5TeVPPbBoost_cff',    
    'Match5TeVPPbBoostReversed':     'GeneratorInterface.HiGenCommon.VtxSmearedMatch5TeVPPbBoostReversed_cff',
    'HLLHC'  :                       'IOMC.EventVertexGenerators.VtxSmearedHLLHC_cfi',
    'ShiftedCollision2015'  :        'IOMC.EventVertexGenerators.VtxSmearedShiftedCollision2015_cfi',
    'NominalCollision2015'  :        'IOMC.EventVertexGenerators.VtxSmearedNominalCollision2015_cfi',
    'ZeroTeslaRun247324Collision'  : 'IOMC.EventVertexGenerators.VtxSmearedZeroTeslaRun247324Collision_cfi',
    'Realistic50ns13TeVCollisionZeroTesla': 'IOMC.EventVertexGenerators.VtxSmearedRealistic50ns13TeVCollisionZeroTesla_cfi',
    'Realistic50ns13TeVCollision': 'IOMC.EventVertexGenerators.VtxSmearedRealistic50ns13TeVCollision_cfi',

}
VtxSmearedDefaultKey='NominalCollision2015'
VtxSmearedHIDefaultKey='RealisticHI2011Collision'
