#include "FWCore/Framework/interface/ModuleFactory.h"
#include "PixelToFEDAssociateFromAsciiESProducer.h"
#include "PixelToLNKAssociateFromAsciiESProducer.h"

DEFINE_FWK_EVENTSETUP_MODULE(PixelToFEDAssociateFromAsciiESProducer);
DEFINE_ANOTHER_FWK_EVENTSETUP_MODULE(PixelToLNKAssociateFromAsciiESProducer);
