#!/bin/bash -ex
# Simple test to use one of the files generated by TestDQMServicesDemo test
# and run compareHistogram.py on it

compareHistograms.py \
  -b DQM_V0001_R000000001__Harvesting__DQMTests__DQMIO.root \
  -p DQM_V0001_R000000001__Harvesting__DQMTests__DQMIO.root >out.log
cat out.log
if [ "$(tail -1 out.log)" != "0 0 0" ] ; then
  exit 1
fi
