#!/bin/bash
eval `scram runtime -sh`

	classes=`cmsglimpse TYPELOOKUP_DATA_REG \
	| awk 'BEGIN{FS="TYPELOOKUP_DATA_REG\\\(|\\\)";OFS="\n";} {print $2}'\
	| ./extract.pl \
	| awk 'BEGIN{FS="::";OFS="\n";} {print $NF}' \
	| tr " " "\n" | sort -u |grep -v -e ^[0-9] `
	echo $classes | tr " " "\n" >/tmp/classes2.txt
	paths=`cmsglimpse -G TYPELOOKUP_DATA_REG  \
	| awk 'BEGIN{FS="\"|<|>";OFS="\n";} /^#include/ {print $2}'| tr " " "\n"| sort -u`
	echo $paths | tr " " "\n"  >/tmp/paths2.txt
	pathtmp=""
	cd  ${CMSSW_RELEASE_BASE}/src
        cat /tmp/paths2.txt | ctags -f - -L - 2>/dev/null | tr "\t" " ">/tmp/ctags2.txt
        for class in  $classes  ;do
                grep -e "^$class\ .*\ c$" /tmp/ctags2.txt | awk '/class/ {print $2}'
        done |  sort -u >/tmp/headers2.txt
 
