#!/bin/bash
#eval `scram runtime -sh`
	classes=`cmsglimpse -F classes_def.xml$ -G class \
	| sed '/<!--.*-->/d'| sed '/<!--/,/-->/d'\
	| awk 'BEGIN{FS="<class name=\"|\"";} /class name/ { print $2 }' \
	| ./extract.pl \
	| awk 'BEGIN{FS="::";OFS="\n";} {print $NF}' \
	| tr " " "\n" | sort -u | grep -v  -e ^[0-9] -e\* -e\&`
	echo $classes | tr " " "\n" >/tmp/classes1.txt
	paths=`cmsglimpse -F classes.h$ -G include \
	| awk 'BEGIN{FS="\"|<|>";OFS="\n";} /^\#include/ {print $2}'\
	| grep -v classes.h | tr " " "\n"| sort -u`
	echo $paths | tr " " "\n"  >/tmp/paths1.txt
	pathtmp=""
	cd ${CMSSW_RELEASE_BASE}/src
	cat /tmp/paths1.txt | ctags -f - -L - 2>/dev/null | tr "\t" " ">/tmp/ctags1.txt
	for class in `echo $classes | tr " " "\n"`  ;do grep -e "^$class\ .*\ c$" /tmp/ctags1.txt | awk '/class/ {print $2}'; done |  sort -u >/tmp/headers1.txt
