#include "FWCore/Framework/interface/MakerMacros.h"
#include "FWCore/Framework/interface/SourceFactory.h"
#include "CalibCalorimetry/EcalCorrectionModules/interface/EcalShowerContainmentCorrectionsESProducer.h"
#include "CalibCalorimetry/EcalCorrectionModules/interface/EcalShowerContainmentCorrectionsLogE2E1ESProducer.h"
#include "CalibCalorimetry/EcalCorrectionModules/interface/EcalGlobalShowerContainmentCorrectionsVsEtaESProducer.h"

DEFINE_SEAL_MODULE();
DEFINE_ANOTHER_FWK_EVENTSETUP_MODULE(EcalShowerContainmentCorrectionsESProducer);
DEFINE_ANOTHER_FWK_EVENTSETUP_MODULE(EcalShowerContainmentCorrectionsLogE2E1ESProducer);
DEFINE_ANOTHER_FWK_EVENTSETUP_MODULE(EcalGlobalShowerContainmentCorrectionsVsEtaESProducer);
