import FWCore.ParameterSet.Config as cms

from Configuration.Eras.ModifierChain_run2_2017_noTrackingModifier_cff import run2_2017_noTrackingModifier

Run2_2017_trackingRun2 = cms.ModifierChain(run2_2017_noTrackingModifier)

