import FWCore.ParameterSet.Config as cms

from Configuration.Eras.Era_Run3_pp_on_PbPb_cff import Run3_pp_on_PbPb
from Configuration.Eras.Modifier_tracker_apv_vfp30_2016_cff import tracker_apv_vfp30_2016
from Configuration.ProcessModifiers.approxSiStripClusters_cff import approxSiStripClusters

Run3_pp_on_PbPb_approxSiStripClusters = cms.ModifierChain(Run3_pp_on_PbPb, approxSiStripClusters)
