import FWCore.ParameterSet.Config as cms

hltDiEG3023IsoCaloIdHgcalIsoUnseededFilter = cms.EDFilter("HLTEgammaGenericQuadraticEtaFilter",
    absEtaLowEdges = cms.vdouble(0.0, 1.0, 1.479, 2.0),
    candTag = cms.InputTag("hltDiEG3023IsoCaloIdEcalIsoUnseededFilter"),
    doRhoCorrection = cms.bool(False),
    effectiveAreas = cms.vdouble(0.0, 0.0, 0.0, 0.0),
    energyLowEdges = cms.vdouble(0.0),
    etaBoundaryEB12 = cms.double(1.0),
    etaBoundaryEE12 = cms.double(2.0),
    l1EGCand = cms.InputTag("hltEgammaCandidatesUnseeded"),
    lessThan = cms.bool(True),
    ncandcut = cms.int32(2),
    rhoMax = cms.double(99999999.0),
    rhoScale = cms.double(1.0),
    rhoTag = cms.InputTag(""),
    saveTags = cms.bool(True),
    thrOverE2EB1 = cms.vdouble(0.0),
    thrOverE2EB2 = cms.vdouble(0.0),
    thrOverE2EE1 = cms.vdouble(0.0),
    thrOverE2EE2 = cms.vdouble(0.0),
    thrOverEEB1 = cms.vdouble(0.05),
    thrOverEEB2 = cms.vdouble(0.05),
    thrOverEEE1 = cms.vdouble(0.05),
    thrOverEEE2 = cms.vdouble(0.05),
    thrRegularEB1 = cms.vdouble(140),
    thrRegularEB2 = cms.vdouble(140),
    thrRegularEE1 = cms.vdouble(140),
    thrRegularEE2 = cms.vdouble(370),
    useEt = cms.bool(False),
    varTag = cms.InputTag("hltEgammaHGCalLayerClusterIsoUnseeded")
)
