#include "DataFormats/Common/interface/Wrapper.h"
#include "DataFormats/FTLDigiSoA/interface/BTLDigiSoA.h"
#include "DataFormats/FTLDigiSoA/interface/BTLDigiHostCollection.h"
#include "DataFormats/FTLDigiSoA/interface/ETLDigiSoA.h"
#include "DataFormats/FTLDigiSoA/interface/ETLDigiHostCollection.h"
